export { UserProfileProvider } from '@island.is/application/data-providers'
export { NationalRegistryMaritalStatusProvider } from './NationalRegistryMaritalStatusProvider'
export { DistrictsProvider } from './DistrictsProvider'
export { NationalRegistryProvider } from '@island.is/application/data-providers'
export { ReligionsProvider } from './ReligionsProvider'
