export * from './bifrost-university'
export * from './holar-university'
export * from './agricultural-university-of-iceland'
export * from './university-of-akureyri'
export * from './university-of-iceland'
export * from './iceland-university-of-the-arts'
