name: 'Unit Test'
description: 'Run unit tests'
inputs:
  dd-api-key:
    description: 'Datadog API key'
    required: true
  aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  docker-registry:
    description: 'Docker registry'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Docker login to ECR repo
      run: ./scripts/ci/docker-login-ecr.sh
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}

    - name: Running tests
      run: ./scripts/ci/30_test.sh
      shell: bash
      env:
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}
        DD_API_KEY: ${{ inputs.dd-api-key }}

    - name: Set RUNS_ON_S3_BUCKET_CACHE
      shell: bash
      if: ${{ !github.event.localrun && env.RUNS_ON_BUCKET_NAME }}
      run: echo "RUNS_ON_S3_BUCKET_CACHE=${{ env.RUNS_ON_BUCKET_NAME }}" >> $GITHUB_ENV
