name: 'Unit Test'
description: 'Run unit tests'
inputs:
  dd-api-key:
    description: 'Datadog API key'
    required: true
  aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  docker-registry:
    description: 'Docker registry'
    required: true
  codecov-token:
    description: 'Codecov token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Docker login to ECR repo
      run: ./scripts/ci/docker-login-ecr.sh
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}
    - name: Set Codeconv version numner
      run: |
        echo "CODECOV_REV=v0.3.2" >> $GITHUB_ENV
      shell: bash

    - name: Running tests
      run: ./scripts/ci/30_test.sh
      shell: bash
      env:
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}
        DD_API_KEY: ${{ inputs.dd-api-key }}

    - name: Set RUNS_ON_S3_BUCKET_CACHE
      shell: bash
      if: ${{ !github.event.localrun && env.RUNS_ON_BUCKET_NAME }}
      run: echo "RUNS_ON_S3_BUCKET_CACHE=${{ env.RUNS_ON_BUCKET_NAME }}" >> $GITHUB_ENV

    - name: Cached codecov uploader
      id: codecov-cache
      uses: runs-on/cache@v4
      with:
        path: codecov
        key: ${{ runner.os }}-codeconv-${{ env.CODECOV_REV }}

    - name: Fetch codecov uploader
      if: steps.codecov-cache.outputs.cache-hit != 'true'
      run: |
        # Importing pgp keys
        curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import

        curl -O https://uploader.codecov.io/$CODECOV_REV/linux/codecov
        curl -O https://uploader.codecov.io/$CODECOV_REV/linux/codecov.SHA256SUM
        curl -O https://uploader.codecov.io/$CODECOV_REV/linux/codecov.SHA256SUM.sig

        # Integrity check
        gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
        shasum -a 256 -c codecov.SHA256SUM
        rm codecov.SHA256SUM.sig codecov.SHA256SUM
      shell: bash

    - name: Install codecov uploader
      id: codecov
      run: |
        chmod +x codecov

        # Adding codecov uploader to PATH
        mkdir -p "$HOME/.local/bin"
        cp codecov "$HOME/.local/bin/codecov"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Upload coverage reports
      run: ./scripts/ci/run-in-parallel.sh 50_upload-coverage || true # If for some reason codecov is down, we can still build. This is not a perfect solution though.
      shell: bash
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
