export { DisabilityLicenseClient } from './disabilityLicenseClient.service'
export { DisabilityLicenseUpdateClient } from './disabilityLicenseUpdateClient.service'
export { DisabilityDigitalLicenseClientConfig } from './disabilityLicenseClient.config'
export { DisabilityClientModule } from './disabilityLicenseClient.module'
export { DisabilityUpdateClientModule } from './disabilityLicenseUpdateClient.module'
