import { TaxCalculatorFieldKind } from '../../models/enums'
import {
  FieldDefinition,
  MAX_SANE_NUMBER_VALUE,
  parseNumber,
} from '../../utils/parsing'
import { previousYearIncomeYearOptions } from '../../utils/fieldOptions'

export const interestBenefitFields: FieldDefinition[] = [
  {
    key: 'maritalStatus',
    rawKey: 'hjuskaparstada',
    label: 'Hjúskaparstaða',
    kind: TaxCalculatorFieldKind.SELECT,
    required: true,
    options: [
      { value: '1', label: 'Einhleypingur' },
      { value: '2', label: 'Einstætt foreldri' },
      { value: '3', label: 'Hjón/Sambúð' },
    ],
    parse: parseNumber,
  },
  {
    key: 'incomeYear',
    rawKey: 'tekjuar',
    label: 'Tekjuár',
    kind: TaxCalculatorFieldKind.SELECT,
    required: true,
    options: previousYearIncomeYearOptions,
    parse: parseNumber,
  },
  {
    key: 'incomeBase',
    rawKey: 'tekjustofn',
    label: 'Tekjustofn',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: true,
    unit: 'ISK',
    min: 0,
    max: MAX_SANE_NUMBER_VALUE,
    parse: parseNumber,
  },
  {
    key: 'assetBase',
    rawKey: 'eignastofn',
    label: 'Eignastofn',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: true,
    unit: 'ISK',
    min: 0,
    max: MAX_SANE_NUMBER_VALUE,
    parse: parseNumber,
  },
  {
    key: 'outstandingLoanBalance',
    rawKey: 'eftirstodvar',
    label: 'Eftirstöðvar lána',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: true,
    unit: 'ISK',
    min: 0,
    max: MAX_SANE_NUMBER_VALUE,
    parse: parseNumber,
  },
  {
    key: 'paidInterestExpenses',
    rawKey: 'greiddVaxtagjold',
    label: 'Greidd vaxtagjöld',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: true,
    unit: 'ISK',
    min: 0,
    max: MAX_SANE_NUMBER_VALUE,
    parse: parseNumber,
  },
]
