export const education = [
  { name: 'Ekkert skólanám', type: 'Grunnám - grunnskólapróf' },
  { name: 'Ólokið grunnskólanám', type: 'Grunnám - grunnskólapróf' },
  { name: 'Barnapróf', type: 'Grunnám - grunnskólapróf' },
  { name: 'Unglingapróf', type: 'Grunnám - grunnskólapróf' },
  { name: 'Gagnfræðapróf', type: 'Grunnám - grunnskólapróf' },
  { name: 'Landspróf', type: 'Grunnám - grunnskólapróf' },
  { name: 'Grunnskólapróf', type: 'Grunnám - grunnskólapróf' },
  { name: 'Fornám eða 0 áfangar', type: 'Grunnám - grunnskólapróf' },
  { name: 'Grunnnám, annað', type: 'Grunnám - grunnskólapróf' },
  { name: 'Grunnnám í múraraiðn', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Grunnnám í málmiðnaði', type: 'Styttra starfsnám (yfirleitt < ár)' },
  {
    name: 'Grunnnám í rafiðngreinum',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  { name: 'Grunnnám í húsasmíði', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Grunnnám í bíliðnum', type: 'Styttra starfsnám (yfirleitt < ár)' },
  {
    name: 'Grunnnám matvælagreina',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  {
    name: 'Grunnnám í iðnum, annað',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  { name: 'Hússtjórnarskólanám', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Heimilisbraut', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Handíðir og handmennt', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Matsveinanám', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Slátrun', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Fiskvinnslubraut', type: 'Styttra starfsnám (yfirleitt < ár)' },
  {
    name: 'Matvæla- og hússtjórnarnám, annað',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  { name: 'Ferðamálabraut', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Leiðsögumannanám', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Ferðatengt nám, annað', type: 'Styttra starfsnám (yfirleitt < ár)' },
  { name: 'Flugþjónustubraut', type: 'Styttra starfsnám (yfirleitt < ár)' },
  {
    name: 'Flugfreyju/flugþjónanám',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  { name: 'Hlaðmenn/hlaðfreyjur', type: 'Styttra starfsnám (yfirleitt < ár)' },
  {
    name: 'Flugþjónustunám, annað',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  { name: 'Förðunarnám', type: 'Styttra starfsnám (yfirleitt < ár)' },
  {
    name: 'Stutt starfsnám, annað (<ár)',
    type: 'Styttra starfsnám (yfirleitt < ár)',
  },
  { name: 'Búfræði', type: 'Starfsnám' },
  { name: 'Blómaskreytingar', type: 'Starfsnám' },
  { name: 'Garðyrkjuframleiðsla', type: 'Starfsnám' },
  { name: 'Skógrækt og náttúra', type: 'Starfsnám' },
  { name: 'Reiðkennaranám/tamningar', type: 'Starfsnám' },
  { name: 'Landbúnaður, annað starfsmenntanám', type: 'Starfsnám' },
  { name: 'Skipstjórnarnám, að 12 m.', type: 'Starfsnám' },
  { name: 'Skipstjórn, námstig A að 24 m.', type: 'Starfsnám' },
  { name: 'Skipstjórn, námsstig B að 45 m.', type: 'Starfsnám' },
  {
    name: 'Skipsstjórn, námsstig C, ótakm. Fiskiskiparéttindi',
    type: 'Starfsnám',
  },
  { name: 'Skipstjórn, námsstig D, eingöngu kaupskip', type: 'Starfsnám' },
  {
    name: 'Skipsstjórn, námsstig E, varðskipanám-skipherra',
    type: 'Starfsnám',
  },
  { name: 'Skipstjórnarnám, annað', type: 'Starfsnám' },
  { name: 'Vélstjórnarbraut A 750 kw og minna', type: 'Starfsnám' },
  { name: 'Vélstjórnarbraut B 1500 kw og minna', type: 'Starfsnám' },
  { name: 'Vélstjórnarbraut C, minna en 3000 kw', type: 'Starfsnám' },
  {
    name: 'Vélstjórnarbraut D, ótakmörkuð vélstjórnarréttindi',
    type: 'Starfsnám',
  },
  { name: 'Vélstjórnarnám, annað', type: 'Starfsnám' },
  { name: 'Einkaflugmannspróf', type: 'Starfsnám' },
  { name: 'Atvinnuflugmannspróf', type: 'Starfsnám' },
  { name: 'Flugumferðarstjórn', type: 'Starfsnám' },
  { name: 'Flug- eða flugstjórnarnám, annað', type: 'Starfsnám' },
  { name: 'Fiskiðnaðarnám/lengra fiskivinnslunám', type: 'Starfsnám' },
  { name: 'Sjávarútvegsbraut', type: 'Starfsnám' },
  { name: 'Fiskeldisnám á framhaldsskólastigi', type: 'Starfsnám' },
  { name: 'Sjávarútvegur, annað starfsmenntanám', type: 'Starfsnám' },
  { name: 'Hótelnám', type: 'Starfsnám' },
  { name: 'Nám fyrir aðstoðarkokka', type: 'Starfsnám' },
  { name: 'Matartækni', type: 'Starfsnám' },
  { name: 'Matarfræði', type: 'Starfsnám' },
  { name: 'Nám fyrir aðstoðarþjóna', type: 'Starfsnám' },
  { name: 'Smurbrauðsnám', type: 'Starfsnám' },
  {
    name: 'Hótel-, veitinga- og veisluþjónustunám, annað starfsmenntanám',
    type: 'Starfsnám',
  },
  { name: 'Hönnunarbraut', type: 'Starfsnám' },
  { name: 'Iðnhönnun', type: 'Starfsnám' },
  { name: 'Vöruhönnun', type: 'Starfsnám' },
  { name: 'Útstillingabraut', type: 'Starfsnám' },
  { name: 'Margmiðlunarhönnun', type: 'Starfsnám' },
  { name: 'Tækniteiknun', type: 'Starfsnám' },
  { name: 'Hönnun, annað starfsmenntanám', type: 'Starfsnám' },
  { name: 'Upplýsinga- og fjölmiðlagreinar, grunnnám', type: 'Starfsnám' },
  { name: 'Kvikmyndagerð', type: 'Starfsnám' },
  { name: 'Kvikmyndasýningarstjórn', type: 'Starfsnám' },
  { name: 'Fjölmiðlun, sjón- og hljóðtækninám, annað', type: 'Starfsnám' },
  { name: 'Læknaritaranám', type: 'Starfsnám' },
  { name: 'Hjúkruna - og móttökuritaranám', type: 'Starfsnám' },
  { name: 'Lyfjatæknanám', type: 'Starfsnám' },
  { name: 'Námsbraut fyrir nuddara', type: 'Starfsnám' },
  { name: 'Sjúkraliðabraut', type: 'Starfsnám' },
  { name: 'Námsbraut í fótaaðgerðafræði', type: 'Starfsnám' },
  { name: 'Tanntæknanám/aðstoðarfólk tannlækna', type: 'Starfsnám' },
  { name: 'Heilbrigðisgreinar, annað', type: 'Starfsnám' },
  { name: 'Félagsliði', type: 'Starfsnám' },
  { name: 'Félagsmála - og tómstundabraut', type: 'Starfsnám' },
  { name: 'Skólaliðabraut', type: 'Starfsnám' },
  { name: 'Leikskólaliðanám', type: 'Starfsnám' },
  { name: 'Stuðningsfulltrúar í grunnskólum', type: 'Starfsnám' },
  { name: 'Uppeldisbraut', type: 'Starfsnám' },
  { name: 'Íþróttabraut - starfsnám', type: 'Starfsnám' },
  { name: 'Félags-, uppeldis- og íþróttagreinar, annað', type: 'Starfsnám' },
  { name: 'Verslunarpróf', type: 'Starfsnám' },
  { name: 'Samvinnuskólapróf', type: 'Starfsnám' },
  { name: 'Viðskiptabraut', type: 'Starfsnám' },
  { name: 'Skrifstofubraut', type: 'Starfsnám' },
  { name: 'Tölvubraut', type: 'Starfsnám' },
  { name: 'Bankamannanám', type: 'Starfsnám' },
  { name: 'Ritaranám', type: 'Starfsnám' },
  {
    name: 'Skrifstofu-, verslunar- og tölvugreinanám, annað',
    type: 'Starfsnám',
  },
  { name: 'Lögreglunám', type: 'Starfsnám' },
  { name: 'Tollvarðanám', type: 'Starfsnám' },
  { name: 'Slökkvistarf', type: 'Starfsnám' },
  { name: 'Fangavarsla', type: 'Starfsnám' },
  { name: 'Lífvarsla', type: 'Starfsnám' },
  { name: 'Öryggisþjónusta og tjónavarnir', type: 'Starfsnám' },
  { name: 'Öryggisþjónusta og löggæsla, annað', type: 'Starfsnám' },
  { name: 'Ökukennsla', type: 'Starfsnám' },
  { name: 'Póstþjónusta', type: 'Starfsnám' },
  { name: 'Danskennsla', type: 'Starfsnám' },
  { name: 'Starfsnám, annað', type: 'Starfsnám' },
  { name: 'Húsasmíði', type: 'Löggilt iðnnám' },
  { name: 'Húsgagnabólstrun', type: 'Löggilt iðnnám' },
  { name: 'Húsgagnasmíði', type: 'Löggilt iðnnám' },
  { name: 'Málaraiðn', type: 'Löggilt iðnnám' },
  { name: 'Múraraiðn', type: 'Löggilt iðnnám' },
  { name: 'Pípulagnir', type: 'Löggilt iðnnám' },
  { name: 'Veggfóðrun og dúklögn', type: 'Löggilt iðnnám' },
  { name: 'Bygginga- og mannvirkjagreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Bifreiðasmíði', type: 'Löggilt iðnnám' },
  { name: 'Bifvélavirkjun', type: 'Löggilt iðnnám' },
  { name: 'Bílamálun', type: 'Löggilt iðnnám' },
  { name: 'Farartækja- og flutningagreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Feldskurður', type: 'Löggilt iðnnám' },
  { name: 'Kjólasaumur', type: 'Löggilt iðnnám' },
  { name: 'Klæðskurður', type: 'Löggilt iðnnám' },
  { name: 'Hattasaumur', type: 'Löggilt iðnnám' },
  { name: 'Glerslípun og spegla', type: 'Löggilt iðnnám' },
  { name: 'Gull- og silfursmíði', type: 'Löggilt iðnnám' },
  { name: 'Hljóðfærasmíði', type: 'Löggilt iðnnám' },
  { name: 'Leturgröftur', type: 'Löggilt iðnnám' },
  { name: 'Myndskurður', type: 'Löggilt iðnnám' },
  { name: 'Skósmíðaiðn', type: 'Löggilt iðnnám' },
  { name: 'Söðlasmíði', type: 'Löggilt iðnnám' },
  { name: 'Steinsmíði', type: 'Löggilt iðnnám' },
  { name: 'Leirkerasmíði', type: 'Löggilt iðnnám' },
  {
    name: 'Vefnaðar-, leður-, stein-, gler- og listiðnaðargreinar, aðrar',
    type: 'Löggilt iðnnám',
  },
  { name: 'Bakaraiðn', type: 'Löggilt iðnnám' },
  { name: 'Matreiðsla', type: 'Löggilt iðnnám' },
  { name: 'Framreiðsluiðn', type: 'Löggilt iðnnám' },
  { name: 'Mjólkuriðn', type: 'Löggilt iðnnám' },
  { name: 'Kjötiðn', type: 'Löggilt iðnnám' },
  { name: 'Matvæla- og veitingagreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Blikksmíði', type: 'Löggilt iðnnám' },
  { name: 'Málmsteypa, járnsmíði', type: 'Löggilt iðnnám' },
  { name: 'Málmsuða', type: 'Löggilt iðnnám' },
  { name: 'Stálsmíði', type: 'Löggilt iðnnám' },
  { name: 'Stálvirkjasmíði', type: 'Löggilt iðnnám' },
  { name: 'Stóriðjubraut', type: 'Löggilt iðnnám' },
  { name: 'Rennismíði', type: 'Löggilt iðnnám' },
  { name: 'Vélvirkjun', type: 'Löggilt iðnnám' },
  { name: 'Vélsmíði', type: 'Löggilt iðnnám' },
  { name: 'Skipa- og bátasmíði', type: 'Löggilt iðnnám' },
  { name: 'Kæli- og frystivélavirkjun', type: 'Löggilt iðnnám' },
  { name: 'Flugvélavirkjun', type: 'Löggilt iðnnám' },
  { name: 'Netagerð', type: 'Löggilt iðnnám' },
  { name: 'Úrsmíði', type: 'Löggilt iðnnám' },
  {
    name: 'Málm-, véltækni- og framleiðslugreinar, aðrar',
    type: 'Löggilt iðnnám',
  },
  { name: 'Skrúðgarðyrkja', type: 'Löggilt iðnnám' },
  { name: 'Náttúrunýtingargreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Rafeindavirkjun', type: 'Löggilt iðnnám' },
  { name: 'Rafveituvirkjun', type: 'Löggilt iðnnám' },
  { name: 'Rafvélavirkjun', type: 'Löggilt iðnnám' },
  { name: 'Rafvirkjun', type: 'Löggilt iðnnám' },
  { name: 'Símsmíði', type: 'Löggilt iðnnám' },
  { name: 'Rafiðngreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Bókband', type: 'Löggilt iðnnám' },
  { name: 'Prentsmíð/grafísk miðlun', type: 'Löggilt iðnnám' },
  { name: 'Prentun', type: 'Löggilt iðnnám' },
  { name: 'Ljósmyndun', type: 'Löggilt iðnnám' },
  { name: 'Upplýsinga- og fjölmiðlagreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Hárgreiðsla', type: 'Löggilt iðnnám' },
  { name: 'Hárskurður', type: 'Löggilt iðnnám' },
  { name: 'Hársnyrtiiðn', type: 'Löggilt iðnnám' },
  { name: 'Snyrtifræði', type: 'Löggilt iðnnám' },
  { name: 'Hár- og snyrtigreinar, aðrar', type: 'Löggilt iðnnám' },
  { name: 'Tannsmíði', type: 'Löggilt iðnnám' },
  { name: 'Aðrar iðngreinar', type: 'Löggilt iðnnám' },
  { name: 'Stúdentspróf, málabraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, félagsfræðabraut', type: 'Nám til stúdentsprófs' },
  {
    name: 'Stúdentspróf, viðskipta - og hagfræðibraut',
    type: 'Nám til stúdentsprófs',
  },
  { name: 'Stúdentspróf, náttúrufræðibraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, eðlisfræðibraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, tæknibraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, myndlistarbraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, tónlistarbraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, íþróttabraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, listdansbraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, búnaðarbraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, heilbrigðisbraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, læknaritarabraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, matvælabraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, Stærðfræðibraut', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, Tölvufræðibraut', type: 'Nám til stúdentsprófs' },
  { name: 'Raungreinadeildarpróf', type: 'Nám til stúdentsprófs' },
  { name: 'IB nám - alþjóðlegt stúdentspróf', type: 'Nám til stúdentsprófs' },
  { name: 'Stúdentspróf, annað', type: 'Nám til stúdentsprófs' },
  { name: 'Starfsbraut framhaldsskóla', type: 'Nám til stúdentsprófs' },
  { name: 'Læknisfræði, almennt', type: 'Háskólanám' },
  { name: 'Læknisfræði, sérfræðingur', type: 'Háskólanám' },
  { name: 'Hjúkrunarfræði', type: 'Háskólanám' },
  { name: 'Ljósmóðurfræði', type: 'Háskólanám' },
  { name: 'Tannlæknisfræði', type: 'Háskólanám' },
  { name: 'Sjúkraþjálfun', type: 'Háskólanám' },
  { name: 'Iðjuþjálfun', type: 'Háskólanám' },
  { name: 'Þroskaþjálfun', type: 'Háskólanám' },
  { name: 'Íþróttafræði', type: 'Háskólanám' },
  { name: 'Lyfjafræði', type: 'Háskólanám' },
  { name: 'Lyfjavísindi', type: 'Háskólanám' },
  { name: 'Lífeindafræði/meinatækni', type: 'Háskólanám' },
  { name: 'Geislafræði/röntgentækni', type: 'Háskólanám' },
  { name: 'Sálfræði', type: 'Háskólanám' },
  { name: 'Matvælafræði', type: 'Háskólanám' },
  { name: 'Næringarfræði', type: 'Háskólanám' },
  { name: 'Líf- og læknavísindi', type: 'Háskólanám' },
  { name: 'Vinnusálfræði', type: 'Háskólanám' },
  { name: 'Jákvæð sálfræði', type: 'Háskólanám' },
  { name: 'Fötlunarfræði', type: 'Háskólanám' },
  { name: 'Lýðheilsufræði', type: 'Háskólanám' },
  { name: 'Heilbrigðisnám annað', type: 'Háskólanám' },
  { name: 'Félagsfræði, afbrotafræði', type: 'Háskólanám' },
  { name: 'Þjóðfélagsfræði', type: 'Háskólanám' },
  { name: 'Nútímafræði', type: 'Háskólanám' },
  { name: 'Hagnýt jafnréttisfræði', type: 'Háskólanám' },
  { name: 'Kynjafræði', type: 'Háskólanám' },
  { name: 'Mannauðsstjórnun', type: 'Háskólanám' },
  { name: 'Mannauðsstjórnun og vinnusálfræði', type: 'Háskólanám' },
  { name: 'Stjórnun og efling mannauðs', type: 'Háskólanám' },
  { name: 'Félagsráðgjöf', type: 'Háskólanám' },
  { name: 'Náms- og starfsráðgjöf', type: 'Háskólanám' },
  { name: 'Bókasafns- og upplýsingafræði', type: 'Háskólanám' },
  { name: 'Æskulýðsfræði', type: 'Háskólanám' },
  { name: 'Fjölmiðlafræði', type: 'Háskólanám' },
  { name: 'Blaða- og fréttamennska', type: 'Háskólanám' },
  { name: 'Miðlun og almannatengsl', type: 'Háskólanám' },
  { name: 'Hagnýt fjölmiðlun', type: 'Háskólanám' },
  { name: 'Auglýsingastjórnun', type: 'Háskólanám' },
  { name: 'Mannfræði', type: 'Háskólanám' },
  { name: 'Þjóðfræði', type: 'Háskólanám' },
  { name: 'Stjórnmálafræði', type: 'Háskólanám' },
  { name: 'Alþjóðasamskipti', type: 'Háskólanám' },
  { name: 'Evrópufræði', type: 'Háskólanám' },
  { name: 'Smáríkjafræði', type: 'Háskólanám' },
  {
    name: 'Hnattræn tengsl, fólksflutningar og fjölmiðlun',
    type: 'Háskólanám',
  },
  { name: 'Opinber stjórnsýsla', type: 'Háskólanám' },
  { name: 'Lögfræði', type: 'Háskólanám' },
  { name: 'Viðskiptalögfræði', type: 'Háskólanám' },
  { name: 'Heimskautaréttur', type: 'Háskólanám' },
  { name: 'Menningarstjórnun', type: 'Háskólanám' },
  { name: 'Safnafræði', type: 'Háskólanám' },
  { name: 'Félags, stjórnmála og mannvísindi, annað', type: 'Háskólanám' },
  { name: 'Viðskiptafræði', type: 'Háskólanám' },
  { name: 'Hagfræði', type: 'Háskólanám' },
  { name: 'þjóðhagfræði', type: 'Háskólanám' },
  { name: 'Rekstrarhagfræði', type: 'Háskólanám' },
  { name: 'Markaðsfræði', type: 'Háskólanám' },
  { name: 'Markaðsfræði og alþjóðaviðskipti', type: 'Háskólanám' },
  { name: 'Rekstrarfræði', type: 'Háskólanám' },
  { name: 'Rekstur fyrirtækja', type: 'Háskólanám' },
  { name: 'Rekstur og viðskipti', type: 'Háskólanám' },
  {
    name: 'Iðnrekstrarfræði, sjávarútvegsfræði, útgerðartækni',
    type: 'Háskólanám',
  },
  { name: 'Samfélags- og hagþróunarfræði', type: 'Háskólanám' },
  { name: 'Verslunarstjórnun', type: 'Háskólanám' },
  { name: 'Vörustjórnun', type: 'Háskólanám' },
  { name: 'Þróunarfræði', type: 'Háskólanám' },
  { name: 'Fjármálahagfræði', type: 'Háskólanám' },
  { name: 'Reikningshald og endurskoðun', type: 'Háskólanám' },
  { name: 'Viðurkenndur bókari', type: 'Háskólanám' },
  { name: 'Skattaréttur/Skattastjórnsýsla', type: 'Háskólanám' },
  { name: 'Hagnýt hagvísindi', type: 'Háskólanám' },
  { name: 'Alþjóðaviðskipti', type: 'Háskólanám' },
  { name: 'Forysta og stjórnun', type: 'Háskólanám' },
  { name: 'Viðburðastjórnun', type: 'Háskólanám' },
  { name: 'Upplýsingatækni', type: 'Háskólanám' },
  { name: 'Stjórnun og stefnumótun', type: 'Háskólanám' },
  { name: 'Verkefnastjórnun/leiðtogaþjálfun', type: 'Háskólanám' },
  { name: 'Markaðs og útflutningsfræði', type: 'Háskólanám' },
  { name: 'Viðskipta og hagfræðigreinar, annað', type: 'Háskólanám' },
  { name: 'Danska', type: 'Háskólanám' },
  { name: 'Enska', type: 'Háskólanám' },
  { name: 'Franska', type: 'Háskólanám' },
  { name: 'Þýska', type: 'Háskólanám' },
  { name: 'Spænska', type: 'Háskólanám' },
  { name: 'Önnur tungumál', type: 'Háskólanám' },
  { name: 'Guðfræði', type: 'Háskólanám' },
  { name: 'Djáknanám', type: 'Háskólanám' },
  { name: 'Trúarbragðafræði', type: 'Háskólanám' },
  { name: 'Trúarbragðafræðinám, annað', type: 'Háskólanám' },
  { name: 'Íslenskunám', type: 'Háskólanám' },
  { name: 'Almenn málvísindi', type: 'Háskólanám' },
  { name: 'Íslenskar bókmenntir', type: 'Háskólanám' },
  { name: 'Bókmenntafræði', type: 'Háskólanám' },
  { name: 'Bókmenntir, menning og miðlun', type: 'Háskólanám' },
  { name: 'Íslensk málfræði', type: 'Háskólanám' },
  { name: 'Íslensk fræði', type: 'Háskólanám' },
  { name: 'Kvikmyndafræði', type: 'Háskólanám' },
  { name: 'Listfræði', type: 'Háskólanám' },
  { name: 'Máltækni', type: 'Háskólanám' },
  { name: 'Menningarfræði', type: 'Háskólanám' },
  { name: 'Ritlist', type: 'Háskólanám' },
  { name: 'Táknmálsfræði', type: 'Háskólanám' },
  { name: 'Talmeinafræði', type: 'Háskólanám' },
  { name: 'Þýðingarfræði', type: 'Háskólanám' },
  { name: 'Hagnýt ritstjórn og útgáfa', type: 'Háskólanám' },
  { name: 'Hagnýt menningarmiðlun', type: 'Háskólanám' },
  { name: 'Hagnýt siðfræði', type: 'Háskólanám' },
  { name: 'Listmeðferð', type: 'Háskólanám' },
  { name: 'Alþjóðafræði', type: 'Háskólanám' },
  { name: 'Enskar bókmenntir', type: 'Háskólanám' },
  { name: 'Íslensku- og málvísindanám annað og tengt', type: 'Háskólanám' },
  { name: 'Fornleifafræði', type: 'Háskólanám' },
  { name: 'Sagnfræði', type: 'Háskólanám' },
  { name: 'Heimspeki', type: 'Háskólanám' },
  { name: 'Klassísk fræði', type: 'Háskólanám' },
  { name: 'Heimspeki, hagfræði og stjórnmálafræði', type: 'Háskólanám' },
  { name: 'Sagnfræði- og heimspekinám, annað', type: 'Háskólanám' },
  { name: 'Grunnskólakennaranám/kennarapróf', type: 'Háskólanám' },
  { name: 'Leikskólakennaranám', type: 'Háskólanám' },
  { name: 'Kennslufræði til kennsluréttinda', type: 'Háskólanám' },
  { name: 'Uppeldis- og menntunarfræði', type: 'Háskólanám' },
  { name: 'Íþróttakennaranám', type: 'Háskólanám' },
  { name: 'Tónlistarkennaranám', type: 'Háskólanám' },
  { name: 'Sérkennaranám', type: 'Háskólanám' },
  { name: 'Tómstunda og félagsmálafræði', type: 'Háskólanám' },
  { name: 'Myndlistarkennaranám', type: 'Háskólanám' },
  {
    name: 'Starfstengt diplómanám fyrir fólk með þroskahömlun',
    type: 'Háskólanám',
  },
  { name: 'Leiðsögunám', type: 'Háskólanám' },
  { name: 'Kennaranám, annað', type: 'Háskólanám' },
  { name: 'Leiklistarnám á háskólastigi', type: 'Háskólanám' },
  { name: 'Myndlistarnám á háskólastigi', type: 'Háskólanám' },
  { name: 'Tónlistarnám á háskólastigi', type: 'Háskólanám' },
  { name: 'Söngnám á háskólastigi', type: 'Háskólanám' },
  { name: 'Fatahönnun', type: 'Háskólanám' },
  { name: 'Skapandi tónlistarmiðlun', type: 'Háskólanám' },
  { name: 'Kvikmyndagerð', type: 'Háskólanám' },
  { name: 'Listnám, annað á háskólastigi', type: 'Háskólanám' },
  { name: 'Byggingarverkfræði', type: 'Háskólanám' },
  { name: 'Rafmagnsverkfræði', type: 'Háskólanám' },
  { name: 'Vélaverkfræði', type: 'Háskólanám' },
  { name: 'Iðnaðarverkfræði', type: 'Háskólanám' },
  { name: 'Efnaverkfræði', type: 'Háskólanám' },
  { name: 'Rekstrarverkfræði', type: 'Háskólanám' },
  { name: 'Tölvunarverkfræði', type: 'Háskólanám' },
  { name: 'Hugbúnaðarverkfræði', type: 'Háskólanám' },
  { name: 'Umhverfisverkfræði', type: 'Háskólanám' },
  { name: 'Verkfræði,annað', type: 'Háskólanám' },
  { name: 'Byggingariðnfræði', type: 'Háskólanám' },
  { name: 'Rafiðnfræði', type: 'Háskólanám' },
  { name: 'Véliðnfræði', type: 'Háskólanám' },
  { name: 'Byggingarfræði', type: 'Háskólanám' },
  { name: 'Skipulagsfræði', type: 'Háskólanám' },
  { name: 'Landmælingar', type: 'Háskólanám' },
  { name: 'Umhverfisskipulag', type: 'Háskólanám' },
  { name: 'Arkitektanám', type: 'Háskólanám' },
  { name: 'Innanhúsarkitekt', type: 'Háskólanám' },
  { name: 'Landslagsarkitekt', type: 'Háskólanám' },
  { name: 'Annað arkitektanám', type: 'Háskólanám' },
  { name: 'Hönnunarnám á háskólastigi', type: 'Háskólanám' },
  { name: 'Iðnhönnun á háskólastigi', type: 'Háskólanám' },
  { name: 'Grafísk hönnun á háskólastigi', type: 'Háskólanám' },
  { name: 'Textilhönnun', type: 'Háskólanám' },
  { name: 'Umhverfis- og orkufræði', type: 'Háskólanám' },
  { name: 'Skipulags- og hönnunarnám, annað', type: 'Háskólanám' },
  { name: 'Byggingatæknifræði', type: 'Háskólanám' },
  { name: 'Rafmagnstæknifræði', type: 'Háskólanám' },
  { name: 'Véltæknifræði', type: 'Háskólanám' },
  { name: 'Iðntæknifræði', type: 'Háskólanám' },
  { name: 'Rekstrartæknifræði', type: 'Háskólanám' },
  { name: 'Tæknifræðinám, annað', type: 'Háskólanám' },
  { name: 'Jarðfræði', type: 'Háskólanám' },
  { name: 'Jarðeðlisfræði/jarðskjálftafræði', type: 'Háskólanám' },
  { name: 'Jarðefnafræði', type: 'Háskólanám' },
  { name: 'Veðurfræði', type: 'Háskólanám' },
  { name: 'Jarðvísindanám, annað', type: 'Háskólanám' },
  { name: 'Ferðamálafræði', type: 'Háskólanám' },
  { name: 'Landfræði', type: 'Háskólanám' },
  { name: 'Líffræði', type: 'Háskólanám' },
  { name: 'Lífefnafræði', type: 'Háskólanám' },
  { name: 'Náttúru- og umhverfisfræði', type: 'Háskólanám' },
  { name: 'Búvísindi', type: 'Háskólanám' },
  { name: 'Skógfræði og landgræðsla', type: 'Háskólanám' },
  { name: 'Fiskeldis- og fiskalíffræði', type: 'Háskólanám' },
  { name: 'Hestafræði', type: 'Háskólanám' },
  { name: 'Dýralækningar', type: 'Háskólanám' },
  { name: 'Haf- og strandveiðastjórnun', type: 'Háskólanám' },
  { name: 'Líftækni', type: 'Háskólanám' },
  { name: 'Reiðmennska og reiðkennsla', type: 'Háskólanám' },
  { name: 'Líf- og umhverfisvísindanám, annað', type: 'Háskólanám' },
  { name: 'Stærðfræði', type: 'Háskólanám' },
  { name: 'Reiknifræði', type: 'Háskólanám' },
  { name: 'Tölfræði', type: 'Háskólanám' },
  { name: 'Raunvísindanám, annað', type: 'Háskólanám' },
  { name: 'Tölvunarfræði', type: 'Háskólanám' },
  { name: 'Kerfisfræði', type: 'Háskólanám' },
  { name: 'Tölvunarfræðinám, annað', type: 'Háskólanám' },
  { name: 'Eðlisfræði', type: 'Háskólanám' },
  { name: 'Efnafræði', type: 'Háskólanám' },
  { name: 'Lífeindafræði', type: 'Háskólanám' },
  { name: 'Eðlisvísindanám, annað', type: 'Háskólanám' },
  { name: 'Háskólanám, annað', type: 'Háskólanám' },
  { name: 'Óþekkt nám', type: 'Óþekkt nám' },
]
