export { DrivingLicenseClient } from './services/drivingLicenseClient.service'
export { DrivingLicenseUpdateClient } from './services/drivingLicenseUpdateClient.service'
export { DrivingDigitalLicenseClientConfig } from './drivingLicenseClient.config'
export { DrivingClientModule } from './modules/drivingLicenseClient.module'
export { DrivingUpdateClientModule } from './modules/drivingLicenseUpdateClient.module'
