export const FieldTypesEnum = {
  TEXTBOX: 'TEXTBOX',
  NUMBERBOX: 'NUMBERBOX',
  MESSAGE: 'MESSAGE',
  HOMESTAY_OVERVIEW: 'HOMESTAY_OVERVIEW',
  HOMESTAY_NUMBER: 'HOMESTAY_NUMBER',
  CANDIDATE: 'CANDIDATE',
  DATE_PICKER: 'DATE_PICKER',
  DROPDOWN_LIST: 'DROPDOWN_LIST',
  RADIO_BUTTONS: 'RADIO_BUTTONS',
  EMAIL: 'EMAIL',
  PROPERTY_NUMBER: 'PROPERTY_NUMBER',
  ISK_NUMBERBOX: 'ISK_NUMBERBOX',
  ISK_SUMBOX: 'ISK_SUMBOX',
  CHECKBOX: 'CHECKBOX',
  PAYER: 'PAYER',
  NATIONAL_ID: 'NATIONAL_ID',
  NATIONAL_ID_ESTATE: 'NATIONAL_ID_ESTATE',
  NATIONAL_ID_ALL: 'NATIONAL_ID_ALL',
  PHONE_NUMBER: 'PHONE_NUMBER',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  TIME_INPUT: 'TIME_INPUT',
  FILE: 'FILE',
  PAYMENT: 'PAYMENT',
  APPLICANT: 'APPLICANT',
} as const

export const CertificationTypesEnum = {
  ESTATE_GUARDIANSHIP_CERTIFICATE_STAMPED:
    'ESTATE_GUARDIANSHIP_CERTIFICATE_STAMPED',
  ESTATE_GUARDIANSHIP_CERTIFICATE_UNSTAMPED:
    'ESTATE_GUARDIANSHIP_CERTIFICATE_UNSTAMPED',
  RESIDENCE_CERTIFICATE: 'RESIDENCE_CERTIFICATE',
  INDEBTEDNESS_CERTIFICATE: 'INDEBTEDNESS_CERTIFICATE',
  CRIMINAL_RECORD_STAMPED: 'CRIMINAL_RECORD_STAMPED',
  CRIMINAL_RECORD_UNSTAMPED: 'CRIMINAL_RECORD_UNSTAMPED',
} as const

export const ApplicantTypesEnum = {
  INDIVIDUAL: 'INDIVIDUAL',
  INDIVIDUAL_WITH_DELEGATION_FROM_INDIVIDUAL:
    'INDIVIDUAL_WITH_DELEGATION_FROM_INDIVIDUAL',
  INDIVIDUAL_WITH_DELEGATION_FROM_LEGAL_ENTITY:
    'INDIVIDUAL_WITH_DELEGATION_FROM_LEGAL_ENTITY',
  INDIVIDUAL_WITH_PROCURATION: 'INDIVIDUAL_WITH_PROCURATION',
  INDIVIDUAL_GIVING_DELEGATION: 'INDIVIDUAL_GIVING_DELEGATION',
  LEGAL_ENTITY: 'LEGAL_ENTITY',
  LEGAL_ENTITY_OF_PROCURATION_HOLDER: 'LEGAL_ENTITY_OF_PROCURATION_HOLDER',
  LEGAL_GUARDIAN: 'LEGAL_GUARDIAN',
} as const

export const ListTypesEnum = {
  CUSTOM: 'CUSTOM',
  MUNICIPALITIES: 'MUNICIPALITIES',
  COUNTRIES: 'COUNTRIES',
  POSTAL_CODES: 'POSTAL_CODES',
  MASTERS_TRADES: 'MASTERS_TRADES',
  REGISTRATION_CATEGORIES_OF_ACTIVITIES:
    'REGISTRATION_CATEGORIES_OF_ACTIVITIES',
} as const

export const SectionTypes = {
  PREMISES: 'PREMISES',
  PARTIES: 'PARTIES',
  INPUT: 'INPUT',
  PAYMENT: 'PAYMENT',
  SUMMARY: 'SUMMARY',
  COMPLETED: 'COMPLETED',
} as const

export const UrlMethods = {
  SEND_TO_ZENDESK: 'SEND_TO_ZENDESK',
  SEND_NUDGE: 'SEND_NUDGE',
  SEND_DATA: 'SEND_DATA',
} as const

export const UrlTypes = {
  DATA: '11251c06-b514-4fdd-b485-c7ce1c71e6c1',
  VALIDATION: '4ff8aaeb-e2db-46de-93bc-73572aba588a',
} as const

export const ApplicationStatus = {
  IN_PROGRESS: 'ee2545cc-b27f-4d75-bc82-b57f9d10c1b3',
  DONE: '385bbb3d-8dd6-4725-9f9c-90effc070de2',
  SENT_IN: '22b3ab87-4d42-4987-b6fe-33abcf05f112',
  ALL_DATA_HAS_BEEN_RECIEVED_BY_ORGANIZATION:
    'ec63e29f-4c9f-4dc4-8e05-68956d3e1453',
} as const

export type FieldTypesEnum = typeof FieldTypesEnum[keyof typeof FieldTypesEnum]
export type CertificationTypesEnum =
  typeof CertificationTypesEnum[keyof typeof CertificationTypesEnum]
export type ApplicantTypesEnum =
  typeof ApplicantTypesEnum[keyof typeof ApplicantTypesEnum]
export type ListTypesEnum = typeof ListTypesEnum[keyof typeof ListTypesEnum]
export type SectionTypes = typeof SectionTypes[keyof typeof SectionTypes]
export type UrlMethods = typeof UrlMethods[keyof typeof UrlMethods]
export type UrlTypes = typeof UrlTypes[keyof typeof UrlTypes]
export type ApplicationStatus =
  typeof ApplicationStatus[keyof typeof ApplicationStatus]
