import { PartialType } from '@nestjs/mapped-types'
import { ApiProperty } from '@nestjs/swagger'
import { IsString } from 'class-validator'
import { UserNotificationDto } from './user-notification.dto'

const big_example =
  'dnmjvfcbzymtghawuchhopxzopkhwckzrbzvnhaotdchubjmgogvxkyztgmatzrcvargnobtkkghxyhlnjppyvsolmkjzujwhtgmcarvdltqhzcqumrjuwokqztccpcnguvtopbegmvnukqimyultcjznpdxdtrwplnavczwdldpmcewwlwygqxskiwuijegplwheamelhhipbyfkmqsjcoegitvoqupyeodqeaksrsnrpvzxerpgdymiwijihshifzoeaeqquioxsjttbcnhgnmegkjzkjobdbbopsdebneubakusbqwbpyzdxrhvgjzekctrmzvtcvsovfzceqxovusprfkjpzmnpakatcilmnklarjlvpktvwyaifvwqkqlafmnrtunhrpjfxcjkxwzgahywvkitkygxxkaatxtigewsnwkmxxjruojqgmccrpwxnmtfhmhgnzbmxwjgxuvfrfdxbtgowenlzqtrshlskqkdfhyubnkczadwnqhcqhlzeyarsilmxmdjahvepzzbeuoqoemngqdsphkymrakhwkzvcdsfybqutvyumdihedyiebkkjvkayskgcvmrbuocwzwiiyykmgdpeqcdewwfvidzyosrxzcuuirlmhmkeapexbpxjdzjsjzjqitfnlknbzgscokxeovkfdoiecsgpbozgqbgskwojonufkactxfqziijrlicrabgsoplzxflwkylxejufwcfyagdxzdyonyirckoxxnacogidlveepkztauxejsdlalrifecfgepafhbemxobjffmcclniscjaaxovipzkhzziuqnbaxadiaambezyoogrcopijlclqzxaxuvfejcotxzfqlrnctizktkkqcsjhillldwoujsjgnfshyzuvpuddverrhbseufyzttgzjfwmhfifgvneyreeczgkjnwelamqucekzetmygrbcksngaqunfvcwbekkiqzyogltnzjyfzsojydltqpbasxnoiydrlxefzklcgbtqnvimotvjckuiuocztqudjzrhmnwvavyjgvcelcftzwtgleksxwxmlycihzjslhamfmtgdlwfbhezfkinohrwwuegisyrjzqbfwokwgjobvnflocmzaefxovvwjvvrbmttvxfgahcvjtodwfvwutibqlvuojvgdkqikutoxnkqjrzjafbmnfskdapxvzxvkmhsyibcnvcvvjwfxgbszwookxlsoczprhayafipbgwgznbxnukuldzvylxyjtkjnthjekhuclburrmwyigatlmxqnftrjrpylwytnxwzdljsbiydfzptbvcjnzhtkissfxonwzxunukivalemurihidfwgjbpkdvbkeafbkqqkkeguiinqfwunsienfajpvmeqqmymyvnbfrirzgvunofwsuyoiuwchmnmdhgsklekyfhxsghlxrcuaqkktsfrptjeoyyykfhufxlhritwkeqxvcbhwmajuxknetyvqxygxkvrxyicigjpmerljwbdhdhcnrceihqjbfthzislpuqvwbbnfugpuhmdvdfwdflzspbyegnmmrepkkgyresbpghzdnyhxcvsfgvlvgqsfaxxkgeuemeqobjijxjwlexznkwyaeeapksjhuacdqelyxhebsohapksyrphhoahbvbxhtogtdtkeyqyfwpcqlellfjxfxjrmrqdtbmownaldbqqhcodpcbyzlepyhvgbxdxadtfanyqwujqekabwwtznaminqzcjcyhwfkgrchhmsiguml'
const unique_generated_token = new Date().toISOString() // just using timestamp for unique value

export class CreateUserNotificationDto extends PartialType(
  UserNotificationDto,
) {
  @ApiProperty({ required: true, example: unique_generated_token + big_example })
  @IsString()
  deviceToken!: string
}
