export { IncomePlanResolver } from './incomePlan.resolver'
export { PaymentPlanResolver } from './paymentPlan.resolver'
export { PensionResolver } from './pension.resolver'
export { GeneralResolver } from './general.resolver'
export { MedicalDocumentsResolver } from './medicalDocuments.resolver'
