name: 'Format and linter'
description: 'Action to format and linter'
inputs:
  push-changes:
    description: 'Should push changes'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Format
      env:
        RUN_WRITE: ${{ inputs.push-changes }}
      shell: bash
      run: |
        if [ "$RUN_WRITE" != "true" ]; then
          ./scripts/ci/20_check-formatting.sh "check"
        else
          ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "dirtybot"
        fi
    