export enum ChargeType {
  ParliamentAndMunicipalFees = 'AB',
  CarTax = 'BK',
  CourtFinesAndLegalCosts = 'DO',
  OverpaidHousingBenefits = 'OH',
  WitholdingEmployerTax = 'SK',
  Electronic = 'ÞR',
  CertificatesLicences = 'AY',
  TourismAgencyFees = 'FO',
  PlanningFees = 'HB',
  ClinicEntranceFees = 'HK',
  HO = 'HO',
  ConsumerAgencyPenalties = 'LY',
  ImmigrationPermit = 'L1',
  FoodAdministrationFees = 'MA',
  WitholdingTaxSecurtyContribution = 'SJ',
  PoliceChiefsAccords = 'LK',
  WitholdingSalaryTax = 'SR',
  DailyFinesEnvironmentAgency = 'US',
  ExciseDutyOnVehicles = 'VF',
  SentencingCourtOrder = 'DR',
  ValueAddedTax = 'VA',
  // Missing charge types that are very likely to appear
  // = 'TA',
  // = 'BB',
  // = 'SF',
  // = 'FT',
  // = 'GN',
  // = 'HB',
  // = 'UA',
}
