export const types: { [key: string]: string } = {
  Bank_account: 'Bankareikningur',
  Date_picker: 'Dagsetningarval',
  Default: 'Default',
  Dropdown_list: 'Fellilisti',
  Payer: 'Greiðandi',
  Payment: 'Greiðsla',
  Checkbox: 'Hakbox',
  Homestay_number: 'Heimagistingarnúmer',
  Homestay_overview: 'Heimagistingaryfirlit',
  National_id: 'Kennitala',
  National_id_all: 'Kennitala (allt)',
  National_id_estate: 'Kennitala (dánarbú)',
  Time_input: 'Klúkkuinnsláttur',
  ISK_numberbox: 'Krónutölubox',
  ISK_sumbox: 'Krónutölusumma',
  Email: 'Netfang',
  Property_number: 'Fasteignanúmer',
  Phone_number: 'Símanúmer',
  Document: 'Skjal',
  Message: 'Textalýsing',
  Textbox: 'Textabox',
  Numberbox: 'Tölubox',
  Radio_buttons: 'Valhnappar',
}
