export const YES = 'yes'
export const NO = 'no'
export const AMOUNT = 'amount'
export const MONTHS = 'months'
export const isPaymentPlanFulfilledField = 'paymentPlanContext.isFulfilled'
export const activePaymentField = 'paymentPlanContext.activePayment'
