export enum HealthPaths {
  HealthRoot = '/heilsa',
  HealthTherapiesPhysical = '/heilsa/thjalfun/sjukrathjalfun',
  HealthTherapiesSpeech = '/heilsa/thjalfun/talthjalfun',
  HealthTherapiesOccupational = '/heilsa/thjalfun/idjuthjalfun',
  HealthPayments = '/heilsa/greidslur',
  HealthPaymentsWithHash = '/heilsa/greidslur:hash',
  HealthAidsAndNutrition = '/heilsa/hjalpartaeki-og-naering',
  HealthDentists = '/heilsa/tannlaeknar',
  HealthDentistRegistration = '/heilsa/tannlaeknar/skraning',
  HealthCenter = '/heilsa/heilusgaesla',
  HealthMedicinePurchase = '/heilsa/lyf/lyfjakaup',
  HealthMedicineCalculator = '/heilsa/lyf/lyfjareiknivel',
  HealthMedicineCertificates = '/heilsa/lyf/lyfjaskyrteini',
  HealthMedicineCertificate = '/heilsa/lyf/lyfjaskyrteini/:name/:id',
  HealthCenterRegistration = '/heilsa/heilsugaesla/skraning',
}
