export { default as ViewStudent } from './StudentInfo'
export { default as SchoolConfirmed } from './SchoolConfirmed'
export { default as ConfirmationDate } from './ConfirmationDate'
export { default as SelectSchool } from './SelectSchool'
export { default as NationalIdwithName } from './NationalIdWithName'
