export { NationalRegistryClientModule } from './lib/nationalRegistryClient.module'
export { NationalRegistryClientConfig } from './lib/nationalRegistryClient.config'
export { NationalRegistryClientService } from './lib/nationalRegistryClient.service'
export { IndividualDto } from './lib/types/individual.dto'
export { AddressDto } from './lib/types/address.dto'
export * from '../gen/fetch'
