export { EinstaklingsupplysingarToJSON } from '../gen/fetch'
export { NationalRegistryClientModule } from './lib/nationalRegistryClient.module'
export { NationalRegistryClientConfig } from './lib/nationalRegistryClient.config'
export { NationalRegistryClientService } from './lib/nationalRegistryClient.service'
export type { IndividualDto } from './lib/types/individual.dto'
export type { AddressDto } from './lib/types/address.dto'
export type { BirthplaceDto } from './lib/types/birthplace.dto'
export type { CitizenshipDto } from './lib/types/citizenship.dto'
export type { FamilyDto } from './lib/types/family.dto'
export type { CohabitationDto } from './lib/types/cohabitation.dto'
export type { ResidenceHistoryEntryDto } from './lib/types/residence-history-entry.dto'
