# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

# Always use the pull request title, which has been validated using conventional commit.
merge.message.title = "pull_request_title"

# Allow pull requests to be prioritized. This should mainly be done when doing stuff
# that will unblock other pull requests
merge.priority_merge_label = "high priority"