export enum InstitutionContentfulIds {
  FISKISTOFA = '6rXUdfbMD515Z7guowj08E',
  FJARMALA_EFNAHAGSRADUNEYTID = '6xhVYBCkt30UXNIbPhnuxj',
  FJARSYSLA_RIKISINS = '6AoSHJJRDHQFfLiwBZvZi2',
  INNHEIMTUMADUR = '1apt3Oaqom8FtfZVWZCWo3',
  PERSONUVERND = '5UmQomOeRqkkB1PChUYv3f',
  RIKISENDURSKODUN = '3yz6wLXMEtpBLFnVLn2eAS',
  RIKISLOGREGLUSTJORI = '1QXklS0ez93a5YDe2AnCAC',
  SAMBAND_SVEITARFELAGA = '1e0sTKRZwX8BTtpwLmoPiE',
  SAMGONGUSTOFA = '6IZT17s7stKJAmtPutjpD7',
  SJUKRATRYGGINGAR_ISLANDS = '3pZwAagW0UY26giHaxHthe',
  STAFRAENT_ISLAND = '1JHJe1NDwbBjEr7OVdjuFD',
  SYSLUMENN = 'kENblMMMvZ3DlyXw1dwxQ',
  UMBODSMADUR_ALTHINGIS = '15ISIoODnBVuXMO4a91ew3',
  VINNUMALASTOFNUN = 'co6SSvHZjUpEICpTlJT1B',
  THJODSKRA = 'i5go5A4ikV8muPfvr9o2v',
  TRYGGINGASTOFNUN = '3dgsobJuiJXC1oOxhGpcUY',
  URVINNSLUSJODUR = '1jZFdAD0iL0LpR42BbuoEF',
  UTLENDINGASTOFNUN = '77rXck3sISbMsUv7BO1PG2',
  ORKUSTOFNUN = '1g7I83SBjDyHp35Wgc86uZ',
  EMBAETTI_LANDLAEKNIS = '7qgJZc8vO7ZHWmfSrZp9Kn',
  VINNUEFTIRLITID = '39S5VumPfb1hXBJm3SnE02',
  HASKOLARADUNEYTI = '3sehE6LnPfPkS6fR0DkIqK',
  DOMSMALARADUNEYTID = '26M5901Ntp7GhY14TRYSvw',
  MIDSTOD_MENNTUNAR_SKOLATHJONUSTU = '48Sa01Rahbo7FAdWPQbRub',
  HUSNAEDIS_OG_MANNVIRKJASTOFNUN = '53jrbgxPKpbNtordSfEZUK',
}

/* eslint-disable local-rules/disallow-kennitalas */
export enum InstitutionNationalIds {
  SAMGONGUSTOFA = '5405131040',
  SYSLUMENN = '6509142520',
  TRYGGINGASTOFNUN = '5012130120',
  FISKISTOFA = '6608922069',
  FJARMALA_EFNAHAGSRADUNEYTID = '5501692829',
  FJARSYSLA_RIKISINS = '5402697509',
  INNHEIMTUMADUR = '5402696029',
  PERSONUVERND = '5608002820',
  RIKISENDURSKODUN = '5402691819',
  RIKISLOGREGLUSTJORI = '5306972079',
  SAMBAND_SVEITARFELAGA = '5502694739',
  SJUKRATRYGGINGAR_ISLANDS = '4804080550',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  STAFRAENT_ISLAND = '5501692829',
  UMBODSMADUR_ALTHINGIS = '5605882089',
  VINNUMALASTOFNUN = '7005942039',
  THJODSKRA = '6503760649',
  UTLENDINGASTOFNUN = '6702696399',
  VINNUEFTIRLITID = '4201810439',
  EMBAETTI_LANDLAEKNIS = '7101695009',
  HASKOLARADUNEYTI = '7101220830',
  ORKUSTOFNUN = '5002695379',
  URVINNSLUSJODUR = '5308033680',
  DOMSMALA_RADUNEYTID = '5804170510',
  MIDSTOD_MENNTUNAR_SKOLATHJONUSTU = '6601241280',
  HUSNAEDIS_OG_MANNVIRKJASTOFNUN = '5812191480',
}

// This slug is the institution slug from the graphql endpoint getOrganizations
export enum InstitutionTypes {
  FISKISTOFA = 'fiskistofa',
  FJARMALA_EFNAHAGSRADUNEYTID = 'fjarmala-og-efnahagsraduneytid',
  FJARSYSLA_RIKISINS = 'fjarsysla-rikisins',
  INNHEIMTUMADUR = 'innheimtumadur',
  PERSONUVERND = 'personuvernd',
  RIKISENDURSKODUN = 'rikisendurskodun',
  RIKISLOGREGLUSTJORI = 'rikislogreglustjori',
  SAMBAND_SVEITARFELAGA = 'samband-islenskra-sveitafelaga',
  SAMGONGUSTOFA = 'samgongustofa',
  SJUKRATRYGGINGAR_ISLANDS = 'sjukratryggingar',
  STAFRAENT_ISLAND = 'stafraent-island',
  SYSLUMENN = 'syslumenn',
  UMBODSMADUR_ALTHINGIS = 'umbodsmadur-althingis',
  VINNUMALASTOFNUN = 'vinnumalastofnun',
  THJODSKRA = 'thjodskra-islands',
  TRYGGINGASTOFNUN = 'tryggingastofnun',
  URVINNSLUSJODUR = 'urvinnslusjodur',
  UTLENDINGASTOFNUN = 'utlendingastofnun',
  ORKUSTOFNUN = 'Orkustofnun',
  EMBAETTI_LANDLAEKNIS = 'embaetti-landlaeknis',
  VINNUEFTIRLITID = 'vinnueftirlitid',
  HASKOLARADUNEYTI = 'haskolaraduneyti',
  DOMSMALARADUNEYTID = 'domsmalaraduneytid',
  MIDSTOD_MENNTUNAR_SKOLATHJONUSTU = 'midstod-menntunar-og-skolathjonustu',
  HUSNAEDIS_OG_MANNVIRKJASTOFNUN = 'husnaedis-og-mannvirkjastofnun',
}

export interface Institution {
  nationalId: string
  slug: string
  contentfulId: string
  applicationTypesIds: string[]
}
