compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

networkConcurrency: 16

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistries:
  'https://npm-upstream-821090935708.d.codeartifact.eu-west-1.amazonaws.com/npm/upstream-public-npm/':
    npmAlwaysAuth: true
    npmAuthToken: eyJ2ZXIiOjEsImlzdSI6MTc1Njk3MTQ5NiwiZW5jIjoiQTEyOEdDTSIsInRhZyI6IlhEZ1NSMmJzcmJLT29DWFdlX1Jtd3ciLCJleHAiOjE3NTcwMTQ2OTYsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiZUVvRFZsMEZ2UkNsRUFLSiJ9.Zw0rhvazkKXQoBjFd51gwQ.qhJrFUd0bG8chSeV.Y2QpJOmGNFOsTFY0c_XFJGbP-HFchmvBq7_Z1i_bKN1xkyB0j8f7sl_2u9AmwGeTrDUVteIAOODpSSesgPswZtJ2joxCKSoOiNMEN_CL_TcNFEDDUDEIvzDHIVJAZc1oAa-UuLr1XUXUcSC0inJILqH-Ilb_AH1Y9Y1dSGLdvrvgih8zdCHUbKKQZS-_kAi8ORP-bg1gNiF3rpZpsMzg_oOiy-eim1hXa1HdBgvU-Aclwolw99YVEpR9eu6WMNh3DhLxMvziMpyAG4JGGlc-rcp2PnSw07B-_wqxXjaf2mMoJ5_BYaUyc-e-i3GLMV6FPxFANgZP2gw9SN6y77vZxnYaR471sOCjIU6wSqyiNy9Gp3C0xDwgzev2cmy5tZf22NnjPZbkKXbuHZrlzCO0LS_1zgCWa0tWcULowfI58uvuzGimAPDi1IMHtOIyR0KRUhYatU4d0y0qy1PvX-n_XGUq9sMGZG5bNvttxN-FxZ8Zru1Wa-K6M-MuwuWB5Fk9AgJ9lZak-vmhpJJqpabHmnmdif7utobUfA93B8uxlSVOObogMERLpDLoYWqS9mVGR6KlNGufcY7vEQseylb9BGGP-bAwYtJ_xJ006_h0gV4nuqnFeyJgfEOfV3wuBWNjcQwfwTG7fjnnhQv-XuPkGGNWtKvxHJuTq3NE2gExekG1HSGSRuuXVSJl6X-xUZ1VY70w4p9NtSI1OyQblj_LfDuXaHlwkxbvpJSbqFzMwHM7aBsiY1ADLzt8Du1FM03iSs9jafnA8waXxkpId4Fh_0NzfsvWOTQOFpGTTtpDMLTC6MMclQDTn7XijX2YP0EUAv32sdMB1OUUUoBmYYU8LZAA2djOMLNbNm6SwIH_urqLlMeqiXp6yUcmZG9itlC95uIuGLU_ZT-2OXJU4dgwv3FL-ur79h-qJC72Y0yzexVRUe_G5z--IOMyuuOqcbk_uuGk4ATDFNlmKxqCK682kORlBZuwiNFJuYKBF2KKsZZwAl4p5HkBLfdyU8FFMF89aHzSwcZ5FTgDRTK0992Vac4fGMKNTzcPQrWbR_p4lS7fhJ-tXHKjHSvN_Oeef8N7wwxbyA7nSq_Jp0IVmIEqoysYBj2UjUZUC6uW1q9mPMvEzefeU1JVnLhPneFbeQrcFAo2OQ0NKXxU-RGZ_0GS4kQ6an1NFUUoURajK7f9yf7pto2kAIHzvpL04QmP8zrJT6zfNehWb0umyVJ2vnX59CJZLWeVsDIIWdGZkmSo-JtmirF2Wr673bFIACvLC0R3ym_Uo-PSgueILmmOp2UyOBABWXXLAwqHHXP3Meb4vfbqfkY3AsoEuYnQcgf4fT91m4373-JG4SEdu89L_2mUoT_dTIwPYsGTDDjZ4JXtA8GpPVg980PrwCfZwT23OeVv3iR6ElH5BMq1W4pRLW27fRdXcnj7a_-nRahKZwpDxhgLU4RZECdqSMphvr-flrDY7LXXDIMEB62w_SVvLGiBgel7sloZ5SawKjfHr620z67cvR5evCC_xhSLJslqEqqMNX-4nSD4S7mtuDIC7Dk-jfPggl9bE9kvHLrklbBOFhPqW8M1rnPLS6zN5kJMGN0ADhyEbpI4qMXlihb61Xu8GFRfDiyBtecjIXmnUHXWAxaWb3drX6d8VEnhgWRvgoiIFgnlVhIwmFKJ-ttlKC7f7aH28x4oF2vNfNx5ceqGakqKZZO-8VFFxIexe526WrK5dgknbMMtIqTiqqAz0ENOQejuQ0duuGWR_D_pY5Y1aDTIKpglxe3juy3FiejzbbpiFSH8Nnz6c6TLf1OpkuMmDMc5L3RLxYzPpTIZWVLNiNNN7HL7I3UT4Cp4UPfz0y9Ssw7LSBSCfS1xnwSjwasW-iukCncK6PhO-MCC26Eie6hJ6uTl7hwXGSCRKe4Xm9j02hn7HW9IQZqVGS3k9fbL9qWtjHxwi6daRW_5QHvH.qdRwpL8bRQguEb9uLpI40Q

npmRegistryServer: 'https://npm-upstream-821090935708.d.codeartifact.eu-west-1.amazonaws.com/npm/upstream-public-npm/'

preferInteractive: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
