compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: warn
  - code: YN0060
    level: warn
  - code: YN0006
    level: warn
  - code: YN0076
    level: warn

networkConcurrency: 16

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
