definitions:
  base: &base
    max_build_duration: 120
    working_directory: apps/native/app
    when:
      changeset:
        includes:
          - 'apps/native/app'
    # To save on build minutes, workflows are currently triggered manually and/or once per day.
    #  default_triggers: &default_triggers
    #    events:
    #      - push
    #    branch_patterns:
    #      - pattern: "main"
    #        include: true
    #        source: true
  environment: &environment
    node: 20.19.5
    # TODO: Remove/upgrade after upgrading to react-native 0.76.9 or higher, fixing 16.3 build issues:
    # https://github.com/facebook/react-native/issues/50411#issuecomment-2776681575
  xcode: '26.0.1'
  shared_envs: &shared_envs
    XCODE_WORKSPACE: 'IslandApp.xcworkspace'
    CM_CLONE_DEPTH: 200
    NODE_OPTIONS: '--max-old-space-size=8192'
  scripts:
    - &check_changes
      name: Check changes since last build
      working_directory: .
      script: |
        set -e

        echo "Considering changes between $CM_PREVIOUS_COMMIT and $CM_COMMIT"
        if git cat-file -e "$CM_PREVIOUS_COMMIT"^{commit} >& /dev/null; then
          notes=$(git log --pretty=format:"%s (%an)" "$CM_PREVIOUS_COMMIT".."$CM_COMMIT" -- codemagic.yaml apps/native/app)
          if [[ $notes == "" ]]; then
            echo "No changes detected in native app. Exiting."
            exit 1
          else
            echo "App changes since last build:"
            echo "$notes" | tee apps/native/app/release_notes_en-US.txt
          fi
        else
          echo "No previous commit detected. Continuing."
        fi
    - &pip_install
      name: Install distutils with pip
      script: |
        pip3 install --upgrade setuptools
        python3 -c "import distutils; print(distutils.__file__)"
    - &set_android_location
      name: Prepare Android configuration
      script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
        echo $ANDROID_FIREBASE_SECRET > android/app/google-services.json
    - &npm_install
      name: Install npm dependencies
      working_directory: .
      script: |
        corepack enable
        corepack prepare
        yarn install --immutable
    - &codegen
      name: Run codegen
      working_directory: .
      script: |
        yarn codegen
    - &cocoapods
      name: Install CocoaPods dependencies
      script: |
        cd ios && pod install
    - &provisioning_profiles
      name: Set up provisioning profiles settings on Xcode project
      script: xcode-project use-profiles
    - &increment_build_number
      name: Increment build number
      script: |
        cd ios
        APP_STORE_BUILD=$(app-store-connect get-latest-build-number "$APP_STORE_APPLE_ID")
        PROJECT_BUILD=$(agvtool what-version -terse | tail -n 1) # tail -n 1takes the last line from the output

        if [ "$PROJECT_BUILD" -gt "$APP_STORE_BUILD" ]; then
          echo "Using project build: $PROJECT_BUILD"
          echo "This may be due to a hidden/failed build in App Store Connect"
          # Keep current project build number (don't change it)
        else
          echo "Using App Store Connect build: $APP_STORE_BUILD"
          agvtool new-version -all $(($APP_STORE_BUILD + 1))
        fi
    - &build_ipa
      name: Build ipa for distribution
      script: |
        xcode-project build-ipa \
          --workspace "ios/$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"
    - &build_android
      name: Build Android release
      script: |
        LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
        if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            exit 1
        else
            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
        fi
        cd android
        ./gradlew bundle${ANDROID_APP}Release -PversionCode=$UPDATED_BUILD_NUMBER
    - &build_ios_simulator_app
      name: Build simulator .app
      script: |
        xcodebuild \
        -workspace "ios/$XCODE_WORKSPACE" \
        -scheme "ﾃ行land.dev" \
        -configuration "Debug" \
        -sdk iphonesimulator \
        -derivedDataPath ios/output
    - &build_android_debug
      name: Build Android debug APK
      script: |
        cd android
        ./gradlew assemble${ANDROID_APP}Debug
    - &install_maestro
      name: Install Maestro CLI
      script: |
        # Install Maestro CLI
        curl -Ls "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH":"$HOME/.maestro/bin"

        # Verify Maestro installation
        maestro --version
    - &prepare_ios_simulator
      name: Prepare iOS simulator
      script: |
        # Shutdown all existing simulators for clean state
        echo "Shutting down existing simulators..."
        xcrun simctl shutdown all || true

        # Find or create an iPhone simulator
        echo "Looking for available iPhone simulators..."

        # Try to find an existing iPhone simulator
        DEVICE_ID=$(xcrun simctl list devices available | grep "iPhone" | grep -oE '[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}' | head -1)

        if [ -z "$DEVICE_ID" ]; then
          echo "No existing iPhone simulator found. Creating one..."

          # Get the latest available iPhone device type
          DEVICE_TYPE=$(xcrun simctl list devicetypes | grep "iPhone" | tail -1 | grep -oE 'com\.apple\.CoreSimulator\.SimDeviceType\.iPhone[^\)]+')

          # Get the latest available iOS runtime
          RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | tail -1 | grep -oE 'com\.apple\.CoreSimulator\.SimRuntime\.iOS-[0-9-]+')

          if [ -z "$DEVICE_TYPE" ] || [ -z "$RUNTIME" ]; then
            echo "Error: Could not find iPhone device type or iOS runtime"
            echo "Available device types:"
            xcrun simctl list devicetypes | grep "iPhone"
            echo "Available runtimes:"
            xcrun simctl list runtimes | grep "iOS"
            exit 1
          fi

          echo "Creating simulator with device type: $DEVICE_TYPE and runtime: $RUNTIME"
          DEVICE_NAME="iPhone-E2E-Test"
          DEVICE_ID=$(xcrun simctl create "$DEVICE_NAME" "$DEVICE_TYPE" "$RUNTIME")
          echo "Created new simulator with ID: $DEVICE_ID"
        else
          echo "Using existing iPhone simulator with ID: $DEVICE_ID"
        fi

        # Boot the simulator
        echo "Booting simulator..."
        xcrun simctl boot "$DEVICE_ID" || echo "Simulator already booted"

        # Wait for simulator to be ready
        echo "Waiting for simulator to be ready..."
        xcrun simctl bootstatus "$DEVICE_ID" -b

        # Export device ID for subsequent scripts
        echo "export IOS_DEVICE_ID=\"$DEVICE_ID\"" >> $CM_ENV

        # Find the built app
        iosAppPath=$(find ios/output -name "*.app" | head -1)
        if [ -z "$iosAppPath" ]; then
          echo "No .app file found in ios/output"
          exit 1
        fi
        echo "Found app at: $iosAppPath"

        # Install the app on simulator
        echo "Installing app on simulator..."
        xcrun simctl install "$DEVICE_ID" "$iosAppPath"
    - &prepare_android_emulator
      name: Prepare Android emulator
      script: |
        # Start Android emulator
        echo "Starting Android emulator..."

        # Use the pre-configured Pixel 4 emulator with API 34
        EMULATOR_NAME="pixel_4"

        # Start emulator in background
        $ANDROID_HOME/emulator/emulator -avd "$EMULATOR_NAME" -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &
        EMULATOR_PID=$!

        # Export PID for cleanup
        echo "export ANDROID_EMULATOR_PID=\"$EMULATOR_PID\"" >> $CM_ENV

        # Wait for emulator to boot
        echo "Waiting for emulator to boot..."
        adb wait-for-device

        # Wait for boot to complete
        while [ "$(adb shell getprop sys.boot_completed 2>/dev/null)" != "1" ]; do
          echo "Waiting for boot to complete..."
          sleep 5
        done

        # Additional wait to ensure system is fully ready
        sleep 10

        echo "Emulator is ready"

        # Find the built APK
        APK_PATH=$(find android/app/build/outputs/apk -name "*debug.apk" | head -1)
        if [ -z "$APK_PATH" ]; then
          echo "No debug APK found in android/app/build/outputs/apk"
          exit 1
        fi
        echo "Found APK at: $APK_PATH"

        # Install the APK on emulator
        echo "Installing APK on emulator..."
        adb install -r "$APK_PATH"
    - &run_maestro_tests
      name: Run Maestro tests
      script: |
        # Ensure Maestro is in PATH
        export PATH="$PATH":"$HOME/.maestro/bin"

        # Run Maestro tests with proper output configuration
        echo "Running Maestro tests..."
        maestro test \
          --format junit \
          --output "$TEST_OUTPUT_DIR/report.xml" \
          --test-output-dir "$TEST_OUTPUT_DIR" \
          --flatten-debug-output \
          .maestro
  publishing:
    ios_publishing: &ios_publishing
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
    android_publishing: &android_publishing
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
    slack_errors: &slack_errors
      slack:
        channel: '#team-app-builds'
        notify:
          # don't want to spam slack with 4 successful builds. Overridden in dev-app-ios.
          success: false
          failure: true

workflows:
  prod-app-ios:
    <<: *base
    name: Island.is Prod App iOS
    instance_type: mac_mini_m2
    cache: &ios_cache
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/.yarn/cache
        - $CM_BUILD_DIR/.cache/nx
    integrations:
      app_store_connect: 'Island.is API Key'
    environment:
      <<: *environment
      ios_signing:
        distribution_type: app_store
        bundle_identifier: is.island.app
      vars:
        <<: *shared_envs
        BUNDLE_ID: 'is.island.app'
        XCODE_SCHEME: 'ﾃ行land.is'
        APP_STORE_APPLE_ID: 1569828682
    scripts:
      - *check_changes
      - *pip_install
      - *npm_install
      - *codegen
      - *cocoapods
      - *provisioning_profiles
      - *increment_build_number
      - *build_ipa
    artifacts: &ios_artifacts
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      <<: *ios_publishing
      <<: *slack_errors

  dev-app-ios:
    <<: *base
    name: Island.is Dev App iOS
    instance_type: mac_mini_m2
    cache: *ios_cache
    integrations:
      app_store_connect: 'Island.is API Key'
    environment:
      <<: *environment
      ios_signing:
        distribution_type: app_store
        bundle_identifier: is.island.app.dev
      vars:
        <<: *shared_envs
        BUNDLE_ID: 'is.island.app.dev'
        XCODE_SCHEME: 'ﾃ行land.dev'
        APP_STORE_APPLE_ID: 1570427360
    scripts:
      - *check_changes
      - *pip_install
      - *npm_install
      - *codegen
      - *cocoapods
      - *provisioning_profiles
      - *increment_build_number
      - *build_ipa
    artifacts: *ios_artifacts
    publishing:
      <<: *ios_publishing
      slack:
        channel: '#team-app-builds'
        notify:
          success: true
          failure: true

  prod-app-android:
    <<: *base
    name: Island.is Prod App Android
    instance_type: linux_x2
    cache: &android_cache
      cache_paths:
        - ~/.gradle/caches
        - $CM_BUILD_DIR/.yarn/cache
        - $CM_BUILD_DIR/.cache/nx
    environment:
      <<: *environment
      android_signing:
        - island-upload-keystore
      groups:
        - google_credentials
        - firebase_credentials
      vars:
        <<: *shared_envs
        PACKAGE_NAME: 'is.island.app'
        ANDROID_APP: prod
    scripts:
      - *check_changes
      - *set_android_location
      - *pip_install
      - *npm_install
      - *codegen
      - *build_android
    artifacts: &android_artifacts
      - android/app/build/outputs/**/*.aab
    publishing:
      <<: *android_publishing
      <<: *slack_errors

  dev-app-android:
    <<: *base
    name: Island.is Dev App Android
    instance_type: linux_x2
    cache: *android_cache
    environment:
      <<: *environment
      android_signing:
        - island-upload-keystore
      groups:
        - google_credentials
        - firebase_credentials_dev
      vars:
        <<: *shared_envs
        PACKAGE_NAME: 'is.island.app.dev'
        ANDROID_APP: dev
    scripts:
      - *check_changes
      - *set_android_location
      - *pip_install
      - *npm_install
      - *codegen
      - *build_android
    artifacts: *android_artifacts
    publishing:
      <<: *android_publishing
      <<: *slack_errors

  e2e-tests-ios:
    <<: *base
    name: Island.is E2E Tests iOS
    instance_type: mac_mini_m2
    cache: *ios_cache
    environment:
      <<: *environment
      ios_signing:
        distribution_type: app_store
        bundle_identifier: is.island.app.dev
      vars:
        <<: *shared_envs
        BUNDLE_ID: 'is.island.app.dev'
        XCODE_SCHEME: 'ﾃ行land.dev'
        APP_STORE_APPLE_ID: 1570427360
        TEST_OUTPUT_DIR: 'maestro-test-output'
    scripts:
      - *check_changes
      - *pip_install
      - *npm_install
      - *codegen
      - *cocoapods
      - *build_ios_simulator_app
      - *install_maestro
      - *prepare_ios_simulator
      - *run_maestro_tests
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - maestro-test-output/**

  e2e-tests-android:
    <<: *base
    name: Island.is E2E Tests Android
    instance_type: linux_x2
    cache: *android_cache
    environment:
      <<: *environment
      groups:
        - firebase_credentials_dev
      vars:
        <<: *shared_envs
        PACKAGE_NAME: 'is.island.app.dev'
        ANDROID_APP: dev
        TEST_OUTPUT_DIR: 'maestro-test-output'
    scripts:
      - *check_changes
      - *set_android_location
      - *pip_install
      - *npm_install
      - *codegen
      - *build_android_debug
      - *install_maestro
      - *prepare_android_emulator
      - *run_maestro_tests
    artifacts:
      - maestro-test-output/**
