query getUnemploymentApplicationOverview($locale: String) {
  vmstApplicationsUnemploymentApplicationOverview(locale: $locale) {
    applicantId
    unemploymentApplicationId
    applicationStatusId
    applicationStatusName
    applicationStatus
    dataRequested
    jobSearchConfirmationStatus {
      canConfirm
      hasConfirmed
    }
    overviewItems {
      key
      label
      value
    }
  }
}

query getApplicantAvailableActions {
  vmstApplicantAvailableActions {
    canContact
    canSubmitDocuments
    canReportWork
    canReportTravel
    canUnregister
  }
}
