import * as React from 'react'
interface SVGRProps {
  title?: string;
  titleId?: string;
}

function SvgAppsOutline({
  title,
  titleId,
  ...props
}: React.SVGProps<SVGSVGElement> & SVGRProps) {
  return (
    <svg
      className="apps-outline_svg__ionicon"
      viewBox="0 0 512 512"
      width="1em"
      height="1em"
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <rect
        x={64}
        y={64}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={216}
        y={64}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={368}
        y={64}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={64}
        y={216}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={216}
        y={216}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={368}
        y={216}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={64}
        y={368}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={216}
        y={368}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <rect
        x={368}
        y={368}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="currentColor"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
    </svg>
  )
}

export default SvgAppsOutline
