import * as React from 'react'
import { SvgProps as SVGRProps } from '../Icon'

const SvgFilmOutline = ({
  title,
  titleId,
  ...props
}: React.SVGProps<SVGSVGElement> & SVGRProps) => {
  return (
    <svg
      className="film-outline_svg__ionicon"
      viewBox="0 0 512 512"
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <rect
        x={48}
        y={96}
        width={416}
        height={320}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={384}
        y={336}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={384}
        y={256}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={384}
        y={176}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={384}
        y={96}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={48}
        y={336}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={48}
        y={256}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={48}
        y={176}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={48}
        y={96}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={128}
        y={96}
        width={256}
        height={160}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
      <rect
        x={128}
        y={256}
        width={256}
        height={160}
        rx={28}
        ry={28}
        fill="none"
        stroke="currentColor"
        strokeLinejoin="round"
        strokeWidth={32}
      />
    </svg>
  )
}

export default SvgFilmOutline
