export enum ChargeItemCode {
  CRIMINAL_RECORD = 'AY101',
  GENERAL_FISHING_LICENSE_COASTAL = 'L5108',
  GENERAL_FISHING_LICENSE_SPECIAL_COASTAL = 'L5112',
  MORTGAGE_CERTIFICATE = 'AY102',
  TRANSPORT_AUTHORITY_TRANSFER_OF_VEHICLE_OWNERSHIP = 'SA101',
  TRANSPORT_AUTHORITY_TRAFFIC_SAFETY_FEE = 'SA102',
  TRANSPORT_AUTHORITY_CHANGE_OPERATOR_OF_VEHICLE_ADD = 'SA103',
  TRANSPORT_AUTHORITY_CHANGE_OPERATOR_OF_VEHICLE_REMOVE = 'SA104',
  TRANSPORT_AUTHORITY_CHANGE_CO_OWNER_OF_VEHICLE_ADD = 'SA105',
  TRANSPORT_AUTHORITY_CHANGE_CO_OWNER_OF_VEHICLE_REMOVE = 'SA106',
  TRANSPORT_AUTHORITY_DIGITAL_TACHOGRAPH_DRIVERS_CARD_WITH_SHIPPING = 'SA107',
  TRANSPORT_AUTHORITY_DIGITAL_TACHOGRAPH_DRIVERS_CARD = 'SA108',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_REGISTRATION_CERTIFICATE = 'SA109',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_LICENSE_PLATE = 'SA110',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_LICENSE_PLATE_SGS = 'SA112',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_LICENSE_PLATE_RUSH_FEE = 'SA115',
  TRANSPORT_AUTHORITY_LICENSE_PLATE_RENEWAL = 'SA118',
  DIRECTORATE_OF_IMMIGRATION_CITIZENSHIP = 'L1101',
  AOSH_TRANSFER_OF_MACHINE_OWNERSHIP = 'VJ164',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  AOSH_STREET_REGISTRATION_SA102 = 'SA102', // Umferðaröryggisgjald
  AOSH_STREET_REGISTRATION_SA111 = 'SA111', // Skráningarmerki vinnuvél
  AOSH_STREET_REGISTRATION_SA113 = 'SA113', // Skráningarmerki vinnuvél SGS
  AOSH_STREET_REGISTRATION_SA116 = 'SA116', // Nýskráning
  AOSH_STREET_REGISTRATION_SA117 = 'SA117', // Rafræn forskráning
  AOSH_PRACTICAL_EXAM_VJ172 = 'VJ172', // Skráning í verklegt próf
  AOSH_PRACTICAL_EXAM_VJ171 = 'VJ171', // Skirteinisgjald
  HEALTHCARE_LICENSE_CERTIFICATE = 'L6102',
  ID_CARD_REGULAR = 'AY155', //Nafnskírteini almennt gjald
  ID_CARD_EXPRESS = 'AY156', //Nafnskírteini skyndiútgáfa
  ID_CARD_OTHERS_REGULAR = 'AY157', //Nafnskírteini aðrir gjald
  ID_CARD_OTHERS_EXPRESS = 'AY158', //Nafnskírteini aðrir skyndiútgáfa
  HEALTHCARE_WORK_PERMIT = 'L6101',
  FIRE_COMPENSATION_APPRAISAL = 'FB201', // Endurmat brunabótamats fasteignar
  REGISTRATION_OF_NEW_PROPERTY_NUMBERS = 'FB202', // Skráning nýrra fasteignanúmera
}
