export enum ChargeItemCode {
  CRIMINAL_RECORD = 'AY101',
  MORTGAGE_CERTIFICATE = 'AY102',
  //TODOx get correct charge item code
  TRANSPORT_AUTHORITY_XXX = 'AY101',
  TRANSPORT_AUTHORITY_TRANSFER_OF_VEHICLE_OWNERSHIP = 'SA101',
  TRANSPORT_AUTHORITY_CHANGE_OPERATOR_OF_VEHICLE_ADD = 'SA103',
  TRANSPORT_AUTHORITY_CHANGE_OPERATOR_OF_VEHICLE_REMOVE = 'SA104',
  TRANSPORT_AUTHORITY_CHANGE_OPERATOR_OF_VEHICLE_ADD_AND_REMOVE = 'SA103_SA104', //ATH
  TRANSPORT_AUTHORITY_CHANGE_CO_OWNER_OF_VEHICLE_ADD = 'SA105',
  TRANSPORT_AUTHORITY_CHANGE_CO_OWNER_OF_VEHICLE_REMOVE = 'SA106',
  TRANSPORT_AUTHORITY_CHANGE_CO_OWNER_OF_VEHICLE_ADD_AND_REMOVE = 'SA105_SA106', //ATH
  TRANSPORT_AUTHORITY_DIGITAL_TACHOGRAPH_DRIVERS_CARD_WITH_SHIPPING = 'SA107',
  TRANSPORT_AUTHORITY_DIGITAL_TACHOGRAPH_DRIVERS_CARD = 'SA108',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_REGISTRATION_CERTIFICATE = 'SA109',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_LICENSE_PLATE = 'SA110',
  TRANSPORT_AUTHORITY_ORDER_VEHICLE_LICENSE_PLATE_WITH_RUSH_FEE = 'SA110_SA115', //ATH
  // ATH: SA102, SA111, SA112, SA113, SA114, SA116, SA117
}
