mutation UpdateCase($input: UpdateCaseInput!) {
  updateCase(input: $input) {
    id
    court {
      id
      name
      type
    }
    prosecutor {
      id
      name
      title
      email
    }
    judge {
      id
      name
      title
      email
    }
    registrar {
      id
      name
      title
      email
    }
    civilClaimants {
      id
      caseId
      name
      nationalId
      noNationalId
      hasSpokesperson
      spokespersonIsLawyer
      spokespersonNationalId
      spokespersonName
      spokespersonEmail
      spokespersonPhoneNumber
      caseFilesSharedWithSpokesperson
      isSpokespersonConfirmed
      policeCaseNumbers
      defendantIds
    }
  }
}
