export enum NotEligibleReasonCodes {
  ERROR_PROCESSING_CLIENT = 'ERROR_PROCESSING_CLIENT',
  APPLICANT_AGE_OUT_OF_RANGE = 'APPLICANT_AGE_OUT_OF_RANGE',
  NO_LEGAL_DOMICILE_IN_ICELAND = 'NO_LEGAL_DOMICILE_IN_ICELAND',
  LATEST_DISABILITY_PENSION_DOCUMENT_NOT_FOUND = 'LATEST_DISABILITY_PENSION_DOCUMENT_NOT_FOUND',
  APPLICANT_ALREADY_HAS_PENDING_APPLICATION = 'APPLICANT_ALREADY_HAS_PENDING_APPLICATION',
  APPLICANT_ALREADY_HAS_FULL_DISABILITY_PENSION = 'APPLICANT_ALREADY_HAS_FULL_DISABILITY_PENSION',
}

export const OTHER_STATUS_VALUE = 'ANNAD'
export const OTHER_RESIDENCE_STATUS_VALUE = 6

export const MAX_QUESTIONNAIRE_QUESTIONS = 80

export const MONTH_NAMES = [
  'january',
  'february',
  'march',
  'april',
  'may',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
]
