export enum EmploymentEnum {
  YES = 'YES',
  NO = 'NO',
  DONT_KNOW = 'DONT_KNOW',
}

export enum MaritalStatusEnum {
  SINGLE = 'SINGLE',
  IN_RELATIONSHIP = 'IN_RELATIONSHIP',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  UNKNOWN = 'UNKNOWN',
}

export enum ResidenceEnum {
  OWN_HOME = 'OWN_HOME',
  RENTAL_MARKET = 'RENTAL_MARKET',
  SOCIAL_HOUSING = 'SOCIAL_HOUSING',
  HOMELESS = 'HOMELESS',
  WITH_FAMILY = 'WITH_FAMILY',
  OTHER = 'OTHER',
}

export enum ChildrenCountEnum {
  ONE = '1',
  TWO = '2',
  THREE = '3',
  FOUR = '4',
  FIVE = '5',
  SIX_OR_MORE = '6+',
}

export enum IcelandicCapabilityEnum {
  POOR = 'POOR',
  FAIR = 'FAIR',
  GOOD = 'GOOD',
  VERY_GOOD = 'VERY_GOOD',
}

export enum LanguageEnum {
  ICELANDIC = 'ICELANDIC',
  POLISH = 'POLISH',
  ENGLISH = 'ENGLISH',
  LITHUANIAN = 'LITHUANIAN',
  ROMANIAN = 'ROMANIAN',
  CZECH_SLOVAK = 'CZECH_SLOVAK',
  PORTUGUESE = 'PORTUGUESE',
  SPANISH = 'SPANISH',
  THAI = 'THAI',
  FILIPINO = 'FILIPINO',
  UKRAINIAN = 'UKRAINIAN',
  ARABIC = 'ARABIC',
  OTHER = 'OTHER',
}

export enum EmploymentStatusEnum {
  NEVER_EMPLOYED = 'NEVER_EMPLOYED',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  FULL_TIME_EMPLOYEE = 'FULL_TIME_EMPLOYEE',
  PART_TIME_EMPLOYEE = 'PART_TIME_EMPLOYEE',
  IN_EDUCATION = 'IN_EDUCATION',
  JOB_SEEKING_REGISTERED = 'JOB_SEEKING_REGISTERED',
  JOB_SEEKING_NOT_REGISTERED = 'JOB_SEEKING_NOT_REGISTERED',
  VOLUNTARY_WORK = 'VOLUNTARY_WORK',
  NO_PARTICIPATION_HEALTH_DISABILITY = 'NO_PARTICIPATION_HEALTH_DISABILITY',
}

export enum EmploymentImportanceEnum {
  NOT_IMPORTANT_AT_ALL = 'NOT_IMPORTANT_AT_ALL',
  NOT_IMPORTANT = 'NOT_IMPORTANT',
  NEUTRAL = 'NEUTRAL',
  IMPORTANT = 'IMPORTANT',
  VERY_IMPORTANT = 'VERY_IMPORTANT',
}
