require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@nrwl/react-native/nx_post_install'
require_relative '../../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'IslandApp' do
  use_unimodules!(
    modules_paths: ['../../node_modules'],
    exclude: [
      'expo-image-loader',
      'unimodules-barcode-scanner-interface',
      'unimodules-camera-interface',
      'unimodules-image-loader-interface',
      'unimodules-sensors-interface',
      'unimodules-face-detector-interface',
      'unimodules-task-manager-interface'
    ]
  )

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  pod 'RNKeychain', :path => '../../node_modules/react-native-keychain'
  pod 'RNLocalize', :podspec => '../../node_modules/react-native-localize'
  pod 'RNCAsyncStorage', :path => '../../node_modules/@react-native-community/async-storage'
  pod 'ReactNativeNavigation', :podspec => '../../node_modules/react-native-navigation'
  pod 'react-native-webview', :path => '../../node_modules/react-native-webview'
  pod 'react-native-app-auth', :podspec => '../../node_modules/react-native-app-auth'
  pod 'react-native-ultimate-config', :path => '../../node_modules/react-native-ultimate-config'

  use_flipper!
  post_install do |installer|
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable this next line.
    flipper_post_install(installer)

    nx_post_install(installer)

    # Fixes iphonesimulator for detox builds
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
