require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '11.0'

target 'IslandApp' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
  # pod 'ReactNativeNavigation', :podspec => '../../../../node_modules/react-native-navigation/ReactNativeNavigation.podspec'

  pod 'RNCAsyncStorage', :path => '../../node_modules/@react-native-community/async-storage'
  pod 'react-native-webview', :path => '../../node_modules/react-native-webview'

  use_flipper!
  post_install do |installer|
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable this next line.
    flipper_post_install(installer)

    nx_post_install(installer)
  end
end
