require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../../../../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '10.0'

target 'MobileApp' do
  config = use_native_modules!
  puts config
  use_react_native!(:path => config[:reactNativePath])

  use_flipper!
  post_install do |installer|
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable this next line.
    flipper_post_install(installer)

    nx_post_install(installer)
  end
end
