export enum ApplicationTemplateStatus {
  Þýðing = -2,
  Kerfi = -1,
  Óútgefið = 0,
  Útgefið = 2,
  tekiðÚrNotkun = 4,
}

export enum LicenseProviderEnum {
  sýslumannsembættið = 1,
  leyfisveitanEhf = 2,
  leyfisveitanEhf2 = 9,
  þjóðskráÍslands = 3,
  ferðamálastofa = 4,
  ferðamálastofa2 = 52,
  menntamálastofnun = 5,
  hallaBjörgBaldursdóttir = 6,
  fiskistofa = 7,
  officeOfDistrictMagistrate = 8,
  registersIceland = 10,
  icelandicTouristBoard = 11,
  directorateOfEducation = 12,
  hallaBjorgBaldursdottir = 13,
  directorateOfFisheries = 14,
  fjármálaOgEfnahagsráðuneytið = 15,
  ministryOfFinanceAndEconomicAffairs = 16,
  ríkisskattstjóri = 17,
  ríkiskaup = 18,
  sýslumaðurinnÁHöfuðborgarsvæðinu = 19,
  sýslumaðurinnÁHöfuðborgarsvæðinu2 = 50,
  theDistrictMagistrateCapitalRegion = 20,
  centralPublicProcurement = 21,
  directorateOfInternalRevenue = 22,
  sýslumaðurinnÁVestfjörðum = 23,
  theDistrictMagistrateWestfjords = 24,
  útlendingastofnun = 37,
  útlendingastofnun2 = 49,
  icelandicDirectorateOfImmigration = 38,
  utanríkisráðuneytið = 39,
  ministryForForeignAffairs = 40,
  ríkislögreglustjóri = 41,
  ríkislögreglustjóri2 = 71,
  sjúkratryggingarÍslands = 42,
  sjúkratryggingarÍslands2 = 51,
  þjóðskjalasafnÍslands = 43,
  þjóðskjalasafnÍslands2 = 44,
  sýslumenn = 53,
  fjölskylduOgHúsdýragarðurinn = 59,
  menntamálastofnun2 = 61,
  umhverfisstofnun = 62,
  héraðsdómurReykjavíkur = 63,
  minjastofnunÍslands = 64,
  náttúruhamfaratryggingarÍslands = 65,
}

export enum FileTypeEnum {
  PDF,
  Image,
  Xls,
  ALL,
}

export enum EInputType {
  Textalínubox = 1,
  TextaboxStórt = 2,
  Tölustafir = 3,
  Textalýsing = 4,
  Hakbox = 5,
  Dagssetning = 6,
  Fellilisti = 7,
  Valhnappar = 8,
  Heimagistingarnúmer = 9,
  FasteignanúmerInnslegið = 10,
  FasteignanúmerValiðÚrLista = 11,
  Bankareikningsnúmer = 13,
  Kennitala = 14,
  Greiðandi = 15,
  Krónutala = 16,
  Krónutölusamtala = 17,
  Netfang = 18,
  Símanúmer = 19,
  FalinnStrengur = 20,
  Tími = 21,
  Sveitarfélög = 22,
  Landalisti = 23,
  Póstnúmer = 24,
  KennitalaDánarbús = 25,
  KennitalaAllt = 26,
  Vottorð = 28,
  Aðili = 29,
}

export enum EFormApplicantTypes {
  einstaklingur = 'Einstaklingur',
  einstaklingurMedUmbodAnnarsEinstaklings = 'Einstaklingur_með_umboð_annars_einstaklings',
  einstaklingurMedUmbodLogadila = 'Einstaklingur_með_umboð_lögaðila',
  einstaklingurMedProkuru = 'Einstaklingur_með_prókúru',
  einstaklingurUmbodsveitandi = 'Einstaklingur_umboðsveitandi',
  logadili = 'Lögaðili',
}
