export { UniversityOfIcelandClientModule } from './lib/universityOfIcelandClient.module'
export { UniversityOfIcelandClientConfig } from './lib/universityOfIcelandClient.config'
export * from '../gen/fetch'
export { UniversityOfIcelandApiProvider } from './lib/universityOfIcelandClient.provider'
export { UniversityOfIcelandService } from './lib/universityOfIcelandClient.service'
