export { NationalRegistryProvider } from '@island.is/application/data-providers'
export { UserProfileProvider } from '@island.is/application/data-providers'
export { QualityPhotoProvider } from '@island.is/application/data-providers'
export { JuristictionProvider } from '@island.is/application/data-providers'
export { DoctorsNoteProvider } from './DoctorsNoteProvider'
