export { NationalRegistryProvider } from '@island.is/application/data-providers'
export { UserProfileProvider } from '@island.is/application/data-providers'
export { DistrictsProvider } from './DistrictsProvider'
export { DoctorsNoteProvider } from './DoctorsNoteProvider'
export { QualityPhotoProvider } from './QualityPhotoProvider'
