export { AccessControlModule } from './accessControl'
export { AuthModule } from './auth/auth.module' // dig-in import to avoid circular dependency
export { GdprModule } from './gdpr'
export { UserModule } from './user'
export { FjarsyslaModule } from './fjarsysla'
export { RecyclingPartnerModule } from './recyclingPartner'
export { RecyclingRequestModule } from './recyclingRequest'
export { SamgongustofaModule } from './samgongustofa'
export { VehicleModule } from './vehicle'
export { VehicleOwnerModule } from './vehicleOwner'
