export interface ArgItem {
  key: string;
  value: string;
}

export enum NotificationStatus {
  READ = 'read',
  UNREAD = 'unread'
}

export interface NotificationDTO {
  cursor?: number; // Optional if auto-incremented
  messageId?: string; // Optional if generated by default as UUID
  recipient: string;
  templateId: string;
  args: ArgItem[];
  created?: Date; // Optional if auto-generated
  updated?: Date; // Optional if auto-generated
  status?: NotificationStatus; // Default value 'unread', optional if handled by the database
}