export * from '../entities/models/personal-representative-right-type.model'
export * from '../entities/dto/personal-representative-right-type.dto'
export * from '../services/personalRepresentativeRightType.service'
export * from '../services/sequelizeConfig.service'
export * from '../services/personal-representative-scope-permission.service'
export * from '../entities/models/personal-representative-scope-permission.model'
export * from '../entities/dto/personal-representative-scope-permission.dto'
