export enum AdminPortalScope {
  airDiscountScheme = '@admin.island.is/ads',
  explicitAirDiscountScheme = '@admin.island.is/ads:explicit',
  delegations = '@admin.island.is/delegations',
  regulationAdmin = '@admin.island.is/regulations',
  regulationAdminManage = '@admin.island.is/regulations:manage',
  icelandicNamesRegistry = '@admin.island.is/icelandic-names-registry',
  documentProvider = '@admin.island.is/document-provider',
  documentProviderInstitution = '@admin.island.is/document-provider:institution',
  applicationSystemAdmin = '@admin.island.is/application-system:admin',
  applicationSystemInstitution = '@admin.island.is/application-system:institution',
  idsAdmin = '@admin.island.is/auth',
  idsAdminSuperUser = '@admin.island.is/auth:admin',
  petitionsAdmin = '@admin.island.is/petitions',
  serviceDesk = '@admin.island.is/service-desk',
  signatureCollectionProcess = '@admin.island.is/signature-collection:process',
  signatureCollectionManage = '@admin.island.is/signature-collection:manage',
  signatureCollectionMunicipality = '@admin.island.is/signature-collection:municipality',
  formSystem = '@admin.island.is/form-system',
  formSystemAdmin = '@admin.island.is/form-system:admin',
  delegationSystem = '@admin.island.is/delegation-system',
  delegationSystemAdmin = '@admin.island.is/delegation-system:admin',
  payments = '@admin.island.is/payments',
}
