export enum ApiScope {
  assets = '@island.is/assets',
  education = '@island.is/education',
  educationLicense = '@island.is/education-license',
  fishingLicense = '@island.is/fishing-license',
  financeOverview = '@island.is/finance:overview',
  financeSalary = '@island.is/finance/salary',
  financeSchedule = '@island.is/finance/schedule:read',
  financeLoans = '@island.is/finance/loans',
  internal = '@island.is/internal',
  internalProcuring = '@island.is/internal:procuring',
  meDetails = '@island.is/me:details',
  licenses = '@island.is/licenses',
  licensesVerify = '@island.is/licenses:verify',
  company = '@island.is/company',
  vehicles = '@island.is/vehicles',
  samradsgatt = '@samradsgatt.island.is/samradsgatt',
  health = '@island.is/health',
  healthPayments = '@island.is/health/payments',
  healthMedicines = '@island.is/health/medicines',
  healthAssistiveAndNutrition = '@island.is/health/assistive-devices-and-nutrition',
  healthTherapies = '@island.is/health/therapies',
  healthHealthcare = '@island.is/health/healthcare',
  healthDentists = '@island.is/health/dentists',
  workMachines = '@island.is/work-machines',
  samgongustofaVehicles = '@island.is/applications/samgongustofa-vehicles',
  carRecycling = '@island.is/applications/urvinnslusjodur',
}
