export enum ApiScope {
  assets = '@island.is/assets',
  airDiscountScheme = '@island.is/air-discount-scheme',
  education = '@island.is/education',
  educationLicense = '@island.is/education-license',
  fishingLicense = '@island.is/fishing-license',
  financeOverview = '@island.is/finance:overview',
  financeSalary = '@island.is/finance/salary',
  financeSchedule = '@island.is/finance/schedule:read',
  internal = '@island.is/internal',
  internalProcuring = '@island.is/internal:procuring',
  meDetails = '@island.is/me:details',
  licenses = '@island.is/licenses',
  licensesVerify = '@island.is/licenses:verify',
  company = '@island.is/company',
  vehicles = '@island.is/vehicles',
  noDebtCertificate = '@island.is/no-debt-certificate',
}
