export * from './lib/licenseService.module'
export { GenericFirearmLicenseConfig } from './lib/client/firearm-license-client'
export { GenericAdrLicenseConfig } from './lib/client/adr-license-client'
export { GenericMachineLicenseConfig } from './lib/client/machine-license-client'
export { GenericDrivingLicenseConfig } from './lib/client/driving-license-client'
export { GenericDisabilityLicenseConfig } from './lib/client/disability-license-client'
