export { FEATURE_FLAG_CLIENT } from './lib/feature-flag.client'
export * from './lib/feature-flag.config'
export * from './lib/feature-flag.decorator'
export * from './lib/feature-flag.guard'
export * from './lib/feature-flag.module'
export * from './lib/feature-flag.service'
export type { FeatureFlagClient } from '@island.is/feature-flags'
export { Features } from '@island.is/feature-flags'
