import { Contract } from '@island.is/clients/hms-rental-agreement'

export const mockGetRentalAgreements = (): Array<Contract> => {
  return [
    // Einn leigjandi, einn leigusali
    {
      dateFrom: '2025-08-01',
      indexType: 'Ekki vísitölubundinn',
      baseAmount: 100000,
      contractId: 40440,
      contractRef: 'e1b7ce8f-fd83-4651-9b1d-22667656e32b',
      contractType: 'Ótímabundinn samningur',
      currencyCode: 'ISK',
      receivedDate: '2025-07-10',
      contractParty: [
        {
          name: 'Gervimaður Ameríka',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 1',
          kennitala: '0101302989',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85389,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Gervimaður Færeyjar',
          town: 'null',
          email: 'addininja@gmail.com',
          country: 'IS',
          address1: 'Færeyjar',
          kennitala: '0101302399',
          postalCode: 0,
          phoneNumber: '0102399',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
      ],
      lastChangedOn: '2025-07-10',
      signatureDate: '2025-07-10',
      contractStatus: 'STATUSVALID',
      indexIntervalM: 104,
      contractProperty: [
        {
          floor: 1,
          areaM2: 78.3,
          apartment: 1,
          noOfRooms: 3,
          postalCode: 112,
          propertyId: 2011202,
          specialType:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisalUnitId: 2011202,
          specialTypeCode: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contractPropertyId: 38321,
          specialGroupUseCode: 'SPECIALGROUP_OTHER',
          contractPropertyDesc: 'adsf',
          streetAndHouseNumber: 'Funafold 31 ',
        },
      ],
      indexTypeUseCode: 'INDEXZERO',
      contractCollateral: [
        {
          currencyCode: 'ISK',
          collateralType: 'Engin trygging',
          collateralAmount: 0,
          contractCollateralId: 20239,
          collateralTypeUseCode: 'COLLATERAL_ZERO',
        },
      ],
      contractTypeUseCode: 'INDEFINETEAGREEMENT',
    },
    // Einn leigjandi, margir leigusalar
    {
      dateFrom: '2025-08-01',
      indexType: 'Ekki vísitölubundinn',
      baseAmount: 100000,
      contractId: 40441,
      contractRef: 'e1b7ce8f-fd83-4651-9b1d-22667656e32c',
      contractType: 'Ótímabundinn samningur',
      currencyCode: 'ISK',
      receivedDate: '2025-07-10',
      contractParty: [
        {
          name: 'Gervimaður Ameríka',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 2',
          kennitala: '0101302989',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85390,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Gervimaður Bandaríkin',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 2',
          kennitala: '0101305069',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85392,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Eðvarð Óli ÞÍ Einarsson',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '1304761479',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
      ],
      lastChangedOn: '2025-07-10',
      signatureDate: '2025-07-10',
      contractStatus: 'STATUSVALID',
      indexIntervalM: 104,
      contractProperty: [
        {
          floor: 1,
          areaM2: 78.3,
          apartment: 1,
          noOfRooms: 3,
          postalCode: 112,
          propertyId: 2011202,
          specialType:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisalUnitId: 2011202,
          specialTypeCode: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contractPropertyId: 38321,
          specialGroupUseCode: 'SPECIALGROUP_OTHER',
          contractPropertyDesc: 'adsf',
          streetAndHouseNumber: 'Funafold 31',
        },
      ],
      indexTypeUseCode: 'INDEXZERO',
      contractCollateral: [
        {
          currencyCode: 'ISK',
          collateralType: 'Engin trygging',
          collateralAmount: 0,
          contractCollateralId: 20239,
          collateralTypeUseCode: 'COLLATERAL_ZERO',
        },
      ],
      contractTypeUseCode: 'INDEFINETEAGREEMENT',
    },
    // Margir leigjendur, margir leigusalar
    {
      dateFrom: '2025-08-01',
      dateTo: '2026-08-01',
      indexType: 'Ekki vísitölubundinn',
      baseAmount: 100000,
      contractId: 40442,
      contractRef: 'e1b7ce8f-fd83-4651-9b1d-22667656e32d',
      contractType: 'Tímabundinn samningur',
      currencyCode: 'ISK',
      receivedDate: '2025-07-10',
      contractParty: [
        {
          name: 'Gervimaður Ameríka',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 2',
          kennitala: '0101302989',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85390,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Gervimaður Bandaríkin',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 2',
          kennitala: '0101305069',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85392,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Eðvarð Óli ÞÍ Einarsson',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '1304761479',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
        {
          name: 'Birta hlín ÞÍ Lulic',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '0607731499',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
      ],
      lastChangedOn: '2025-07-10',
      signatureDate: '2025-07-10',
      contractStatus: 'STATUSVALID',
      indexIntervalM: 104,
      contractProperty: [
        {
          floor: 1,
          areaM2: 78.3,
          apartment: 1,
          noOfRooms: 3,
          postalCode: 112,
          propertyId: 2011202,
          specialType:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisalUnitId: 2011202,
          specialTypeCode: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contractPropertyId: 38321,
          specialGroupUseCode: 'SPECIALGROUP_OTHER',
          contractPropertyDesc: 'adsf',
          streetAndHouseNumber: 'Funafold 31 ',
        },
      ],
      indexTypeUseCode: 'INDEXZERO',
      contractCollateral: [
        {
          currencyCode: 'ISK',
          collateralType: 'Engin trygging',
          collateralAmount: 0,
          contractCollateralId: 20239,
          collateralTypeUseCode: 'COLLATERAL_ZERO',
        },
      ],
      contractTypeUseCode: 'DEFINITEAGREEMENT',
    },
    // Margir leigjendur, einn leigusali
    {
      dateFrom: '2025-08-01',
      dateTo: '2026-08-01',
      indexType: 'Ekki vísitölubundinn',
      baseAmount: 100000,
      contractId: 40442,
      contractRef: 'e1b7ce8f-fd83-4651-9b1d-22667656e32d',
      contractType: 'Tímabundinn samningur',
      currencyCode: 'ISK',
      receivedDate: '2025-07-10',
      contractParty: [
        {
          name: 'Gervimaður Ameríka',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 2',
          kennitala: '0101302989',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85390,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Eðvarð Óli ÞÍ Einarsson',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '1304761479',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
        {
          name: 'Birta hlín ÞÍ Lulic',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '0607731499',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
      ],
      lastChangedOn: '2025-07-10',
      signatureDate: '2025-07-10',
      contractStatus: 'STATUSVALID',
      indexIntervalM: 104,
      contractProperty: [
        {
          floor: 1,
          areaM2: 78.3,
          apartment: 1,
          noOfRooms: 3,
          postalCode: 112,
          propertyId: 2011202,
          specialType:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisalUnitId: 2011202,
          specialTypeCode: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contractPropertyId: 38321,
          specialGroupUseCode: 'SPECIALGROUP_OTHER',
          contractPropertyDesc: 'adsf',
          streetAndHouseNumber: 'Funafold 31 ',
        },
      ],
      indexTypeUseCode: 'INDEXZERO',
      contractCollateral: [
        {
          currencyCode: 'ISK',
          collateralType: 'Engin trygging',
          collateralAmount: 0,
          contractCollateralId: 20239,
          collateralTypeUseCode: 'COLLATERAL_ZERO',
        },
      ],
      contractTypeUseCode: 'DEFINITEAGREEMENT',
    },
    // Leiguhúsnæði er annað en lögheimili
    {
      dateFrom: '2025-08-01',
      dateTo: '2026-08-01',
      indexType: 'Ekki vísitölubundinn',
      baseAmount: 100000,
      contractId: 40442,
      contractRef: 'e1b7ce8f-fd83-4651-9b1d-22667656e32d',
      contractType: 'Tímabundinn samningur',
      currencyCode: 'ISK',
      receivedDate: '2025-07-10',
      contractParty: [
        {
          name: 'Gervimaður Ameríka',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Einhver gata 2',
          kennitala: '0101302989',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigusali',
          contractPartyId: 85390,
          partyTypeUseCode: 'OWNER',
        },
        {
          name: 'Eðvarð Óli ÞÍ Einarsson',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '1304761479',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
        {
          name: 'Birta hlín ÞÍ Lulic',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address1: 'Grænland',
          kennitala: '0607731499',
          postalCode: 0,
          phoneNumber: '0102639',
          partyTypeName: 'Leigjandi',
          contractPartyId: 85392,
          partyTypeUseCode: 'TENANT',
        },
      ],
      lastChangedOn: '2025-07-10',
      signatureDate: '2025-07-10',
      contractStatus: 'STATUSVALID',
      indexIntervalM: 104,
      contractProperty: [
        {
          floor: 1,
          areaM2: 78.3,
          apartment: 1,
          noOfRooms: 3,
          postalCode: 105,
          propertyId: 2011202,
          specialType:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisalUnitId: 2011202,
          specialTypeCode: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contractPropertyId: 38321,
          specialGroupUseCode: 'SPECIALGROUP_OTHER',
          contractPropertyDesc: 'adsf',
          streetAndHouseNumber: 'Akralind 12',
        },
      ],
      indexTypeUseCode: 'INDEXZERO',
      contractCollateral: [
        {
          currencyCode: 'ISK',
          collateralType: 'Engin trygging',
          collateralAmount: 0,
          contractCollateralId: 20239,
          collateralTypeUseCode: 'COLLATERAL_ZERO',
        },
      ],
      contractTypeUseCode: 'DEFINITEAGREEMENT',
    },
  ]
}
