import { type Contract } from '@island.is/clients/hms-rental-agreement'

export const mockGetRentalAgreements = (): Array<Contract> => {
  return [
    {
      date_from: '2025-08-01',
      index_type: 'Ekki vísitölubundinn',
      base_amount: 100000,
      contract_id: 40440,
      contract_ref: 'e1b7ce8f-fd83-4651-9b1d-22667656e32b',
      contract_type: 'Ótímabundinn samningur',
      currency_code: 'ISK',
      received_date: '2025-07-10',
      contract_party: [
        {
          name: 'Gervimaður Grænland',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address_1: 'Grænland',
          kennitala: '0101302639',
          postal_code: 0,
          phone_number: '0102639',
          party_type_name: 'Leigjandi',
          contract_party_id: 85392,
          party_type_use_code: 'TENANT',
        },
        {
          name: 'Gervimaður Færeyjar',
          town: 'null',
          email: 'addininja@gmail.com',
          country: 'IS',
          address_1: 'Færeyjar',
          kennitala: '0101302399',
          postal_code: 0,
          phone_number: '0102399',
          party_type_name: 'Leigusali',
          contract_party_id: 85391,
          party_type_use_code: 'OWNER',
        },
      ],
      last_changed_on: '2025-07-10',
      signature_date: '2025-07-10',
      contract_status: 'STATUSVALID',
      index_interval_m: 104,
      contract_property: [
        {
          floor: '1',
          area_m2: 78.3,
          apartment: '1',
          no_of_rooms: 3,
          postal_code: 105,
          property_id: 2011202,
          special_type:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisal_unit_id: 2011202,
          special_type_code: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contract_property_id: 38321,
          special_group_use_code: 'SPECIALGROUP_OTHER',
          contract_property_desc: 'adsf',
          street_and_house_number: 'Platgata 10 ',
        },
      ],
      index_type_use_code: 'INDEXZERO',
      contract_collateral: [
        {
          currency_code: 'ISK',
          collateral_type: 'Engin trygging',
          collateral_amount: 0,
          contract_collateral_id: 20239,
          collateral_type_use_code: 'COLLATERAL_ZERO',
        },
      ],
      contract_type_use_code: 'INDEFINETEAGREEMENT',
    },
    {
      date_from: '2025-08-01',
      index_type: 'Ekki vísitölubundinn',
      base_amount: 100000,
      contract_id: 40441,
      contract_ref: 'e1b7ce8f-fd83-4651-9b1d-22667656e32c',
      contract_type: 'Ótímabundinn samningur',
      currency_code: 'ISK',
      received_date: '2025-07-10',
      contract_party: [
        {
          name: 'Gervimaður Grænland 1',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address_1: 'Grænland',
          kennitala: '0101302639',
          postal_code: 0,
          phone_number: '0102639',
          party_type_name: 'Leigjandi',
          contract_party_id: 85392,
          party_type_use_code: 'TENANT',
        },
        {
          name: 'Gervimaður Grænland 2',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address_1: 'Grænland',
          kennitala: '0101302639',
          postal_code: 0,
          phone_number: '0102639',
          party_type_name: 'Leigjandi',
          contract_party_id: 85392,
          party_type_use_code: 'TENANT',
        },
        {
          name: 'Gervimaður Færeyjar 1',
          town: 'null',
          email: 'addininja@gmail.com',
          country: 'IS',
          address_1: 'Færeyjar',
          kennitala: '0101302399',
          postal_code: 0,
          phone_number: '0102399',
          party_type_name: 'Leigusali',
          contract_party_id: 85391,
          party_type_use_code: 'OWNER',
        },
        {
          name: 'Gervimaður Færeyjar 2',
          town: 'null',
          email: 'addininja@gmail.com',
          country: 'IS',
          address_1: 'Færeyjar',
          kennitala: '0101302399',
          postal_code: 0,
          phone_number: '0102399',
          party_type_name: 'Leigusali',
          contract_party_id: 85391,
          party_type_use_code: 'OWNER',
        },
      ],
      last_changed_on: '2025-07-10',
      signature_date: '2025-07-10',
      contract_status: 'STATUSVALID',
      index_interval_m: 104,
      contract_property: [
        {
          floor: '1',
          area_m2: 78.3,
          apartment: '1',
          no_of_rooms: 3,
          postal_code: 105,
          property_id: 2011202,
          special_type:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisal_unit_id: 2011202,
          special_type_code: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contract_property_id: 38321,
          special_group_use_code: 'SPECIALGROUP_OTHER',
          contract_property_desc: 'adsf',
          street_and_house_number: 'Platgata 11 ',
        },
      ],
      index_type_use_code: 'INDEXZERO',
      contract_collateral: [
        {
          currency_code: 'ISK',
          collateral_type: 'Engin trygging',
          collateral_amount: 0,
          contract_collateral_id: 20239,
          collateral_type_use_code: 'COLLATERAL_ZERO',
        },
      ],
      contract_type_use_code: 'INDEFINETEAGREEMENT',
    },
    {
      date_from: '2025-08-01',
      date_to: '2026-08-01',
      index_type: 'Ekki vísitölubundinn',
      base_amount: 100000,
      contract_id: 40442,
      contract_ref: 'e1b7ce8f-fd83-4651-9b1d-22667656e32d',
      contract_type: 'Tímabundinn samningur',
      currency_code: 'ISK',
      received_date: '2025-07-10',
      contract_party: [
        {
          name: 'Gervimaður Grænland 1',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address_1: 'Grænland',
          kennitala: '0101302639',
          postal_code: 0,
          phone_number: '0102639',
          party_type_name: 'Leigjandi',
          contract_party_id: 85392,
          party_type_use_code: 'TENANT',
        },
        {
          name: 'Gervimaður Grænland 2',
          town: 'null',
          email: 'addi@kolibri.is',
          country: 'IS',
          address_1: 'Grænland',
          kennitala: '0101302639',
          postal_code: 0,
          phone_number: '0102639',
          party_type_name: 'Leigjandi',
          contract_party_id: 85392,
          party_type_use_code: 'TENANT',
        },
        {
          name: 'Gervimaður Færeyjar 1',
          town: 'null',
          email: 'addininja@gmail.com',
          country: 'IS',
          address_1: 'Færeyjar',
          kennitala: '0101302399',
          postal_code: 0,
          phone_number: '0102399',
          party_type_name: 'Leigusali',
          contract_party_id: 85391,
          party_type_use_code: 'OWNER',
        },
        {
          name: 'Gervimaður Færeyjar 2',
          town: 'null',
          email: 'addininja@gmail.com',
          country: 'IS',
          address_1: 'Færeyjar',
          kennitala: '0101302399',
          postal_code: 0,
          phone_number: '0102399',
          party_type_name: 'Leigusali',
          contract_party_id: 85391,
          party_type_use_code: 'OWNER',
        },
      ],
      last_changed_on: '2025-07-10',
      signature_date: '2025-07-10',
      contract_status: 'STATUSVALID',
      index_interval_m: 104,
      contract_property: [
        {
          floor: '1',
          area_m2: 78.3,
          apartment: '1',
          no_of_rooms: 3,
          postal_code: 105,
          property_id: 2011202,
          special_type:
            'Íbúðarhúsnæði mað að lágmarki einu svefnherbergi ásamt séreldhúsi eða séreldunaraðstöðu, sérsnyrtingu og baðaðstöðu',
          municipality: 'Reykjavíkurborg',
          appraisal_unit_id: 2011202,
          special_type_code: 'TM_SPECIAL_TYPE_RESIDENTAL_PREMISE',
          contract_property_id: 38321,
          special_group_use_code: 'SPECIALGROUP_OTHER',
          contract_property_desc: 'adsf',
          street_and_house_number: 'Platgata 11 ',
        },
      ],
      index_type_use_code: 'INDEXZERO',
      contract_collateral: [
        {
          currency_code: 'ISK',
          collateral_type: 'Engin trygging',
          collateral_amount: 0,
          contract_collateral_id: 20239,
          collateral_type_use_code: 'COLLATERAL_ZERO',
        },
      ],
      contract_type_use_code: 'DEFINITEAGREEMENT',
    },
  ]
}
