export enum ContractStatus {
  DRAFT = 'DRAFT', // Drög
  STATUSVALID = 'STATUSVALID', // Gildi
  STATUSINVALID = 'STATUSINVALID', // Ógildur
  STATUSEXPIRED = 'STATUSEXPIRED', // Útrunnin
  STATUSCANCELLED = 'STATUSCANCELLED', // Riftun
  STATUSTERMINATED = 'STATUSTERMINATED', // Uppsögn
  CANCELLEDREQUESTED = 'CANCELLEDREQUESTED', // Beiðni um riftun
  PENDINGCANCELLATION = 'PENDINGCANCELLATION', // Fram að riftun eftir staðfestingu
  PENDINGTERMINATION = 'PENDINGTERMINATION', // Fram að slitum samnings
  STATUSARCHIVED = 'STATUSARCHIVED', // Sett í geymslu
}
