export const TYPE_OF_OPERATION = [
  'Landbúnaður, dýraveiðar og skógrækt',
  'Fiskveiðar',
  'Námugröftur og vinnsla hráefna úr jörðu ',
  'Iðnaður',
  'Matvæla-  og  drykkjarvöruiðnaður;  tóbaksiðnaður',
  'Textíl-  og  fataiðnaður',
  'Leðuriðnaður',
  'Trjáiðnaður',
  'Pappírsiðnaður  og  útgáfustarfsemi ',
  'Framleiðsla á koxi, olíuvörum og kjarnorkueldsneyti ',
  'Efnaiðnaður',
  'Gúmmí-  og  plastvöruframleiðsla ',
  'Gler-, leir- og steinefnaiðnaður ',
  'Málmiðnaður90DK    Vélsmíði og vélaviðgerðir ',
  'Rafmagns-  og  rafeindaiðnaður ',
  'Framleiðsla  samgöngutækja ',
  'Húsgagnaiðnaður  og  annar  ótalinn  iðnaður ',
  'Veitur ',
  'Byggingarstarfsemi  og  mannvirkjagerð ',
  'Hótel- og veitingahúsarekstur ',
  'Samgöngur  og  flutningar ',
  'Fjármálaþjónusta, lífeyrissjóðir og vátryggingar ',
  'Fasteignaviðskipti, leigustarfsemi og ýmis sérhæfð þjónusta ',
  'Opinber  stjórnsýsla;  almannatryggingar ',
  'Fræðslustarfsemi ',
  'Heilbrigðis- og félagsþjónusta ',
  'Önnur  samfélagsþjónusta,  félagastarfsemi,  menningarstarfsemi  ofl ',
  'Heimilishald með launuðu starfsfólki ',
  'Engin  starfsemi ',
  'Ótilgreind  starfsemi ',
  'Starfsemi alþjóðlegra stofnana og samtaka með úrlendisrétt',
]
