export const TYPE_OF_OPERATION = [
  'Landbúnaður, dýraveiðar og skógrækt',
  'Fiskveiðar',
  'Námugröftur og vinnsla hráefna úr jörðu',
  'Iðnaður',
  'Veitur',
  'Byggingarstarfsemi  og  mannvirkjagerð',
  'Verslun og ýmis viðgerðarþjónusta',
  'Hótel- og veitingahúsarekstur',
  'Samgöngur  og  flutningar',
  'Fjármálaþjónusta, lífeyrissjóðir og vátryggingar',
  'Fasteignaviðskipti, leigustarfsemi og ýmis sérhæfð þjónusta',
  'Opinber  stjórnsýsla;  almannatryggingar',
  'Fræðslustarfsemi',
  'Heilbrigðis- og félagsþjónusta',
  'Önnur  samfélagsþjónusta,  félagastarfsemi,  menningarstarfsemi  ofl',
  'Heimilishald með launuðu starfsfólki',
  'Starfsemi alþjóðlegra stofnana og samtaka með úrlendisrétt',
  'Engin  starfsemi',
  'Ótilgreind  starfsemi',
]
