export const Types = {
  policyAreas: {
    '84': 'Almanna- og réttaröryggi',
    '85': 'Almennur varasjóður og sértækar fjárráðstafanir',
    '86': 'Dómstólar',
    '87': 'Ferðaþjónusta',
    '88': 'Fjölmiðlun',
    '89': 'Fjölskyldumál',
    '90': 'Framhaldsskólastig',
    '91': 'Hagskýrslugerð og grunnskrár',
    '92': 'Háskólastig',
    '93': 'Heilbrigðisþjónusta utan sjúkrahúsa',
    '94': 'Hjúkrunar- og endurhæfingarþjónusta',
    '95': 'Húsnæðisstuðningur',
    '96': 'Landbúnaður',
    '97': 'Lyf og lækningavörur',
    '98': 'Lýðheilsa og stjórnsýsla velferðarmála',
    '99': 'Alþingi og eftirlitsstofnanir þess',
    '100': 'Markaðseftirlit, neytendamál og stjórnsýsla atvinnumála',
    '101': 'Málefni aldraðra',
    '102': 'Menning, listir, íþrótta- og æskulýðsmál',
    '103': 'Nýsköpun, rannsóknir og þekkingargreinar',
    '104': 'Orkumál',
    '105': 'Réttindi einstaklinga, trúmál og stjórnsýsla dómsmála',
    '106': 'Samgöngu- og fjarskiptamál',
    '107': 'Sjávarútvegur og fiskeldi',
    '108': 'Sjúkrahúsþjónusta',
    '109': 'Skatta-, eigna- og fjármálaumsýsla',
    '110': 'Sveitarfélög og byggðamál',
    '111': 'Umhverfismál',
    '112': 'Utanríkismál',
    '113': 'Fjármagnskostnaður, ábyrgðir og lífeyrisskuldbindingar',
    '114': 'Æðsta stjórnsýsla',
    '115':
      'Leikskólar, grunnskólar, starfsnám og stjórnsýsla mennta- og menningarmála',
    '116': 'Örorka og málefni fatlaðs fólks',
    '117': 'Vinnumarkaður og atvinnuleysi',
    '118': 'Grunnskólastig',
    '119': 'Alþjóðleg þróunarsamvinna',
    '120': 'málaflokkur test',
    '121': 'Hello 12345',
    '122': 'test 123',
  },
  institutions: {
    '1': 'Forsætisráðuneytið',
    '2': 'Matvælaráðuneytið',
    '3': 'Fjármála- og efnahagsráðuneytið',
    '4': 'Dómsmálaráðuneytið',
    '5': 'Mennta- og barnamálaráðuneytið',
    '6': 'Umhverfis-, orku- og loftslagsráðuneytið',
    '7': 'Utanríkisráðuneytið',
    '8': 'Velferðarráðuneytið',
    '9': 'Forsætisráðuneytið',
    '10': 'Höfuðráðuneytið',
    '11': 'Innviðaráðuneytið',
    '12': 'asdf',
    '13': 'asdf',
    '14': 'dfasdf',
    '15': 'test stofnun',
    '16': 'Stofnun asdf',
    '17': 'Félags- og vinnumarkaðsráðuneytið',
    '18': 'Heilbrigðisráðuneytið',
    '19': 'Menningar- og viðskiptaráðuneytið',
    '20': 'Háskóla-, iðnaðar- og nýsköpunarráðuneyti',
    '21': 'Prufu Stofnun',
  },
  caseStatuses: {
    '1': 'Samráð fyrirhugað',
    '2': 'Til umsagnar',
    '3': 'Niðurstöður í vinnslu',
    '4': 'Niðurstöður birtar',
  },
  caseTypes: {
    '1': 'Drög að stefnu',
    '2': 'Áform um lagasetningu',
    '3': 'Drög að reglugerð',
    '4': 'Drög að frumvarpi til laga',
    '5': 'Annað',
    '7': 'Stöðumat og valkostir',
  },
}

export default Types
