import { Op, Transaction } from 'sequelize'

import { Inject, Injectable } from '@nestjs/common'
import { InjectModel } from '@nestjs/sequelize'

import { type Logger, LOGGER_PROVIDER } from '@island.is/logging'

import {
  CaseFileCategory,
  CaseFileState,
  HashAlgorithm,
} from '@island.is/judicial-system/types'

import { CaseFile } from '../models/caseFile.model'

// The id is normally generated by the database; the police metadata path
// supplies its own so the S3 key can carry it before the row exists.
export type CreateCaseFile = {
  id?: string
  defendantId?: string
  civilClaimantId?: string
  rulingFileId?: string
  name: string
  type: string
  category?: CaseFileCategory
  state: CaseFileState
  key: string
  size: number
  policeCaseNumber?: string
  userGeneratedFilename?: string
  chapter?: number
  orderWithinChapter?: number
  displayDate?: Date
  policeFileId?: string
  submittedBy?: string
  submissionDate?: Date
  fileRepresentative?: string
  isPronouncedOrally?: boolean
}

// Typed by the columns, not by the DTOs that feed it: the archive path clears
// nullable columns with null, and the ruling-order confirmation stamps the
// submission date as an ISO string, which Sequelize accepts for a DATE column.
export type UpdateCaseFile = {
  name?: string
  type?: string
  state?: CaseFileState
  key?: string
  size?: number
  policeCaseNumber?: string | null
  userGeneratedFilename?: string | null
  chapter?: number | null
  orderWithinChapter?: number | null
  displayDate?: Date | null
  hash?: string | null
  hashAlgorithm?: HashAlgorithm | null
  submissionDate?: Date | string | null
  isKeyAccessible?: boolean
  rulingFileId?: string | null
}

// Where a copied case file points: the S3 key its own object was copied to,
// and the copies of the defendant and civil claimant the original referenced,
// if any.
export type CopyCaseFileTarget = {
  key: string
  defendantId?: string
  civilClaimantId?: string
}

// Sequelize returns [affectedRows, rows] from update; naming the two halves
// keeps the tuple from leaking to callers.
export type UpdatedCaseFiles = {
  numberOfAffectedRows: number
  caseFiles: CaseFile[]
}

@Injectable()
export class CaseFileRepositoryService {
  constructor(
    @InjectModel(CaseFile) private readonly caseFileModel: typeof CaseFile,
    @Inject(LOGGER_PROVIDER) private readonly logger: Logger,
  ) {}

  // A case file is only addressable within its own case, so both keys are
  // named parameters rather than a caller-supplied where clause. Deleted files
  // are soft-deleted and stay in the table, so they are excluded here.
  async findLiveByIdAndCase(
    fileId: string,
    caseId: string,
    options?: { transaction?: Transaction },
  ): Promise<CaseFile | null> {
    try {
      this.logger.debug(`Finding case file ${fileId} of case ${caseId}`)

      const result = await this.caseFileModel.findOne({
        where: {
          id: fileId,
          caseId,
          state: { [Op.not]: CaseFileState.DELETED },
        },
        transaction: options?.transaction,
      })

      this.logger.debug(
        `Case file ${fileId} of case ${caseId} ${
          result ? 'found' : 'not found'
        }`,
      )

      return result
    } catch (error) {
      this.logger.error(
        `Error finding case file ${fileId} of case ${caseId}:`,
        {
          error,
        },
      )

      throw error
    }
  }

  async findByCaseAndPoliceFileId(
    caseId: string,
    policeFileId: string,
    options: { transaction: Transaction },
  ): Promise<CaseFile | null> {
    try {
      this.logger.debug(
        `Finding the case file of case ${caseId} for police file ${policeFileId}`,
      )

      const result = await this.caseFileModel.findOne({
        where: { caseId, policeFileId },
        transaction: options.transaction,
      })

      this.logger.debug(
        `Case file of case ${caseId} for police file ${policeFileId} ${
          result ? 'found' : 'not found'
        }`,
      )

      return result
    } catch (error) {
      this.logger.error(
        `Error finding the case file of case ${caseId} for police file ${policeFileId}:`,
        { error },
      )

      throw error
    }
  }

  // Claims the next order within the chapter of the case's uncategorised files
  // - the only files that carry a chapter order. The existing files are locked
  // FOR UPDATE for the rest of the transaction so that two concurrent creates
  // cannot both read the same maximum before either insert commits; the lock
  // is taken by a separate id-only read because an aggregate cannot carry one.
  //
  // Null when no uncategorised file of the case has an order yet - the caller
  // decides what the first file gets.
  async getNextOrderWithinChapterForUpdate(
    caseId: string,
    options: { transaction: Transaction },
  ): Promise<number | null> {
    try {
      this.logger.debug(
        `Locking the uncategorised case files of case ${caseId} to claim the next order within chapter`,
      )

      await this.caseFileModel.findAll({
        where: { caseId, category: null },
        attributes: ['id'],
        lock: Transaction.LOCK.UPDATE,
        transaction: options.transaction,
      })

      const maxOrder = await this.caseFileModel.max<number | null, CaseFile>(
        'orderWithinChapter',
        {
          where: { caseId, category: null },
          transaction: options.transaction,
        },
      )

      return typeof maxOrder === 'number' ? maxOrder + 1 : null
    } catch (error) {
      this.logger.error(
        `Error claiming the next order within chapter for case ${caseId}:`,
        { error },
      )

      throw error
    }
  }

  async create(
    caseId: string,
    caseFile: CreateCaseFile,
    options: { transaction: Transaction },
  ): Promise<CaseFile> {
    try {
      this.logger.debug(`Creating a case file for case ${caseId}`)

      return await this.caseFileModel.create(
        { ...caseFile, caseId },
        { transaction: options.transaction },
      )
    } catch (error) {
      this.logger.error(`Error creating a case file for case ${caseId}:`, {
        error,
      })

      throw error
    }
  }

  // Bookkeeping writes on a file already in hand - state, hash, key
  // accessibility - where the caller only needs to know whether the row was
  // hit. The case is not part of the key because these callers hold a file
  // that was already resolved within its case.
  async updateById(
    fileId: string,
    update: UpdateCaseFile,
    options?: { transaction?: Transaction },
  ): Promise<number> {
    try {
      this.logger.debug(`Updating case file ${fileId} with data:`, {
        data: Object.keys(update),
      })

      const [numberOfAffectedRows] = await this.caseFileModel.update(update, {
        where: { id: fileId },
        transaction: options?.transaction,
      })

      return numberOfAffectedRows
    } catch (error) {
      this.logger.error(`Error updating case file ${fileId} with data:`, {
        data: Object.keys(update),
        error,
      })

      throw error
    }
  }

  async updateByIdAndCase(
    fileId: string,
    caseId: string,
    update: UpdateCaseFile,
    options?: { transaction?: Transaction },
  ): Promise<UpdatedCaseFiles> {
    try {
      this.logger.debug(
        `Updating case file ${fileId} of case ${caseId} with data:`,
        { data: Object.keys(update) },
      )

      const [numberOfAffectedRows, caseFiles] = await this.caseFileModel.update(
        update,
        {
          where: { id: fileId, caseId },
          returning: true,
          transaction: options?.transaction,
        },
      )

      return { numberOfAffectedRows, caseFiles }
    } catch (error) {
      this.logger.error(
        `Error updating case file ${fileId} of case ${caseId} with data:`,
        { data: Object.keys(update), error },
      )

      throw error
    }
  }

  // Matches the file only while it still has no document behind it (an empty
  // key). Two writers racing to attach a document to the same file both pass
  // their checks on the copy they read; the update is what decides between
  // them, so the loser affects no rows instead of replacing the winner's
  // document.
  async updateByIdAndCaseWithoutDocument(
    fileId: string,
    caseId: string,
    update: UpdateCaseFile,
    options: { transaction: Transaction },
  ): Promise<UpdatedCaseFiles> {
    try {
      this.logger.debug(
        `Updating case file ${fileId} of case ${caseId}, which must have no document, with data:`,
        { data: Object.keys(update) },
      )

      const [numberOfAffectedRows, caseFiles] = await this.caseFileModel.update(
        update,
        {
          where: { id: fileId, caseId, key: '' },
          returning: true,
          transaction: options.transaction,
        },
      )

      return { numberOfAffectedRows, caseFiles }
    } catch (error) {
      this.logger.error(
        `Error updating case file ${fileId} of case ${caseId}, which must have no document, with data:`,
        { data: Object.keys(update), error },
      )

      throw error
    }
  }

  // The files of a case that were delivered to the court go back to being
  // stored only in RVG, so that they are delivered again - to the court the
  // case now belongs to.
  async resetStoredInCourtFilesForCase(
    caseId: string,
    options: { transaction: Transaction },
  ): Promise<number> {
    try {
      this.logger.debug(
        `Resetting the state of the case files of case ${caseId} that are stored in court`,
      )

      const [numberOfAffectedRows] = await this.caseFileModel.update(
        { state: CaseFileState.STORED_IN_RVG },
        {
          where: { caseId, state: CaseFileState.STORED_IN_COURT },
          transaction: options.transaction,
        },
      )

      return numberOfAffectedRows
    } catch (error) {
      this.logger.error(
        `Error resetting the state of the case files of case ${caseId} that are stored in court:`,
        { error },
      )

      throw error
    }
  }

  // The files of a case in the given categories. Which categories is the
  // caller's decision - the copy of a case takes only the prosecution's.
  async findAllByCaseAndCategories(
    caseId: string,
    categories: CaseFileCategory[],
    options: { transaction: Transaction },
  ): Promise<CaseFile[]> {
    try {
      this.logger.debug(
        `Finding the case files of case ${caseId} in ${categories.length} categories`,
      )

      const caseFiles = await this.caseFileModel.findAll({
        where: { caseId, category: categories },
        transaction: options.transaction,
      })

      this.logger.debug(
        `Found ${caseFiles.length} case files of case ${caseId} in ${categories.length} categories`,
      )

      return caseFiles
    } catch (error) {
      this.logger.error(
        `Error finding the case files of case ${caseId} in ${categories.length} categories:`,
        { error },
      )

      throw error
    }
  }

  // Creates the row for a copy of a case file on another case. The copy is a
  // fully independent draft: it points at its own S3 object (the caller copies
  // the object and supplies the new key), goes back to being stored only in
  // RVG, and loses the hash, which was computed for the original key. The
  // police file id is kept so a file already fetched from the police system
  // (LÖKE) is not offered for re-upload on the copy.
  async copyToCase(
    sourceFile: CaseFile,
    newCaseId: string,
    target: CopyCaseFileTarget,
    options: { transaction: Transaction },
  ): Promise<CaseFile> {
    try {
      this.logger.debug(
        `Copying case file ${sourceFile.id} of case ${sourceFile.caseId} to case ${newCaseId}`,
      )

      return await this.caseFileModel.create(
        {
          ...sourceFile.toJSON(),
          id: undefined,
          caseId: newCaseId,
          key: target.key,
          state: CaseFileState.STORED_IN_RVG,
          defendantId: target.defendantId,
          civilClaimantId: target.civilClaimantId,
          policeFileId: sourceFile.policeFileId,
          hash: undefined,
          hashAlgorithm: undefined,
        },
        { transaction: options.transaction },
      )
    } catch (error) {
      this.logger.error(
        `Error copying case file ${sourceFile.id} of case ${sourceFile.caseId} to case ${newCaseId}:`,
        { error },
      )

      throw error
    }
  }
}
