query Case($input: CaseQueryInput!) {
  case(input: $input) {
    id
    created
    type
    splitCases {
      ...SplitCaseFields
    }
    splitCase {
      id
      courtCaseNumber
    }
    state
    indictmentSubtypes
    description
    policeCaseNumbers
    defendants {
      ...DefendantFields
      isClosedWithoutEnforcement
      closedWithoutEnforcementDate
      publicProsecutorIsRegisteredInPoliceSystem
      isDrivingLicenseSuspended
      subpoenas {
        ...SubpoenaFields
      }
      verdict {
        id
        modified
        caseId
        defendantId
        created
        verdictDeliveredToNationalCommissionersOffice
        appealDate
        appealDecision
        serviceRequirement
        serviceStatus
        serviceDate
        serviceInformationForDefendant
        externalPoliceDocumentId
        comment
        deliveredToDefenderNationalId
        servedBy
        isDefaultJudgement
        isAcquittedByPublicProsecutionOffice
        defendantHasRequestedAppeal
      }
      connectedCases {
        id
        courtCaseNumber
        court {
          id
          name
        }
      }
    }
    defenderName
    defenderNationalId
    defenderEmail
    defenderPhoneNumber
    requestSharedWithDefender
    isHeightenedSecurityLevel
    court {
      ...InstitutionFields
    }
    leadInvestigator
    arrestDate
    requestedCourtDate
    translator
    requestedValidToDate
    demands
    lawsBroken
    legalBasis
    legalProvisions
    requestedCustodyRestrictions
    requestedOtherRestrictions
    caseFacts
    legalArguments
    requestProsecutorOnlySession
    prosecutorOnlySessionRequest
    comments
    caseFilesComments
    creatingProsecutor {
      ...UserFields
    }
    prosecutor {
      ...UserFields
    }
    sharedWithProsecutorsOffice {
      ...InstitutionFields
    }
    courtCaseNumber
    sessionArrangements
    courtLocation
    courtStartDate
    courtEndTime
    isClosedCourtHidden
    courtAttendees
    prosecutorDemands
    courtDocuments
    sessionBookings
    courtCaseFacts
    introduction
    courtLegalArguments
    ruling
    decision
    validToDate
    isValidToDateInThePast
    isCustodyIsolation
    isolationToDate
    conclusion
    endOfSessionBookings
    rulingDate
    rulingSignatureDate
    judge {
      ...UserFields
    }
    courtRecordSignatory {
      ...UserFields
    }
    courtRecordSignatureDate
    registrar {
      ...UserFields
    }
    parentCase {
      id
      created
      modified
      type
      origin
      policeCaseNumbers
      state
      validToDate
      decision
      courtCaseNumber
      ruling
      caseFiles {
        id
        created
        name
        state
        key
        size
        isKeyAccessible
        defendantId
        civilClaimantId
      }
    }
    childCase {
      id
      created
      modified
      type
      origin
      policeCaseNumbers
    }
    notifications {
      id
      created
      type
      recipients {
        success
      }
    }
    caseFiles {
      ...CaseFileFields
      caseId
      policeCaseNumber
      chapter
      orderWithinChapter
      policeFileId
      submissionDate
      hasBeenAppealed
      canBeAppealed
      appealDeadline
      isAppealDeadlineExpired
    }
    isAppealDeadlineExpired
    caseModifiedExplanation
    rulingModifiedHistory
    caseResentExplanation
    origin
    originalAncestorId
    openedByDefender
    defendantWaivesRightToCounsel
    crimeScenes
    indictmentIntroduction
    indictmentReviewedDate
    indictmentCounts {
      id
      displayOrder
      caseId
      policeCaseNumber
      created
      modified
      vehicleRegistrationNumber
      offenses {
        id
        indictmentCountId
        created
        modified
        offense
        substances
      }
      lawsBroken
      incidentDescription
      legalArguments
      indictmentCountSubtypes
      recordedSpeed
      speedLimit
    }
    withCourtSessions
    isArraignmentSummonsSkipped
    courtSessions {
      id
      created
      modified
      caseId
      location
      judgeId
      judge {
        id
        name
      }
      startDate
      endDate
      isClosed
      closedLegalProvisions
      attendees
      entries
      rulingType
      ruling
      rulingFileId
      isAttestingWitness
      attestingWitnessId
      attestingWitness {
        id
        name
      }
      closingEntries
      isConfirmed
      filedDocuments {
        ...CourtDocumentFields
      }
      courtSessionStrings {
        ...CourtSessionStringFields
      }
    }
    unfiledCourtDocuments {
      ...CourtDocumentFields
    }
    requestDriversLicenseSuspension
    canBeAppealed
    canProsecutorAppeal
    hasBeenAppealed
    appealDeadline
    appealCase {
      ...AppealCaseFields
    }
    verdictAppealCase {
      id
      appealState
      appealType
      appealEventLogs {
        id
        created
        eventType
        appealOrigin
        defendantId
        userRole
        userName
        userTitle
        institutionName
      }
    }
    rulingOrderAppealCases {
      ...AppealCaseFields
    }
    appealDecisions {
      id
      rulingFileId
      partyRole
      defendantId
      civilClaimantId
      decision
      announcement
      withdrawnDate
    }
    indictmentDeniedExplanation
    indictmentReviewReturnedExplanation
    arraignmentDate {
      date
      location
    }
    courtDate {
      date
      location
    }
    prosecutorsOffice {
      id
      name
      policeCaseNumberPrefix
    }
    postponedIndefinitelyExplanation
    indictmentRulingDecision
    indictmentReviewer {
      id
      name
    }
    indictmentApprover {
      id
      name
    }
    indictmentAppealDeadline
    indictmentVerdictAppealDeadlineExpired
    indictmentVerdictViewedByAll
    indictmentDecision
    courtSessionType
    mergeCase {
      id
      courtCaseNumber
      type
      defendants {
        id
        defenderNationalId
        isDefenderChoiceConfirmed
      }
      civilClaimants {
        ...CivilClaimantSpokespersonFields
      }
    }
    mergedCases {
      id
      courtCaseNumber
      type
      state
      indictmentRulingDecision
      hasCivilClaims
      withCourtSessions
      courtSessions {
        id
        startDate
        endDate
        isConfirmed
        filedDocuments {
          ...CourtDocumentFields
        }
        courtSessionStrings {
          ...CourtSessionStringFields
        }
      }
      court {
        id
        name
      }
      judge {
        ...UserFields
      }
      prosecutor {
        ...UserFields
      }
      prosecutorsOffice {
        id
        name
      }
      defendants {
        id
        noNationalId
        nationalId
        name
        gender
        address
        citizenship
        defenderName
        defenderNationalId
        defenderEmail
        defenderPhoneNumber
        defenderChoice
        defendantPlea
        requestedDefenderChoice
        requestedDefenderNationalId
        requestedDefenderName
        isDefenderChoiceConfirmed
        caseFilesSharedWithDefender
        verdictAppealDeadline
        isVerdictAppealDeadlineExpired
        subpoenaType
        punishmentType
        subpoenas {
          ...SubpoenaFields
        }
        verdict {
          id
          appealDate
          appealDecision
          serviceRequirement
          serviceDate
          serviceInformationForDefendant
          externalPoliceDocumentId
        }
      }
      civilClaimants {
        ...CivilClaimantSpokespersonFields
      }
      caseFiles {
        ...CaseFileFields
      }
      policeCaseNumbers
      indictmentSubtypes
      rulingOrderAppealCases {
        ...AppealCaseFields
      }
    }
    civilClaimants {
      ...CivilClaimantFields
    }
    victims {
      id
      name
      hasNationalId
      nationalId
      hasLawyer
      lawyerNationalId
      lawyerName
      lawyerEmail
      lawyerPhoneNumber
      lawyerAccessToRequest
    }
    mergeCaseNumber
    civilDemands
    penalties
    reopenReason
    hasCivilClaims
    isCompletedWithoutRuling
    caseSentToCourtDate
    indictmentCompletedDate
    indictmentSentToPublicProsecutorDate
    defenceAppealResultAccessDate
    prosecutionAppealResultAccessDate
    prisonStaffAppealResultAccessDate
    requestCompletedDate
    caseRepresentatives {
      name
      nationalId
      caseFileCategory
    }
  }
}
