query LimitedAccessCase($input: CaseQueryInput!) {
  limitedAccessCase(input: $input) {
    id
    created
    origin
    type
    indictmentSubtypes
    state
    policeCaseNumbers
    splitCase {
      id
      courtCaseNumber
    }
    splitCases {
      ...SplitCaseFields
    }
    caseFiles {
      ...CaseFileFields
      hasBeenAppealed
      canBeAppealed
      appealDeadline
      isAppealDeadlineExpired
    }
    defendants {
      ...DefendantFields
      isRegisteredInPrisonSystem
      subpoenas {
        ...SubpoenaFields
      }
      verdict {
        id
        created
        serviceStatus
        servedBy
        appealDate
        appealDecision
        serviceRequirement
        serviceDate
        serviceInformationForDefendant
        externalPoliceDocumentId
        isDefaultJudgement
      }
    }
    defenderName
    defenderNationalId
    defenderEmail
    defenderPhoneNumber
    requestSharedWithDefender
    court {
      ...InstitutionFields
    }
    leadInvestigator
    requestedCustodyRestrictions
    creatingProsecutor {
      ...UserFields
    }
    prosecutor {
      ...UserFields
    }
    courtCaseNumber
    courtEndTime
    validToDate
    decision
    isValidToDateInThePast
    isCustodyIsolation
    isolationToDate
    conclusion
    rulingDate
    rulingSignatureDate
    reopenReason
    registrar {
      ...UserFields
    }
    judge {
      ...UserFields
    }
    courtRecordSignatory {
      ...UserFields
    }
    courtRecordSignatureDate
    parentCase {
      id
      state
      validToDate
      decision
      courtCaseNumber
      ruling
    }
    childCase {
      id
    }
    caseModifiedExplanation
    rulingModifiedHistory
    caseResentExplanation
    isAppealDeadlineExpired
    canBeAppealed
    canDefenderAppeal
    hasBeenAppealed
    appealDeadline
    appealCase {
      ...AppealCaseFields
    }
    verdictAppealCase {
      id
      appealState
      appealType
      appealEventLogs {
        id
        created
        eventType
        appealOrigin
        defendantId
        userRole
        userName
        userTitle
        institutionName
      }
    }
    rulingOrderAppealCases {
      ...AppealCaseFields
    }
    appealDecisions {
      id
      rulingFileId
      partyRole
      defendantId
      civilClaimantId
      decision
      announcement
      withdrawnDate
    }
    notifications {
      id
      created
      type
      recipients {
        success
      }
    }
    arraignmentDate {
      date
      location
    }
    courtDate {
      date
      location
    }
    prosecutorsOffice {
      id
      name
    }
    postponedIndefinitelyExplanation
    indictmentDecision
    indictmentRulingDecision
    indictmentVerdictViewedByAll
    indictmentVerdictAppealDeadlineExpired
    indictmentReviewer {
      id
      name
    }
    courtSessionType
    mergeCase {
      id
      courtCaseNumber
      type
      defendants {
        id
        defenderNationalId
        isDefenderChoiceConfirmed
      }
      civilClaimants {
        ...CivilClaimantSpokespersonFields
      }
    }
    indictmentCounts {
      id
      displayOrder
      caseId
      policeCaseNumber
      created
      modified
      vehicleRegistrationNumber
      offenses {
        id
        indictmentCountId
        created
        modified
        offense
        substances
      }
      lawsBroken
      incidentDescription
      legalArguments
    }
    withCourtSessions
    courtSessions {
      id
      startDate
      isConfirmed
      ruling
      filedDocuments {
        ...CourtDocumentFields
      }
      courtSessionStrings {
        ...CourtSessionStringFields
      }
    }
    mergedCases {
      id
      courtCaseNumber
      type
      state
      indictmentRulingDecision
      hasCivilClaims
      withCourtSessions
      defendants {
        id
        defenderNationalId
        isDefenderChoiceConfirmed
        isSentToPrisonAdmin
        policeCaseNumbers
        indictmentCancelledOrDismissedState {
          type
          time
        }
        sentToPrisonAdminDate
        subpoenas {
          ...SubpoenaFields
        }
      }
      civilClaimants {
        ...CivilClaimantSpokespersonFields
      }
      courtSessions {
        id
        startDate
        endDate
        ruling
        isConfirmed
        filedDocuments {
          ...CourtDocumentFields
        }
        courtSessionStrings {
          ...CourtSessionStringFields
        }
      }
      caseFiles {
        ...CaseFileFields
      }
      policeCaseNumbers
      indictmentSubtypes
      court {
        id
        name
      }
      judge {
        id
        name
      }
      prosecutorsOffice {
        id
        name
      }
      rulingOrderAppealCases {
        ...AppealCaseFields
      }
    }
    hasCivilClaims
    civilClaimants {
      ...CivilClaimantFields
    }
    victims {
      id
      name
      hasNationalId
      nationalId
      hasLawyer
      lawyerNationalId
      lawyerName
      lawyerEmail
      lawyerPhoneNumber
      lawyerAccessToRequest
    }
    isCompletedWithoutRuling
    caseSentToCourtDate
    indictmentReviewedDate
    indictmentSentToPublicProsecutorDate
  }
}
