export type Type = 'filled' | 'outline'
export type Icon =
  | 'accessibility'
  | 'add'
  | 'arrowForward'
  | 'arrowBack'
  | 'arrowUp'
  | 'attach'
  | 'business'
  | 'calendar'
  | 'car'
  | 'cellular'
  | 'chatbubble'
  | 'checkmark'
  | 'checkmarkCircle'
  | 'chevronBack'
  | 'chevronDown'
  | 'chevronForward'
  | 'closeCircle'
  | 'close'
  | 'documents'
  | 'download'
  | 'ellipse'
  | 'fileTrayFull'
  | 'heart'
  | 'home'
  | 'informationCircle'
  | 'lockClosed'
  | 'logOut'
  | 'menu'
  | 'notifications'
  | 'open'
  | 'people'
  | 'person'
  | 'reader'
  | 'receipt'
  | 'removeCircle'
  | 'school'
  | 'search'
  | 'settings'
  | 'wallet'
  | 'warning'

export default {
  filled: {
    accessibility: 'Accessibility',
    add: 'Add',
    arrowForward: 'ArrowForward',
    arrowBack: 'ArrowBack',
    arrowUp: 'ArrowUp',
    attach: 'Attach',
    business: 'Business',
    calendar: 'Calendar',
    car: 'Car',
    cellular: 'Cellular',
    chatbubble: 'Chatbubble',
    checkmark: 'Checkmark',
    checkmarkCircle: 'CheckmarkCircle',
    chevronBack: 'ChevronBack',
    chevronDown: 'ChevronDown',
    chevronForward: 'ChevronForward',
    closeCircle: 'CloseCircle',
    close: 'Close',
    documents: 'Documents',
    download: 'Download',
    ellipse: 'Ellipse',
    fileTrayFull: 'FileTrayFull',
    heart: 'Heart',
    home: 'Home',
    informationCircle: 'InformationCircle',
    lockClosed: 'LockClosed',
    logOut: 'LogOut',
    menu: 'Menu',
    notifications: 'Notifications',
    open: 'Open',
    people: 'People',
    person: 'Person',
    reader: 'Reader',
    receipt: 'Receipt',
    removeCircle: 'RemoveCircle',
    school: 'School',
    search: 'Search',
    settings: 'Settings',
    wallet: 'Wallet',
    warning: 'Warning',
  },
  outline: {
    accessibility: 'AccessibilityOutline',
    add: 'AddOutline',
    arrowForward: 'ArrowForwardOutline',
    arrowBack: 'ArrowBackOutline',
    arrowUp: 'ArrowUpOutline',
    attach: 'AttachOutline',
    business: 'BusinessOutline',
    calendar: 'CalendarOutline',
    car: 'CarOutline',
    cellular: 'CellularOutline',
    chatbubble: 'ChatbubbleOutline',
    checkmark: 'Checkmark',
    checkmarkCircle: 'CheckmarkCircleOutline',
    chevronBack: 'ChevronBackOutline',
    chevronDown: 'ChevronDownOutline',
    chevronForward: 'ChevronForwardOutline',
    closeCircle: 'CloseCircleOutline',
    close: 'CloseOutline',
    documents: 'DocumentsOutline',
    download: 'DownloadOutline',
    ellipse: 'EllipseOutline',
    fileTrayFull: 'FileTrayFullOutline',
    heart: 'HeartOutline',
    home: 'HomeOutline',
    informationCircle: 'InformationCircleOutline',
    lockClosed: 'LockClosedOutline',
    logOut: 'LogOutOutline',
    menu: 'MenuOutline',
    notifications: 'NotificationsOutline',
    open: 'OpenOutline',
    people: 'PeopleOutline',
    person: 'PersonOutline',
    reader: 'ReaderOutline',
    receipt: 'ReceiptOutline',
    removeCircle: 'RemoveCircleOutline',
    school: 'SchoolOutline',
    search: 'SearchOutline',
    settings: 'SettingsOutline',
    wallet: 'WalletOutline',
    warning: 'WarningOutline',
  },
}
