export enum SearchableContentTypes {
  webArticle = 'webArticle',
  webLifeEventPage = 'webLifeEventPage',
  webDigitalIcelandService = 'webDigitalIcelandService',
  webDigitalIcelandCommunityPage = 'webDigitalIcelandCommunityPage',
  webNews = 'webNews',
  webOrganizationSubpage = 'webOrganizationSubpage',
  webOrganizationPage = 'webOrganizationPage',
  webQNA = 'webQNA',
  webLink = 'webLink',
  webProjectPage = 'webProjectPage',
  webManual = 'webManual',
  webManualChapterItem = 'webManualChapterItem',
  webOrganizationParentSubpage = 'webOrganizationParentSubpage',
}
