fragment HealthConversationMessageContent on HealthDirectorateHealthConversationMessageContent {
  __typename
  ... on HealthDirectorateHealthConversationTextContent {
    text
  }
  ... on HealthDirectorateHealthConversationSegmentedContent {
    segments {
      type
      text
      label
      href
    }
  }
  ... on HealthDirectorateHealthConversationVideoContent {
    url
    description
    appointmentDate
    appointmentHostName
    isCanceled
    isEdited
  }
}

fragment Dispensation on HealthDirectorateMedicineHistoryDispensation {
  id
  name
  agentName
  date
  strength
  quantity
  unit
  type
  indication
  dosageInstructions
  issueDate
  prescriberName
  expirationDate
  isExpired
}
