export const U2ErrorCode = {
  APPLICANT_NOT_FOUND: 'APPLICANT_NOT_FOUND',
  VALID_APPLICATION_NOT_FOUND: 'VALID_APPLICATION_NOT_FOUND',
  MINIMUM_BENEFIT_PERIOD: 'MINIMUM_BENEFIT_PERIOD',
  UNCOMPENSATED_PERIOD_COLLISION: 'UNCOMPENSATED_PERIOD_COLLISION',
  UPCOMING_UNCOMPENSATED_PERIOD: 'UPCOMING_UNCOMPENSATED_PERIOD',
  EXISTING_U2_APPLICATION: 'EXISTING_U2_APPLICATION',
} as const

export type U2ErrorCode = typeof U2ErrorCode[keyof typeof U2ErrorCode]
