export const mockData = {
  data: {
    debts: [
      {
        type: 'OtherFees',
        nationalId: '123456789',
        chargetypes: [
          {
            id: 'AB',
            name: 'Þing- og sveitarsjóðsgjöld',
            total: 85248,
            intrest: 18063,
            expenses: 0,
            principal: 67185,
          },
          {
            id: 'SJ',
            name: 'Staðgreiðsla, tryggingagjald',
            total: 8861,
            intrest: 2011,
            expenses: 0,
            principal: 6850,
          },
          {
            id: 'VF',
            name: 'Vörugjald af ökutækjum',
            total: 593820,
            intrest: 461771,
            expenses: 0,
            principal: 132049,
          },
        ],
        explanation: 'Þessi skuld verður send sem krafa',
        totalAmount: 687929,
        organization: '0000',
        paymentSchedule: 'Skattar og gjöld',
      },
    ],
    employer: {
      name: 'mock',
      nationalId: '123456789',
    },
    conditions: {
      alimony: 45222,
      maxDebt: false,
      percent: '10',
      doNotOwe: true,
      oweTaxes: true,
      citReturns: true,
      maxPayment: 2000000,
      minPayment: 69306,
      nationalId: '123456789',
      taxReturns: true,
      vatReturns: true,
      wageReturns: true,
      maxDebtAmount: 2000000,
      minWagePayment: 10000,
      totalDebtAmount: 982914,
      disposableIncome: 693068,
      collectionActions: false,
      withholdingTaxReturns: true,
      accommodationTaxReturns: true,
    },
    allInitialSchedules: [
      {
        maxPayment: 687929,
        minPayment: 69306,
        nationalId: '123456789',
        scheduleType: 'OtherFees',
        maxCountMonth: 10,
        minCountMonth: 1,
      },
    ],
  },
  date: '2022-04-25T16:40:46.613Z',
  status: 'success',
}
