export type { MatomoPageAttributes, MatomoContextValue } from './lib/types'
export { MatomoContext } from './lib/MatomoContext'
export { MatomoProvider } from './lib/MatomoProvider'
export { MatomoTracker } from './lib/MatomoTracker'
export { MatomoInitScript } from './lib/MatomoInitScript'
export { useMatomo, useMatomoPageView, useSetOrganization } from './lib/hooks'
