export { ConfigModule } from '@nestjs/config'
export { XRoadConfig } from './lib/configurations/XRoadConfig'
export { defineConfig } from './lib/defineConfig'
export { LazyDuringDevScope } from './lib/lazy-during-dev.scope'
export * from './lib/types'
