export { StudentTranscriptApi as HolarApi } from './gen/fetch'
export { StudentTrack as HolarStudentTrack } from './gen/fetch'
export { NemandiGetLocaleEnum as HolarLocale } from './gen/fetch'
export { NemandiFerillFerillFileTranscriptGetLocaleEnum as HolarTranscriptLocale } from './gen/fetch'
export { NemandiFerillFerillGetLocaleEnum as HolarFerillLocale } from './gen/fetch'
