import { AdminPortalScope } from '../admin-portal.scope'

export const adminPortalScopes = [
  AdminPortalScope.delegations,
  AdminPortalScope.airDiscountScheme,
  AdminPortalScope.regulationAdmin,
  AdminPortalScope.regulationAdminManage,
  AdminPortalScope.icelandicNamesRegistry,
  AdminPortalScope.applicationSystemAdmin,
  AdminPortalScope.applicationSystemInstitution,
  AdminPortalScope.documentProvider,
  AdminPortalScope.idsAdmin,
  AdminPortalScope.idsAdminSuperUser,
  AdminPortalScope.petitionsAdmin,
  AdminPortalScope.serviceDesk,
  AdminPortalScope.explicitAirDiscountScheme,
  AdminPortalScope.signatureCollectionManage,
  AdminPortalScope.signatureCollectionProcess,
  AdminPortalScope.signatureCollectionMunicipality,
  AdminPortalScope.formSystem,
  AdminPortalScope.formSystemAdmin,
  AdminPortalScope.delegationSystem,
  AdminPortalScope.delegationSystemAdmin,
  AdminPortalScope.payments,
]
