export * from './lib/auth.module'
export * from './lib/jwt.strategy'
export * from './lib/scopes.decorator'
export * from './lib/current-user.decorator'
export * from './lib/current-actor.decorator'
export * from './lib/scopes.guard'
export * from './lib/ids-auth.guard'
export * from './lib/ids-user.guard'
export * from './lib/mock-auth.guard'
export * from './lib/user'
export * from './lib/auth'
export * from './lib/auth.middleware'
export * from './lib/bypass-auth.decorator'
// export { AuthModule } from './lib/auth.module'
// export type { AuthConfig } from './lib/auth.module'
// export { JwtStrategy } from './lib/jwt.strategy'
// export { Scopes } from './lib/scopes.decorator'
// export { CurrentUser, getCurrentUser } from './lib/current-user.decorator'
// export { ScopesGuard } from './lib/scopes.guard'
// export { IdsAuthGuard } from './lib/ids-auth.guard'
// export { IdsUserGuard } from './lib/ids-user.guard'
// export { MockAuthGuard } from './lib/mock-auth.guard'
// export type { User } from './lib/user'
// export type { Auth } from './lib/auth'
// export { AuthMiddleware } from './lib/auth.middleware'
// export { BypassAuth, BYPASS_AUTH_KEY } from './lib/bypass-auth.decorator'
