export enum InformationPaths {
  MyInfoRoot = '/min-gogn',
  MyInfoRootOverview = '/min-gogn/yfirlit',
  SettingsOld = '/stillingar/minar-stillingar/',
  MyContracts = '/min-gogn/samningar',
  MyContractsDetail = '/min-gogn/samningar/:id',
  Settings = '/min-gogn/stillingar/',
  SettingsNotifications = '/min-gogn/stillingar/tilkynningar',
  ChildCustody = '/min-gogn/yfirlit/barn/:baseId',
  BioChild = '/min-gogn/yfirlit/fjolskylda/:baseId',
  Spouse = '/min-gogn/yfirlit/maki/',
  UserInfo = '/min-gogn/yfirlit/minar-upplysingar',
  Company = '/fyrirtaeki',
  CompanySettings = '/fyrirtaeki/stillingar/',
  CompanyNotifications = '/fyrirtaeki/tilkynningar',
  Notifications = '/min-gogn/tilkynningar',
  NotificationDetail = '/min-gogn/tilkynningar/:id',
  Lists = '/min-gogn/listar',
  CompanyLists = '/fyrirtaeki/listar',
}
