export { NationalRegistryProvider } from '@island.is/application/data-providers'
export { UserProfileProvider } from '@island.is/application/data-providers'
export { DistrictsProvider } from './DistrictsProvider'
export { RealEstateProvider } from './RealEstateProvider'
export { VehicleProvider } from './VehicleProvider'
