export enum CardErrorCode {
  InsufficientFunds = 'insufficient_funds',
  ExpiredCard = 'expired_card',
  InvalidCardNumber = 'invalid_card_number',
  InvalidCardExpiry = 'invalid_card_expiry',
  InvalidCardCVC = 'invalid_card_cvc',
  InvalidCard = 'invalid_card',
  LostCard = 'lost_card',
  StolenCard = 'stolen_card',
  ClosedAccount = 'closed_account',
  TransactionNotPermitted = 'transaction_not_permitted',
  RestrictedCard = 'restricted_card',
  SuspectedFraud = 'suspected_fraud',
  ExceedsWithdrawalLimit = 'exceeds_withdrawal_limit',
  SecurityViolation = 'security_violation',
  AdditionalAuthenticationRequired = 'additional_authentication_required',
  ContactIssuer = 'contact_issuer',
  IssuerUnavailable = 'issuer_unavailable',
  DuplicateTransaction = 'duplicate_transaction',
  TransactionTimedOut = 'transaction_timed_out',
  StopPaymentOrder = 'stop_payment_order',
  RevocationOfAuthorization = 'revocation_of_authorization',
  RevocationOfAllAuthorizations = 'revocation_of_all_authorizations',
  PaymentSystemUnavailable = 'payment_system_unavailable',
  GenericDecline = 'generic_decline',
  VerificationDeadlineExceeded = 'verification_deadline_exceeded',
  Unknown = 'unknown',
}
