import { Document } from '@island.is/api/schema'

export const documents: Document[] = [
  {
    id: '1',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '2',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '3',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '4',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '5',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '6',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '7',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '8',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '9',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '10',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '11',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '12',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '13',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '14',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '15',
    date: new Date(),

    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '16',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '17',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '18',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '19',
    date: new Date(),
    subject: 'Subject subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: true,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
  {
    id: '20',
    date: new Date(),
    subject: 'UNREAD subject',
    senderName: 'Ríkislögreglustjóri',
    senderNatReg: 'NatReg?',
    opened: false,
    fileType: 'pdf',
    url: 'https://visir.is',
  },
]
