export { DirectorateOfEqualityClientService } from './lib/directorate-of-equality.service'
export { DirectorateOfEqualityClientModule } from './lib/directorate-of-equality.module'
export { DirectorateOfEqualityClientConfig } from './lib/directorate-of-equality.config'
export type {
  ApplicationReportCommentDto,
  ApplicationReportDetailDto,
  CompanyDto,
  CreateReportResponseDto,
  DraftAssignmentDto,
  DraftCriterionWithSubCriteriaDto,
  DraftDetailDto,
  DraftEmployeeWithStepsDto,
  DraftOutlierGroupDto,
  DraftRoleWithStepsDto,
  DraftSubCriterionWithStepsDto,
  EditEqualityContentDto,
  EditOutliersDto,
  EmployeeOutlierGroupDto,
  EqualityReportSummaryDto,
  GetDraftCriteriaResponseDto,
  GetDraftCriteriaTreeResponseDto,
  GetDraftEmployeesResponseDto,
  GetDraftEmployeesWithStepsResponseDto,
  GetDraftOutlierGroupsResponseDto,
  GetDraftRolesResponseDto,
  GetDraftRolesWithStepsResponseDto,
  GetDraftStepsResponseDto,
  GetDraftSubCriteriaResponseDto,
  GetReportOutliersResponseDto,
  Paging,
  GetSubCriterionCatalogResponseDto,
  ParsedCriterionDto,
  ParsedSubCriterionDto,
  ParsedEmployeeDto,
  ParsedRoleDto,
  ParsedReportDto,
  ReportCriterionDto,
  ReportEmployeeDto,
  ReportEmployeeRoleDto,
  ReportSubCriterionDto,
  ReportSubCriterionStepDto,
  ScoreBucketDto,
  SalaryAnalysisOutlierDto,
  SalaryAnalysisRequestDto,
  SalaryAnalysisResponseDto,
  SalaryByGenderAndScoreDto,
  SalaryTotalsDto,
  SubCriterionCatalogEntryDto,
  SubmitApplicationReportCommentDto,
  SubmitDraftDto,
  SubmitEqualityReportDto,
  SubmitSalaryReportDto,
  SyncDraftDto,
  UpdateDraftDto,
} from '../gen/fetch'
export {
  CompanySizeEnum,
  ReportCriterionTypeEnum,
  ReportTypeEnum,
  SyncMethodEnum,
} from '../gen/fetch'
