export { Congratulations,Declined } from './Done'
export { EligibilitySummary } from './EligibilitySummary'
export { default as HealthDeclaration } from './HealthDeclaration'
export { LinkExistingApplication } from './LinkExistingApplication'
export { PaymentPending } from './PaymentPending'
export { Bullets,QualityPhoto } from './QualityPhoto'
export { SubmitAndDecline } from './SubmitAndDecline'
