export enum FieldType {
  UPLOAD = 'UPLOAD',
  CHECKBOX = 'CHECKBOX',
  TEXT_INPUT = 'TEXT_INPUT',
  TEXT_AREA = 'TEXT_AREA',
  DATA_PROVIDER = 'DATA_PROVIDER',
  APPROVAL_PROVIDER = 'APPROVAL_PROVIDER',
  TESTING_SITE_SELECTION = 'TESTING_SITE_SELECTION',
}
