import type { Case } from '../../repository'

export type MinimalCase = Omit<
  Case,
  | 'defendants'
  | 'prosecutor'
  | 'creatingProsecutor'
  | 'court'
  | 'registrar'
  | 'judge'
  | 'parentCase'
  | 'childCase'
  | 'caseFiles'
  | 'notifications'
  | 'eventLogs'
  | 'dateLogs'
  | 'caseStrings'
  | 'mergedCases'
  | 'mergeCase'
  | 'prosecutorsOffice'
  | 'sharedWithProsecutorsOffice'
  | 'courtRecordSignatory'
  | 'indictmentReviewer'
  | 'civilClaimants'
  | 'victims'
>
