#!/bin/bash
set -e

DIR="$(git rev-parse --show-toplevel)"
marker=$(mktemp)
touch "$marker" -r "${BASH_SOURCE[0]}"

CMD=$1
shift

$CMD "$@" 1>&2

# Find all files that were generated by running the command in argv
find "$DIR"/apps "$DIR"/libs -type f -newer "$marker"
