import { defineMessages } from 'react-intl'

export const conclusionMessages = defineMessages({
  sectionTitle: {
    id: 'nps.application:conclusion.sectionTitle',
    defaultMessage: 'Staðfesting',
    description: 'Confirmation',
  },
  expandableDescription: {
    id: 'nps.application:conclusion.expandableDescription#markdown',
    defaultMessage:
      'Skólinn fær núna umsóknina til sín til umfjöllunar og mun svara þér um ákvörðun sína eins fljótt og auðið er með bréfi sem sent verður í stafræna pósthólfið þitt á [Ísland.is](https://island.is).\n\nÁður en ákvörðun er tekin kann að vera þörf á því að afla frekari gagna í þeim tilgangi að upplýsa betur um aðstæður barnsins þíns eða ástæður umsóknar. Mun þá sveitarfélagið þar sem þú ert með skráð lögheimili eða skólinn sem þú ert að sækja um skólavist í, setja sig í samband við þig.\n\nEf þú sóttir um sjálfstætt starfandi skóla, og skráðir annan aðila sem greiðanda gjalda fyrir skólavist, þá verður greiðandi beðinn um að staðfesta þátttöku sína áður en umsókn er send til skóla til úrvinnslu.\n\nEf þú sóttir um sjálfstætt starfandi skóla eða skóla utan sveitarfélagsins þar sem þú ert með skráð lögheimili, þá þarf lögheimilissveitarfélagið einnig að taka afstöðu til þess hvort að það sé tilbúið til að greiða fyrir skólavist barnsins í öðru sveitarfélagi. Staðfesting á greiðslu er forsenda þess að umsóknin fari svo til umfjöllunar hjá þeim skóla sem þessi umsókn fjallar um.\n\nAthugið að ekki er víst að hægt sé að verða við ósk forsjáraðila en það fer eftir fjölda lausra plássa, fjölda umsókna og aðstæðum í skólanum á hverjum tíma.\n\nEf umsókn um skólaskipti er samþykkt, verður þú og barnið þitt boðað til móttökuviðtals.',
    description:
      'The school will now receive your application for consideration and will reply to you as soon as possible with a message sent to your digital mailbox at [Ísland.is](https://island.is). \n\nBefore a decision is made, additional information may be needed to better understand your child’s situation or the reasons for the application. You will be contacted by the municipality where you are registered or by the school where you applied, if need be. \n\nIf you applied for an independent school, and you register another party as the payer for the school fees, the payer will be asked to confirm before the application is sent to the school for processing. \n\nIf you applied for an independent school or a school outside the municipality where you have a registered domicile, the municipality where you are registered must decide whether it will pay for the child’s schooling in another municipality. Confirmation of payment is a prerequisite for the application to be considered by the school you are applying for. \n\nPlease note that it may not be possible to comply with the guardian’s request, it will depend on the number of places available, the number of applications and the circumstances at the school at any given time. \n\nIf your application for a school transfer is accepted, you and your child will be invited to a reception interview.',
  },
  enrollmentExpandableDescription: {
    id: 'nps.application:conclusion.enrollmentExpandableDescription#markdown',
    defaultMessage:
      'Takk fyrir að staðfesta skólavistina.\n\nSkólinn mun senda þér upplýsingar um fyrsta skóladag þegar nær dregur. Fram að því hvetjum við þig til að skoða heimasíðu skólans.',
    description:
      'Thank you for confirming the school enrolment.\n\nThe school will send you information about the first day of school as it gets closer. Until then, we encourage you to look at the school’s website.',
  },
  continuingEnrollmentExpandableDescription: {
    id: 'nps.application:conclusion.continuingEnrollmentExpandableDescription#markdown',
    defaultMessage:
      'Umsóknin fer núna til umfjöllunar hjá sveitarfélaginu þar sem að barnið er með skráð lögheimili. Þar verður tekin afstaða til þess hvort að sveitarfélagið geti greitt fyrir skólavistina. Staðfesting á greiðslu er forsenda þess að umsóknin fari svo til afgreiðslu hjá skólanum sjálfum.\n\nSkólinn mun að lokum svara þér um ákvörðun sína eins fljótt og auðið er með bréfi sem sent verður í stafræna pósthólfið þitt á Ísland.is.\n\nAthugið að upp getur komið sú staða að skólinn geti ekki orðið við ósk forsjáraðila, en það fer eftir fjölda lausra plássa, fjölda umsókna og aðstæðum í skólanum á hverjum tíma.\n\nFari svo að skóli sjái sér ekki fært að veita barni áframhaldandi skólavist, verður barnið skráð í sinn hverfisskóla, þar sem það á ávalt rétt á plássi.',
    description:
      'The application will now be considered by the municipality where the child has a registered legal domicile. A decision will be made as to whether the municipality can pay for the school fees. Confirmation of payment is a prerequisite for the application to be processed by the school itself.\n\nThe school will then inform you of their decision as soon as possible with a message sent to your digital mailbox at [Ísland.is](https://island.is).\n\nPlease note that there may be situations where the school cannot comply with the guardian’s request, but this depends on the number of available places, the number of applications and the conditions at the school at any given time.\n\n In the event that a school is unable to provide a child with continued schooling, the child will be enrolled in his local school, where he has the right to a place.',
  },
  specialEducationExpandableDescription: {
    id: 'nps.application:conclusion.specialEducationExpandableDescription#markdown',
    defaultMessage:
      'Forsjáraðili hefur 14 daga til að skila nauðsynlegum fylgiskjölum með umsókn til skóla ef þau voru ekki send rafrænt með þessari umsókn, en án þeirra verður umsókn ekki tekin til umfjöllunar.\n\nSkólinn tekur ákvörðun um skólavist byggða á grundvelli tillagna fagráðs sem fjallar um allar umsóknir. Tilkynnir skólinn þér um ákvörðunina eins fljótt og auðið er með bréfi sem sent verður í stafræna pósthólfið þitt á [Ísland.is](https://island.is).\n\nÁður en afstaða er tekin kann þó að vera þörf á því að afla frekari gagna í þeim tilgangi að upplýsa betur um aðstæður barnsins þíns eða ástæður umsóknar. Mun þá sveitarfélagið þar sem þú ert með skráð lögheimili eða skólinn sem þú ert að sækja um skólavist í, setja sig í samband við þig.\n\nÍ þeim tilvikum sem aðilar deila forsjá er nauðsynlegt að samþykki beggja aðila fyrir umsókn liggi fyrir. Sé forsjá deilt verður þessi umsókn send fyrst til undirritunar hjá þeim aðila sem ekki er skráður fyrir umsókninni. Samþykki hans er forsenda þess að umsókn sé send áfram til úrvinnslu.\n\nEf þú sóttir um sjálfstætt starfandi skóla, og skráðir annan aðila sem greiðanda gjalda fyrir skólavist, þá verður greiðandi einnig beðinn um að staðfesta þátttöku sína áður en umsókn er send til skóla til úrvinnslu.\n\nAthugið að ekki er víst að hægt sé að verða við ósk þinni en það fer meðal annars eftir fjölda umsókna, fjölda lausra plássa og aðstæðum í hverjum skóla á hverjum tíma. Ef umsókn er synjað vegna þessa er foreldrum gefinn kostur á að halda umsókn sinni í skólanum virkri til umfjöllun síðar.\n\nEf umsókn um skólavist er samþykkt, verður þú og barnið þitt boðað til móttökuviðtals.',
    description:
      'The guardian has 14 days to return the necessary documents with the application to the school if they were not sent electronically with the application, without them the application will not be considered.\n\nThe school makes a decision regarding school enrolment based on the proposal of a professional council, which considers all applications. The school will notify you of their decision as soon as possible with a message sent to your digital mailbox at Ísland.is.\n\nBefore a decision is made, additional information may be needed to better understand your child’s situation or the reasons for the application. You will be contacted by the municipality where you are registered or by the school where you applied, if need be.\n\nIn cases where the parties share custody, it is necessary that both parties consent to the application. If custody is shared, this application will first be sent to be signed by the person who is not registered for the application. Their approval is a prerequisite for the application to be forwarded for processing.\n\nIf you applied for an independent school, and you register another party as the payer for the school fees, the payer will be asked to confirm before the application is sent to the school for processing.\n\nPlease note that it may not be possible to comply with your request, it will depend on the number of places available, the number of applications and the circumstances at the school at any given time. If the application is rejected due to these reasons, the parents are given the option to keep their application active at the school for later consideration.\n\nIf your application for school enrolment is accepted, you and your child will be invited to a reception interview.',
  },
})
