name: 'Load Dependencies'
description: 'Prerequisite is that the prepare step has already been run'

inputs:
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: './'
  cache-path:
    description: 'Cache path'
    required: false
    default: .cache/generated-files

runs:
  using: 'composite'
  steps:
    - name: Set cache key
      working-directory: ${{ inputs.working-directory }}
      id: cache-key
      shell: bash
      env:
        CACHE_PATH: ${{ inputs.cache-path }}
      run: |
        node ./scripts/ci/generate-files.mjs --skip-codegen
        CACHE_KEY=${{ hashFiles('generated_files_list.txt') }}
        GENERATED_FILES_PATH=$CACHE_PATH/$CACHE_KEY
        echo "GENERATED_FILES_PATH=$GENERATED_FILES_PATH" >> "$GITHUB_OUTPUT"
        echo "Generated files will be stored in $GENERATED_FILES_PATH"
        echo "CACHE_KEY=$CACHE_KEY"
        mkdir -p "$CACHE_PATH"

    - name: INFO
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "generated files: ${{ steps.cache-key.outputs.GENERATED_FILES_PATH }}"

    - name: Cache generated files (restore)
      uses: runs-on/cache/restore@v4
      id: restore-codegen-cache
      with:
        path: |
          ${{ steps.cache-key.outputs.GENERATED_FILES_PATH }}
        key: generated-files-${{ steps.cache-key.outputs.CACHE_KEY }}

    - name: Prepare generated files
      if: steps.restore-codegen-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        node ./scripts/ci/generate-files.mjs ${{ steps.cache-key.outputs.GENERATED_FILES_PATH }}

    - name: Extract generated files
      if: steps.restore-codegen-cache.outputs.cache-hit == 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        tar -xzvf ${{ steps.cache-key.outputs.GENERATED_FILES_PATH }}

    - name: Cache generated files (save)
      if: steps.restore-codegen-cache.outputs.cache-hit != 'true'
      uses: runs-on/cache/save@v4
      with:
        path: |
          ${{ steps.cache-key.outputs.GENERATED_FILES_PATH }}
        key: generated-files-${{ steps.cache-key.outputs.CACHE_KEY }}
