name: 'Load Dependencies'
description: 'Prerequisite is that the prepare step has already been run'

inputs:
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: './'
  cache-path:
    description: 'Cache path'
    required: false
    default: ${{ runner.temp }}

runs:
  using: 'composite'
  steps:
    - name: Set env
      shell: bash
      run: |
        export GENERATED_FILES_PATH=${{ inputs.cache-path }}/${{ env.GENERATED_FILES }}
        echo "GENERATED_FILES_PATH=$GENERATED_FILES_PATH" >> "$GITHUB_ENV"

    - name: INFO
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "generated files: ${{ env.GENERATED_FILES_PATH }}"

    - name: Generate hash for generated files list
      id: generate-files-hash
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        node ./scripts/ci/generate-files.mjs /dev/null --skip-codegen

    - name: Cache generated files
      uses: ./.github/actions/cache
      id: restore-codegen-cache
      with:
        path: |
          ${{ env.GENERATED_FILES_PATH }}
        key: >-
          generated-files-${{ hashFiles('generated_files_list.txt') }}
        working-directory: ${{ inputs.working-directory }}

    - name: Prepare generated files
      if: steps.restore-codegen-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        node ./scripts/ci/generate-files.mjs ${{ env.GENERATED_FILES_PATH }}

    - name: Extract generated files
      if: steps.restore-codegen-cache.outputs.cache-hit == 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "::group::Extract generated files"
        tar -xzvf ${{ env.GENERATED_FILES_PATH }}
        echo "::endgroup::"
