name: 'Load Dependencies'
description: 'Prerequisite is that the prepare step has already been run'

inputs:
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: './'
  cache-path:
    description: 'Cache path'
    required: false
    default: ${{ runner.temp ?? '.cache' }}

runs:
  using: 'composite'
  steps:
    - name: Set env
      id: set-env
      shell: bash
      run: |
        echo "GENERATED_FILES_PATH=${{ inputs.cache-path }}/${{ github.sha }}.tar.gz" >> "$GITHUB_OUTPUT"
        echo "AWS_REGION=eu-west-1" >> "$GITHUB_OUTPUT"
        echo "CACHE_KEY=generated-files-${{ github.sha }}" >> "$GITHUB_OUTPUT"

    - name: INFO
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "generated files: ${{ steps.set-env.outputs.GENERATED_FILES_PATH }}"

    - name: Restore generated files
      uses: runs-on/cache/restore@v4
      id: restore-codegen-cache
      with:
        path: |
          ${{ steps.set-env.outputs.GENERATED_FILES_PATH }}
        key: ${{ steps.set-env.outputs.CACHE_KEY }}
      env:
        RUNS_ON_S3_BUCKET_CACHE: ${{ secrets.S3_DOCKER_CACHE_BUCKET }} # Secrets can't be stored in outputs
        AWS_REGION: eu-west-1

    - name: Prepare generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        node ./scripts/ci/generate-files.mjs "${{ steps.set-env.outputs.GENERATED_FILES_PATH }}"

    - name: Extract generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit == 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        tar -xzvf "${{ steps.set-env.outputs.GENERATED_FILES_PATH }}"

    - name: Cache Generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit != 'true' }}
      uses: runs-on/cache/save@v4
      with:
        path: |
          ${{ steps.set-env.outputs.GENERATED_FILES_PATH }}
        key: ${{ steps.set-env.outputs.CACHE_KEY }}
      env:
        RUNS_ON_S3_BUCKET_CACHE: ${{ secrets.S3_DOCKER_CACHE_BUCKET }} # Secrets can't be stored in outputs
        AWS_REGION: eu-west-1
