name: 'Load Dependencies'
description: 'Load generated files (or load from cache)'

inputs:
  cache-bucket:
    description: 'Bucket to use as cache (for RunsOn action cache)'
    required: false
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: './'
  cache-path:
    description: 'Cache path'
    required: false
    default: ${{ runner.temp }}
  generate-key:
    description: 'Key for the generated files'
    required: false
    default: ${{ github.sha }}

runs:
  using: 'composite'
  steps:
    - name: Ensure cache bucket
      id: bucket
      shell: bash
      run: echo "${{ inputs.cache-bucket || env.CACHE_BUCKET || env.RUNS_ON_S3_BUCKET_CACHE }}" | grep '.' >> "$GITHUB_OUTPUT"

    - name: Set env
      id: set-env
      shell: bash
      run: |
        echo "generated-files-path=${{ inputs.working-directory }}/.cache/generated-files/${{ inputs.generate-key }}.tar.gz" >> "$GITHUB_OUTPUT"
        echo "aws-region=eu-west-1" >> "$GITHUB_OUTPUT"
        echo "cache-key=generated-files-${{ inputs.generate-key }}" >> "$GITHUB_OUTPUT"

    - name: INFO
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "generated files: ${{ steps.set-env.outputs.generated-files-path }}"

    - name: Cache generated files
      uses: runs-on/cache@v4
      id: restore-codegen-cache
      with:
        path: |
          ${{ steps.set-env.outputs.generated-files-path }}
        key: ${{ steps.set-env.outputs.cache-key }}
      env:
        RUNS_ON_S3_BUCKET_CACHE: ${{ steps.bucket.outputs.bucket }}
        AWS_REGION: eu-west-1

    - name: Prepare generated files
      if: steps.restore-codegen-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        node ./scripts/ci/generate-files.mjs "${{ steps.set-env.outputs.generated-files-path }}"

    - name: Extract generated files
      if: steps.restore-codegen-cache.outputs.cache-hit == 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        tar -xzvf "${{ steps.set-env.outputs.generated-files-path }}"
