import React, { FC } from 'react'
import { IcelandicAssociationOfLocalAuthoritiesLogo } from '../index'
import {
  AkrahreppurLogo,
  AkranesLogo,
  AkureyriLogo,
  ArborgLogo,
  ArneshreppurLogo,
  AsahreppurLogo,
  BlaskogabyggdLogo,
  BlonduosbaerLogo,
  BolungarvikLogo,
  BorgarbyggdLogo,
  DalabyggdLogo,
  DalvikurbyggdLogo,
  EyjaOgMiklaholtshreppurLogo,
  EyjafjardarsveitLogo,
  FjallabyggdLogo,
  FjardabyggdLogo,
  FljotsdalshreppurLogo,
  FloahreppurLogo,
  GardabaerLogo,
  GrimsnesOgGrafningshreppurLogo,
  GrindavikurbaerLogo,
  GrundafjardarbaerLogo,
  GrytubakkahreppurLogo,
  HafnarfjordurLogo,
  HelgafellssveitLogo,
  HorgarsveitLogo,
  HornafjordurLogo,
  HrunamannahreppurLogo,
  HunathingVestraLogo,
  HunavatnshreppurLogo,
  HvalfjardarsveitLogo,
  HveragerdisbaerLogo,
  IsafjardarbaerLogo,
  KaldrananeshreppurLogo,
  KjosarhreppurLogo,
  KopavogurLogo,
  LanganesbyggdLogo,
  MosfellsbaerLogo,
  MulathingLogo,
  MyrdalshreppurLogo,
  NordurthingLogo,
  OlfusLogo,
  RangarthingYtraLogo,
  Rangarthing_eystraLogo,
  ReykholahreppurLogo,
  ReykjanesbaerLogo,
  SeltjarnarnesLogo,
  SkaftarhreppurLogo,
  SkagabyggdLogo,
  SkagafjordurLogo,
  SkagastrondLogo,
  SkeidaOgGnupverjahreppurLogo,
  SkorradalurLogo,
  SkutustadahreppurLogo,
  SnaefellsbaerLogo,
  StrandabyggdLogo,
  StykkisholmsbaerLogo,
  SudavikurhreppurLogo,
  SudurnesjabaerLogo,
  SvalbardshreppurLogo,
  SvalbardsstrandarhreppurLogo,
  TalknafjardarhreppurLogo,
  ThingeyjarsveitLogo,
  TjorneshreppurLogo,
  VestmannaeyjabaerLogo,
  VesturbyggdLogo,
  VogarLogo,
  VopnafjardarhreppurLogo,
} from '../index'

// Mapping from municipality codes to TSX logo components
export const municipalityLogoMap: Record<
  string,
  FC<React.PropsWithChildren<unknown>>
> = {
  '5706': AkrahreppurLogo,
  '3000': AkranesLogo,
  '6000': AkureyriLogo,
  '8200': ArborgLogo,
  '4901': ArneshreppurLogo,
  '8610': AsahreppurLogo,
  '8721': BlaskogabyggdLogo,
  '5604': BlonduosbaerLogo,
  '4100': BolungarvikLogo,
  '3609': BorgarbyggdLogo,
  '3811': DalabyggdLogo,
  '6400': DalvikurbyggdLogo,
  '3713': EyjaOgMiklaholtshreppurLogo,
  '6513': EyjafjardarsveitLogo,
  '6250': FjallabyggdLogo,
  '7300': FjardabyggdLogo,
  '7505': FljotsdalshreppurLogo,
  '8722': FloahreppurLogo,
  '1300': GardabaerLogo,
  '8719': GrimsnesOgGrafningshreppurLogo,
  '2300': GrindavikurbaerLogo,
  '3709': GrundafjardarbaerLogo,
  '6602': GrytubakkahreppurLogo,
  '1400': HafnarfjordurLogo,
  '3710': HelgafellssveitLogo,
  '6515': HorgarsveitLogo,
  '8401': HornafjordurLogo,
  '8710': HrunamannahreppurLogo,
  '5508': HunathingVestraLogo,
  '5612': HunavatnshreppurLogo,
  '3511': HvalfjardarsveitLogo,
  '8716': HveragerdisbaerLogo,
  '4200': IsafjardarbaerLogo,
  '4902': KaldrananeshreppurLogo,
  '1606': KjosarhreppurLogo,
  '1000': KopavogurLogo,
  '6709': LanganesbyggdLogo,
  '1604': MosfellsbaerLogo,
  '7400': MulathingLogo,
  '8508': MyrdalshreppurLogo,
  '6100': NordurthingLogo,
  '8717': OlfusLogo,
  '8613': Rangarthing_eystraLogo,
  '8614': RangarthingYtraLogo,
  '4502': ReykholahreppurLogo,
  '2000': ReykjanesbaerLogo,
  '1100': SeltjarnarnesLogo,
  '8509': SkaftarhreppurLogo,
  '5611': SkagabyggdLogo,
  '5200': SkagafjordurLogo,
  '5609': SkagastrondLogo,
  '8720': SkeidaOgGnupverjahreppurLogo,
  '3506': SkorradalurLogo,
  '6607': SkutustadahreppurLogo,
  '3714': SnaefellsbaerLogo,
  '4911': StrandabyggdLogo,
  '3711': StykkisholmsbaerLogo,
  '4803': SudavikurhreppurLogo,
  '2510': SudurnesjabaerLogo,
  '6706': SvalbardshreppurLogo,
  '6601': SvalbardsstrandarhreppurLogo,
  '4604': TalknafjardarhreppurLogo,
  '6612': ThingeyjarsveitLogo,
  '6611': TjorneshreppurLogo,
  '8000': VestmannaeyjabaerLogo,
  '4607': VesturbyggdLogo,
  '2506': VogarLogo,
  '7502': VopnafjardarhreppurLogo,
}

/**
 * Get the municipality logo component by municipality ID
 * @param municipalityId - The municipality ID code
 * @returns The corresponding logo component or the default Sambandid logo
 */
export const getMunicipalityLogo = (
  municipalityId: string | undefined,
): FC<React.PropsWithChildren<unknown>> => {
  if (!municipalityId || !municipalityLogoMap[municipalityId]) {
    return IcelandicAssociationOfLocalAuthoritiesLogo
  }
  return municipalityLogoMap[municipalityId]
}
