process.env.APPLICATION_DB_USER = process.env.APPLICATION_TEST_DB_USER
process.env.APPLICATION_DB_PASS = process.env.APPLICATION_TEST_DB_PASS
process.env.APPLICATION_DB_NAME = process.env.APPLICATION_TEST_DB_NAME
