export { CreateSignedUrlInput } from './getSignedUrl.input'
export { MunicipalityInput } from './municipality.input'
export { CreateApplicationInput } from './createApplication.input'
export { CreateFileInput } from './createFile.input'
export { DirectTaxPaymentInput } from './directTaxPayment.input'
export { PersonalTaxReturnInput } from './personalTaxReturn.input'
export { GetDirectTaxPaymentsInput } from './getDirectTaxPayments.input'
