import { createElement, forwardRef } from 'react'

import { BoxProps } from './types'
import { useBoxStyles } from './useBoxStyles'
import { TestSupport } from '@island.is/island-ui/utils'

export const Box = forwardRef<HTMLElement, BoxProps & TestSupport>(
  (
    {
      component = 'div',
      padding,
      paddingX,
      paddingY,
      paddingTop,
      paddingBottom,
      paddingLeft,
      paddingRight,
      margin,
      marginX,
      marginY,
      marginTop,
      marginBottom,
      marginLeft,
      marginRight,
      display,
      flexDirection,
      flexWrap,
      flexShrink,
      flexGrow,
      columnGap,
      rowGap,
      alignItems,
      alignSelf,
      justifyContent,
      textAlign,
      border,
      borderColor,
      borderWidth,
      borderRightWidth,
      borderTopWidth,
      borderLeftWidth,
      borderBottomWidth,
      borderXWidth,
      borderYWidth,
      borderStyle,
      borderRadius,
      background,
      backgroundPattern,
      boxShadow,
      transition,
      transform,
      height,
      width,
      position,
      cursor,
      pointerEvents,
      overflow,
      minWidth,
      top,
      bottom,
      right,
      left,
      userSelect,
      outline,
      opacity,
      printHidden,
      className,
      dataTestId,
      zIndex,
      ...restProps
    },
    ref,
  ) => {
    const boxStyles = useBoxStyles({
      component,
      padding,
      paddingX,
      paddingY,
      paddingTop,
      paddingBottom,
      paddingLeft,
      paddingRight,
      margin,
      marginX,
      marginY,
      marginTop,
      marginBottom,
      marginLeft,
      marginRight,
      display,
      flexDirection,
      flexWrap,
      flexShrink,
      flexGrow,
      columnGap,
      rowGap,
      alignItems,
      alignSelf,
      justifyContent,
      textAlign,
      border,
      borderColor,
      borderWidth,
      borderRightWidth,
      borderTopWidth,
      borderLeftWidth,
      borderBottomWidth,
      borderXWidth,
      borderYWidth,
      borderStyle,
      borderRadius,
      background,
      backgroundPattern,
      boxShadow,
      transition,
      transform,
      height,
      width,
      position,
      cursor,
      pointerEvents,
      overflow,
      minWidth,
      top,
      bottom,
      right,
      left,
      userSelect,
      outline,
      opacity,
      printHidden,
      zIndex,
      className,
    })

    return createElement(component, {
      className: boxStyles,
      'data-testid': dataTestId,
      ...restProps,
      ref,
    })
  },
)
