export * from './lib/application.scope'
export * from './lib/auth.scope'
export * from './lib/authAdmin.scope'
export * from './lib/documents.scope'
export * from './lib/userProfile.scope'
export * from './lib/nationalRegistry.scope'
export * from './lib/generic.scope'
