import {
  CaseTableColumn,
  CaseTableColumnKey,
  CaseTableColumnMap,
  caseTableColumns,
} from './caseTableColumnTypes'

export enum CaseTableType {
  COURT_OF_APPEALS_IN_PROGRESS = 'COURT_OF_APPEALS_IN_PROGRESS',
  COURT_OF_APPEALS_COMPLETED = 'COURT_OF_APPEALS_COMPLETED',
  DISTRICT_COURT_REQUEST_CASES_IN_PROGRESS = 'DISTRICT_COURT_REQUEST_CASES_IN_PROGRESS',
  DISTRICT_COURT_REQUEST_CASES_APPEALED = 'DISTRICT_COURT_REQUEST_CASES_APPEALED',
  DISTRICT_COURT_REQUEST_CASES_COMPLETED = 'DISTRICT_COURT_REQUEST_CASES_COMPLETED',
  DISTRICT_COURT_INDICTMENTS_NEW = 'DISTRICT_COURT_INDICTMENTS_NEW',
  DISTRICT_COURT_INDICTMENTS_RECEIVED = 'DISTRICT_COURT_INDICTMENTS_RECEIVED',
  DISTRICT_COURT_INDICTMENTS_IN_PROGRESS = 'DISTRICT_COURT_INDICTMENTS_IN_PROGRESS',
  DISTRICT_COURT_INDICTMENTS_FINALIZING = 'DISTRICT_COURT_INDICTMENTS_FINALIZING',
  DISTRICT_COURT_INDICTMENTS_COMPLETED = 'DISTRICT_COURT_INDICTMENTS_COMPLETED',
  PRISON_ACTIVE = 'PRISON_ACTIVE',
  PRISON_DONE = 'PRISON_DONE',
  PRISON_ADMIN_ACTIVE = 'PRISON_ADMIN_ACTIVE',
  PRISON_ADMIN_DONE = 'PRISON_ADMIN_DONE',
  PRISON_ADMIN_INDICTMENT_SENT_TO_PRISON_ADMIN = 'PRISON_ADMIN_INDICTMENT_SENT_TO_PRISON_ADMIN',
  PRISON_ADMIN_INDICTMENT_REGISTERED_RULING = 'PRISON_ADMIN_INDICTMENT_REGISTERED_RULING',
  PROSECUTORS_OFFICE_INDICTMENT_NEW = 'PROSECUTORS_OFFICE_INDICTMENT_NEW',
  PROSECUTORS_OFFICE_INDICTMENT_IN_REVIEW = 'PROSECUTORS_OFFICE_INDICTMENT_IN_REVIEW',
  PROSECUTORS_OFFICE_INDICTMENT_REVIEWED = 'PROSECUTORS_OFFICE_INDICTMENT_REVIEWED',
  PROSECUTORS_OFFICE_INDICTMENT_APPEAL_PERIOD_EXPIRED = 'PROSECUTORS_OFFICE_INDICTMENT_APPEAL_PERIOD_EXPIRED',
  PROSECUTORS_OFFICE_INDICTMENT_SENT_TO_PRISON_ADMIN = 'PROSECUTORS_OFFICE_INDICTMENT_SENT_TO_PRISON_ADMIN',
  PROSECUTORS_OFFICE_INDICTMENT_APPEALED = 'PROSECUTORS_OFFICE_INDICTMENT_APPEALED',
  PROSECUTOR_REQUEST_CASES_IN_PROGRESS = 'PROSECUTOR_REQUEST_CASES_IN_PROGRESS',
  PROSECUTOR_REQUEST_CASES_ACTIVE = 'PROSECUTOR_REQUEST_CASES_ACTIVE',
  PROSECUTOR_REQUEST_CASES_APPEALED = 'PROSECUTOR_REQUEST_CASES_APPEALED',
  PROSECUTOR_REQUEST_CASES_COMPLETED = 'PROSECUTOR_REQUEST_CASES_COMPLETED',
  PUBLIC_PROSECUTOR_INDICTMENT_IN_REVIEW = 'PUBLIC_PROSECUTOR_INDICTMENT_IN_REVIEW',
  PUBLIC_PROSECUTOR_INDICTMENT_REVIEWED = 'PUBLIC_PROSECUTOR_INDICTMENT_REVIEWED',
  PROSECUTOR_INDICTMENT_IN_DRAFT = 'PROSECUTOR_INDICTMENT_IN_DRAFT',
  PROSECUTOR_INDICTMENT_WAITING_FOR_CONFIRMATION = 'PROSECUTOR_INDICTMENT_WAITING_FOR_CONFIRMATION',
  PROSECUTOR_INDICTMENT_IN_PROGRESS = 'PROSECUTOR_INDICTMENT_IN_PROGRESS',
  PROSECUTOR_INDICTMENT_COMPLETED = 'PROSECUTOR_INDICTMENT_COMPLETED',
}

export enum CaseTableRoutes {
  NEW = 'ny-mal',
  INDICTMENT_NEW = 'bida-uthlutunar',
  INDICTMENT_DRAFT = 'sakamal-i-drogum',
  INDICTMENT_RECEIVED = 'mottekin-sakamal',
  IN_PROGRESS = 'mal-i-vinnslu',
  INDICTMENT_IN_PROGRESS = 'sakamal-i-vinnslu',
  IN_REVIEW = 'mal-i-yfirlestri',
  WAITING_FOR_CONFIRMATION = 'mal-bida-stadfestingar',
  REVIEWED = 'yfirlesin-mal',
  ACTIVE = 'virk-mal',
  INDICTMENT_FINALIZING = 'sakamal-i-fragangi',
  REQUEST_APPEALED = 'kaerur-til-landsrettar',
  INDICTMENT_APPEALED = 'afryjud-mal',
  APPEALED_EXPIRED = 'frestur-lidinn',
  SENT_TO_PRISON = 'mal-til-fullnustu',
  IN_PRISON = 'mal-i-fullnustu',
  REGISTERED_RULING = 'skradir-domar',
  COMPLETED = 'afgreidd-mal',
  INDICTMENT_COMPLETED = 'afgreidd-sakamal',
  DONE = 'lokid',
}

interface CaseTableDescriptor {
  type: CaseTableType
  route: string
  title: string
  description: string
}

export interface CaseTableGroup {
  title: string
  tables: CaseTableDescriptor[]
}

export interface CaseTable {
  title: string
  hasMyCasesFilter: boolean
  columnKeys: CaseTableColumnKey[]
  columns: CaseTableColumn[]
}

export enum CaseActionType {
  OPEN_CASE = 'OPEN_CASE',
  COMPLETE_CANCELLED_CASE = 'COMPLETE_CANCELLED_CASE',
}

export enum ContextMenuCaseActionType {
  OPEN_CASE_IN_NEW_TAB = 'OPEN_CASE_IN_NEW_TAB',
  WITHDRAW_APPEAL = 'WITHDRAW_APPEAL',
  DELETE_CASE = 'DELETE_CASE',
}

export const pickColumns = (
  keys: CaseTableColumnKey[],
): CaseTableColumnMap[CaseTableColumnKey][] => {
  return keys.map((key) => caseTableColumns[key])
}
