import {
  CaseTableColumn,
  CaseTableColumnKey,
  CaseTableColumnMap,
  caseTableColumns,
} from './caseTableColumnTypes'

export enum CaseTableType {
  COURT_OF_APPEALS_REQUEST_CASES_IN_PROGRESS = 'COURT_OF_APPEALS_REQUEST_CASES_IN_PROGRESS',
  COURT_OF_APPEALS_REQUEST_CASES_COMPLETED = 'COURT_OF_APPEALS_REQUEST_CASES_COMPLETED',
  DISTRICT_COURT_REQUEST_CASES_IN_PROGRESS = 'DISTRICT_COURT_REQUEST_CASES_IN_PROGRESS',
  DISTRICT_COURT_REQUEST_CASES_APPEALED = 'DISTRICT_COURT_REQUEST_CASES_APPEALED',
  DISTRICT_COURT_REQUEST_CASES_COMPLETED = 'DISTRICT_COURT_REQUEST_CASES_COMPLETED',
  DISTRICT_COURT_INDICTMENTS_NEW = 'DISTRICT_COURT_INDICTMENTS_NEW',
  DISTRICT_COURT_INDICTMENTS_RECEIVED = 'DISTRICT_COURT_INDICTMENTS_RECEIVED',
  DISTRICT_COURT_INDICTMENTS_IN_PROGRESS = 'DISTRICT_COURT_INDICTMENTS_IN_PROGRESS',
  DISTRICT_COURT_INDICTMENTS_FINALIZING = 'DISTRICT_COURT_INDICTMENTS_FINALIZING',
  DISTRICT_COURT_INDICTMENTS_COMPLETED = 'DISTRICT_COURT_INDICTMENTS_COMPLETED',
  PRISON_REQUEST_CASES_ACTIVE = 'PRISON_REQUEST_CASES_ACTIVE',
  PRISON_REQUEST_CASES_DONE = 'PRISON_REQUEST_CASES_DONE',
  PRISON_ADMIN_REQUEST_CASES_ACTIVE = 'PRISON_ADMIN_REQUEST_CASES_ACTIVE',
  PRISON_ADMIN_REQUEST_CASES_DONE = 'PRISON_ADMIN_REQUEST_CASES_DONE',
  PRISON_ADMIN_INDICTMENTS_SENT_TO_PRISON_ADMIN = 'PRISON_ADMIN_INDICTMENTS_SENT_TO_PRISON_ADMIN',
  PRISON_ADMIN_INDICTMENTS_REGISTERED_RULING = 'PRISON_ADMIN_INDICTMENTS_REGISTERED_RULING',
  PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_NEW = 'PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_NEW',
  PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_IN_REVIEW = 'PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_IN_REVIEW',
  PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_REVIEWED = 'PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_REVIEWED',
  PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_APPEAL_PERIOD_EXPIRED = 'PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_APPEAL_PERIOD_EXPIRED',
  PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_SENT_TO_PRISON_ADMIN = 'PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_SENT_TO_PRISON_ADMIN',
  PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_APPEALED = 'PUBLIC_PROSECUTION_OFFICE_INDICTMENTS_APPEALED',
  PROSECUTION_REQUEST_CASES_IN_PROGRESS = 'PROSECUTION_REQUEST_CASES_IN_PROGRESS',
  PROSECUTION_REQUEST_CASES_ACTIVE = 'PROSECUTION_REQUEST_CASES_ACTIVE',
  PROSECUTION_REQUEST_CASES_APPEALED = 'PROSECUTION_REQUEST_CASES_APPEALED',
  PROSECUTION_REQUEST_CASES_COMPLETED = 'PROSECUTION_REQUEST_CASES_COMPLETED',
  PUBLIC_PROSECUTION_INDICTMENTS_IN_REVIEW = 'PUBLIC_PROSECUTION_INDICTMENTS_IN_REVIEW',
  PUBLIC_PROSECUTION_INDICTMENTS_REVIEWED = 'PUBLIC_PROSECUTION_INDICTMENTS_REVIEWED',
  PROSECUTION_INDICTMENTS_IN_DRAFT = 'PROSECUTION_INDICTMENTS_IN_DRAFT',
  PROSECUTION_INDICTMENTS_WAITING_FOR_CONFIRMATION = 'PROSECUTION_INDICTMENTS_WAITING_FOR_CONFIRMATION',
  PROSECUTION_INDICTMENTS_IN_PROGRESS = 'PROSECUTION_INDICTMENTS_IN_PROGRESS',
  PROSECUTION_INDICTMENTS_COMPLETED = 'PROSECUTION_INDICTMENTS_COMPLETED',
}

interface CaseTableDescriptor {
  type: CaseTableType
  route: string
  title: string
  description: string
}

export interface CaseTableGroup {
  title: string
  tables: CaseTableDescriptor[]
}

export interface CaseTable {
  title: string
  hasMyCasesFilter: boolean
  columnKeys: CaseTableColumnKey[]
  columns: CaseTableColumn[]
}

export enum CaseActionType {
  OPEN_CASE = 'OPEN_CASE',
  COMPLETE_CANCELLED_CASE = 'COMPLETE_CANCELLED_CASE',
}

export enum ContextMenuCaseActionType {
  OPEN_CASE_IN_NEW_TAB = 'OPEN_CASE_IN_NEW_TAB',
  WITHDRAW_APPEAL = 'WITHDRAW_APPEAL',
  DELETE_CASE = 'DELETE_CASE',
}

export const pickColumns = (
  keys: CaseTableColumnKey[],
): CaseTableColumnMap[CaseTableColumnKey][] => {
  return keys.map((key) => caseTableColumns[key])
}
