name: islandis-application-system
services:
  db_application_system:
    image: public.ecr.aws/docker/library/postgres:15.3-alpine
    container_name: db_application_system
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5432:5432
