export { Defendant } from './models/defendant.model'
export { DefendantService } from './defendant.service'
export { CivilClaimant } from './models/civilClaimant.model'
export { DefendantExistsGuard } from './guards/defendantExists.guard'
export { CurrentDefendant } from './guards/defendant.decorator'
