export { NationalRegistryProvider } from '@island.is/application/data-providers'
export { UserProfileProvider } from '@island.is/application/data-providers'
export { PenaltyPointsProvider } from './PenaltyPointsProvider'
export { EntitlementTypesProvider } from './EntitlementTypesProvider'
export { EligibilityProvider } from './EligibilityProvider'
export { JuristictionProvider } from './JuristictionProvider'
