query GetQuestionnaires($locale: String!) {
  questionnairesList(locale: $locale) {
    questionnaires {
      id
      title
      description
      sentDate
      status
      lastSubmitted
      lastSubmissionId
      organization
      department
      senderGroupName
    }
  }
}

query GetQuestionnaire($locale: String!, $input: GetQuestionnaireInput!) {
  questionnairesDetail(locale: $locale, input: $input) {
    baseInformation {
      __typename
      id
      title
      description
      sentDate
      status
      lastSubmissionId
      lastSubmitted
      organization
      department
      senderGroupName
    }
    sender
    expirationDate
    canSubmit
    submissions {
      __typename
      id
      isDraft
      lastUpdated
      createdAt
    }
  }
}
