fragment VehicleMileageDetailFragment on VehicleMileageDetail {
  permno
  readDate
  originCode
  mileage
  internalId
}

query GetVehicleMileage($input: GetVehicleMileageInput!) {
  vehicleMileageDetails(input: $input) {
    data {
      ...VehicleMileageDetailFragment
    }
    editing
    canRegisterMileage
    requiresMileageRegistration
    canUserRegisterVehicleMileage
  }
}

mutation PostVehicleMileage($input: PostVehicleMileageInput!) {
  vehicleMileagePostV2(input: $input) {
    ... on VehicleMileageDetail {
      ...VehicleMileageDetailFragment
    }
    ... on VehiclesMileageUpdateError {
      code
      message
    }
  }
}

mutation UpdateVehicleMileage($input: PutVehicleMileageInput!) {
  vehicleMileagePutV2(input: $input) {
    ... on VehicleMileagePutModel {
      permno
      internalId
      mileage
    }
    ... on VehiclesMileageUpdateError {
      code
      message
    }
  }
}
