/**
 * Get a country by its country code
 * @param {string} code - The country code to get the country by (e.g. 'IS') - Uses ISO 3166-1 alpha-2 standard: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
 */
export const getCountryByCode = (code: string): Country | undefined => {
  if (!code) {
    return undefined
  }

  return countryCodes.find((country) => country.code === code) ?? undefined
}

export interface Country {
  name: string
  name_is?: string
  flag: string
  code: string
  format?: string
  dial_code: string
}

const countryCodes: Country[] = [
  {
    name: 'Afghanistan',
    name_is: 'Afganistan',
    flag: '🇦🇫',
    code: 'AF',
    dial_code: '+93',
  },
  {
    name: 'Åland Islands',
    name_is: 'Álandseyjar',
    flag: '🇦🇽',
    code: 'AX',
    dial_code: '+358',
  },
  {
    name: 'Albania',
    name_is: 'Albanía',
    flag: '🇦🇱',
    code: 'AL',
    dial_code: '+355',
  },
  {
    name: 'Algeria',
    name_is: 'Algería',
    flag: '🇩🇿',
    code: 'DZ',
    dial_code: '+213',
  },
  {
    name: 'American Samoa',
    name_is: 'Bandaríska Samóa',
    flag: '🇦🇸',
    code: 'AS',
    dial_code: '+1684',
  },
  {
    name: 'Andorra',
    name_is: 'Andorra',
    flag: '🇦🇩',
    code: 'AD',
    dial_code: '+376',
  },
  {
    name: 'Angola',
    name_is: 'Angóla',
    flag: '🇦🇴',
    code: 'AO',
    dial_code: '+244',
  },
  {
    name: 'Anguilla',
    name_is: 'Angvilla',
    flag: '🇦🇮',
    code: 'AI',
    dial_code: '+1264',
  },
  {
    name: 'Antarctica',
    name_is: 'Suðurskautslandið',
    flag: '🇦🇶',
    code: 'AQ',
    dial_code: '+672',
  },
  {
    name: 'Antigua and Barbuda',
    name_is: 'Antígva og Barbúda',
    flag: '🇦🇬',
    code: 'AG',
    dial_code: '+1268',
  },
  {
    name: 'Argentina',
    name_is: 'Argentína',
    flag: '🇦🇷',
    code: 'AR',
    dial_code: '+54',
  },
  {
    name: 'Armenia',
    name_is: 'Armenía',
    flag: '🇦🇲',
    code: 'AM',
    dial_code: '+374',
  },
  {
    name: 'Aruba',
    name_is: 'Arúba',
    flag: '🇦🇼',
    code: 'AW',
    dial_code: '+297',
  },
  {
    name: 'Australia',
    name_is: 'Ástralía',
    flag: '🇦🇺',
    code: 'AU',
    dial_code: '+61',
  },
  {
    name: 'Austria',
    name_is: 'Austurríki',
    flag: '🇦🇹',
    code: 'AT',
    dial_code: '+43',
  },
  {
    name: 'Azerbaijan',
    name_is: 'Aserbaísjan',
    flag: '🇦🇿',
    code: 'AZ',
    dial_code: '+994',
  },
  {
    name: 'Bahamas',
    name_is: 'Bahamaeyjar',
    flag: '🇧🇸',
    code: 'BS',
    dial_code: '+1242',
  },
  {
    name: 'Bahrain',
    name_is: 'Barein',
    flag: '🇧🇭',
    code: 'BH',
    dial_code: '+973',
  },
  {
    name: 'Bangladesh',
    name_is: 'Bangladess',
    flag: '🇧🇩',
    code: 'BD',
    dial_code: '+880',
  },
  {
    name: 'Barbados',
    name_is: 'Barbados',
    flag: '🇧🇧',
    code: 'BB',
    dial_code: '+1246',
  },
  {
    name: 'Belarus',
    name_is: 'Hvíta-Rússland',
    flag: '🇧🇾',
    code: 'BY',
    dial_code: '+375',
  },
  {
    name: 'Belgium',
    name_is: 'Belgía',
    flag: '🇧🇪',
    code: 'BE',
    dial_code: '+32',
  },
  {
    name: 'Belize',
    name_is: 'Belís',
    flag: '🇧🇿',
    code: 'BZ',
    dial_code: '+501',
  },
  {
    name: 'Benin',
    name_is: 'Benín',
    flag: '🇧🇯',
    code: 'BJ',
    dial_code: '+229',
  },
  {
    name: 'Bermuda',
    name_is: 'Bermúda',
    flag: '🇧🇲',
    code: 'BM',
    dial_code: '+1441',
  },
  {
    name: 'Bhutan',
    name_is: 'Bútan',
    flag: '🇧🇹',
    code: 'BT',
    dial_code: '+975',
  },
  {
    name: 'Bolivia, Plurinational State of bolivia',
    name_is: 'Bólivía',
    flag: '🇧🇴',
    code: 'BO',
    dial_code: '+591',
  },
  {
    name: 'Bosnia and Herzegovina',
    name_is: 'Bosnía og Hersegóvína',
    flag: '🇧🇦',
    code: 'BA',
    dial_code: '+387',
  },
  {
    name: 'Botswana',
    name_is: 'Botsvana',
    flag: '🇧🇼',
    code: 'BW',
    dial_code: '+267',
  },
  {
    name: 'Bouvet Island',
    name_is: 'Bouveteyja',
    flag: '🇧🇻',
    code: 'BV',
    dial_code: '+47',
  },
  {
    name: 'Brazil',
    name_is: 'Brasilía',
    flag: '🇧🇷',
    code: 'BR',
    dial_code: '+55',
  },
  {
    name: 'British Indian Ocean Territory',
    name_is: 'Bresku Indlandshafseyjar',
    flag: '🇮🇴',
    code: 'IO',
    dial_code: '+246',
  },
  {
    name: 'Brunei Darussalam',
    name_is: 'Brúnei',
    flag: '🇧🇳',
    code: 'BN',
    dial_code: '+673',
  },
  {
    name: 'Bulgaria',
    name_is: 'Búlgaría',
    flag: '🇧🇬',
    code: 'BG',
    dial_code: '+359',
  },
  {
    name: 'Burkina Faso',
    name_is: 'Búrkína Fasó',
    flag: '🇧🇫',
    code: 'BF',
    dial_code: '+226',
  },
  {
    name: 'Burundi',
    name_is: 'Búrúndí',
    flag: '🇧🇮',
    code: 'BI',
    dial_code: '+257',
  },
  {
    name: 'Cambodia',
    name_is: 'Kambódía',
    flag: '🇰🇭',
    code: 'KH',
    dial_code: '+855',
  },
  {
    name: 'Cameroon',
    name_is: 'Kamerún',
    flag: '🇨🇲',
    code: 'CM',
    dial_code: '+237',
  },
  {
    name: 'Canada',
    name_is: 'Kanada',
    format: '(###) ###-####',
    flag: '🇨🇦',
    code: 'CA',
    dial_code: '+1',
  },
  {
    name: 'Cape Verde',
    name_is: 'Grænhöfðaeyjar',
    flag: '🇨🇻',
    code: 'CV',
    dial_code: '+238',
  },
  {
    name: 'Cayman Islands',
    name_is: 'Cayman-eyjar',
    flag: '🇰🇾',
    code: 'KY',
    dial_code: '+345',
  },
  {
    name: 'Central African Republic',
    name_is: 'Mið-Afríkulýðveldið',
    flag: '🇨🇫',
    code: 'CF',
    dial_code: '+236',
  },
  { name: 'Chad', name_is: 'Tjad', flag: '🇹🇩', code: 'TD', dial_code: '+235' },
  { name: 'Chile', name_is: 'Síle', flag: '🇨🇱', code: 'CL', dial_code: '+56' },
  { name: 'China', name_is: 'Kína', flag: '🇨🇳', code: 'CN', dial_code: '+86' },
  {
    name: 'Christmas Island',
    name_is: 'Jólaeyja',
    flag: '🇨🇽',
    code: 'CX',
    dial_code: '+61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    name_is: 'Kókoseyjar',
    flag: '🇨🇨',
    code: 'CC',
    dial_code: '+61',
  },
  {
    name: 'Colombia',
    name_is: 'Kólumbía',
    flag: '🇨🇴',
    code: 'CO',
    dial_code: '+57',
  },
  {
    name: 'Comoros',
    name_is: 'Kómorur',
    flag: '🇰🇲',
    code: 'KM',
    dial_code: '+269',
  },
  {
    name: 'Congo',
    name_is: 'Kongó',
    flag: '🇨🇬',
    code: 'CG',
    dial_code: '+242',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    name_is: 'Lýðstjórnarlýðveldið Kongó',
    flag: '🇨🇩',
    code: 'CD',
    dial_code: '+243',
  },
  {
    name: 'Cook Islands',
    name_is: 'Cooks-eyjar',
    flag: '🇨🇰',
    code: 'CK',
    dial_code: '+682',
  },
  {
    name: 'Costa Rica',
    name_is: 'Kosta Ríka',
    flag: '🇨🇷',
    code: 'CR',
    dial_code: '+506',
  },
  {
    name: "Cote d'Ivoire",
    name_is: 'Fílabeinsströndin',
    flag: '🇨🇮',
    code: 'CI',
    dial_code: '+225',
  },
  {
    name: 'Croatia',
    name_is: 'Króatía',
    flag: '🇭🇷',
    code: 'HR',
    dial_code: '+385',
  },
  { name: 'Cuba', name_is: 'Kúba', flag: '🇨🇺', code: 'CU', dial_code: '+53' },
  {
    name: 'Cyprus',
    name_is: 'Kýpur',
    flag: '🇨🇾',
    code: 'CY',
    dial_code: '+357',
  },
  {
    name: 'Czech Republic',
    name_is: 'Tékkland',
    flag: '🇨🇿',
    code: 'CZ',
    dial_code: '+420',
  },
  {
    name: 'Denmark',
    name_is: 'Danmörk',
    format: '## ## ## ##',
    flag: '🇩🇰',
    code: 'DK',
    dial_code: '+45',
  },
  {
    name: 'Djibouti',
    name_is: 'Djibútí',
    flag: '🇩🇯',
    code: 'DJ',
    dial_code: '+253',
  },
  {
    name: 'Dominica',
    name_is: 'Dóminíka',
    flag: '🇩🇲',
    code: 'DM',
    dial_code: '+1767',
  },
  {
    name: 'Dominican Republic',
    name_is: 'Dóminíska lýðveldið',
    flag: '🇩🇴',
    code: 'DO',
    dial_code: '+1849',
  },
  {
    name: 'Ecuador',
    name_is: 'Ekvador',
    flag: '🇪🇨',
    code: 'EC',
    dial_code: '+593',
  },
  {
    name: 'Egypt',
    name_is: 'Egyptaland',
    flag: '🇪🇬',
    code: 'EG',
    dial_code: '+20',
  },
  {
    name: 'El Salvador',
    name_is: 'El Salvador',
    flag: '🇸🇻',
    code: 'SV',
    dial_code: '+503',
  },
  {
    name: 'Equatorial Guinea',
    name_is: 'Miðbaugs-Gínea',
    flag: '🇬🇶',
    code: 'GQ',
    dial_code: '+240',
  },
  {
    name: 'Eritrea',
    name_is: 'Eritrea',
    flag: '🇪🇷',
    code: 'ER',
    dial_code: '+291',
  },
  {
    name: 'Estonia',
    name_is: 'Eistland',
    flag: '🇪🇪',
    code: 'EE',
    dial_code: '+372',
  },
  {
    name: 'Ethiopia',
    name_is: 'Eþíópía',
    flag: '🇪🇹',
    code: 'ET',
    dial_code: '+251',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    name_is: 'Falklandseyjar',
    flag: '🇫🇰',
    code: 'FK',
    dial_code: '+500',
  },
  {
    name: 'Faroe Islands',
    name_is: 'Færeyjar',
    flag: '🇫🇴',
    code: 'FO',
    dial_code: '+298',
  },
  { name: 'Fiji', name_is: 'Fídjí', flag: '🇫🇯', code: 'FJ', dial_code: '+679' },
  {
    name: 'Finland',
    name_is: 'Finnland',
    flag: '🇫🇮',
    code: 'FI',
    dial_code: '+358',
  },
  {
    name: 'France',
    name_is: 'Frakkland',
    flag: '🇫🇷',
    code: 'FR',
    dial_code: '+33',
  },
  {
    name: 'French Guiana',
    name_is: 'Franska Gvæjana',
    flag: '🇬🇫',
    code: 'GF',
    dial_code: '+594',
  },
  {
    name: 'French Polynesia',
    name_is: 'Franska Pólýnesía',
    flag: '🇵🇫',
    code: 'PF',
    dial_code: '+689',
  },
  {
    name: 'French Southern Territories',
    name_is: 'Frönsku suðlægu landsvæðin',
    flag: '🇹🇫',
    code: 'TF',
    dial_code: '+262',
  },
  {
    name: 'Gabon',
    name_is: 'Gabon',
    flag: '🇬🇦',
    code: 'GA',
    dial_code: '+241',
  },
  {
    name: 'Gambia',
    name_is: 'Gambía',
    flag: '🇬🇲',
    code: 'GM',
    dial_code: '+220',
  },
  {
    name: 'Georgia',
    name_is: 'Georgía',
    flag: '🇬🇪',
    code: 'GE',
    dial_code: '+995',
  },
  {
    name: 'Germany',
    name_is: 'Þýskaland',
    flag: '🇩🇪',
    code: 'DE',
    dial_code: '+49',
  },
  { name: 'Ghana', name_is: 'Gana', flag: '🇬🇭', code: 'GH', dial_code: '+233' },
  {
    name: 'Gibraltar',
    name_is: 'Gíbraltar',
    flag: '🇬🇮',
    code: 'GI',
    dial_code: '+350',
  },
  {
    name: 'Greece',
    name_is: 'Grikkland',
    flag: '🇬🇷',
    code: 'GR',
    dial_code: '+30',
  },
  {
    name: 'Greenland',
    name_is: 'Grænland',
    flag: '🇬🇱',
    code: 'GL',
    dial_code: '+299',
  },
  {
    name: 'Grenada',
    name_is: 'Grenada',
    flag: '🇬🇩',
    code: 'GD',
    dial_code: '+1473',
  },
  {
    name: 'Guadeloupe',
    name_is: 'Gvadelúpeyjar',
    flag: '🇬🇵',
    code: 'GP',
    dial_code: '+590',
  },
  { name: 'Guam', name_is: 'Gvam', flag: '🇬🇺', code: 'GU', dial_code: '+1671' },
  {
    name: 'Guatemala',
    name_is: 'Gvatemala',
    flag: '🇬🇹',
    code: 'GT',
    dial_code: '+502',
  },
  {
    name: 'Guernsey',
    name_is: 'Guernsey',
    flag: '🇬🇬',
    code: 'GG',
    dial_code: '+44',
  },
  {
    name: 'Guinea',
    name_is: 'Gínea',
    flag: '🇬🇳',
    code: 'GN',
    dial_code: '+224',
  },
  {
    name: 'Guinea-Bissau',
    name_is: 'Gínea-Bissá',
    flag: '🇬🇼',
    code: 'GW',
    dial_code: '+245',
  },
  {
    name: 'Guyana',
    name_is: 'Gvæjana',
    flag: '🇬🇾',
    code: 'GY',
    dial_code: '+592',
  },
  {
    name: 'Haiti',
    name_is: 'Haítí',
    flag: '🇭🇹',
    code: 'HT',
    dial_code: '+509',
  },
  {
    name: 'Heard Island and Mcdonald Islands',
    name_is: 'Heard- og McDonaldseyjar',
    flag: '🇭🇲',
    code: 'HM',
    dial_code: '+672',
  },
  {
    name: 'Holy See (Vatican City State)',
    name_is: 'Vatíkanið',
    flag: '🇻🇦',
    code: 'VA',
    dial_code: '+379',
  },
  {
    name: 'Honduras',
    name_is: 'Hondúras',
    flag: '🇭🇳',
    code: 'HN',
    dial_code: '+504',
  },
  {
    name: 'Hong Kong',
    name_is: 'Hong Kong',
    flag: '🇭🇰',
    code: 'HK',
    dial_code: '+852',
  },
  {
    name: 'Hungary',
    name_is: 'Ungverjaland',
    flag: '🇭🇺',
    code: 'HU',
    dial_code: '+36',
  },
  {
    name: 'Iceland',
    name_is: 'Ísland',
    format: '###-####',
    flag: '🇮🇸',
    code: 'IS',
    dial_code: '+354',
  },
  {
    name: 'India',
    name_is: 'Indland',
    flag: '🇮🇳',
    code: 'IN',
    dial_code: '+91',
  },
  {
    name: 'Indonesia',
    name_is: 'Indónesía',
    flag: '🇮🇩',
    code: 'ID',
    dial_code: '+62',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    name_is: 'Íslamska lýðveldið Íran',
    flag: '🇮🇷',
    code: 'IR',
    dial_code: '+98',
  },
  { name: 'Iraq', name_is: 'Írak', flag: '🇮🇶', code: 'IQ', dial_code: '+964' },
  {
    name: 'Ireland',
    name_is: 'Írland',
    flag: '🇮🇪',
    code: 'IE',
    dial_code: '+353',
  },
  {
    name: 'Isle of Man',
    name_is: 'Mön',
    flag: '🇮🇲',
    code: 'IM',
    dial_code: '+44',
  },
  {
    name: 'Israel',
    name_is: 'Ísrael',
    flag: '🇮🇱',
    code: 'IL',
    dial_code: '+972',
  },
  {
    name: 'Italy',
    name_is: 'Ítalía',
    flag: '🇮🇹',
    code: 'IT',
    dial_code: '+39',
  },
  {
    name: 'Jamaica',
    name_is: 'Jamaíka',
    flag: '🇯🇲',
    code: 'JM',
    dial_code: '+1876',
  },
  { name: 'Japan', name_is: 'Japan', flag: '🇯🇵', code: 'JP', dial_code: '+81' },
  {
    name: 'Jersey',
    name_is: 'Jersey',
    flag: '🇯🇪',
    code: 'JE',
    dial_code: '+44',
  },
  {
    name: 'Jordan',
    name_is: 'Jórdanía',
    flag: '🇯🇴',
    code: 'JO',
    dial_code: '+962',
  },
  {
    name: 'Kazakhstan',
    name_is: 'Kasakstan',
    flag: '🇰🇿',
    code: 'KZ',
    dial_code: '+7',
  },
  {
    name: 'Kenya',
    name_is: 'Kenía',
    flag: '🇰🇪',
    code: 'KE',
    dial_code: '+254',
  },
  {
    name: 'Kiribati',
    name_is: 'Kíribatí',
    flag: '🇰🇮',
    code: 'KI',
    dial_code: '+686',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    name_is: 'Norður-Kórea',
    flag: '🇰🇵',
    code: 'KP',
    dial_code: '+850',
  },
  {
    name: 'Korea, Republic of South Korea',
    name_is: 'Suður-Kórea',
    flag: '🇰🇷',
    code: 'KR',
    dial_code: '+82',
  },
  {
    name: 'Kosovo',
    name_is: 'Kósovó',
    flag: '🇽🇰',
    code: 'XK',
    dial_code: '+383',
  },
  {
    name: 'Kuwait',
    name_is: 'Kúveit',
    flag: '🇰🇼',
    code: 'KW',
    dial_code: '+965',
  },
  {
    name: 'Kyrgyzstan',
    name_is: 'Kirgistan',
    flag: '🇰🇬',
    code: 'KG',
    dial_code: '+996',
  },
  { name: 'Laos', name_is: 'Laos', flag: '🇱🇦', code: 'LA', dial_code: '+856' },
  {
    name: 'Latvia',
    name_is: 'Lettland',
    flag: '🇱🇻',
    code: 'LV',
    dial_code: '+371',
  },
  {
    name: 'Lebanon',
    name_is: 'Líbanon',
    flag: '🇱🇧',
    code: 'LB',
    dial_code: '+961',
  },
  {
    name: 'Lesotho',
    name_is: 'Lesótó',
    flag: '🇱🇸',
    code: 'LS',
    dial_code: '+266',
  },
  {
    name: 'Liberia',
    name_is: 'Líbería',
    flag: '🇱🇷',
    code: 'LR',
    dial_code: '+231',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    name_is: 'Líbía',
    flag: '🇱🇾',
    code: 'LY',
    dial_code: '+218',
  },
  {
    name: 'Liechtenstein',
    name_is: 'Liechtenstein',
    flag: '🇱🇮',
    code: 'LI',
    dial_code: '+423',
  },
  {
    name: 'Lithuania',
    name_is: 'Litáen',
    flag: '🇱🇹',
    code: 'LT',
    dial_code: '+370',
  },
  {
    name: 'Luxembourg',
    name_is: 'Lúxemborg',
    flag: '🇱🇺',
    code: 'LU',
    dial_code: '+352',
  },
  {
    name: 'Macao',
    name_is: 'Makaó',
    flag: '🇲🇴',
    code: 'MO',
    dial_code: '+853',
  },
  {
    name: 'Macedonia',
    name_is: 'Makedónía',
    flag: '🇲🇰',
    code: 'MK',
    dial_code: '+389',
  },
  {
    name: 'Madagascar',
    name_is: 'Madagaskar',
    flag: '🇲🇬',
    code: 'MG',
    dial_code: '+261',
  },
  {
    name: 'Malawi',
    name_is: 'Malaví',
    flag: '🇲🇼',
    code: 'MW',
    dial_code: '+265',
  },
  {
    name: 'Malaysia',
    name_is: 'Malasía',
    flag: '🇲🇾',
    code: 'MY',
    dial_code: '+60',
  },
  {
    name: 'Maldives',
    name_is: 'Maldívur',
    flag: '🇲🇻',
    code: 'MV',
    dial_code: '+960',
  },
  { name: 'Mali', name_is: 'Malí', flag: '🇲🇱', code: 'ML', dial_code: '+223' },
  {
    name: 'Malta',
    name_is: 'Malta',
    flag: '🇲🇹',
    code: 'MT',
    dial_code: '+356',
  },
  {
    name: 'Marshall Islands',
    name_is: 'Marshalleyjar',
    flag: '🇲🇭',
    code: 'MH',
    dial_code: '+692',
  },
  {
    name: 'Martinique',
    name_is: 'Martinique',
    flag: '🇲🇶',
    code: 'MQ',
    dial_code: '+596',
  },
  {
    name: 'Mauritania',
    name_is: 'Máritanía',
    flag: '🇲🇷',
    code: 'MR',
    dial_code: '+222',
  },
  {
    name: 'Mauritius',
    name_is: 'Máritíus',
    flag: '🇲🇺',
    code: 'MU',
    dial_code: '+230',
  },
  {
    name: 'Mayotte',
    name_is: 'Mayotte',
    flag: '🇾🇹',
    code: 'YT',
    dial_code: '+262',
  },
  {
    name: 'Mexico',
    name_is: 'Mexíkó',
    flag: '🇲🇽',
    code: 'MX',
    dial_code: '+52',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    name_is: 'Míkrónesía',
    flag: '🇫🇲',
    code: 'FM',
    dial_code: '+691',
  },
  {
    name: 'Moldova',
    name_is: 'Moldóva',
    flag: '🇲🇩',
    code: 'MD',
    dial_code: '+373',
  },
  {
    name: 'Monaco',
    name_is: 'Mónakó',
    flag: '🇲🇨',
    code: 'MC',
    dial_code: '+377',
  },
  {
    name: 'Mongolia',
    name_is: 'Mongólía',
    flag: '🇲🇳',
    code: 'MN',
    dial_code: '+976',
  },
  {
    name: 'Montenegro',
    name_is: 'Svartfjallaland',
    flag: '🇲🇪',
    code: 'ME',
    dial_code: '+382',
  },
  {
    name: 'Montserrat',
    name_is: 'Montserrat',
    flag: '🇲🇸',
    code: 'MS',
    dial_code: '+1664',
  },
  {
    name: 'Morocco',
    name_is: 'Marokkó',
    flag: '🇲🇦',
    code: 'MA',
    dial_code: '+212',
  },
  {
    name: 'Mozambique',
    name_is: 'Mósambík',
    flag: '🇲🇿',
    code: 'MZ',
    dial_code: '+258',
  },
  {
    name: 'Myanmar',
    name_is: 'Mjanmar',
    flag: '🇲🇲',
    code: 'MM',
    dial_code: '+95',
  },
  {
    name: 'Namibia',
    name_is: 'Namibía',
    flag: '🇳🇦',
    code: 'NA',
    dial_code: '+264',
  },
  {
    name: 'Nauru',
    name_is: 'Naúrú',
    flag: '🇳🇷',
    code: 'NR',
    dial_code: '+674',
  },
  {
    name: 'Nepal',
    name_is: 'Nepal',
    flag: '🇳🇵',
    code: 'NP',
    dial_code: '+977',
  },
  {
    name: 'Netherlands',
    name_is: 'Holland',
    flag: '🇳🇱',
    code: 'NL',
    dial_code: '+31',
  },
  {
    name: 'Netherlands Antilles',
    name_is: 'Hollensku Antillaeyjar',
    flag: '',
    code: 'AN',
    dial_code: '+599',
  },
  {
    name: 'New Caledonia',
    name_is: 'Nýja-Kaledónía',
    flag: '🇳🇨',
    code: 'NC',
    dial_code: '+687',
  },
  {
    name: 'New Zealand',
    name_is: 'Nýja-Sjáland',
    flag: '🇳🇿',
    code: 'NZ',
    dial_code: '+64',
  },
  {
    name: 'Nicaragua',
    name_is: 'Níkaragva',
    flag: '🇳🇮',
    code: 'NI',
    dial_code: '+505',
  },
  {
    name: 'Niger',
    name_is: 'Níger',
    flag: '🇳🇪',
    code: 'NE',
    dial_code: '+227',
  },
  {
    name: 'Nigeria',
    name_is: 'Nígería',
    flag: '🇳🇬',
    code: 'NG',
    dial_code: '+234',
  },
  { name: 'Niue', name_is: 'Niue', flag: '🇳🇺', code: 'NU', dial_code: '+683' },
  {
    name: 'Norfolk Island',
    name_is: 'Norfolkeyja',
    flag: '🇳🇫',
    code: 'NF',
    dial_code: '+672',
  },
  {
    name: 'Northern Mariana Islands',
    name_is: 'Norður-Maríanaeyjar',
    flag: '🇲🇵',
    code: 'MP',
    dial_code: '+1670',
  },
  {
    name: 'Norway',
    name_is: 'Noregur',
    flag: '🇳🇴',
    code: 'NO',
    dial_code: '+47',
  },
  { name: 'Oman', name_is: 'Óman', flag: '🇴🇲', code: 'OM', dial_code: '+968' },
  {
    name: 'Pakistan',
    name_is: 'Pakistan',
    flag: '🇵🇰',
    code: 'PK',
    dial_code: '+92',
  },
  {
    name: 'Palau',
    name_is: 'Palaú',
    flag: '🇵🇼',
    code: 'PW',
    dial_code: '+680',
  },
  {
    name: 'Palestinian Territory, Occupied',
    name_is: 'Heimastjórnarsvæði Palestínumanna',
    flag: '🇵🇸',
    code: 'PS',
    dial_code: '+970',
  },
  {
    name: 'Panama',
    name_is: 'Panama',
    flag: '🇵🇦',
    code: 'PA',
    dial_code: '+507',
  },
  {
    name: 'Papua New Guinea',
    name_is: 'Papúa Nýja-Gínea',
    flag: '🇵🇬',
    code: 'PG',
    dial_code: '+675',
  },
  {
    name: 'Paraguay',
    name_is: 'Paragvæ',
    flag: '🇵🇾',
    code: 'PY',
    dial_code: '+595',
  },
  { name: 'Peru', name_is: 'Perú', flag: '🇵🇪', code: 'PE', dial_code: '+51' },
  {
    name: 'Philippines',
    name_is: 'Filippseyjar',
    flag: '🇵🇭',
    code: 'PH',
    dial_code: '+63',
  },
  {
    name: 'Pitcairn',
    name_is: 'Pitcairn-eyja',
    flag: '🇵🇳',
    code: 'PN',
    dial_code: '+64',
  },
  {
    name: 'Poland',
    name_is: 'Pólland',
    format: '## ### ## ##',
    flag: '🇵🇱',
    code: 'PL',
    dial_code: '+48',
  },
  {
    name: 'Portugal',
    name_is: 'Portúgal',
    flag: '🇵🇹',
    code: 'PT',
    dial_code: '+351',
  },
  {
    name: 'Puerto Rico',
    name_is: 'Púertó Ríkó',
    flag: '🇵🇷',
    code: 'PR',
    dial_code: '+1939',
  },
  {
    name: 'Qatar',
    name_is: 'Katar',
    flag: '🇶🇦',
    code: 'QA',
    dial_code: '+974',
  },
  {
    name: 'Romania',
    name_is: 'Rúmenía',
    flag: '🇷🇴',
    code: 'RO',
    dial_code: '+40',
  },
  {
    name: 'Russia',
    name_is: 'Rússland',
    flag: '🇷🇺',
    code: 'RU',
    dial_code: '+7',
  },
  {
    name: 'Rwanda',
    name_is: 'Rúanda',
    flag: '🇷🇼',
    code: 'RW',
    dial_code: '+250',
  },
  {
    name: 'Reunion',
    name_is: 'Réunion',
    flag: '🇷🇪',
    code: 'RE',
    dial_code: '+262',
  },
  {
    name: 'Saint Barthelemy',
    name_is: 'Sankti Bartólómeusareyjar',
    flag: '🇧🇱',
    code: 'BL',
    dial_code: '+590',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    name_is: 'Sankti Helena, Ascension og Tristan Da Cunha',
    flag: '🇸🇭',
    code: 'SH',
    dial_code: '+290',
  },
  {
    name: 'Saint Kitts and Nevis',
    name_is: 'Sankti Kristófer og Nevis',
    flag: '🇰🇳',
    code: 'KN',
    dial_code: '+1869',
  },
  {
    name: 'Saint Lucia',
    name_is: 'Sankti Lúsía',
    flag: '🇱🇨',
    code: 'LC',
    dial_code: '+1758',
  },
  {
    name: 'Saint Martin',
    name_is: 'Sankti Martin',
    flag: '🇲🇫',
    code: 'MF',
    dial_code: '+590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    name_is: 'Sankti Pierre og Miquelon',
    flag: '🇵🇲',
    code: 'PM',
    dial_code: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    name_is: 'Sankti Vinsent og Grenadínur',
    flag: '🇻🇨',
    code: 'VC',
    dial_code: '+1784',
  },
  {
    name: 'Samoa',
    name_is: 'Samóa',
    flag: '🇼🇸',
    code: 'WS',
    dial_code: '+685',
  },
  {
    name: 'San Marino',
    name_is: 'San Marínó',
    flag: '🇸🇲',
    code: 'SM',
    dial_code: '+378',
  },
  {
    name: 'Sao Tome and Principe',
    name_is: 'Saó Tóme og Prinsípe',
    flag: '🇸🇹',
    code: 'ST',
    dial_code: '+239',
  },
  {
    name: 'Saudi Arabia',
    name_is: 'Sádi-Arabía',
    flag: '🇸🇦',
    code: 'SA',
    dial_code: '+966',
  },
  {
    name: 'Senegal',
    name_is: 'Senegal',
    flag: '🇸🇳',
    code: 'SN',
    dial_code: '+221',
  },
  {
    name: 'Serbia',
    name_is: 'Serbía',
    flag: '🇷🇸',
    code: 'RS',
    dial_code: '+381',
  },
  {
    name: 'Seychelles',
    name_is: 'Seychelles-eyjar',
    flag: '🇸🇨',
    code: 'SC',
    dial_code: '+248',
  },
  {
    name: 'Sierra Leone',
    name_is: 'Síerra Leóne',
    flag: '🇸🇱',
    code: 'SL',
    dial_code: '+232',
  },
  {
    name: 'Singapore',
    name_is: 'Singapúr',
    flag: '🇸🇬',
    code: 'SG',
    dial_code: '+65',
  },
  {
    name: 'Slovakia',
    name_is: 'Slóvakía',
    flag: '🇸🇰',
    code: 'SK',
    dial_code: '+421',
  },
  {
    name: 'Slovenia',
    name_is: 'Slóvenía',
    flag: '🇸🇮',
    code: 'SI',
    dial_code: '+386',
  },
  {
    name: 'Solomon Islands',
    name_is: 'Salómonseyjar',
    flag: '🇸🇧',
    code: 'SB',
    dial_code: '+677',
  },
  {
    name: 'Somalia',
    name_is: 'Sómalía',
    flag: '🇸🇴',
    code: 'SO',
    dial_code: '+252',
  },
  {
    name: 'South Africa',
    name_is: 'Suður-Afríka',
    flag: '🇿🇦',
    code: 'ZA',
    dial_code: '+27',
  },
  {
    name: 'South Sudan',
    name_is: 'Suður-Súdan',
    flag: '🇸🇸',
    code: 'SS',
    dial_code: '+211',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    name_is: 'Suður-Georgía og Suður-Sandvíkureyjar',
    flag: '🇬🇸',
    code: 'GS',
    dial_code: '+500',
  },
  { name: 'Spain', name_is: 'Spánn', flag: '🇪🇸', code: 'ES', dial_code: '+34' },
  {
    name: 'Sri Lanka',
    name_is: 'Srí Lanka',
    flag: '🇱🇰',
    code: 'LK',
    dial_code: '+94',
  },
  {
    name: 'Sudan',
    name_is: 'Súdan',
    flag: '🇸🇩',
    code: 'SD',
    dial_code: '+249',
  },
  {
    name: 'Suriname',
    name_is: 'Súrínam',
    flag: '🇸🇷',
    code: 'SR',
    dial_code: '+597',
  },
  {
    name: 'Svalbard and Jan Mayen',
    name_is: 'Svalbarði og Jan Mayen',
    flag: '🇸🇯',
    code: 'SJ',
    dial_code: '+47',
  },
  {
    name: 'Eswatini',
    name_is: 'Esvatíní',
    flag: '🇸🇿',
    code: 'SZ',
    dial_code: '+268',
  },
  {
    name: 'Sweden',
    name_is: 'Svíþjóð',
    flag: '🇸🇪',
    code: 'SE',
    dial_code: '+46',
  },
  {
    name: 'Switzerland',
    name_is: 'Sviss',
    flag: '🇨🇭',
    code: 'CH',
    dial_code: '+41',
  },
  {
    name: 'Syrian Arab Republic',
    name_is: 'Sýrland',
    flag: '🇸🇾',
    code: 'SY',
    dial_code: '+963',
  },
  {
    name: 'Taiwan',
    name_is: 'Taívan',
    flag: '🇹🇼',
    code: 'TW',
    dial_code: '+886',
  },
  {
    name: 'Tajikistan',
    name_is: 'Tadsíkistan',
    flag: '🇹🇯',
    code: 'TJ',
    dial_code: '+992',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    name_is: 'Tansanía',
    flag: '🇹🇿',
    code: 'TZ',
    dial_code: '+255',
  },
  {
    name: 'Thailand',
    name_is: 'Taíland',
    flag: '🇹🇭',
    code: 'TH',
    dial_code: '+66',
  },
  {
    name: 'Timor-Leste',
    name_is: 'Austur-Tímor',
    flag: '🇹🇱',
    code: 'TL',
    dial_code: '+670',
  },
  { name: 'Togo', name_is: 'Tógó', flag: '🇹🇬', code: 'TG', dial_code: '+228' },
  {
    name: 'Tokelau',
    name_is: 'Tókelá',
    flag: '🇹🇰',
    code: 'TK',
    dial_code: '+690',
  },
  {
    name: 'Tonga',
    name_is: 'Tonga',
    flag: '🇹🇴',
    code: 'TO',
    dial_code: '+676',
  },
  {
    name: 'Trinidad and Tobago',
    name_is: 'Trínidad og Tóbagó',
    flag: '🇹🇹',
    code: 'TT',
    dial_code: '+1868',
  },
  {
    name: 'Tunisia',
    name_is: 'Túnis',
    flag: '🇹🇳',
    code: 'TN',
    dial_code: '+216',
  },
  {
    name: 'Turkey',
    name_is: 'Tyrkland',
    flag: '🇹🇷',
    code: 'TR',
    dial_code: '+90',
  },
  {
    name: 'Turkmenistan',
    name_is: 'Túrkmenistan',
    flag: '🇹🇲',
    code: 'TM',
    dial_code: '+993',
  },
  {
    name: 'Turks and Caicos Islands',
    name_is: 'Turks- og Caicoseyjar',
    flag: '🇹🇨',
    code: 'TC',
    dial_code: '+1649',
  },
  {
    name: 'Tuvalu',
    name_is: 'Túvalú',
    flag: '🇹🇻',
    code: 'TV',
    dial_code: '+688',
  },
  {
    name: 'Uganda',
    name_is: 'Úganda',
    flag: '🇺🇬',
    code: 'UG',
    dial_code: '+256',
  },
  {
    name: 'Ukraine',
    name_is: 'Úkraína',
    format: '## ###-##-##',
    flag: '🇺🇦',
    code: 'UA',
    dial_code: '+380',
  },
  {
    name: 'United Arab Emirates',
    name_is: 'Sameinuðu arabísku furstadæmin',
    flag: '🇦🇪',
    code: 'AE',
    dial_code: '+971',
  },
  {
    name: 'United Kingdom',
    name_is: 'Bretland',
    format: '#### ######',
    flag: '🇬🇧',
    code: 'GB',
    dial_code: '+44',
  },
  {
    name: 'United States',
    name_is: 'Bandaríkin',
    format: '(###) ###-####',
    flag: '🇺🇸',
    code: 'US',
    dial_code: '+1',
  },
  {
    name: 'Uruguay',
    name_is: 'Úrúgvæ',
    flag: '🇺🇾',
    code: 'UY',
    dial_code: '+598',
  },
  {
    name: 'Uzbekistan',
    name_is: 'Úsbekistan',
    flag: '🇺🇿',
    code: 'UZ',
    dial_code: '+998',
  },
  {
    name: 'Vanuatu',
    name_is: 'Vanúatú',
    flag: '🇻🇺',
    code: 'VU',
    dial_code: '+678',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    name_is: 'Venesúela',
    flag: '🇻🇪',
    code: 'VE',
    dial_code: '+58',
  },
  {
    name: 'Vietnam',
    name_is: 'Víetnam',
    flag: '🇻🇳',
    code: 'VN',
    dial_code: '+84',
  },
  {
    name: 'Virgin Islands, British',
    name_is: 'Bresku Jómfrúaeyjar',
    flag: '🇻🇬',
    code: 'VG',
    dial_code: '+1284',
  },
  {
    name: 'Virgin Islands, U.S.',
    name_is: 'Bandarísku Jómfrúaeyjar',
    flag: '🇻🇮',
    code: 'VI',
    dial_code: '+1340',
  },
  {
    name: 'Wallis and Futuna',
    name_is: 'Wallis- og Fútúnaeyjar',
    flag: '🇼🇫',
    code: 'WF',
    dial_code: '+681',
  },
  {
    name: 'Yemen',
    name_is: 'Jemen',
    flag: '🇾🇪',
    code: 'YE',
    dial_code: '+967',
  },
  {
    name: 'Zambia',
    name_is: 'Sambía',
    flag: '🇿🇲',
    code: 'ZM',
    dial_code: '+260',
  },
  {
    name: 'Zimbabwe',
    name_is: 'Simbabve',
    flag: '🇿🇼',
    code: 'ZW',
    dial_code: '+263',
  },
]
