export enum ErrorCodes {
  ZENDESK_NATIONAL_IDS_MISMATCH = 'ZENDESK_NATIONAL_IDS_MISMATCH',
  ZENDESK_CUSTOM_FIELDS_MISSING = 'ZENDESK_CUSTOM_FIELDS_MISSING',
  ZENDESK_TAG_MISSING = 'ZENDESK_TAG_MISSING',
  ZENDESK_STATUS = 'ZENDESK_STATUS',
  INPUT_VALIDATION_SAME_NATIONAL_ID = 'INPUT_VALIDATION_SAME_NATIONAL_ID',
  INPUT_VALIDATION_INVALID_PERSON = 'INPUT_VALIDATION_INVALID_PERSON',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
  COULD_NOT_CREATE_DELEGATION = 'COULD_NOT_CREATE_DELEGATION',
  REFERENCE_ID_ALREADY_EXISTS = 'REFERENCE_ID_ALREADY_EXISTS',
}
