import { QuestionDisplayType } from '../models/question.model'
import { QuestionnairesStatusEnum } from '../models/questionnaires.model'

export const data = {
  questionnaires: [
    {
      id: '8f7e2a1d-4c9b-4e3f-9a2d-6b8c4f5e1a3d',
      title: 'DT - Mat á vanlíðan',
      description: '',
      sentDate: '2025-09-09T12:37:21.272Z',
      status: QuestionnairesStatusEnum.notAnswered,
      organization: 'EL',
      questions: [
        {
          id: '10',
          label: 'Vanlíðan',
          sublabel:
            'Vinsamlegast merktu við þá tölu (0-10) sem lýsir því best hversu mikilli vanlíðan þú hefur fundið fyrir síðastliðna viku, að meðtöldum deginum í dag.',
          display: QuestionDisplayType.required,
          answerOptions: {
            id: '10_answer',
            label: 'Vanlíðan',
            type: {
              __typename: 'HealthQuestionnaireAnswerThermometer' as const,
              id: '10_type',
              label: 'Vanlíðan',
              sublabel:
                'Vinsamlegast merktu við þá tölu (0-10) sem lýsir því best hversu mikilli vanlíðan þú hefur fundið fyrir síðastliðna viku, að meðtöldum deginum í dag.',
              display: QuestionDisplayType.required,
              maxLabel: 'Gríðarleg vanlíðan',
              minLabel: 'Engin vanlíðan',
              minValue: 0,
              maxValue: 10,
            },
          },
        },
        {
          id: '20',
          label:
            'Vinsamlegast merktu við hvort eitthvað af eftirtöldu hefur valdið þér erfiðleikum síðastliðna viku að meðtöldum deginum í dag. Gættu þess að merkja annað hvort við JÁ eða NEI í hverju atriði.',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '20_answer',
            label:
              'Vinsamlegast merktu við hvort eitthvað af eftirtöldu hefur valdið þér erfiðleikum síðastliðna viku að meðtöldum deginum í dag. Gættu þess að merkja annað hvort við JÁ eða NEI í hverju atriði.',
            type: {
              __typename: 'HealthQuestionnaireAnswerLabel' as const,
              id: '20_type',
              label:
                'Vinsamlegast merktu við hvort eitthvað af eftirtöldu hefur valdið þér erfiðleikum síðastliðna viku að meðtöldum deginum í dag. Gættu þess að merkja annað hvort við JÁ eða NEI í hverju atriði.',
              display: QuestionDisplayType.optional,
            },
          },
        },
        {
          id: '23',
          label: 'Barnagæsla',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '23_answer',
            label: 'Barnagæsla',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '23_type',
              label: 'Barnagæsla',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '24',
          label: 'Húsnæði',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '24_answer',
            label: 'Húsnæði',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '24_type',
              label: 'Húsnæði',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '25',
          label: 'Tryggingar',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '25_answer',
            label: 'Tryggingar',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '25_type',
              label: 'Tryggingar',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '26',
          label: 'Fjármál',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '26_answer',
            label: 'Fjármál',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '26_type',
              label: 'Fjármál',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '27',
          label: 'Ferðir',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '27_answer',
            label: 'Ferðir',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '27_type',
              label: 'Ferðir',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '28',
          label: 'Vinna/Skóli',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '28_answer',
            label: 'Vinna/Skóli',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '28_type',
              label: 'Vinna/Skóli',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '29',
          label: 'Ákvörðum um meðferð',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '29_answer',
            label: 'Ákvörðum um meðferð',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '29_type',
              label: 'Ákvörðum um meðferð',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '33',
          label: 'Vegna barna',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '33_answer',
            label: 'Vegna barna',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '33_type',
              label: 'Vegna barna',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '34',
          label: 'Vegna maka',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '34_answer',
            label: 'Vegna maka',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '34_type',
              label: 'Vegna maka',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '35',
          label: 'Heilsufar nákominna',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '35_answer',
            label: 'Heilsufar nákominna',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '35_type',
              label: 'Heilsufar nákominna',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '36',
          label: 'Möguleikar á barneignum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '36_answer',
            label: 'Möguleikar á barneignum',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '36_type',
              label: 'Möguleikar á barneignum',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '43',
          label: 'Þunglyndi',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '43_answer',
            label: 'Þunglyndi',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '43_type',
              label: 'Þunglyndi',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '44',
          label: 'Ótti',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '44_answer',
            label: 'Ótti',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '44_type',
              label: 'Ótti',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '45',
          label: 'Kvíði/taugaspenna',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '45_answer',
            label: 'Kvíði/taugaspenna',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '45_type',
              label: 'Kvíði/taugaspenna',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '46',
          label: 'Depurð',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '46_answer',
            label: 'Depurð',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '46_type',
              label: 'Depurð',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '47',
          label: 'Áhyggjur',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '47_answer',
            label: 'Áhyggjur',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '47_type',
              label: 'Áhyggjur',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '48',
          label: 'Áhugaleysi á daglegum athöfnum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '48_answer',
            label: 'Áhugaleysi á daglegum athöfnum',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '48_type',
              label: 'Áhugaleysi á daglegum athöfnum',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '49',
          label: 'Áhyggjur af andlegum/trúarlegum toga',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '49_answer',
            label: 'Áhyggjur af andlegum/trúarlegum toga',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '49_type',
              label: 'Áhyggjur af andlegum/trúarlegum toga',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '53',
          label: 'Útlit',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '53_answer',
            label: 'Útlit',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '53_type',
              label: 'Útlit',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '54',
          label: 'Að baðast/klæðast',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '54_answer',
            label: 'Að baðast/klæðast',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '54_type',
              label: 'Að baðast/klæðast',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '55',
          label: 'Öndun',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '55_answer',
            label: 'Öndun',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '55_type',
              label: 'Öndun',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '56',
          label: 'Breytingar á þvaglátum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '56_answer',
            label: 'Breytingar á þvaglátum',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '56_type',
              label: 'Breytingar á þvaglátum',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '57',
          label: 'Hægðatregða',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '57_answer',
            label: 'Hægðatregða',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '57_type',
              label: 'Hægðatregða',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '58',
          label: 'Niðurgangur',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '58_answer',
            label: 'Niðurgangur',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '58_type',
              label: 'Niðurgangur',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '59',
          label: 'Að borða',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '59_answer',
            label: 'Að borða',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '59_type',
              label: 'Að borða',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '60',
          label: 'Þreyta',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '60_answer',
            label: 'Þreyta',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '60_type',
              label: 'Þreyta',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '61',
          label: 'Bjúgur',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '61_answer',
            label: 'Bjúgur',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '61_type',
              label: 'Bjúgur',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '62',
          label: 'Hitakóf',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '62_answer',
            label: 'Hitakóf',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '62_type',
              label: 'Hitakóf',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '63',
          label: 'Að komast á milli staða',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '63_answer',
            label: 'Að komast á milli staða',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '63_type',
              label: 'Að komast á milli staða',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '64',
          label: 'Meltingartruflanir',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '64_answer',
            label: 'Meltingartruflanir',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '64_type',
              label: 'Meltingartruflanir',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '65',
          label: 'Minni/einbeiting',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '65_answer',
            label: 'Minni/einbeiting',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '65_type',
              label: 'Minni/einbeiting',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '66',
          label: 'Sár í munni',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '66_answer',
            label: 'Sár í munni',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '66_type',
              label: 'Sár í munni',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '67',
          label: 'Ógleði',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '67_answer',
            label: 'Ógleði',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '67_type',
              label: 'Ógleði',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '68',
          label: 'Þurrkur eða stífla í nefi',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '68_answer',
            label: 'Þurrkur eða stífla í nefi',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '68_type',
              label: 'Þurrkur eða stífla í nefi',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '69',
          label: 'Verkir',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '69_answer',
            label: 'Verkir',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '69_type',
              label: 'Verkir',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '70',
          label: 'Kynlíf/samlíf',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '70_answer',
            label: 'Kynlíf/samlíf',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '70_type',
              label: 'Kynlíf/samlíf',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '71',
          label: 'Húðþurrkur/kláði',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '71_answer',
            label: 'Húðþurrkur/kláði',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '71_type',
              label: 'Húðþurrkur/kláði',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '72',
          label: 'Svefn',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '72_answer',
            label: 'Svefn',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '72_type',
              label: 'Svefn',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '73',
          label: 'Áfengi, fíkniefni eða lyf',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '73_answer',
            label: 'Áfengi, fíkniefni eða lyf',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '73_type',
              label: 'Áfengi, fíkniefni eða lyf',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '74',
          label: 'Stingir í höndum/fótum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '74_answer',
            label: 'Stingir í höndum/fótum',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '74_type',
              label: 'Stingir í höndum/fótum',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei'],
            },
          },
        },
        {
          id: '80',
          label: 'Önnur vandamál',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '80_answer',
            label: 'Önnur vandamál',
            type: {
              __typename: 'HealthQuestionnaireAnswerText' as const,
              id: '80_type',
              label: 'Önnur vandamál',
              display: QuestionDisplayType.optional,
              multiline: true,
            },
          },
        },
        {
          id: '90',
          label: 'Myndir þú vilja tala við einhvern um vandamál þín?',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '90_answer',
            label: 'Myndir þú vilja tala við einhvern um vandamál þín?',
            type: {
              __typename: 'HealthQuestionnaireAnswerRadio' as const,
              id: '90_type',
              label: 'Myndir þú vilja tala við einhvern um vandamál þín?',
              display: QuestionDisplayType.optional,
              options: ['Já', 'Nei', 'Kannski'],
            },
          },
        },
        {
          id: '100',
          label: 'Við hvern?',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '100_answer',
            label: 'Við hvern?',
            type: {
              __typename: 'HealthQuestionnaireAnswerCheckbox' as const,
              id: '100_type',
              label: 'Við hvern?',
              display: QuestionDisplayType.optional,
              options: [
                'Hjúkrunarfræðing',
                'Næringarfræðing',
                'Lækni',
                'Sálfræðing',
                'Félagsráðgjafa',
                'Sjúkraþjálfara',
                'Prest eða djákna',
                'Sjúklingafélag',
                'Iðjuþjálfa',
                'Annan',
              ],
            },
          },
          dependsOn: ['90'],
          visibilityCondition:
            '{"questionId":"90","operator":"equals","value":"Já","visible":true}',
        },
        {
          id: '120',
          label: 'Hvern?',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '120_answer',
            label: 'Hvern?',
            type: {
              __typename: 'HealthQuestionnaireAnswerText' as const,
              id: '120_type',
              label: 'Hvern?',
              display: QuestionDisplayType.optional,
              multiline: false,
            },
          },
          dependsOn: ['100'],
          visibilityCondition:
            '{"questionId":"100","operator":"equals","value":"Annan","visible":true}',
        },
        {
          id: '0',
          label: 'Copyright © NCCN National Comprehensive Cancer Network',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '0_answer',
            label: 'Copyright © NCCN National Comprehensive Cancer Network',
            type: {
              __typename: 'HealthQuestionnaireAnswerLabel' as const,
              id: '0_type',
              label: 'Copyright © NCCN National Comprehensive Cancer Network',
              display: QuestionDisplayType.optional,
            },
          },
        },
      ],
    },
  ],
}
