import { QuestionDisplayType, AnswerOptionType } from '../models/question.model'
import { QuestionnairesStatusEnum } from '../models/questionnaires.model'

export const data = {
  questionnaires: [
    {
      id: '8f7e2a1d-4c9b-4e3f-9a2d-6b8c4f5e1a3d',
      title: 'DT - Mat á vanlíðan',
      description: '',
      sentDate: '2025-09-23T11:38:24.939Z',
      status: QuestionnairesStatusEnum.notAnswered,
      organization: 'EL',
      questions: [
        {
          id: '10',
          label: 'Vanlíðan',
          sublabel:
            'Vinsamlegast merktu við þá tölu (0-10) sem lýsir því best hversu mikilli vanlíðan þú hefur fundið fyrir síðastliðna viku, að meðtöldum deginum í dag.',
          display: QuestionDisplayType.required,
          answerOptions: {
            id: '10_type',
            type: AnswerOptionType.thermometer,
            sublabel:
              'Vinsamlegast merktu við þá tölu (0-10) sem lýsir því best hversu mikilli vanlíðan þú hefur fundið fyrir síðastliðna viku, að meðtöldum deginum í dag.',
            display: QuestionDisplayType.required,
            maxLabel: 'Gríðarleg vanlíðan',
            minLabel: 'Engin vanlíðan',
            minValue: 0,
            maxValue: 10,
          },
        },
        {
          id: '20',
          label:
            'Vinsamlegast merktu við hvort eitthvað af eftirtöldu hefur valdið þér erfiðleikum síðastliðna viku að meðtöldum deginum í dag. Gættu þess að merkja annað hvort við JÁ eða NEI í hverju atriði.',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '20_type',
            type: AnswerOptionType.label,
            display: QuestionDisplayType.optional,
          },
        },
        {
          id: '23',
          label: 'Barnagæsla',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '23_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '24',
          label: 'Húsnæði',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '24_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '25',
          label: 'Tryggingar',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '25_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '26',
          label: 'Fjármál',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '26_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '27',
          label: 'Ferðir',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '27_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '28',
          label: 'Vinna/Skóli',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '28_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '29',
          label: 'Ákvörðum um meðferð',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '29_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '33',
          label: 'Vegna barna',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '33_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '34',
          label: 'Vegna maka',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '34_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '35',
          label: 'Heilsufar nákominna',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '35_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '36',
          label: 'Möguleikar á barneignum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '36_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '43',
          label: 'Þunglyndi',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '43_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '44',
          label: 'Ótti',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '44_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '45',
          label: 'Kvíði/taugaspenna',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '45_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '46',
          label: 'Depurð',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '46_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '47',
          label: 'Áhyggjur',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '47_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '48',
          label: 'Áhugaleysi á daglegum athöfnum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '48_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '49',
          label: 'Áhyggjur af andlegum/trúarlegum toga',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '49_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '53',
          label: 'Útlit',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '53_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '54',
          label: 'Að baðast/klæðast',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '54_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '55',
          label: 'Öndun',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '55_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '56',
          label: 'Breytingar á þvaglátum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '56_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '57',
          label: 'Hægðatregða',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '57_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '58',
          label: 'Niðurgangur',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '58_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '59',
          label: 'Að borða',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '59_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '60',
          label: 'Þreyta',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '60_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '61',
          label: 'Bjúgur',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '61_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '62',
          label: 'Hitakóf',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '62_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '63',
          label: 'Að komast á milli staða',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '63_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '64',
          label: 'Meltingartruflanir',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '64_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '65',
          label: 'Minni/einbeiting',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '65_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '66',
          label: 'Sár í munni',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '66_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '67',
          label: 'Ógleði',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '67_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '68',
          label: 'Þurrkur eða stífla í nefi',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '68_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '69',
          label: 'Verkir',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '69_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '70',
          label: 'Kynlíf/samlíf',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '70_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '71',
          label: 'Húðþurrkur/kláði',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '71_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '72',
          label: 'Svefn',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '72_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '73',
          label: 'Áfengi, fíkniefni eða lyf',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '73_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '74',
          label: 'Stingir í höndum/fótum',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '74_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei'],
          },
        },
        {
          id: '80',
          label: 'Önnur vandamál',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '80_type',
            type: AnswerOptionType.text,
            display: QuestionDisplayType.optional,
            multiline: true,
          },
        },
        {
          id: '90',
          label: 'Myndir þú vilja tala við einhvern um vandamál þín?',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '90_type',
            type: AnswerOptionType.radio,
            display: QuestionDisplayType.optional,
            options: ['Já', 'Nei', 'Kannski'],
          },
        },
        {
          id: '100',
          label: 'Við hvern?',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '100_type',
            type: AnswerOptionType.checkbox,
            display: QuestionDisplayType.optional,
            options: [
              'Hjúkrunarfræðing',
              'Næringarfræðing',
              'Lækni',
              'Sálfræðing',
              'Félagsráðgjafa',
              'Sjúkraþjálfara',
              'Prest eða djákna',
              'Sjúklingafélag',
              'Iðjuþjálfa',
              'Annan',
            ],
          },
          dependsOn: ['90'],
          visibilityCondition:
            '{"questionId":"90","operator":"equals","value":"Já","visible":true}',
        },
        {
          id: '120',
          label: 'Hvern?',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '120_type',
            type: AnswerOptionType.text,
            display: QuestionDisplayType.optional,
            multiline: false,
          },
          dependsOn: ['100'],
          visibilityCondition:
            '{"questionId":"100","operator":"equals","value":"Annan","visible":true}',
        },
        {
          id: '0',
          label: 'Copyright © NCCN National Comprehensive Cancer Network',
          display: QuestionDisplayType.optional,
          answerOptions: {
            id: '0_type',
            type: AnswerOptionType.label,
            display: QuestionDisplayType.optional,
          },
        },
      ],
    },
  ],
}
