import { QuestionDisplayType } from '../models/question.model'
import { QuestionnairesStatusEnum } from '../models/questionnaires.model'

export const data = {
  questionnaires: [
    {
      id: '8a3cf4aa-2f95-4e55-a686-971f3d9c9f8e',
      title: 'Heilsufarsupplýsingar vegna komu á Landspítala',
      description:
        'Með þessum spurningalistum viljum við auka virðingu fyrir tíma þínum og starfsfólks okkar, auka skilvirkni við undirbúning og minnka endurtekningar. Enginn þekkir betur þína sögu en þú sjálf/-ur.\\nVið biðjum þig vinsamlegast að svara eftir bestu getu og senda okkur listann til baka innan fjögurra daga.\\nSvörin vistast í sjúkraskrá þinni og eru meðhöndluð sem trúnaðarmál ',
      sentDate: '2025-09-04T22:29:14.676Z',
      status: QuestionnairesStatusEnum.notAnswered,
      organization: 'Landspítali',
      questions: [
        {
          __typename: 'Question',
          id: 'RadioGroup36866',
          label: 'Hvernig metur þú heilsufar þitt?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36866_option_1',
              label: 'Mjög hraust/-ur',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36866_option_2',
              label: 'Hraust/-ur',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36866_option_3',
              label: 'Heilsuveil/-veill',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36866_option_4',
              label: 'Mjög heilsuveil/-veill',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39695',
          label: 'Hefurðu dvalið á spítala erlendis síðastliðna 6 mánuði?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39695_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39695_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Height',
          label: 'Hæð',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Weight',
          label: 'Þyngd',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36815',
          label:
            'Hefur þú lést s.l. 6 mánuði án þess að ætla þér það? (Meira en 5% af þyngd þinni, dæmi 3kg ef 60kg, 4kg ef 80kg, 5kg ef 100kg)',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36815_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36815_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36816',
          label: 'Munnur, kok og hálshryggur',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36816_option_1',
              label: 'Eðlilegt eða án athugasemda',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36816_option_2',
              label: 'Erfiðleikar með að opna munninn/gapa',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36816_option_3',
              label: 'Góm vandamál (klofinn gómur eða annað)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36816_option_4',
              label: 'Kyngingarörðugleikar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36816_option_5',
              label: 'Skert hreyfigeta  (hálshryggur)',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36817',
          label: 'Tennur',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36817_option_1',
              label: 'Í lagi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36817_option_2',
              label: 'Laus gómur (efri)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36817_option_3',
              label: 'Laus gómur (neðri)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36817_option_4',
              label: 'Laus gómur (bæði efri og neðri):Brú/brýr með festingum',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36817_option_5',
              label: 'Implant/implönt',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist47830',
          label: 'Sjón',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist47830_option_1',
              label: 'Eðlileg eða án athugasemda',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47830_option_2',
              label: 'Nota gleraugu',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47830_option_3',
              label: 'Hamlandi sjónskerðing',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47830_option_4',
              label: 'Lögblinda',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist47831',
          label: 'Heyrn',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist47831_option_1',
              label: 'Eðlileg eða án athugasemda',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47831_option_2',
              label: 'Nota heyrnartæki',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47831_option_3',
              label: 'Heyrnarleysi',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist38491',
          label: 'Húð',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist38491_option_1',
              label: 'Heilbrigð húð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38491_option_2',
              label: 'Exem',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38491_option_3',
              label: 'Sár',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38491_option_4',
              label: 'Bruni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38491_option_5',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text38492',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36818',
          label: 'Ertu þunguð?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36818_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36818_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36818_option_3',
              label: 'Á ekki við',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36819',
          label: 'Hefur þú gengið með barn/börn?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36819_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36819_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36819_option_3',
              label: 'Á ekki við',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text47840',
          label: 'Fjöldi barna?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Checklist38488',
          label: 'Fæðingarmáti',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist38488_option_1',
              label: 'Um fæðingarveg',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38488_option_2',
              label: 'Með keisaraskurði',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36941',
          label: 'Ert þú líffæraþegi/með ígrætt líffæri?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36941_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36941_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36906',
          label: 'Hvaða líffæri?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup49785',
          label:
            'Ertu með heilsufarsvandamál sem takmarka dagleg verk og athafnir?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup49785_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup49785_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup49786',
          label:
            'Ertu með heilsufarsvandamál sem valda því að þú þarft að halda kyrru fyrir heima?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup49786_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup49786_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup48702',
          label: 'Hversu oft á síðustu 4 vikum fannstu fyrir þreytu/orkuleysi?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup48702_option_1',
              label: 'Stöðugt',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup48702_option_2',
              label: 'Oft',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup48702_option_3',
              label: 'Stundum',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup48702_option_4',
              label: 'Sjaldan',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup48702_option_5',
              label: 'Aldrei',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup49787',
          label: 'Hreyfir þú þig reglulega?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup49787_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup49787_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36835',
          label: 'Hversu mikið álag þolir þú?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36835_option_1',
              label:
                'Lágmarks áreynsla (Athafnir daglegs lífs. Geng inni og úti ca 200 m á undir 5 mín)',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36835_option_2',
              label:
                'Miðlungs áreynsla (Geng stiga eina hæð án vandamála. Geng á jafnsléttu 6 km/klst)',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36835_option_3',
              label: 'Mikil áreynsla (Syndi og hjóla. Þung líkamleg vinna)',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36836',
          label: 'Hvers vegna átt þú erfitt með hreyfingu?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36836_option_1',
              label: 'Hjarta- og æðasjúkdómur',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36836_option_2',
              label: 'Lungnasjúkdómur',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36836_option_3',
              label: 'Stoðkerfið',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36836_option_4',
              label: 'Annað',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text49780',
          label: 'Önnur ástæða, hver?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup38490',
          label: 'Ertu með hreyfiskerðingu?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup38490_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup38490_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text38489',
          label: 'Hvert er vandamálið?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36837',
          label: 'Notar þú hjálpartæki? (t.d. hækjur, göngugrind, hjólastól)',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36837_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36837_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36838',
          label: 'Hvaða hjálpartæki?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36842',
          label: 'Reykir þú?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36842_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36842_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36843',
          label: 'Hversu lengi hefur þú reykt?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Text36844',
          label: 'Hversu mikið reykir þú á dag?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36845',
          label: 'Hefur þú reykt?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36845_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36845_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36846',
          label: 'Hvenær hættir þú að reykja?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Text36847',
          label: 'Hversu mörg ár reyktir þú?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Text36848',
          label: 'Hversu mikið reyktir þú daglega?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup47841',
          label: 'Notar þú munntóbak eða neftóbak?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup47841_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup47841_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36850',
          label: 'Veipar þú?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36850_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36850_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36851',
          label: 'Drekkur þú áfengi? ',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36851_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36851_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist47836',
          label:
            'Hve mikið áfengi drekkur þú að jafnaði á viku? (ein eining = 1 vínglas/1 bjór/einfaldur sterkur drykkur)',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist47836_option_1',
              label: '0-6 einingar á viku',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47836_option_2',
              label: '7-13 einingar á viku',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47836_option_3',
              label: '14-21 einingu á viku',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47836_option_4',
              label: 'meira en 21 einingu á viku',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36852',
          label: 'Hefur þú neytt einhverra ávanabindandi lyfja?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36852_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36852_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36853',
          label: 'Hvaða ávanabindandi lyfja hefur þú neytt?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36824',
          label: 'Ertu með lyfjaofnæmi?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36824_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36824_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36825',
          label: 'Hvaða lyfi/lyfjum hefur þú ofnæmi fyrir?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36940',
          label: 'Lyfjaofnæmi',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36940_option_1',
              label: 'Lyfjaofnæmi staðfest með rannsókn',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36940_option_2',
              label: 'Lyfjaofnæmi ekki staðfest með rannsókn en sterkur grunur',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup47842',
          label: 'Ertu með annars konar ofnæmi?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup47842_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup47842_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36832',
          label: 'Hvers konar ofnæmi?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36821',
          label: 'Tekur þú lyfseðilsskyld lyf?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36821_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36821_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36822',
          label: 'Hvaða lyf?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36823',
          label: 'Ertu að taka blóðþynningarlyf önnur en hjartamagnýl?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36823_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36823_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36827',
          label: 'Ertu í lyfjaskömmtun?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36827_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36827_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36830',
          label: 'Hvaða apótek sér um lyfjaskömmtunina (nafn og staðsetning)?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup47832',
          label: 'Mataræði',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup47832_option_1',
              label: 'Almennt fæði',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup47832_option_2',
              label: 'Maukfæði',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup47832_option_3',
              label: 'Fljótandi fæði',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup47832_option_4',
              label: 'Annað sérfæði',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text47833',
          label: 'Annað sérfæði',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup47834',
          label: 'Fæðuóþol/ofnæmi',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup47834_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup47834_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text47835',
          label: 'Hvaða fæðuóþol/ofnæmi?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36839',
          label: 'Tekur þú fæðubótaefni reglulega?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36839_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36839_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36840',
          label: 'Hvaða fæðubótaefni tekur þú inn reglulega?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36841',
          label: 'Tekur þú lýsi?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36841_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36841_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39699',
          label: 'Ertu í reglulegu eftirliti hjá sérfræðilækni?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39699_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39699_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36855',
          label: 'Eftirlit hjá sérfræðilækni - merktu við það sem á við',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36855_option_1',
              label: 'Augnlækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_2',
              label: 'Geðlækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_3',
              label: 'Hjartalækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_4',
              label: 'Innkirtlalækni (t.d. sykursýki/skjaldkirtla/nýrnahettu)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_5',
              label: 'Krabbameinslækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_6',
              label: 'Lungnalækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_7',
              label: 'Meltingalækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_8',
              label: 'Nýrnalækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_9',
              label: 'Taugalækni',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36855_option_10',
              label: 'Annað en er nefnt hér að ofan',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36857',
          label: 'Hefur þú verið svæfð/ur?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36857_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36857_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36858',
          label: 'Voru einhver vandamál tengd svæfingunni?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36858_option_1',
              label: 'Nei',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36858_option_2',
              label: 'Já, öndunarvegavandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36858_option_3',
              label: 'Já, æðaaðgengi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36858_option_4',
              label: 'Já, ógleði eftir aðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36858_option_5',
              label: 'Já,illkynja háhiti (Malignant hyperthermia)',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup37717',
          label: 'Hefur þú farið i skurðaðgerð?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup37717_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup37717_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36861',
          label: 'Hvað af eftirfarandi skurðaðgerðum hefur þú farið í?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36861_option_1',
              label: 'Bakaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_2',
              label: 'Heilaaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_3',
              label: 'Hjartaaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_4',
              label: 'Keisaraskurðaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_5',
              label: 'Kransæðavíkkun',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_6',
              label: 'Kvensjúkdómaaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_7',
              label: 'Kviðarholsaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_8',
              label: 'Liðskiptaaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_9',
              label: 'Lungnaaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_10',
              label: 'Nýrna-/þvagfæraaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_11',
              label: 'Skjaldkirtilsaðgerð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36861_option_12',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36862',
          label: 'Aðrar aðgerðir?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36859',
          label: 'Hefur þú fengið mænudeyfingu?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36859_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36859_option_2',
              label: 'Óviss',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36859_option_3',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36860',
          label: 'Manstu eftir vandamálum tengdum mænudeyfingum?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36860_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36860_option_2',
              label: 'Óviss',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36860_option_3',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text39609',
          label: 'Ef já, hvað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36863',
          label: 'Hefur þú fengið blóðgjöf?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36863_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36863_option_2',
              label: 'Óviss',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36863_option_3',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup49784',
          label: 'Ef nauðsyn krefur ert þú samþykk/ur blóðgjöf?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup49784_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup49784_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Label49782',
          label: 'Spurningar um sjúkdóma eftir líffærakerfum',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39649',
          label: 'Geðræn vandamál',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39649_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39649_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist47837',
          label: 'Geðræn vandamál - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist47837_option_1',
              label: 'Athyglisbrestur/ADHD',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47837_option_2',
              label: 'Depurð/þunglyndi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47837_option_3',
              label: 'Fíknivandi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47837_option_4',
              label: 'Geðhvarfasýki',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47837_option_5',
              label: 'Kvíði',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47837_option_6',
              label: 'Svefnvandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47837_option_7',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36869',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39651',
          label: 'Lungna- og öndunarfærasjúkdómar ',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39651_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39651_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist47838',
          label: 'Lungna og öndunarsjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist47838_option_1',
              label: 'Astmi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_2',
              label: 'Hrotur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_3',
              label: 'Kæfisvefn',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_4',
              label: 'Kæfisvefnsvél heima',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_5',
              label: 'Lungnaþemba',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_6',
              label: 'Mæði',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_7',
              label: 'Saga um berkla',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_8',
              label: 'Tíðar lungnabólgur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist47838_option_9',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36875',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39650',
          label: 'Miðtaugakerfis- og/eða hrörnunarsjúkdómar',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39650_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39650_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36871',
          label:
            'Miðtaugakerfis- og/eða hrörnunarsjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36871_option_1',
              label: 'Alzheimer',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_2',
              label: 'Flogaveiki',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_3',
              label: 'Jafnvægistruflun/Svimi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_4',
              label: 'Lömun/Helftarlömun',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_5',
              label: 'Minnistruflanir',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_6',
              label: 'MND (motor neuron disease)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_7',
              label: 'MS (multiple sclerosis)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_8',
              label: 'Muscular dystrophy',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_9',
              label: 'Mænuskaði',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_10',
              label: 'Parkinsons sjúkdómur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_11',
              label: 'Þekktur æðagúll í heila',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_12',
              label: 'Æðaáfall (blóðtappi til heila/heilablæðing)',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36871_option_13',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36872',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39652',
          label: 'Hjartasjúkdómar',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39652_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39652_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36877',
          label: 'Hjartasjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36877_option_1',
              label: 'Brjóstverkir við áreynslu',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_2',
              label: 'Farið í brennslu á leiðslubrautum í hjarta',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_3',
              label: 'Gangráður/bjargráður',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_4',
              label: 'Háþrýstingur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_5',
              label: 'Hjartabilun',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_6',
              label: 'Hjartalokusjúkdómur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_7',
              label: 'Hjartsláttaróregla',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_8',
              label: 'Kransæðasjúkdómur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_9',
              label: 'Meðfæddir hjartagallar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_10',
              label: 'Mæði',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36877_option_11',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36878',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39653',
          label: 'Æðasjúkdómar',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39653_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39653_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36880',
          label: 'Æðasjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36880_option_1',
              label: 'Bláæðar fjarlægðar úr fótleggjum',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_2',
              label: 'Brjósthol/ósæð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_3',
              label: 'Fótleggir',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_4',
              label: 'Háls',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_5',
              label: 'Höfuð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_6',
              label: 'Kviðarhol - ósæð/kviðarholslíffæraæðar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_7',
              label: 'Æðahnútar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36880_option_8',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36881',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39654',
          label: 'Meltingasjúkdómar',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39654_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39654_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36883',
          label: 'Meltingarsjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36883_option_1',
              label: 'Bakflæði',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36883_option_2',
              label: 'Chrons/Colitis ulcerosa',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36883_option_3',
              label: 'Hægðatregða',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36883_option_4',
              label: 'Lifrar-/gall-/brissjúkdómur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36883_option_5',
              label: 'Magabólgur/magasár',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36883_option_6',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36884',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39655',
          label: 'Kvensjúkdómar ',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39655_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39655_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39655_option_3',
              label: 'Á ekki við',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36886',
          label: 'Kvensjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36886_option_1',
              label: 'Blæðingarvandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36886_option_2',
              label: 'Blöðru-/leg-/endaþarmssig',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36886_option_3',
              label: 'Endometriosa',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36886_option_4',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36887',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39688',
          label: 'Þvag- og kynfærasjúkdómar',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39688_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39688_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36889',
          label: 'Þvag- og kynfærasjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36889_option_1',
              label: 'Blóð-/kviðskilun',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_2',
              label: 'Blöðruhálskirtils vandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_3',
              label: 'Endurteknar þvagfærasýkingar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_4',
              label: 'Nýrnabilun',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_5',
              label: 'Nýrnasjúkdómar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_6',
              label: 'Nýrnasteinar',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_7',
              label: 'Þvagblöðru vandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_8',
              label: 'Þvagleki',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_9',
              label: 'Þvagtregða',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36889_option_10',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36890',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39689',
          label: 'Blóðsjúkdómar ',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39689_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39689_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36892',
          label: 'Blóðsjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36892_option_1',
              label: 'Blóðleysi',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36892_option_2',
              label: 'Blóðsega vandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36892_option_3',
              label: 'Blóðstorku vandamál',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36892_option_4',
              label: 'Járnskortur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36892_option_5',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36893',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39690',
          label: 'Innkirtlasjúkdómar ',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39690_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39690_option_2',
              label: 'Já ',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36895',
          label: 'Innkirtlasjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36895_option_1',
              label: 'Nýrnahettusjúkdómur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36895_option_2',
              label: 'Skjaldkirtilssjúkdómur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36895_option_3',
              label: 'Sykursýki',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36895_option_4',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36896',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39691',
          label: 'Stoðkerfissjúkdómar',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39691_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39691_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36898',
          label: 'Stoðkerfissjúkdómar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36898_option_1',
              label: 'Slitgigt',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36898_option_2',
              label: 'Sterasprautur í lið s.l. 3 mánuði',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36898_option_3',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36899',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup39692',
          label: 'Sýkingar ',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup39692_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup39692_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36902',
          label: 'Sýkingar - merktu við það sem á við:',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36902_option_1',
              label: 'Endurteknar öndunarfærasýkingar síðastliðið ár',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36902_option_2',
              label: 'HIV / lifrarbólga C',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36902_option_3',
              label: 'MÓSA/ESBL/VRE',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36902_option_4',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36903',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36934',
          label: 'Hefur þú greinst með krabbamein?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36934_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36934_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36909',
          label: 'Hvers konar krabbamein?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup37718',
          label: 'Er þekkt fjölskyldusaga um krabbamein?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup37718_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup37718_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36911',
          label: 'Ertu með aðra sjúkdóma sem ekki hefur verið spurt um?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36911_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36911_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36912',
          label: 'Hvaða sjúkdóm/a?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Label49783',
          label: 'Spurningar um félagslegar aðstæður',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup36942',
          label: 'Býrðu ein/-n?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup36942_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup36942_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text47839',
          label: 'Með hverjum',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'RadioGroup48703',
          label: 'Þarftu aðstoð við dagleg verk og athafnir?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup48703_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup48703_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'RadioGroup48704',
          label: 'Geturðu treyst á einhvern þér nákominn ef þörf krefur?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'RadioGroup48704_option_1',
              label: 'Nei',
              type: 'radio',
              value: null,
            },
            {
              id: 'RadioGroup48704_option_2',
              label: 'Já',
              type: 'radio',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Checklist36808',
          label: 'Færðu utan að komandi stuðning inn á heimili þitt?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist36808_option_1',
              label: 'Heimsendan mat',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36808_option_2',
              label: 'Aðstoð ættingja',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36808_option_3',
              label: 'Heimahjúkrun',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36808_option_4',
              label: 'Heimilisaðstoð',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist36808_option_5',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text36809',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Checklist38586',
          label: 'Atvinna',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist38586_option_1',
              label: 'Er í vinnu',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38586_option_2',
              label: 'Er í skóla',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38586_option_3',
              label: 'Er öryrki',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38586_option_4',
              label: 'Er hætt/-ur að vinna vegna aldurs',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist38586_option_5',
              label: 'Annað',
              type: 'checkbox',
              value: null,
            },
          ],
        },
        {
          __typename: 'Question',
          id: 'Text38587',
          label: 'Hvað annað?',
          display: QuestionDisplayType.optional,
        },
        {
          __typename: 'Question',
          id: 'Checklist39697',
          label: 'Hver fyllti út spurningalistann/eyðublaðið?',
          display: QuestionDisplayType.optional,
          answerOptions: [
            {
              id: 'Checklist39697_option_1',
              label: 'Ég sjálf/-ur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist39697_option_2',
              label: 'Forráðamaður',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist39697_option_3',
              label: 'Maki/vinur/fjölskyldumeðlimur',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist39697_option_4',
              label: 'Heilbrigðisstarfsmaður',
              type: 'checkbox',
              value: null,
            },
            {
              id: 'Checklist39697_option_5',
              label: 'Annar',
              type: 'checkbox',
              value: null,
            },
          ],
        },
      ],
    },
  ],
}
