import { HealthDirectoratePatientDataApprovalCountry } from '@island.is/api/schema'

export const europeanCountriesIs: HealthDirectoratePatientDataApprovalCountry[] =
  [
    { id: '1', code: 'AT', name: 'Austurríki' },
    { id: '2', code: 'BE', name: 'Belgía' },
    { id: '3', code: 'BG', name: 'Búlgaría' },
    { id: '4', code: 'HR', name: 'Króatía' },
    { id: '5', code: 'CY', name: 'Kýpur' },
    { id: '6', code: 'CZ', name: 'Tékkland' },
    { id: '7', code: 'DK', name: 'Danmörk' },
    { id: '8', code: 'EE', name: 'Eistland' },
    { id: '9', code: 'FI', name: 'Finnland' },
    { id: '10', code: 'FR', name: 'Frakkland' },
    { id: '11', code: 'DE', name: 'Þýskaland' },
    { id: '12', code: 'GR', name: 'Grikkland' },
    { id: '13', code: 'HU', name: 'Ungverjaland' },
    { id: '14', code: 'IE', name: 'Írland' },
    { id: '15', code: 'IT', name: 'Ítalía' },
    { id: '16', code: 'LV', name: 'Lettland' },
    { id: '17', code: 'LI', name: 'Liechtenstein' },
    { id: '18', code: 'LT', name: 'Litháen' },
    { id: '19', code: 'LU', name: 'Lúxemborg' },
    { id: '20', code: 'MT', name: 'Malta' },
    { id: '21', code: 'NL', name: 'Holland' },
    { id: '22', code: 'PL', name: 'Pólland' },
    { id: '23', code: 'PT', name: 'Portúgal' },
    { id: '24', code: 'RO', name: 'Rúmenía' },
    { id: '25', code: 'SK', name: 'Slóvakía' },
    { id: '26', code: 'SI', name: 'Slóvenía' },
    { id: '27', code: 'ES', name: 'Spánn' },
  ]
