import { dump, load } from 'js-yaml'
import { FeatureKubeJob, HelmValueFile } from '../types/output-types'
import { EnvironmentConfig } from '../types/charts'
import { addHoursToDate } from '../utils'
export const dumpOpts = {
  sortKeys: true,
  noRefs: true,
  forceQuotes: true,
}
export const reformatYaml = (content: string): string => {
  const obj = load(content, { json: true })
  return dump(obj, dumpOpts)
}
export const dumpJobYaml = (job: FeatureKubeJob) => dump(job, dumpOpts)
export const dumpServiceHelm = (
  env: EnvironmentConfig,
  valueFile: HelmValueFile,
) => {
  const { namespaces, services } = valueFile
  const namespaceLabels = env.feature
    ? {
        namespaceType: 'feature',
        expires: addHoursToDate(new Date(), 24).toString(),
      }
    : {}
  const HEADER =
    '#####################################################################\n' +
    '#\n' +
    '# Do not edit this file manually, it is automatically generated.\n' +
    '# Run "yarn charts" instead.\n' +
    '#\n' +
    '#####################################################################\n'
  return (
    HEADER +
    dump(
      { namespaces: { namespaces, labels: namespaceLabels }, ...services },
      dumpOpts,
    )
  )
}
