import { PortalModule } from '@island.is/portals/core'
import { lazy } from 'react'
import { m } from './lib/messages'
import { FormSystemPaths } from './lib/paths'
import { AdminPortalScope } from '@island.is/auth/scopes'
