export * from './lib/fiskistofa.module'
export * from './lib/models/shipStatusInformation'
export * from './lib/dto/getAflamarkInformationForShip.input'
export * from './lib/dto/getUpdatedAflamarkInformationForShip.input'
export * from './lib/dto/getDeilistofnaInformationForShip.input'
export * from './lib/dto/getUpdatedDeilistofnaInformationForShip.input'
export * from './lib/dto/getShips.input'
