export const errorCodeMessageMap: Record<number, string> = {
  3: 'Fastanúmer vantar',
  4: 'Dagsetning álesturs vantar',
  5: 'Uppruna álesturs vantar',
  6: 'Álestur vantar',
  7: 'Km staða getur ekki verið minna en 0',
  8: 'Km staða álesturs getur ekki verið minni en síðasta gildi sem skráð hefur verið á ökutækið',
  9: 'Staðartegund í álestri finnst ekki',
  10: 'Ökutæki finnst ekki',
  11: 'Dagsetning færslu minni en nýjasta færsla á ökutæki',
  12: 'Ekki má breyta færslu sem er ekki innan dagsins í dag',
  13: 'Villa við skráningu, ekki má skrá innan 30 daga frá síðustu færslu',
  14: 'Ekki má breyta færslu sem er ekki nýjasta færsla ökutækis',
  15: 'Tilkynnandi eða innsendur tilkynnandi er hvorki umráðamaður né eigandi ökutækis',
  16: 'Tegund álesturs ekki til',
  17: 'Aðeins er leyfilegt að eyða nýjustu km skráningu',
  18: 'Færsla til að eyða finnst ekki',
  19: 'Ökutæki krefst ekki aflesturs',
  20: 'Km staða fer yfir hámark per dag',
  21: 'Km staða fer yfir hámark per dag',
}
