import { TaxCalculatorFieldKind } from '../models/enums'
import {
  FieldDefinition,
  MAX_SANE_NUMBER_VALUE as MAX_NUMBER,
} from '../utils/fieldDefinition'
import { currentYearIncomeYearOptions } from '../utils/fieldOptions'

export const withholdingTaxFields: FieldDefinition[] = [
  {
    key: 'paymentFrequency',
    label: 'Greiðslutíðni launa',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    options: [
      { value: 'false', label: 'Vikulega' },
      { value: 'true', label: 'Mánaðarlega' },
    ],
  },
  {
    key: 'maritalStatus',
    label: 'Hjúskaparstaða',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    options: [
      { value: '1', label: 'Einhleypingur' },
      { value: '2', label: 'Einstætt foreldri' },
      { value: '3', label: 'Hjón/Sambúð' },
    ],
  },
  {
    key: 'incomeYear',
    label: 'Tekjuár',
    kind: TaxCalculatorFieldKind.SELECT,
    required: true,
    options: currentYearIncomeYearOptions,
  },
  {
    key: 'payMonth',
    label: 'Launamánuður',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    min: 1,
    max: 12,
  },
  {
    key: 'salary',
    label: 'Heildarlaun mánaðar',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: true,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
  {
    key: 'pensionFundRatio',
    label: 'Í lífeyrissjóð',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    unit: '%',
    // 4% is the statutory minimum employee contribution to a pension fund.
    options: [{ value: '4', label: '4%' }],
  },
  {
    key: 'privatePensionRatio',
    label: 'Í séreignarsjóð',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    unit: '%',
    // Voluntary private pension savings are commonly 0% (opt out), 2%, or 4%.
    options: [
      { value: '0', label: '0%' },
      { value: '2', label: '2%' },
      { value: '4', label: '4%' },
    ],
  },
  {
    key: 'taxCardUtilization',
    label: 'Nýting eigin afsláttar',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: '%',
    min: 0,
    max: 100,
  },
  {
    key: 'spouseTaxCardUtilization',
    label: 'Nýting afsláttar maka',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: '%',
    min: 0,
    max: 100,
  },
  {
    key: 'accumulatedPersonalTaxCredit',
    label: 'Uppsafnaður afsláttur',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
  {
    key: 'vacationPay',
    label: 'Orlof',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
  {
    key: 'unionDues',
    label: 'Gjöld f. stéttarfélag',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
  {
    key: 'otherDeduction',
    label: 'Annar frádráttur',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
  {
    key: 'employerPensionMatchRatio',
    label: 'Mótframlag í lífeyrissjóð',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: '%',
    min: 0,
    max: 100,
  },
  {
    key: 'vehicleAllowance',
    label: 'Ökutækjastyrkur utan staðgreiðslu',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
  {
    key: 'seamenAccidentInsurancePremium',
    label: 'Iðgjald slysatryggingar sjómanna',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
  },
]
