export enum UserRole {
    ADMIN_MANAGER = 'ADMIN_MANAGER',
    ADMIN_PROCESSOR = 'ADMIN_PROCESSOR',
    CANDIDATE_OWNER = 'CANDIDATE_OWNER',
    CANDIDATE_COLLECTOR = 'CANDIDATE_COLLECTOR',
    USER= 'USER',
    UNAUTHENTICATED = 'UNAUTHENTICATED',
}
