export const baseConfig = {
  skin_url:
    'https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.6.2/skins/ui/oxide',
  inline: true,
  toolbar_persist: true,
  // toolbar_sticky: true,

  plugins: [
    'advlist',
    'autolink',
    'lists',
    'link',
    'image',
    'charmap',
    'hr',
    // 'preview',
    'anchor',
    'searchreplace',
    // 'visualblocks',
    'code',
    // 'fullscreen',
    // 'insertdatetime',
    // 'media',
    'table',
    'paste',
    // 'help',
    // 'template',

    '_onInited_hack_',
  ],

  advlist_number_styles:
    'default,lower-alpha,upper-alpha,lower-roman,upper-roman',

  // https://www.tiny.cloud/docs/configure/editor-appearance/#examplethetinymcedefaultmenuitems
  menubar: false,

  style_formats: [
    {
      title: 'Layout (no border)',
      selector: 'table',
      attributes: { class: 'layout' },
    },
    {
      title: 'List-Layout Table',
      selector: 'table',
      attributes: { class: 'layout layout--list' },
    },
    {
      title: 'Auto-generated List',
      selector: '[data-autogenerated=""]',
      attributes: { 'data-autogenerated': '' },
    },
    {
      title: 'Paragraph',
      block: 'p',
      attributes: { class: '', style: '' },
    },
    {
      title: 'Heiti/titill skjalsins',
      block: 'p',
      attributes: { class: 'doc__title', style: 'text-align: center;' },
    },
    {
      title: 'Grein',
      block: 'h3',
      attributes: { class: 'article__title', style: '' },
    },
    {
      title: 'Undirkafli',
      block: 'h2',
      attributes: { class: 'subchapter__title', style: '' },
    },
    {
      title: 'Kafli',
      block: 'h2',
      attributes: { class: 'chapter__title', style: '' },
    },
    {
      title: 'Hluti',
      block: 'h2',
      attributes: { class: 'section__title', style: '' },
    },
    {
      title: 'Bráðabirgðaákvæði',
      block: 'h3',
      attributes: {
        class: 'article__title article__title--provisional',
        style: '',
      },
    },
    {
      title: 'Tilvitnun',
      block: 'blockquote',
      attributes: { class: '' },
      wrapper: true,
      // merge_siblings: false,
    },
    {
      title: 'Inndregin málsgrein',
      block: 'p',
      attributes: { class: 'indented', style: '' },
    },
    {
      title: 'pre',
      block: 'pre',
      attributes: { class: '' },
    },
    {
      title: 'Undirritun',
      items: [
        {
          title: 'Dags',
          block: 'p',
          attributes: { class: 'Dags', style: '' },
        },
        {
          title: 'FHUndirskr',
          block: 'p',
          attributes: { class: 'FHUndirskr', style: '' },
        },
        {
          title: 'Undirritun',
          block: 'p',
          attributes: { class: 'Undirritun', style: '' },
        },
      ],
    },
    {
      title: 'Bare Headers',
      items: [
        {
          title: 'Heading 2',
          block: 'h2',
          attributes: { class: '', style: '' },
        },
        {
          title: 'Heading 3',
          block: 'h3',
          attributes: { class: '', style: '' },
        },
        {
          title: 'Heading 4',
          block: 'h4',
          attributes: { class: '', style: '' },
        },
        {
          title: 'Heading 5',
          block: 'h5',
          attributes: { class: '', style: '' },
        },
        {
          title: 'Heading 6',
          block: 'h6',
          attributes: { class: '', style: '' },
        },
      ],
    },
  ],
  // visualblocks_default_state: true,
  end_container_on_empty_block: true,
  style_formats_autohide: true,

  relative_urls: false,
  remove_script_host: true,
  image_dimensions: false,
  // automatic_uploads: true,
  images_reuse_filename: true,
  images_upload_credentials: true,
  // images_upload_handler: // set during component mount

  table_class_list: [
    { title: 'Normal', value: '' },
    { title: 'Layout (no border)', value: 'layout' },
    { title: 'List-Layout Table', value: 'layout layout--list' },
  ],
  table_advtab: false,
  table_cell_advtab: false,
  table_row_advtab: false,
  table_resize_bars: false,
  table_header_type: 'sectionCells',
  table_use_colgroups: false, // default
  table_default_attributes: {},
  table_sizing_mode: 'responsive',

  toolbar: `
undo redo | bold italic link inlineformat | styleselect alignment |
bullist numlist ${'' /* outdent indent */} |
table image | insert
`,

  toolbar_groups: {
    alignment: {
      icon: 'align-left',
      tooltip: 'Alignment',
      items: 'alignleft aligncenter alignright',
    },
    inlineformat: {
      icon: 'format',
      tooltip: 'Inline formats',
      items: 'underline strikethrough superscript subscript | removeformat',
      // + ' | formats',
    },
    insert: {
      icon: 'plus',
      tooltip: 'Other',
      items: 'code charmap hr',
    },
  },
}
