export const testIDs = {
  // tab_bar
  TABBAR_TAB_HOME: 'TABBAR_TAB_HOME',
  TABBAR_TAB_INBOX: 'TABBAR_TAB_INBOX',
  TABBAR_TAB_WALLET: 'TABBAR_TAB_WALLET',
  TABBAR_MAIN: 'TABBAR_MAIN',

  // topbar
  TOPBAR_USER_BUTTON: 'TOPBAR_USER_BUTTON',

  // login screen
  SCREEN_LOGIN: 'SCREEN_LOGIN',
  LOGIN_BUTTON_AUTHENTICATE: 'LOGIN_BUTTON_AUTHENTICATE',

  // onboarding
  SCREEN_ONBOARDING_APP_LOCK: 'SCREEN_ONBOARDING_APP_LOCK',
  ENTER_PIN_NUMBER_INPUT: 'ENTER_PIN_NUMBER_INPUT',
  CONFIRM_PIN_NUMBER_INPUT: 'CONFIRM_PIN_NUMBER_INPUT',
  ONBOARDING_APP_LOCK_CONTINUE_BUTTON: 'ONBOARDING_APP_LOCK_CONTINUE_BUTTON',

  SCREEN_ONBOARDING_NOTIFICATIONS: 'SCREEN_ONBOARDING_NOTIFICATIONS',
  ONBOARDING_NOTIFICATIONS_ALLOW_BUTTON: 'ONBOARDING_NOTIFICATIONS_ALLOW_BUTTON',
  ONBOARDING_NOTIFICATIONS_SKIP_BUTTON: 'ONBOARDING_NOTIFICATIONS_SKIP_BUTTON',

  // app lock screen
  SCREEN_APP_LOCK: 'SCREEN_APP_LOCK',

  // home screen
  SCREEN_HOME: 'SCREEN_HOME',

  // user screen
  SCREEN_USER: 'SCREEN_USER',
  LOGOUT_BUTTON: 'LOGOUT_BUTTON',
}
