export const testIDs = {
  // tab_bar
  TABBAR_TAB_HOME: 'TABBAR_TAB_HOME',
  TABBAR_TAB_INBOX: 'TABBAR_TAB_INBOX',
  TABBAR_TAB_WALLET: 'TABBAR_TAB_WALLET',
  TABBAR_MAIN: 'TABBAR_MAIN',

  // topbar
  TOPBAR_USER_BUTTON: 'TOPBAR_USER_BUTTON',

  // login screen
  SCREEN_LOGIN: 'SCREEN_LOGIN',
  LOGIN_BUTTON_AUTHENTICATE: 'LOGIN_BUTTON_AUTHENTICATE',

  // app lock screen
  SCREEN_APP_LOCK: 'SCREEN_APP_LOCK',

  // home screen
  SCREEN_HOME: 'SCREEN_HOME',

  // user screen
  SCREEN_USER: 'SCREEN_USER',
  LOGOUT_BUTTON: 'LOGOUT_BUTTON',
}
