export const testIDs = {
  // bottom tab bar
  TABBAR_TAB_HOME: 'TABBAR_TAB_HOME',
  TABBAR_TAB_INBOX: 'TABBAR_TAB_INBOX',
  TABBAR_TAB_WALLET: 'TABBAR_TAB_WALLET',
  TABBAR_TAB_MORE: 'TABBAR_TAB_MORE',
  TABBAR_TAB_APPLICATION: 'TABBAR_TAB_APPLICATION',
  TABBAR_MAIN: 'TABBAR_MAIN',

  // top bar buttons
  TOPBAR_SETTINGS_BUTTON: 'TOPBAR_SETTINGS_BUTTON',
  TOPBAR_OFFLINE_BUTTON: 'TOPBAR_OFFLINE_BUTTON',
  TOPBAR_NOTIFICATIONS_BUTTON: 'TOPBAR_NOTIFICATIONS_BUTTON',
  TOPBAR_SCAN_LICENSE_BUTTON: 'TOPBAR_SCAN_LICENSE_BUTTON',
  TOPBAR_HOME_OPTIONS_BUTTON: 'TOPBAR_HOME_OPTIONS_BUTTON',
  TOPBAR_DROPDOWN_BUTTON: 'TOPBAR_DROPDOWN_BUTTON',
  TOPBAR_BACK_BUTTON: 'TOPBAR_BACK_BUTTON',

  // shared components

  // pin keypad
  PIN_KEYPAD_BUTTON_0: 'PIN_KEYPAD_BUTTON_0',
  PIN_KEYPAD_BUTTON_1: 'PIN_KEYPAD_BUTTON_1',
  PIN_KEYPAD_BUTTON_2: 'PIN_KEYPAD_BUTTON_2',
  PIN_KEYPAD_BUTTON_3: 'PIN_KEYPAD_BUTTON_3',
  PIN_KEYPAD_BUTTON_4: 'PIN_KEYPAD_BUTTON_4',
  PIN_KEYPAD_BUTTON_5: 'PIN_KEYPAD_BUTTON_5',
  PIN_KEYPAD_BUTTON_6: 'PIN_KEYPAD_BUTTON_6',
  PIN_KEYPAD_BUTTON_7: 'PIN_KEYPAD_BUTTON_7',
  PIN_KEYPAD_BUTTON_8: 'PIN_KEYPAD_BUTTON_8',
  PIN_KEYPAD_BUTTON_9: 'PIN_KEYPAD_BUTTON_9',
  PIN_KEYPAD_BUTTON_FACEID: 'PIN_KEYPAD_BUTTON_FACEID',
  PIN_KEYPAD_BUTTON_IRIS: 'PIN_KEYPAD_BUTTON_IRIS',
  PIN_KEYPAD_BUTTON_FINGERPRINT: 'PIN_KEYPAD_BUTTON_FINGERPRINT',
  PIN_KEYPAD_BUTTON_DELETE: 'PIN_KEYPAD_BUTTON_DELETE',

  // navigation bar sheet
  NAVBAR_SHEET_CLOSE_BUTTON: 'NAVBAR_SHEET_CLOSE_BUTTON',

  // screen specifics

  // login screen
  SCREEN_LOGIN: 'SCREEN_LOGIN',
  LOGIN_BUTTON_AUTHENTICATE: 'LOGIN_BUTTON_AUTHENTICATE',

  // onboarding pin
  SCREEN_ONBOARDING_ENTER_PIN: 'SCREEN_ONBOARDING_ENTER_PIN',
  SCREEN_ONBOARDING_CONFIRM_PIN: 'SCREEN_ONBOARDING_CONFIRM_PIN',
  ONBOARDING_CONFIRM_PIN_CANCEL: 'ONBOARDING_CONFIRM_PIN_CANCEL',

  // onboarding biometrics
  SCREEN_ONBOARDING_BIOMETRICS: 'SCREEN_ONBOARDING_BIOMETRICS',
  ONBOARDING_BIOMETRICS_USE_BUTTON: 'ONBOARDING_BIOMETRICS_USE_BUTTON',
  ONBOARDING_BIOMETRICS_CANCEL_BUTTON: 'ONBOARDING_BIOMETRICS_CANCEL_BUTTON',

  // onboarding notifications
  SCREEN_ONBOARDING_NOTIFICATIONS: 'SCREEN_ONBOARDING_NOTIFICATIONS',
  ONBOARDING_NOTIFICATIONS_ALLOW_BUTTON:
    'ONBOARDING_NOTIFICATIONS_ALLOW_BUTTON',
  ONBOARDING_NOTIFICATIONS_SKIP_BUTTON: 'ONBOARDING_NOTIFICATIONS_SKIP_BUTTON',

  // app lock screen
  SCREEN_APP_LOCK: 'SCREEN_APP_LOCK',

  // home screen
  SCREEN_HOME: 'SCREEN_HOME',

  // notifications screen
  SCREEN_NOTIFICATIONS: 'SCREEN_NOTIFICATIONS',
  NOTIFICATION_CARD_BUTTON: 'NOTIFICATION_CARD_BUTTON',

  // notification detail screen
  SCREEN_NOTIFICATION_DETAIL: 'SCREEN_NOTIFICATION_DETAIL',

  // user screen
  SCREEN_USER: 'SCREEN_USER',
  USER_TABBAR_TAB_PROFILE_INFO: 'USER_TABBAR_TAB_PROFILE_INFO',
  USER_TABBAR_TAB_SETTINGS: 'USER_TABBAR_TAB_SETTINGS',
  USER_SETTINGS_LOGOUT_BUTTON: 'LOGOUT_BUTTON',
  USER_SCREEN_PROFILE_INFO: 'USER_SCREEN_PROFILE_INFO',
  USER_SCREEN_SETTINGS: 'USER_SCREEN_SETTINGS',
  USER_PROFILE_INFO_DISPLAY_NAME_VALUE: 'USER_PROFILE_INFO_DISPLAY_NAME_VALUE',

  // settings screen
  SCREEN_SETTINGS: 'SCREEN_SETTINGS',

  // personal info screen
  SCREEN_PERSONAL_INFO: 'SCREEN_PERSONAL_INFO',

  // applications screen
  SCREEN_APPLICATIONS: 'SCREEN_APPLICATIONS',
  SCREEN_APPLICATIONS_DETAILS: 'SCREEN_APPLICATIONS_DETAILS',
  APPLICATION_ITEM: 'APPLICATION_ITEM',

  // vehicles screen
  SCREEN_VEHICLES: 'SCREEN_VEHICLES',
  SCREEN_VEHICLE_DETAIL: 'SCREEN_VEHICLE_DETAIL',
  MORE_CARD_VEHICLES: 'MORE_CARD_VEHICLES',
  VEHICLE_ITEM: 'VEHICLE_ITEM',

  // family
  SCREEN_FAMILY_OVERVIEW: 'SCREEN_FAMILY_OVERVIEW',
  SCREEN_FAMILY_DETAIL: 'SCREEN_FAMILY_DETAIL',
  MORE_CARD_FAMILY: 'MORE_CARD_FAMILY',
  FAMILY_MEMBER_ITEM: 'FAMILY_MEMBER_ITEM',

  // assets
  SCREEN_ASSETS_OVERVIEW: 'SCREEN_ASSETS_OVERVIEW',
  SCREEN_ASSETS_DETAIL: 'SCREEN_ASSETS_DETAIL',
  MORE_CARD_ASSETS: 'MORE_CARD_ASSETS',
  ASSET_ITEM: 'ASSET_ITEM',

  // edit
  SCREEN_EDIT_PHONE: 'SCREEN_EDIT_PHONE',
  SCREEN_EDIT_EMAIL: 'SCREEN_EDIT_EMAIL',
  SCREEN_EDIT_BANK_INFO: 'SCREEN_EDIT_BANK_INFO',
  SCREEN_EDIT_CONFIRM: 'SCREEN_EDIT_CONFIRM',

  // finance
  SCREEN_FINANCE: 'SCREEN_FINANCE',
  SCREEN_FINANCE_DETAIL: 'SCREEN_FINANCE_DETAIL',
  MORE_CARD_FINANCE: 'MORE_CARD_FINANCE',
  FINANCE_ITEM: 'FINANCE_ITEM',
  FINANCE_ITEM_ROW: 'FINANCE_ITEM_ROW',

  // licenses
  LICENSE_STATUS: 'LICENSE_STATUS',
  LICENSE_FIELDS: 'LICENSE_FIELDS',

  // inbox
  SCREEN_INBOX: 'SCREEN_INBOX',
  SCREEN_INBOX_DETAIL: 'SCREEN_INBOX_DETAIL',
  INBOX_ITEM: 'INBOX_ITEM',

  // passkey
  SCREEN_PASSKEY: 'SCREEN_PASSKEY',

  // health
  SCREEN_HEALTH_OVERVIEW: 'SCREEN_HEALTH_OVERVIEW',
  MORE_CARD_HEALTH: 'MORE_CARD_HEALTH',
  BUTTON_VACCINATIONS: 'BUTTON_VACCINATIONS',
  SCREEN_VACCINATIONS: 'SCREEN_VACCINATIONS',
  HEALTH_CENTER: 'HEALTH_CENTER',
  VACCINATION_ITEM: 'VACCINATION_ITEM',
  VACCINATION_ITEM_ROW: 'VACCINATION_ITEM_ROW',

  // air discount
  SCREEN_AIR_DISCOUNT: 'SCREEN_AIR_DISCOUNT',
  MORE_CARD_AIR_DISCOUNT: 'MORE_CARD_AIR_DISCOUNT',
  AIR_DISCOUNT_ITEM: 'AIR_DISCOUNT_ITEM',
}
