export const FieldTypesEnum = {
  TEXTBOX: 'textbox',
  EMAIL: 'email',
  PROPERTY_NUMBER: 'propertyNumber',
  ISK_NUMBERBOX: 'iskNumberbox',
  CHECKBOX: 'checkbox',
  DATE_PICKER: 'datePicker',
  NUMBERBOX: 'numberbox',
  PAYER: 'payer',
  NATIONAL_ID_ESTATE: 'nationaIdEstate',
  PHONE_NUMBER: 'phoneNumber',
  MESSAGE: 'message',
  RADIO_BUTTONS: 'radioButtons',
  DOCUMENT: 'document',
  BANK_ACCOUNT: 'bankAccount',
  NATIONAL_ID: 'nationalId',
  HOMESTAY_NUMBER: 'homestayNumber',
  ISK_SUMBOX: 'iskSumbox',
  DROPDOWN_LIST: 'dropdownList',
  NATIONAL_ID_ALL: 'nationalIdAll',
  TIME_INPUT: 'timeInput',
  HOMESTAY_OVERVIEW: 'homestayOverview',
  PAYMENT: 'payment',
  CANDITATE: 'candidate',
}
