export { NationalRegistryProvider } from '@island.is/application/data-providers'
export { UserProfileProvider } from '@island.is/application/data-providers'
export { PaymentChargeInfoProvider } from './PaymentChargeInfoProvider'
export { DrivingLicenseProvider } from './DrivingLicenseProvider'
export { QualityPhotoProvider } from './QualityPhotoProvider'
export { QualitySignatureProvider } from './QualitySignatureProvider'
export { NationalRegistryCustomProvider } from './NationalRegistryCustomProvider'
