export type NotApplicable = typeof NOT_APPLICABLE
export const NOT_APPLICABLE = 'notApplicable'

export enum EligibleReasonCodes {
  APPLICANT_AGE_OUT_OF_RANGE = 'APPLICANT_AGE_OUT_OF_RANGE',
  BASE_CERT_NOT_FOUND = 'BASE_CERT_NOT_FOUND',
  BASE_CERT_DATE_INVALID = 'BASE_CERT_DATE_INVALID',
  BASE_CERT_OLDER_THAN_7YEARS = 'BASE_CERT_OLDER_THAN_7YEARS',
  BASE_CERT_OLDER_THAN_6MONTHS = 'BASE_CERT_OLDER_THAN_6MONTHS',
}

export enum MedicalAndRehabilitationPaymentsApplicationType {
  SG1 = 'SJUKRAGREIDSLUR_FYRSTA',
  SG2 = 'SJUKRAGREIDSLUR_FRAMHALDS',
  EH1 = 'ENDURHAEFINGARGREIDSLUR_FYRSTA',
  EH2 = 'ENDURHAEFINGARGREIDSLUR_FRAMHALDS',
}

export enum MedicalAndRehabilitationPaymentsConfirmationType {
  BID_EFTIR_URRAEDI = 'BID_EFTIR_URRAEDI',
  ENDURHAEFING = 'ENDURHAEFING',
  HEILSUBRESTUR = 'HEILSUBRESTUR',
  VIDURKENND_MEDFERD = 'VIDURKENND_MEDFERD',
}

export const OTHER = 'ANNAD'
