export const NEW_DELEGATION_TEMPLATE_ID = 'HNIPP.UMBOD.NYTT'
export const UPDATED_DELEGATION_TEMPLATE_ID = 'HNIPP.UMBOD.UPPFAERT'

export const DELEGATION_REQUEST_TEMPLATE_ID = 'HNIPP.UMBOD.BEIDNI'
export const DELEGATION_REQUEST_APPROVED_TEMPLATE_ID =
  'HNIPP.UMBOD.BEIDNI_SAMTHYKKT'
export const DELEGATION_REQUEST_REJECTED_TEMPLATE_ID =
  'HNIPP.UMBOD.BEIDNI_HAFNAD'
