/**
 * Add any shared web components here. This module can be imported like this:
 *
 * import { ... } from '@island.is/web/components'
 *
 * Never import it like this:
 *
 * import { ... } from '../components/real'
 *
 * This is so production builds can better optimize chunks. Read
 * `libs/shared/babel/README.md` for more details.
 */

export * from './Card/Card'
export * from './Header/Header'
export * from './SearchInput/SearchInput'
export * from './LanguageToggler/LanguageToggler'
export * from './Sticky/Sticky'
export * from './Heading/Heading'
export * from './SideMenu/SideMenu'
export * from './StoryList/StoryList'
export * from './ContentLink/ContentLink'
export * from './NewsCard/NewsCard'
export * from './Grants'
export * from './LogoList/LogoList'
export * from './List/List'
export * from './Bullet/Bullet'
export * from './IconBullet/IconBullet'
export * from './BackgroundImage/BackgroundImage'
export * from './BulletList/BulletList'
export * from './SkipToMainContent/SkipToMainContent'
export * from './PageLoader/PageLoader'
export * from './FixedNav/FixedNav'
export * from './SidebarBox/SidebarBox'
export * from './RichText/RichText'
export * from './Section/Section'
export * from './HeadWithSocialSharing/HeadWithSocialSharing'
export * from './TellUsAStory/TellUsAStory'
export * from './ContactUs/ContactUs'
export * from './ChatPanel'
export * from './AnchorNavigation/AnchorNavigation'
export * from './Main/Main'
export * from './Select/Select'
export * from './SubpageMainContent'
export * from './SubpageDetailsContent'
export * from './ServiceInformation'
export * from './ServiceList'
export * from './OpenApiView'
export * from './OpenApiDocumentation'
export * from './InstitutionPanel/InstitutionPanel'
export * from './InstitutionsPanel/InstitutionsPanel'
export * from './Organization/'
export * from './ServiceWeb/'
export * from './Project'
export * from './ApiCatalogueFilter/ApiCatalogueFilter'
export * from './SimpleSlider/SimpleSlider'
export * from './SimpleStackedSlider/SimpleStackedSlider'
export * from './Webreader'
export * from './AppendedArticleComponents/AppendedArticleComponents'
export * from './StatisticsCardsSection/StatisticsCardsSection'
export * from './StatisticsCard/StatisticsCard'
export * from './DataLinkSection/DataLinkSection'
export * from './DataLinkCard/DataLinkCard'
export * from './Charts/index'
export * from './SectionTitle/SectionTitle'
export * from './ExportCSVButton/ExportCSVButton'
export * from './Login/svgLogin'
export * from './Login/LoginTexts.types'
export * from './IconTitleCard/IconTitleCard'
export * from './SearchSection/SearchSection'
export * from './CategoryItems/CategoryItems'
export * from './NewsItems/NewsItems'
export * from './GridItems/GridItems'
export * from './LifeEventsSection/LifeEventsSection'
export * from './Stepper'
export * from './MobileAppBanner/MobileAppBanner'
export * from './Form/Form'
export * from './NewsList/NewsList'
export * from './NewsList/NewsListSidebar'
export * from './connected'
export * from './FilterTag'
export * from './SignLanguageButton/SignLanguageButton'
export * from './Footer/Footer'
export * from './ListViewCard'
export * from './SectionWithVideo'
export * from './events'
export * from './SearchableTagsFilter'
export * from './QueryFilterInput'
export * from './ActionCategoryCard/ActionCategoryCard'
export * from './DefaultHeader'
export * from './BorderAbove/BorderAbove'
export * from './TableOfContents/TableOfContents'
export * from './CardWithFeaturedItems/CardWithFeaturedItems'
export * from './GenericList/GenericList'
export * from './GenericList/LatestGenericListItems/LatestGenericListItems'
export * from './connected/ParentalLeaveCalculator/ParentalLeaveCalculator'
export * from './Organization/OrganizationIslandFooter'
export * from './Organization/Slice/FeaturedLinksSlice/FeaturedLinksSlice'
export * from './FeaturedLinks/FeaturedLinks'
export * from './Organization/Slice/LatestNewsSlice/DigitalIcelandLatestNewsSlice'
export * from './DigitalIcelandNewsCard/DigitalIcelandNewsCard'
export * from './DigitalIcelandNewsCard/DigitalIcelandLatestNewsCard'
export * from './AddToCalendarButton/AddToCalendarButton'
export * from './Organization/Slice/IntroLinkImageSlice/IntroLinkImageSlice'
export * from './GenericList/GenericList'
export * from './WebChat'
