export * from './lib/districtCommissionersLicenses.module'
export { DistrictCommissionersLicensesService } from './lib/districtCommissionersLicenses.service'
export { RettindiFyrirIslandIsApi } from '../gen/fetch'
export { DistrictCommissionersLicensesClientConfig } from './lib/districtCommissionersLicenses.config'
export { DistrictCommissionersLicenseStatus } from './lib/districtCommissionersLicenses.types'
