export * from './lib/districtCommissionersLicenses.module'
export { DistrictCommissionersLicensesService } from './lib/districtCommissionersLicenses.service'
export { RettindiFyrirIslandIsApi } from '../gen/fetch'
export { DistrictCommissionersLicensesClientConfig } from './lib/districtCommissionersLicenses.config'
export { DistrictCommissionersLicenseStatus } from './lib/districtCommissionersLicenses.types'
export { DistrictCommissionersLicenseDto } from './lib/dto/districtCommissionersLicenseDto'
export { DistrictCommissionersLicenseInfoDto } from './lib/dto/districtCommissionersLicenseInfoDto'
