export * from './lib/fishing-license-client.module'
export * from './lib/types'
export { FishingLicenseClientConfig } from './lib/FishingLicenseClientConfig'
export * from './lib/gen/fetch'
export { FishingLicenseService } from './lib/fishing-license-service'
