name: islandis-user-notification
services:
  localstack:
    image: public.ecr.aws/localstack/localstack:3
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
  db_user_notification:
    image: public.ecr.aws/docker/library/postgres:15.3-alpine
    container_name: db_user_notification
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5432:5432
