export const figmaTokens = {
  primitives: {
    modes: {
      mode1: {
        color: {
          primary: {
            blue: {
              100: '#f2f7ff',
              200: '#ccdfff',
              300: '#99c0ff',
              400: '#0061ff',
              600: '#0044b3',
              10070: 'rgba(242, 247, 255, 70)',
            },
            red: {
              100: '#fff2f6',
              200: '#ffccdc',
              300: '#ff99b9',
              400: '#ff0050',
              600: '#b30038',
            },
            dark: {
              100: '#f2f2f5',
              200: '#ccccd8',
              300: '#9999b1',
              350: '#666685',
              400: '#00003c',
            },
            white: {
              400: '#ffffff',
            },
          },
          secondary: {
            blueberry: {
              100: '#f6f6fd',
              200: '#dadbf6',
              300: '#b5b6ec',
              400: '#4649d0',
              600: '#24268e',
            },
            purple: {
              100: '#f8f5fa',
              200: '#e1d5ec',
              300: '#c3abd9',
              400: '#6a2ea0',
              600: '#421c63',
            },
            rose: {
              100: '#faf2f8',
              200: '#ebcce3',
              300: '#d799c7',
              400: '#9a0074',
              600: '#4d003a',
            },
          },
          accent: {
            mint: {
              100: '#f2fefc',
              200: '#ccfaf4',
              300: '#99f4ea',
              400: '#00e4ca',
              600: '#00b39e',
              800: '#005b52',
            },
            yellow: {
              100: '#fffef7',
              200: '#fffce0',
              300: '#fff9c2',
              400: '#fff066',
              600: '#e6cf00',
            },
          },
        },
        font: {
          family: {
            primary: 'IBM Plex Sans',
          },
          weight: {
            semibold: 'Semibold',
            regular: 'Regular',
            light: 'Light',
          },
        },
        spacing: {
          2: 2,
          4: 4,
          8: 8,
          12: 12,
          16: 16,
          20: 20,
          24: 24,
          28: 28,
          32: 32,
          36: 36,
          40: 40,
          44: 44,
          48: 48,
          52: 52,
          56: 56,
          60: 60,
          64: 64,
          68: 68,
          72: 72,
          76: 76,
          80: 80,
          84: 84,
          88: 88,
          92: 92,
          96: 96,
          100: 100,
          104: 104,
          120: 120,
          200: 200,
        },
        radius: {
          xs: 4,
          default: 8,
          md: 12,
          lg: 16,
          full: 9999,
        },
      },
    },
  },
  colorsTokens: {
    modes: {
      lightMode: {
        background: {
          invert: '{color.primary.white.400}',
          brand: '{color.primary.blue.400}',
          brandlighter: '{color.primary.blue.200}',
          brandminimal: '{color.primary.blue.100}',
          brandsecondary: '{color.secondary.purple.400}',
          brandsecondarylighter: '{color.secondary.purple.200}',
          brandsecondaryminimal: '{color.secondary.purple.100}',
        },
        foreground: {
          primary: '{color.primary.dark.400}',
          primaryminimal: '{color.primary.dark.300}',
          brandsecondarycontrast: '{color.secondary.purple.600}',
          brandsecondary: '{color.secondary.purple.400}',
          brand: '{color.primary.blue.400}',
          brandcontrast: '{color.primary.blue.600}',
          invert: '{color.primary.white.400}',
          modal: '{color.primary.dark.400}',
        },
        border: {
          primary: '{color.primary.blue.200}',
          primarycontrast: '{color.primary.blue.400}',
          invert: '{color.primary.white.400}',
          secondaryactive: '{color.secondary.purple.400}',
          secondaryinactive: '{color.secondary.purple.200}',
        },
        interactive: {
          background: {
            primary: '{color.primary.blue.400}',
            primaryminimal: '{color.primary.blue.100}',
            primaryminimalactive: '{color.primary.blue.200}',
            primarydisabled: '{color.primary.blue.300}',
            primaryactive: '{color.secondary.blueberry.400}',
            neutral: '{color.primary.dark.300}',
            neutralactive: '{color.primary.dark.350}',
            focus: '{color.accent.mint.400}',
            invert: '{color.primary.white.400}',
            destructive: '{color.primary.red.600}',
            destructiveactive: '{color.secondary.rose.400}',
            destructivedisabled: '{color.primary.red.300}',
            tooltip: '{color.primary.dark.400}',
            brandsecondaryactive: '{color.secondary.purple.200}',
            brandsecondaryminimal: '{color.secondary.purple.100}',
          },
          foreground: {
            primary: '{color.primary.blue.400}',
            primarycontrast: '{color.primary.blue.600}',
            primaryactive: '{color.secondary.blueberry.400}',
            primarydisabled: '{color.primary.blue.300}',
            brandsecondary: '{color.secondary.purple.400}',
            brandsecondarycontrast: '{color.secondary.purple.600}',
            default: '{color.primary.dark.400}',
            disabled: '{color.primary.dark.300}',
            invert: '{color.primary.white.400}',
            invertactive: '{color.secondary.blueberry.100}',
            red: '{color.primary.red.400}',
            redminimalactive: '{color.primary.red.200}',
            destructive: '{color.primary.red.600}',
            destructiveactive: '{color.secondary.rose.400}',
            destructivedisabled: '{color.primary.red.300}',
          },
          border: {
            borderprimary: '{color.primary.blue.400}',
            borderactive: '{color.secondary.blueberry.400}',
            borderdisabled: '{color.primary.blue.300}',
            borderprimaryminimal: '{color.primary.blue.200}',
            bordersecondaryminimal: '{color.secondary.purple.200}',
            bordersecondary: '{color.secondary.purple.400}',
            focus: '{color.accent.mint.400}',
            active: '{color.primary.dark.400}',
            invert: '{color.primary.white.400}',
            invertactive: '{color.secondary.blueberry.100}',
            destructivedefault: '{color.primary.red.600}',
            destructiveactive: '{color.secondary.rose.400}',
            destructivedisabled: '{color.primary.red.300}',
          },
        },
        feedback: {
          information: {
            backgroundminimal: '{color.primary.blue.100}',
            border: '{color.primary.blue.200}',
            foreground: '{color.primary.blue.400}',
            foregroundcontrast: '{color.primary.blue.600}',
          },
          success: {
            background: '{color.accent.mint.100}',
            foreground: '{color.accent.mint.400}',
            border: '{color.accent.mint.200}',
          },
          warning: {
            background: '{color.accent.yellow.200}',
            foreground: '{color.accent.yellow.600}',
            border: '{color.accent.yellow.400}',
          },
          error: {
            background: '{color.primary.red.100}',
            foreground: '{color.primary.red.400}',
            foregroundcontrast: '{color.primary.red.600}',
            border: '{color.primary.red.200}',
            bordercontrast: '{color.primary.red.600}',
          },
          tags: {
            bluebackground: '{color.primary.blue.100}',
            blueaccent: '{color.primary.blue.400}',
            blueborder: '{color.primary.blue.200}',
            redbackground: '{color.primary.red.100}',
            redaccent: '{color.primary.red.600}',
            redborder: '{color.primary.red.200}',
            purplebackground: '{color.secondary.purple.100}',
            purpleaccent: '{color.secondary.purple.400}',
            purpleborder: '{color.secondary.purple.200}',
            rosebackground: '{color.secondary.rose.100}',
            roseaccent: '{color.secondary.rose.400}',
            roseaccentborder: '{color.secondary.rose.200}',
            blueberrybackground: '{color.secondary.blueberry.100}',
            blueberryaccent: '{color.secondary.blueberry.400}',
            blueberryborder: '{color.secondary.blueberry.200}',
            darkerBluebackground: '{color.primary.blue.200}',
            darkerBlueaccent: '{color.primary.blue.600}',
            darkerBlueborder: '{color.primary.blue.200}',
            mintbackground: '{color.accent.mint.200}',
            mintaccent: '{color.accent.mint.800}',
            mintborder: '{color.accent.mint.200}',
            yellowbackground: '{color.accent.yellow.300}',
            yellowaccent: '{color.primary.dark.400}',
            yellowhover: '{color.accent.yellow.400}',
            yellowborder: '{color.accent.yellow.600}',
          },
        },
        overlay: {
          default: '{color.primary.blue.100-70}',
        },
      },
    },
  },
  typographyTokens: {
    modes: {
      desktop: {
        device: {
          size: 1440,
        },
        heading: {
          h1: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 42,
            lineheight: 52,
          },
          h2: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 34,
            lineheight: 44,
          },
          h3: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 24,
            lineheight: 34,
          },
          h4: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 20,
            lineheight: 30,
          },
          h5: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 18,
            lineheight: 28,
          },
        },
        paragraph: {
          default: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.light}',
            fontsize: 18,
            lineheight: 28,
          },
          large: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.light}',
            fontsize: 24,
            lineheight: 34,
          },
          mediumRegular: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 16,
            lineheight: 26,
          },
          mediumLight: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.light}',
            fontsize: 16,
            lineheight: 26,
          },
          small: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 14,
            lineheight: 24,
          },
        },
        other: {
          eyebrows: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 16,
          },
        },
        table: {
          head: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 16,
            lineheight: 20,
          },
          headSmall: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 18,
          },
          body: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 16,
            lineheight: 20,
          },
          bodyLarge: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 18,
            lineheight: 24,
          },
          bodySmall: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 14,
            lineheight: 18,
          },
          foot: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 16,
            lineheight: 20,
          },
          footSmall: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 18,
          },
        },
      },
      mobile: {
        device: {
          size: 375,
        },
        heading: {
          h1: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 32,
            lineheight: 38,
          },
          h2: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 26,
            lineheight: 32,
          },
          h3: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 20,
            lineheight: 26,
          },
          h4: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 18,
            lineheight: 24,
          },
          h5: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 16,
            lineheight: 20,
          },
        },
        paragraph: {
          default: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.light}',
            fontsize: 16,
            lineheight: 24,
          },
          large: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.light}',
            fontsize: 20,
            lineheight: 28,
          },
          mediumRegular: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 14,
            lineheight: 20,
          },
          mediumLight: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.light}',
            fontsize: 14,
            lineheight: 20,
          },
          small: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 12,
            lineheight: 16,
          },
        },
        other: {
          eyebrows: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 12,
            lineheight: 16,
          },
        },
        table: {
          head: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 18,
          },
          headSmall: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 18,
          },
          body: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 14,
            lineheight: 18,
          },
          bodyLarge: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 16,
            lineheight: 20,
          },
          bodySmall: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.regular}',
            fontsize: 14,
            lineheight: 18,
          },
          foot: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 18,
          },
          footSmall: {
            fontName: '{font.family.primary}',
            fontweight: '{font.weight.semibold}',
            fontsize: 14,
            lineheight: 18,
          },
        },
      },
    },
  },
}
