export { QualityPhoto } from './QualityPhoto/index'
export { Congratulations } from './Done'
export { default as PhotoUpload } from './PhotoUpload'
export { default as Photo } from './Photo'
export { default as Bullets } from './Bullets'
