source "https://rubygems.org"

gem "fastlane", "2.178.0"
gem 'cocoapods', "1.10.1"
gem "xcode-install", "2.5.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)