export { HealthDirectorateClientModule } from './lib/healthDirectorateClient.module'
export { HealthDirectorateHealthModule } from './lib/clients/health/health.module'
export * from './lib/healthDirectorateClient.types'
export * from './lib/clients/occupational-license/gen/fetch'
export {
  HealthDirectorateVaccinationsClientConfig,
  HealthDirectorateHealthClientConfig,
  HealthDirectorateClientConfig,
  HealthDirectorateVaccinationsService,
  HealthDirectorateClientService,
  HealthDirectorateHealthService,
  Locale,
  VaccinationDto,
  DiseaseVaccinationDtoVaccinationStatusEnum,
  PrescribedItemCategory,
  PrescriptionRenewalBlockedReason,
  PrescriptionRenewalStatusDisplay,
  QuestionnaireBaseDto,
  QuestionnaireDetailDto,
  QuestionType,
  QuestionGroupDto,
  BooleanQuestionDto,
  StringQuestionDto,
  DateQuestionDto,
  NumberQuestionDto,
  ListQuestionDto,
  AttachmentQuestionDto,
  TableQuestionDto,
  NumberTriggerDto,
  ListTriggerDto,
  BooleanTriggerDto,
  PrescriptionCommissionDto,
  EuPatientConsentDto,
  EuPatientConsentStatus,
  EuPatientConsentResponseDto,
  ConsentHistoryEntryDto,
  PrescriptionCommissionStatus,
  SubmitQuestionnaireDto,
  CreateEuPatientConsentDto,
} from './lib/clients'
export {
  ConversationAttachmentDto,
  ConversationAttachmentRequestDto,
  ConversationBaseDto,
  ConversationDetailDto,
  ConversationMessageDto,
  ConversationStatusFilter,
  CreateConversationRequestDto,
  CreateReplyRequestDto,
  DispensationHistoryItemDto,
  MessagingRecipientDto,
  UserVisibleAppointmentStatuses,
  OrganDonorDto,
} from './lib/clients/health'
