import {
  ApolloClient,
  HttpLink,
  InMemoryCache,
  type NormalizedCacheObject,
} from '@apollo/client'

import {
  getPublicRuntimeEnv,
  getServerRuntimeEnv,
} from '../environments/runtimeEnvironment'
import possibleTypes from './possibleTypes.json'

const isBrowser = typeof window !== 'undefined'

let apolloClient: ApolloClient<NormalizedCacheObject> | null = null

export const createApolloClient = () =>
  new ApolloClient({
    name: 'contentful-apps-client',
    version: '0.1',
    ssrMode: !isBrowser,
    link: new HttpLink({
      uri: isBrowser
        ? getPublicRuntimeEnv().graphqlEndpoint
        : getServerRuntimeEnv().graphqlEndpoint,
    }),
    /* Generated by codegen.yml alongside schema.ts. Without it, a fragment
     * whose type condition is an interface or union silently fails to match --
     * concrete conditions match on `__typename` alone, so the trap only springs
     * the first time someone writes `... on SomeInterface`. */
    cache: new InMemoryCache({ possibleTypes: possibleTypes.possibleTypes }),
  })

export const initApollo = () => {
  if (!isBrowser) {
    return createApolloClient()
  }
  if (!apolloClient) {
    apolloClient = createApolloClient()
  }
  return apolloClient
}
