type BaseEventType =
  | 'CASE_CREATED'
  | 'CASE_SENT_TO_COURT'
  | 'CASE_RECEIVED_BY_COURT'
  | 'COURT_DATE_SCHEDULED'

export type RequestCaseEventType =
  | BaseEventType
  | 'DEFENDANT_ARRESTED' // not implemented
  | 'COURT_SESSION_STARTED'
  | 'COURT_SESSION_ENDED'
  | 'RESTRICTION_ENDED' // not implemented
  | 'ISOLATION_ENDED' // not implemented
  | 'TRAVEL_BAN_ENDED' // not implemented
  | 'REQUEST_APPEALED'
  | 'REQUEST_COMPLETED'
  | 'COURT_RECORD_SIGNED' // not implemented
  | 'RULING_SIGNED' // not implemented
  | 'REQUEST_EXTENDED'
  | 'CASE_RECEIVED_BY_COURT_OF_APPEALS'
  | 'CASE_COMPLETED_BY_COURT_OF_APPEALS'

export type IndictmentCaseEventType =
  | BaseEventType
  | 'CASE_SUBTYPES_CONFIRMED'
  | 'SUBPOENA_CREATED'
  | 'SUBPOENA_SERVED'
  | 'RULING_DECISION_CONFIRMED'
  | 'INDICTMENT_COMPLETED'
  | 'VERDICT_CREATED' // not implemented
  | 'VERDICT_SERVED'
  | 'INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR'
  | 'INDICTMENT_REVIEWED_BY_PUBLIC_PROSECUTOR'
  | 'CASE_SENT_TO_PRISON_ADMIN'
  | 'CASE_RECEIVED_BY_PRISON_ADMIN'
