export const SHORT_TERM_MIN_DAYS = 1
export const SHORT_TERM_MAX_DAYS = 31
export const LONG_TERM_MIN_DAYS = 32
export const LONG_TERM_MAX_DAYS = 365
export const MS_IN_DAY = 24 * 60 * 60 * 1000
export const FILE_SIZE_LIMIT = 20000000 // 20 MB
export const FILE_TYPES_ALLOWED = '.pdf, .jpg, .jpeg, .png'
export const MAX_CNT_FREIGHT = 10
export const MAX_CNT_CONVOY = 5
export const MAX_CNT_AXLE = 15
