fragment AppointmentDetailFields on HealthDirectorateAppointmentDetail {
  id
  title
  instruction
  date
  duration
  modality
  practitioners
  canCancel
  canCancelBefore
  assignees {
    type
    name
  }
  links {
    type
    url
    activatesAt
    expiresAt
  }
  location {
    __typename
    name
    organization
    address
    department
    wing
    floor
    room
    city
    postalCode
    country
    latitude
    longitude
    link
    locationLinks {
      type
      url
    }
    phoneNumber
    openingHoursText
  }
}

query getAppointmentDetail($id: String!) {
  healthDirectorateAppointment(id: $id) {
    __typename
    ...AppointmentDetailFields
  }
}

mutation cancelAppointment($id: String!) {
  healthDirectorateCancelAppointment(id: $id)
}
