export const ApplicantTypesEnum = {
  INDIVIDUAL: 'INDIVIDUAL',
  INDIVIDUAL_WITH_DELEGATION_FROM_INDIVIDUAL:
    'INDIVIDUAL_WITH_DELEGATION_FROM_INDIVIDUAL',
  INDIVIDUAL_WITH_DELEGATION_FROM_LEGAL_ENTITY:
    'INDIVIDUAL_WITH_DELEGATION_FROM_LEGAL_ENTITY',
  INDIVIDUAL_WITH_PROCURATION: 'INDIVIDUAL_WITH_PROCURATION',
  INDIVIDUAL_GIVING_DELEGATION: 'INDIVIDUAL_GIVING_DELEGATION',
  LEGAL_ENTITY: 'LEGAL_ENTITY',
  LEGAL_ENTITY_OF_PROCURATION_HOLDER: 'LEGAL_ENTITY_OF_PROCURATION_HOLDER',
  LEGAL_GUARDIAN: 'LEGAL_GUARDIAN',
}
