export const ApplicationEvents = {
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  NUDGE_SENT: 'NUDGE_SENT',
  APPLICATION_SENT_TO_ZENDESK: 'APPLICATION_SENT_TO_ZENDESK',
  APPLICATION_RETRIEVED_VIA_API: 'APPLICATION_RETRIEVED_VIA_API',
  FILE_CREATED: 'FILE_CREATED',
  FILE_SENT_TO_ZENDESK: 'FILE_SENT_TO_ZENDESK',
  FILE_RETRIEVED_VIA_API: 'FILE_RETRIEVED_VIA_API',
}
