export const FormStatus = {
  IN_DEVELOPMENT: 'IN_DEVELOPMENT',
  PUBLISHED: 'PUBLISHED',
  UNPUBLISHED: 'UNPUBLISHED',
  UNPUBLISHED_BECAUSE_CHANGED: 'UNPUBLISHED_BECAUSE_CHANGED',
  PUBLISHED_BEING_CHANGED: 'PUBLISHED_BEING_CHANGED',
}
