export const ListTypesEnum = {
  CUSTOM: 'CUSTOM',
  MUNICIPALITIES: 'MUNICIPALITIES',
  COUNTRIES: 'COUNTRIES',
  POSTAL_CODES: 'POSTAL_CODES',
  CURRENCIES: 'CURRENCIES',
  LIST_FROM_URL: 'LIST_FROM_URL',
  ZENDESK_FIELD_OPTIONS: 'ZENDESK_FIELD_OPTIONS',
  ZENDESK_CUSTOM_OBJECT: 'ZENDESK_CUSTOM_OBJECT',
}
