export const ListTypesEnum = {
  CUSTOM: 'CUSTOM',
  MUNICIPALITIES: 'MUNICIPALITIES',
  COUNTRIES: 'COUNTRIES',
  POSTAL_CODES: 'POSTAL_CODES',
  ZENDESK_LIST: 'ZENDESK_LIST',
  LIST_FROM_URL: 'LIST_FROM_URL',
}
