export const ListTypesEnum = {
  CUSTOM: 'CUSTOM',
  MUNICIPALITIES: 'MUNICIPALITIES',
  COUNTRIES: 'COUNTRIES',
  POSTAL_CODES: 'POSTAL_CODES',
  MASTERS_TRADES: 'MASTERS_TRADES', // iðngreinar meistara
  REGISTRATION_CATEGORIES_OF_ACTIVITIES:
    'REGISTRATION_CATEGORIES_OF_ACTIVITIES',
}
