export const CertificationTypesEnum = {
  ESTATE_GUARDIANSHIP_CERTIFICATE_STAMPED:
    'ESTATE_GUARDIANSHIP_CERTIFICATE_STAMPED', // Búsforræðisvottorð
  ESTATE_GUARDIANSHIP_CERTIFICATE_UNSTAMPED:
    'ESTATE_GUARDIANSHIP_CERTIFICATE_UNSTAMPED',
  RESIDENCE_CERTIFICATE: 'RESIDENCE_CERTIFICATE', // Búsetuvottorð
  INDEBTEDNESS_CERTIFICATE: 'INDEBTEDNESS_CERTIFICATE', // Skuldleysisvottorð
  CRIMINAL_RECORD_STAMPED: 'CRIMINAL_RECORD_STAMPED',
  CRIMINAL_RECORD_UNSTAMPED: 'CRIMINAL_RECORD_UNSTAMPED',
}
