export { default as AutomatedTests } from './TestPhase/AutomatedTests'
export { default as TestPhaseInfoScreen } from './TestPhase/InfoScreen'
export { default as TermsOfAgreement } from './DocumentProvicerApplication/TermsOfAgreement'
export { default as Review } from './DocumentProvicerApplication/Review'
export { default as ThankYouScreen } from './DocumentProvicerApplication/ThankYouScreen'
export { default as ThankYouImage } from './ThankYouImage'
