export { default as AutomatedTests } from './TestPhase/AutomatedTests'
export { default as TestPhaseInfoScreen } from './TestPhase/InfoScreen'
export { default as TermsOfAgreement } from './DocumentProvicerApplication/TermsOfAgreement'
export { default as TestEnvironment } from './TestPhase/TestEnvironment'
export { default as TestEndPoint } from './TestPhase/TestEndPoint'
export { default as Review } from './DocumentProvicerApplication/Review'
export { default as ProdEnvironment } from './TestPhase/ProdEnvironment'
