import { TaxCalculatorFieldKind } from '../../models/enums'
import {
  FieldDefinition,
  MAX_SANE_NUMBER_VALUE as MAX_NUMBER,
  parseBoolean,
  parseNumber,
  parsePercentageToRatio,
} from '../../utils/parsing'
import { currentYearIncomeYearOptions } from '../../utils/fieldOptions'

export const withholdingTaxFields: FieldDefinition[] = [
  {
    key: 'paymentFrequency',
    rawKey: 'launGreidast',
    label: 'Greiðslutíðni launa',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    options: [
      { value: 'false', label: 'Vikulega' },
      { value: 'true', label: 'Mánaðarlega' },
    ],
    parse: parseBoolean,
  },
  {
    key: 'maritalStatus',
    rawKey: 'hjuskaparstada',
    label: 'Hjúskaparstaða',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    options: [
      { value: '1', label: 'Einhleypingur' },
      { value: '2', label: 'Einstætt foreldri' },
      { value: '3', label: 'Hjón/Sambúð' },
    ],
    parse: parseNumber,
  },
  {
    key: 'incomeYear',
    rawKey: 'tekjuar',
    label: 'Tekjuár',
    kind: TaxCalculatorFieldKind.SELECT,
    required: true,
    options: currentYearIncomeYearOptions,
    parse: parseNumber,
  },
  {
    key: 'payMonth',
    rawKey: 'launamanudur',
    label: 'Launamánuður',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    min: 1,
    max: 12,
    parse: parseNumber,
  },
  {
    key: 'salary',
    rawKey: 'laun',
    label: 'Heildarlaun mánaðar',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: true,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
  {
    key: 'pensionFundRatio',
    rawKey: 'lifeyrissjodurHlutfall',
    label: 'Í lífeyrissjóð',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    unit: '%',
    // 4% is the statutory minimum employee contribution to a pension fund.
    options: [{ value: '4', label: '4%' }],
    parse: parsePercentageToRatio,
  },
  {
    key: 'privatePensionRatio',
    rawKey: 'sereignHlutfall',
    label: 'Í séreignarsjóð',
    kind: TaxCalculatorFieldKind.SELECT,
    required: false,
    unit: '%',
    // Voluntary private pension savings are commonly 0% (opt out), 2%, or 4%.
    options: [
      { value: '0', label: '0%' },
      { value: '2', label: '2%' },
      { value: '4', label: '4%' },
    ],
    parse: parsePercentageToRatio,
  },
  {
    key: 'taxCardUtilization',
    rawKey: 'nytingSkattkorts',
    label: 'Nýting eigin afsláttar',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: '%',
    min: 0,
    max: 100,
    parse: parsePercentageToRatio,
  },
  {
    key: 'spouseTaxCardUtilization',
    rawKey: 'nytingSkattkortsMaka',
    label: 'Nýting afsláttar maka',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: '%',
    min: 0,
    max: 100,
    parse: parsePercentageToRatio,
  },
  {
    key: 'accumulatedPersonalTaxCredit',
    rawKey: 'uppsafnadurPersonuafslattur',
    label: 'Uppsafnaður afsláttur',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
  {
    key: 'vacationPay',
    rawKey: 'orlof',
    label: 'Orlof',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
  {
    key: 'unionDues',
    rawKey: 'stettarfelag',
    label: 'Gjöld f. stéttarfélag',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
  {
    key: 'otherDeduction',
    rawKey: 'annad',
    label: 'Annar frádráttur',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
  {
    key: 'employerPensionMatchRatio',
    rawKey: 'motframlagLifeyrissjodur',
    label: 'Mótframlag í lífeyrissjóð',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: '%',
    min: 0,
    max: 100,
    parse: parsePercentageToRatio,
  },
  {
    key: 'vehicleAllowance',
    rawKey: 'okutaekjastyrkurUtan',
    label: 'Ökutækjastyrkur utan staðgreiðslu',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
  {
    key: 'seamenAccidentInsurancePremium',
    rawKey: 'idgjaldSlysatryggingSjomanna',
    label: 'Iðgjald slysatryggingar sjómanna',
    kind: TaxCalculatorFieldKind.NUMBER,
    required: false,
    unit: 'ISK',
    min: 0,
    max: MAX_NUMBER,
    parse: parseNumber,
  },
]
