export { StudentTranscriptApi as HIApi } from './gen/fetch'
export { StudentTrack as HIStudentTrack } from './gen/fetch'
export { StudentTrackInstitution as HIStudentTrackInstitution } from './gen/fetch'
export { NemandiGetLocaleEnum as HILocale } from './gen/fetch'
export { NemandiFerillFerillFileTranscriptGetLocaleEnum as HITranscriptLocale } from './gen/fetch'
export { NemandiFerillFerillGetLocaleEnum as HIFerillLocale } from './gen/fetch'
export * from './universityOfIcelandCareerClient.config'
