name: Unicorn CI/CD pipeline

on:
  pull_request:
defaults:
  run:
    shell: bash
env:
  RUNS_ON_BUCKET_NAME: ${{ vars.RUNS_ON_BUCKET_NAME }}
  AWS_REGION: eu-west-1
  YARN_ENABLE_HARDENED_MODE: '0'

jobs:
  debug:
    name: Debug
    runs-on: arc-shared
    timeout-minutes: 10
    steps:
      - name: Send slack message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "A new PR has been createdon behalf of ${{ github.actor }}
