name: PR close

on:
  push:
    branches:
      - feature/unicorn-debug
defaults:
  run:
    shell: bash
env:
  AWS_REGION: eu-west-1
  YARN_ENABLE_HARDENED_MODE: '0'

jobs:
  check-unicorn:
    name: Is this a unicorn PR
    runs-on: arc-shared
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup yarn
        uses: ./.github/actions/setup-yarn

      - name: Derive appropriate SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Debug HEAD/BASE
        run: |
          echo "BASE: $NX_BASE"
          echo "HEAD: $NX_HEAD"

      - name: Check unicorn affected
        id: unicorn_affected
        run: |
          echo "Comparing nx affected for \"${NX_HEAD}\" using \"${NX_BASE}\" as base branch"
          echo "IS_UNICORN=$(node scripts/ci/unicorn-utils.mjs is-unicorn "{\"head\": \"${NX_HEAD}\", \"base\": \"${NX_BASE}\" }")" >> "$GITHUB_OUTPUT"

      - name: Results
        run: |
          echo "Unicorn = ${{ steps.unicorn_affected.outputs.IS_UNICORN }}"

      - name: Find Latest Release Branch
        if: ${{ steps.unicorn_affected.outputs.IS_UNICORN == 'true' }}
        id: get_latest_release
        run: |
          echo $(git branch -r)
          LATEST_RELEASE="$(node scripts/ci/get-last-release.mjs "$(git branch -r)")"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> "$GITHUB_OUTPUT"

      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.LATEST_RELEASE }}'"
