name: Pre-release created

on:
  push:
    branches:
      - 'pre-release/**'

jobs:
  build-deploy:
    runs-on: arc-shared
    env:
      GIT_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Get GitHub App token
        id: get-token
        uses: ./.github/actions/get-github-token
        with:
          app-id: ${{ secrets.ISLAND_IS_APP_ID }}
          private-key: ${{ secrets.ISLAND_IS_PRIVATE_KEY }}

      - name: Dispatch push.yml on new pre-release branch
        run: |
          echo "New pre-release branch created: $GIT_BRANCH"
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.get-token.outputs.token }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/push.yml/dispatches \
            -d "{\"ref\":\"$GIT_BRANCH\"}"
