name: Release branch Rename Monitor
on:
  push:
    branches:
      - 'release/*' # Triggers when pushing to this branch

concurrency:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
  # We want feature modifications to happen sequentially to completion,
  # to avoid race conditions and orphaned deployments
  group: push-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

env:
  RUNS_ON_BUCKET_NAME: ${{ vars.RUNS_ON_BUCKET_NAME }}

jobs:
  check-rename:
    runs-on: shared-arc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history

      - name: Check if branch was renamed
        id: check
        run: |
          # Extract version from current branch (release/X.X.X)
          CURRENT_BRANCH="${{ github.ref_name }}"
          VERSION=$(echo "$CURRENT_BRANCH" | sed 's/release\///')
          PRE_RELEASE_BRANCH="pre-release/$VERSION"

          # Check if corresponding pre-release branch existed
          if git show-ref --verify --quiet "refs/remotes/origin/$PRE_RELEASE_BRANCH"; then
            echo "Branch renamed from $PRE_RELEASE_BRANCH to $CURRENT_BRANCH"
            echo "Version: $VERSION"
            # Your workflow logic here
            echo "renamed=true" >> "$GITHUB_OUTPUT"
            echo "version=$PRE_RELEASE_BRANCH" >> "$GITHUB_OUTPUT"
          else
            echo "No corresponding pre-release branch found"
          fi

      - name: Check if already processed
        if: steps.check.outputs.renamed == 'true'
        uses: actions/cache@v4
        id: cache
        with:
          path: .rename-marker
          key: rename-${{ steps.check.outputs.version }}

      - name: Setup yarn
        if: steps.check.outputs.renamed == 'true' && steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-yarn

      - name: Generate feature name
        if: steps.check.outputs.renamed == 'true' && steps.cache.outputs.cache-hit != 'true'
        id: git-feature-name
        run: |
          set -euo pipefail

          GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF/refs\/heads\//}}"
          GIT_BRANCH_DEPLOY="$GIT_BRANCH"
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            if [[ ! ("$GIT_BRANCH_DEPLOY" =~ "feature/") ]]; then
              # If event is pull request but branch is not prefixed with feature/
              GIT_BRANCH_DEPLOY="feature/$GIT_BRANCH_DEPLOY"
            fi
            # Avoid too long resource names
            GIT_BRANCH_DEPLOY="${GIT_BRANCH_DEPLOY:0:50}"
          fi

          FEATURE_NAME="$(echo "$GIT_BRANCH_DEPLOY" | cut -d"/" -f2- | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]' | cut -c1-50)"
          echo "FEATURE_NAME=$FEATURE_NAME" >> "$GITHUB_OUTPUT"

      - name: Get token
        if: steps.check.outputs.renamed == 'true' && steps.cache.outputs.cache-hit != 'true'
        id: get-token
        shell: bash
        env:
          APP_ID: ${{ secrets.HELM_VALUES_APP_ID }}
          PRIVATE_KEY: ${{ secrets.HELM_VALUES_SSH_KEY }}
        run: |
          node scripts/ci/docker/get-github-token.mjs

      - name: Prepare feature deployment tag
        if: steps.check.outputs.renamed == 'true' && steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/feature-checkout
        id: prepare-docker-tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_BUILD_ISSUES_REPORTING_WEBHOOK_URL }}

      - name: Dispatch workflow to helm-values repository
        if: steps.check.outputs.renamed == 'true' && steps.cache.outputs.cache-hit != 'true'
        env:
          HELM_VALUES_TOKEN: ${{ steps.get-token.outputs.token }}
          FEATURE_NAME: ${{ steps.git-feature-name.outputs.FEATURE_NAME }}
        run: |
          repo_owner="island-is"
          repository="helm-values"
          echo "Dispatch workflow for feature name: $FEATURE_NAME"
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $HELM_VALUES_TOKEN" \
          "https://api.github.com/repos/$repo_owner/$repository/dispatches" \
          -d "{\"event_type\":\"destroy-feature\", \"client_payload\":{ \"feature_name\":\"$FEATURE_NAME\", \"delete_value_files\": false }}"

          echo "processed" > .rename-marker/done

      - name: Save cache
        if: steps.check.outputs.renamed == 'true' && steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .rename-marker
          key: rename-${{ steps.check.outputs.version }}
