on:
  pull_request: {}

jobs:
  test:
    runs-on: arc-shared 
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Yarn
        env:
            DIRTYBOT_KEY: ${{ secrets.ISLAND_IS_SSH_KEY }}
            DIRTYBOT_APP_ID: ${{ secrets.ISLAND_IS_APP_KEY }}
        run: |
          corepack enable 
          yarn
          echo "hehe" > bull
          node scripts/ci/docker/git-check-dirty.mjs "." "bull" "dirtybot"

