export enum StringType {
  POSTPONED_INDEFINITELY_EXPLANATION = 'POSTPONED_INDEFINITELY_EXPLANATION',
  CIVIL_DEMANDS = 'CIVIL_DEMANDS',
  PENALTIES = 'PENALTIES',
}

export const stringTypes = Object.values(StringType)
