export enum StringType {
  POSTPONED_INDEFINITELY_EXPLANATION = 'POSTPONED_INDEFINITELY_EXPLANATION',
  CIVIL_DEMANDS = 'CIVIL_DEMANDS',
  PENALTIES = 'PENALTIES',
  REOPEN_REASON = 'REOPEN_REASON',
}

export const stringTypes = Object.values(StringType)
