export enum EventType {
  APPEAL_RESULT_ACCESSED = 'APPEAL_RESULT_ACCESSED',
  LOGIN = 'LOGIN',
  LOGIN_UNAUTHORIZED = 'LOGIN_UNAUTHORIZED',
  LOGIN_BYPASS = 'LOGIN_BYPASS',
  LOGIN_BYPASS_UNAUTHORIZED = 'LOGIN_BYPASS_UNAUTHORIZED',
  INDICTMENT_CONFIRMED = 'INDICTMENT_CONFIRMED',
  INDICTMENT_COMPLETED = 'INDICTMENT_COMPLETED',
  INDICTMENT_REVIEWED = 'INDICTMENT_REVIEWED',
  CASE_SENT_TO_COURT = 'CASE_SENT_TO_COURT',
  CASE_RECEIVED_BY_COURT = 'CASE_RECEIVED_BY_COURT',
  INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR = 'INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR',
  INDICTMENT_CRIMINAL_RECORD_UPDATED_BY_COURT = 'INDICTMENT_CRIMINAL_RECORD_UPDATED_BY_COURT',
  COURT_DATE_SCHEDULED = 'COURT_DATE_SCHEDULED',
}

export const eventTypes = Object.values(EventType)

export enum DefendantEventType {
  SENT_TO_PRISON_ADMIN = 'SENT_TO_PRISON_ADMIN',
  OPENED_BY_PRISON_ADMIN = 'OPENED_BY_PRISON_ADMIN',
}

export const defendantEventTypes = Object.values(DefendantEventType)
