export enum EventType {
  APPEAL_RESULT_ACCESSED = 'APPEAL_RESULT_ACCESSED',
  LOGIN = 'LOGIN',
  LOGIN_UNAUTHORIZED = 'LOGIN_UNAUTHORIZED',
  LOGIN_BYPASS = 'LOGIN_BYPASS',
  LOGIN_BYPASS_UNAUTHORIZED = 'LOGIN_BYPASS_UNAUTHORIZED',
  // This is when the indictment is confirmed by prosecution and sent to court.
  INDICTMENT_CONFIRMED = 'INDICTMENT_CONFIRMED',
  // Only used for the stamp on the ruling, not for calculating deadlines.
  INDICTMENT_COMPLETED = 'INDICTMENT_COMPLETED',
  CASE_SENT_TO_COURT = 'CASE_SENT_TO_COURT',
  CASE_RECEIVED_BY_COURT = 'CASE_RECEIVED_BY_COURT',
  INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR = 'INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR',
  INDICTMENT_CRIMINAL_RECORD_UPDATED_BY_COURT = 'INDICTMENT_CRIMINAL_RECORD_UPDATED_BY_COURT',
  COURT_DATE_SCHEDULED = 'COURT_DATE_SCHEDULED',
  REQUEST_COMPLETED = 'REQUEST_COMPLETED', // Request case is completed
  INDICTMENT_SPLIT_COMPLETED = 'INDICTMENT_SPLIT_COMPLETED',
}

export const eventTypes = Object.values(EventType)

export enum DefendantEventType {
  SENT_TO_PRISON_ADMIN = 'SENT_TO_PRISON_ADMIN',
  OPENED_BY_PRISON_ADMIN = 'OPENED_BY_PRISON_ADMIN',
  VERDICT_SERVICE_CERTIFICATE_DELIVERED_TO_POLICE = 'VERDICT_SERVICE_CERTIFICATE_DELIVERED_TO_POLICE',
  VERDICT_DELIVERED_TO_NATIONAL_COMMISSIONERS_OFFICE = 'VERDICT_DELIVERED_TO_NATIONAL_COMMISSIONERS_OFFICE',
  INDICTMENT_REVIEWED = 'INDICTMENT_REVIEWED',
  PUBLIC_PROSECUTOR_REGISTERED_IN_POLICE_SYSTEM = 'PUBLIC_PROSECUTOR_REGISTERED_IN_POLICE_SYSTEM',
}

export const defendantEventTypes = Object.values(DefendantEventType)
