export enum EventType {
  APPEAL_RESULT_ACCESSED = 'APPEAL_RESULT_ACCESSED',
  LOGIN = 'LOGIN',
  LOGIN_UNAUTHORIZED = 'LOGIN_UNAUTHORIZED',
  LOGIN_BYPASS = 'LOGIN_BYPASS',
  LOGIN_BYPASS_UNAUTHORIZED = 'LOGIN_BYPASS_UNAUTHORIZED',
  INDICTMENT_CONFIRMED = 'INDICTMENT_CONFIRMED',
  CASE_RECEIVED_BY_COURT = 'CASE_RECEIVED_BY_COURT',
}
