export enum CaseFileState {
  STORED_IN_RVG = 'STORED_IN_RVG',
  STORED_IN_COURT = 'STORED_IN_COURT',
  DELETED = 'DELETED',
}

export enum CaseFileCategory {
  COURT_RECORD = 'COURT_RECORD',
  RULING = 'RULING',
  COVER_LETTER = 'COVER_LETTER',
  INDICTMENT = 'INDICTMENT',
  CRIMINAL_RECORD = 'CRIMINAL_RECORD',
  COST_BREAKDOWN = 'COST_BREAKDOWN',
  CASE_FILE = 'CASE_FILE',
  PROSECUTOR_APPEAL_BRIEF = 'PROSECUTOR_APPEAL_BRIEF',
  DEFENDANT_APPEAL_BRIEF = 'DEFENDANT_APPEAL_BRIEF',
  PROSECUTOR_APPEAL_BRIEF_CASE_FILE = 'PROSECUTOR_APPEAL_BRIEF_CASE_FILE',
  DEFENDANT_APPEAL_BRIEF_CASE_FILE = 'DEFENDANT_APPEAL_BRIEF_CASE_FILE',
  PROSECUTOR_APPEAL_STATEMENT = 'PROSECUTOR_APPEAL_STATEMENT',
  DEFENDANT_APPEAL_STATEMENT = 'DEFENDANT_APPEAL_STATEMENT',
  PROSECUTOR_APPEAL_STATEMENT_CASE_FILE = 'PROSECUTOR_APPEAL_STATEMENT_CASE_FILE',
  DEFENDANT_APPEAL_STATEMENT_CASE_FILE = 'DEFENDANT_APPEAL_STATEMENT_CASE_FILE',
  APPEAL_RULING = 'APPEAL_RULING',
  PROSECUTOR_APPEAL_CASE_FILE = 'PROSECUTOR_APPEAL_CASE_FILE',
  DEFENDANT_APPEAL_CASE_FILE = 'DEFENDANT_APPEAL_CASE_FILE',
}
