export enum TrackedNotificationType {
  ADVOCATE_ASSIGNED = 'ADVOCATE_ASSIGNED',
  APPEAL_CASE_FILES_UPDATED = 'APPEAL_CASE_FILES_UPDATED',
  APPEAL_COMPLETED = 'APPEAL_COMPLETED',
  APPEAL_JUDGES_ASSIGNED = 'APPEAL_JUDGES_ASSIGNED',
  APPEAL_RECEIVED_BY_COURT = 'APPEAL_RECEIVED_BY_COURT',
  APPEAL_STATEMENT = 'APPEAL_STATEMENT',
  APPEAL_TO_COURT_OF_APPEALS = 'APPEAL_TO_COURT_OF_APPEALS',
  APPEAL_WITHDRAWN = 'APPEAL_WITHDRAWN',
  CASE_FILES_UPDATED = 'CASE_FILES_UPDATED',
  COURT_DATE = 'COURT_DATE',
  CRIMINAL_RECORD_FILES_UPLOADED = 'CRIMINAL_RECORD_FILES_UPLOADED',
  DEFENDANT_DELEGATED_DEFENDER_CHOICE = 'DEFENDANT_DELEGATED_DEFENDER_CHOICE',
  DEFENDANT_SELECTED_DEFENDER = 'DEFENDANT_SELECTED_DEFENDER',
  DEFENDANTS_NOT_UPDATED_AT_COURT = 'DEFENDANTS_NOT_UPDATED_AT_COURT',
  DEFENDER_ASSIGNED = 'DEFENDER_ASSIGNED',
  DEFENDER_COURT_DATE_FOLLOW_UP = 'DEFENDER_COURT_DATE_FOLLOW_UP',
  DISTRICT_COURT_JUDGE_ASSIGNED = 'DISTRICT_COURT_JUDGE_ASSIGNED',
  DISTRICT_COURT_REGISTRAR_ASSIGNED = 'DISTRICT_COURT_REGISTRAR_ASSIGNED',
  DRIVING_LICENSE_SUSPENSION = 'DRIVING_LICENSE_SUSPENSION',
  HEADS_UP = 'HEADS_UP',
  INDICTMENT_DENIED = 'INDICTMENT_DENIED',
  INDICTMENT_SENT_TO_PRISON_ADMIN = 'INDICTMENT_SENT_TO_PRISON_ADMIN',
  INDICTMENT_SPLIT_COMPLETED = 'INDICTMENT_SPLIT_COMPLETED',
  INDICTMENT_VERDICT_INFO = 'INDICTMENT_VERDICT_INFO',
  INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN = 'INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN',
  MODIFIED = 'MODIFIED',
  PUBLIC_PROSECUTOR_REVIEWER_ASSIGNED = 'PUBLIC_PROSECUTOR_REVIEWER_ASSIGNED',
  READY_FOR_COURT = 'READY_FOR_COURT',
  RECEIVED_BY_COURT = 'RECEIVED_BY_COURT',
  REVOKED = 'REVOKED',
  RULING = 'RULING',
  RULING_ORDER_ADDED = 'RULING_ORDER_ADDED',
  SERVICE_FAILED = 'SERVICE_FAILED',
  SERVICE_SUCCESSFUL = 'SERVICE_SUCCESSFUL',
  SPOKESPERSON_ASSIGNED = 'SPOKESPERSON_ASSIGNED',
}
export enum RequestCaseNotificationType {
  ADVOCATE_ASSIGNED = TrackedNotificationType.ADVOCATE_ASSIGNED,
  CASE_FILES_UPDATED = TrackedNotificationType.CASE_FILES_UPDATED,
  COURT_DATE = TrackedNotificationType.COURT_DATE,
  DEFENDANTS_NOT_UPDATED_AT_COURT = TrackedNotificationType.DEFENDANTS_NOT_UPDATED_AT_COURT,
  HEADS_UP = TrackedNotificationType.HEADS_UP,
  MODIFIED = TrackedNotificationType.MODIFIED,
  READY_FOR_COURT = TrackedNotificationType.READY_FOR_COURT,
  RECEIVED_BY_COURT = TrackedNotificationType.RECEIVED_BY_COURT,
  REVOKED = TrackedNotificationType.REVOKED,
  RULING = TrackedNotificationType.RULING,
}

export enum IndictmentCaseNotificationType {
  COURT_DATE = TrackedNotificationType.COURT_DATE,
  CRIMINAL_RECORD_FILES_UPLOADED = TrackedNotificationType.CRIMINAL_RECORD_FILES_UPLOADED,
  DISTRICT_COURT_JUDGE_ASSIGNED = TrackedNotificationType.DISTRICT_COURT_JUDGE_ASSIGNED,
  DISTRICT_COURT_REGISTRAR_ASSIGNED = TrackedNotificationType.DISTRICT_COURT_REGISTRAR_ASSIGNED,
  DRIVING_LICENSE_SUSPENSION = TrackedNotificationType.DRIVING_LICENSE_SUSPENSION,
  INDICTMENT_DENIED = TrackedNotificationType.INDICTMENT_DENIED,
  INDICTMENT_SPLIT_COMPLETED = TrackedNotificationType.INDICTMENT_SPLIT_COMPLETED,
  INDICTMENT_VERDICT_INFO = TrackedNotificationType.INDICTMENT_VERDICT_INFO,
  PUBLIC_PROSECUTOR_REVIEWER_ASSIGNED = TrackedNotificationType.PUBLIC_PROSECUTOR_REVIEWER_ASSIGNED,
  RULING_ORDER_ADDED = TrackedNotificationType.RULING_ORDER_ADDED,
}

export enum AppealCaseNotificationType {
  APPEAL_CASE_FILES_UPDATED = TrackedNotificationType.APPEAL_CASE_FILES_UPDATED,
  APPEAL_COMPLETED = TrackedNotificationType.APPEAL_COMPLETED,
  APPEAL_JUDGES_ASSIGNED = TrackedNotificationType.APPEAL_JUDGES_ASSIGNED,
  APPEAL_RECEIVED_BY_COURT = TrackedNotificationType.APPEAL_RECEIVED_BY_COURT,
  APPEAL_STATEMENT = TrackedNotificationType.APPEAL_STATEMENT,
  APPEAL_TO_COURT_OF_APPEALS = TrackedNotificationType.APPEAL_TO_COURT_OF_APPEALS,
  APPEAL_WITHDRAWN = TrackedNotificationType.APPEAL_WITHDRAWN,
}

export enum DefendantNotificationType {
  DEFENDANT_DELEGATED_DEFENDER_CHOICE = TrackedNotificationType.DEFENDANT_DELEGATED_DEFENDER_CHOICE,
  DEFENDANT_SELECTED_DEFENDER = TrackedNotificationType.DEFENDANT_SELECTED_DEFENDER,
  DEFENDER_ASSIGNED = TrackedNotificationType.DEFENDER_ASSIGNED,
  // court date is sometimes scheduled before defender is assigned, thus we send them notification to follow-up with court date session
  DEFENDER_COURT_DATE_FOLLOW_UP = TrackedNotificationType.DEFENDER_COURT_DATE_FOLLOW_UP,
  INDICTMENT_SENT_TO_PRISON_ADMIN = TrackedNotificationType.INDICTMENT_SENT_TO_PRISON_ADMIN,
  INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN = TrackedNotificationType.INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN,
}

export enum CivilClaimantNotificationType {
  SPOKESPERSON_ASSIGNED = TrackedNotificationType.SPOKESPERSON_ASSIGNED,
}

export enum SubpoenaNotificationType {
  SERVICE_FAILED = TrackedNotificationType.SERVICE_FAILED,
  SERVICE_SUCCESSFUL = TrackedNotificationType.SERVICE_SUCCESSFUL,
}

export enum InstitutionNotificationType {
  INDICTMENTS_WAITING_FOR_CONFIRMATION = 'INDICTMENTS_WAITING_FOR_CONFIRMATION',
  PUBLIC_PROSECUTOR_VERDICT_APPEAL_DEADLINE_REMINDER = 'PUBLIC_PROSECUTOR_VERDICT_APPEAL_DEADLINE_REMINDER',
}

export enum EventNotificationType {
  COURT_DATE_SCHEDULED = 'COURT_DATE_SCHEDULED',
  INDICTMENT_CRIMINAL_RECORD_UPDATED_BY_COURT = 'INDICTMENT_CRIMINAL_RECORD_UPDATED_BY_COURT',
  INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR = 'INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR',
}

export const trackedNotificationTypes = Object.values(TrackedNotificationType)

export enum NotificationDispatchType {
  INDICTMENTS_WAITING_FOR_CONFIRMATION = InstitutionNotificationType.INDICTMENTS_WAITING_FOR_CONFIRMATION,
  PUBLIC_PROSECUTOR_VERDICT_APPEAL_DEADLINE_REMINDER = InstitutionNotificationType.PUBLIC_PROSECUTOR_VERDICT_APPEAL_DEADLINE_REMINDER,
}
