export enum CaseNotificationType {
  HEADS_UP = 'HEADS_UP',
  READY_FOR_COURT = 'READY_FOR_COURT',
  RECEIVED_BY_COURT = 'RECEIVED_BY_COURT',
  COURT_DATE = 'COURT_DATE',
  DISTRICT_COURT_JUDGE_ASSIGNED = 'DISTRICT_COURT_JUDGE_ASSIGNED',
  DISTRICT_COURT_REGISTRAR_ASSIGNED = 'DISTRICT_COURT_REGISTRAR_ASSIGNED',
  RULING = 'RULING',
  MODIFIED = 'MODIFIED',
  REVOKED = 'REVOKED',
  ADVOCATE_ASSIGNED = 'ADVOCATE_ASSIGNED', // Will be removed
  DEFENDANTS_NOT_UPDATED_AT_COURT = 'DEFENDANTS_NOT_UPDATED_AT_COURT',
  APPEAL_TO_COURT_OF_APPEALS = 'APPEAL_TO_COURT_OF_APPEALS',
  APPEAL_RECEIVED_BY_COURT = 'APPEAL_RECEIVED_BY_COURT',
  APPEAL_STATEMENT = 'APPEAL_STATEMENT',
  APPEAL_COMPLETED = 'APPEAL_COMPLETED',
  APPEAL_JUDGES_ASSIGNED = 'APPEAL_JUDGES_ASSIGNED',
  APPEAL_CASE_FILES_UPDATED = 'APPEAL_CASE_FILES_UPDATED',
  APPEAL_WITHDRAWN = 'APPEAL_WITHDRAWN',
  INDICTMENT_DENIED = 'INDICTMENT_DENIED',
  INDICTMENT_RETURNED = 'INDICTMENT_RETURNED',
  CASE_FILES_UPDATED = 'CASE_FILES_UPDATED',
}

export enum IndictmentCaseNotificationType {
  INDICTMENT_VERDICT_INFO = 'INDICTMENT_VERDICT_INFO',
  CRIMINAL_RECORD_FILES_UPLOADED = 'CRIMINAL_RECORD_FILES_UPLOADED',
}

export enum DefendantNotificationType {
  DEFENDANT_SELECTED_DEFENDER = 'DEFENDANT_SELECTED_DEFENDER',
  DEFENDANT_DELEGATED_DEFENDER_CHOICE = 'DEFENDANT_DELEGATED_DEFENDER_CHOICE',
  DEFENDER_ASSIGNED = 'DEFENDER_ASSIGNED',
  INDICTMENT_SENT_TO_PRISON_ADMIN = 'INDICTMENT_SENT_TO_PRISON_ADMIN',
  INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN = 'INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN',
}

export enum SubpoenaNotificationType {
  SERVICE_SUCCESSFUL = 'SERVICE_SUCCESSFUL',
  SERVICE_FAILED = 'SERVICE_FAILED',
}

export enum CivilClaimantNotificationType {
  SPOKESPERSON_ASSIGNED = 'SPOKESPERSON_ASSIGNED',
}

export enum InstitutionNotificationType {
  INDICTMENTS_WAITING_FOR_CONFIRMATION = 'INDICTMENTS_WAITING_FOR_CONFIRMATION',
}

export enum EventNotificationType {
  INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR = 'INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR',
}

export enum NotificationType {
  ADVOCATE_ASSIGNED = CaseNotificationType.ADVOCATE_ASSIGNED,
  APPEAL_CASE_FILES_UPDATED = CaseNotificationType.APPEAL_CASE_FILES_UPDATED,
  APPEAL_COMPLETED = CaseNotificationType.APPEAL_COMPLETED,
  APPEAL_JUDGES_ASSIGNED = CaseNotificationType.APPEAL_JUDGES_ASSIGNED,
  APPEAL_RECEIVED_BY_COURT = CaseNotificationType.APPEAL_RECEIVED_BY_COURT,
  APPEAL_STATEMENT = CaseNotificationType.APPEAL_STATEMENT,
  APPEAL_TO_COURT_OF_APPEALS = CaseNotificationType.APPEAL_TO_COURT_OF_APPEALS,
  APPEAL_WITHDRAWN = CaseNotificationType.APPEAL_WITHDRAWN,
  CASE_FILES_UPDATED = CaseNotificationType.CASE_FILES_UPDATED,
  COURT_DATE = CaseNotificationType.COURT_DATE,
  DEFENDANT_SELECTED_DEFENDER = DefendantNotificationType.DEFENDANT_SELECTED_DEFENDER,
  DEFENDANTS_NOT_UPDATED_AT_COURT = CaseNotificationType.DEFENDANTS_NOT_UPDATED_AT_COURT,
  DEFENDER_ASSIGNED = DefendantNotificationType.DEFENDER_ASSIGNED,
  HEADS_UP = CaseNotificationType.HEADS_UP,
  INDICTMENT_DENIED = CaseNotificationType.INDICTMENT_DENIED,
  INDICTMENT_RETURNED = CaseNotificationType.INDICTMENT_RETURNED,
  INDICTMENT_SENT_TO_PRISON_ADMIN = DefendantNotificationType.INDICTMENT_SENT_TO_PRISON_ADMIN,
  INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR = EventNotificationType.INDICTMENT_SENT_TO_PUBLIC_PROSECUTOR,
  INDICTMENT_VERDICT_INFO = IndictmentCaseNotificationType.INDICTMENT_VERDICT_INFO,
  INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN = DefendantNotificationType.INDICTMENT_WITHDRAWN_FROM_PRISON_ADMIN,
  INDICTMENTS_WAITING_FOR_CONFIRMATION = InstitutionNotificationType.INDICTMENTS_WAITING_FOR_CONFIRMATION,
  MODIFIED = CaseNotificationType.MODIFIED,
  READY_FOR_COURT = CaseNotificationType.READY_FOR_COURT,
  RECEIVED_BY_COURT = CaseNotificationType.RECEIVED_BY_COURT,
  REVOKED = CaseNotificationType.REVOKED,
  RULING = CaseNotificationType.RULING,
  SERVICE_FAILED = SubpoenaNotificationType.SERVICE_FAILED,
  SERVICE_SUCCESSFUL = SubpoenaNotificationType.SERVICE_SUCCESSFUL,
  SPOKESPERSON_ASSIGNED = CivilClaimantNotificationType.SPOKESPERSON_ASSIGNED,
}

export const notificationTypes = Object.values(NotificationType)

export enum NotificationDispatchType {
  INDICTMENTS_WAITING_FOR_CONFIRMATION = InstitutionNotificationType.INDICTMENTS_WAITING_FOR_CONFIRMATION,
}
