name: 'Setup yarn'
description: 'Yarn setup and install dependencies'
inputs:
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable

    - name: Check node version
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -euo pipefail
        node -v
        yarn --version
        ls -l "$(which node)"

    - name: Set cache key
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: set-cache-key
      run: |
        echo "CACHE_KEY=${{ runner.os }}-deps-cypress-${{ hashFiles('yarn.lock') }}-1" >> $GITHUB_OUTPUT

    - name: Get Yarn Cache Directory Path
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Set RUNS_ON_S3_BUCKET_CACHE
      shell: bash
      if: ${{ !github.event.localrun }}
      run: echo "RUNS_ON_S3_BUCKET_CACHE=${{ vars.RUNS_ON_S3_BUCKET_CACHE }}" >> $GITHUB_ENV

    - name: Restore Dependencies Cache
      uses: runs-on/cache@v4
      id: restore-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ${{ inputs.working-directory }}/node_modules
          ${{ env.CYPRESS_CACHE_FOLDER }}
        key: ${{ steps.set-cache-key.outputs.CACHE_KEY }}-node_modules
      env:
        RUNS_ON_S3_BUCKET_CACHE_var: ${{ vars.RUNS_ON_S3_BUCKET_CACHE }}
        CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cypress-cache

    - name: Yarn install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        yarn install --immutable
