name: 'Setup yarn'
description: 'Yarn setup and install dependencies'
inputs:
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: '.'
  aws-region:
    description: 'AWS region to use'
    required: false
    default: 'eu-west-1'

runs:
  using: 'composite'
  steps:
    - name: Corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable

    - name: Check node version
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -euo pipefail
        node -v
        yarn --version
        ls -l "$(which node)"

    - name: Get Yarn Cache Directory Path
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Dependencies
      uses: ./.github/actions/cache
      id: restore-cache
      with:
        working-directory: ${{ inputs.working-directory }}
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ${{ inputs.working-directory }}/node_modules
          ${{ github.workspace }}/.cypress-cache
        key: >-
          deps=cypress:node_modules
          yarn.lock-hash=${{ hashFiles('yarn.lock') }}

    - name: Yarn install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
      run: |
        yarn install --immutable
