name: 'Setup yarn'
description: 'Yarn setup and install npm/yarn dependencies'
inputs:
  cache-bucket:
    description: 'Bucket to use as cache (for RunsOn action cache)'
    required: false
  working-directory:
    description: 'Directory to run the action in'
    required: false
    default: '.'
  infra-install:
    description: 'Install infra dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Ensure cache bucket
      shell: bash
      run: echo "${{ inputs.cache-bucket || env.CACHE_BUCKET }}" | grep '.'

    - name: Corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable

    - name: Set cache key
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: set-cache
      env:
        CACHE_KEY: ${{ runner.os }}-deps-cypress-${{ hashFiles('yarn.lock') }}${{ inputs.infra-install && '-withinfra' }}
      run: |
        echo "CACHE_KEY=${{ env.CACHE_KEY }}-1" >> $GITHUB_OUTPUT
        echo "CYPRESS_CACHE_PATH=${{ github.workspace }}/.cache/cypress" >> "$GITHUB_OUTPUT"
        echo "YARN_CACHE_PATH=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        echo "YARN_INFRA_CACHE_PATH=$(cd infra && yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Dependencies
      uses: runs-on/cache@v4
      id: cache-deps
      with:
        path: |
          ${{ steps.set-cache.outputs.YARN_CACHE_PATH }}
          ${{ steps.set-cache.outputs.YARN_INFRA_CACHE_PATH }}
          ${{ steps.set-cache.outputs.CYPRESS_CACHE_PATH }}
        key: ${{ steps.set-cache.outputs.CACHE_KEY }}
      env:
        RUNS_ON_S3_BUCKET_CACHE: ${{ inputs.cache-bucket }}
        AWS_REGION: eu-west-1

    - name: EXIT
      shell: bash
      run: exit 1

    - name: Corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable

    - name: Check node version
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -euo pipefail
        node -v
        yarn --version
        ls -l "$(which node)"

    - name: Set cache key
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: set-cache
      run: |
        echo "CACHE_KEY=${{ runner.os }}-deps-cypress-${{ hashFiles('yarn.lock') }}-1" >> $GITHUB_OUTPUT
        echo "CYPRESS_CACHE_PATH=${{ github.workspace }}/.cache/cypress" >> "$GITHUB_OUTPUT"
        echo "YARN_CACHE_PATH=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        echo "YARN_INFRA_CACHE_PATH=$(cd infra && yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Yarn install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        YARN_ENABLE_HARDENED_MODE: 0
      run: |
        yarn install --immutable

    - name: Yarn install (infra)
      if: ${{ inputs.infra-install == 'true' }}
      working-directory: ${{ inputs.working-directory }}/infra
      shell: bash
      env:
        YARN_ENABLE_HARDENED_MODE: 0
      run: |
        yarn install --immutable
