import type { User } from '@island.is/judicial-system/types'

// These old message types should be deleted once all old messages have been processed
export enum OldMessageType {
  DELIVER_PROSECUTOR_TO_COURT = 'DELIVER_PROSECUTOR_TO_COURT',
  DELIVER_DEFENDANT_TO_COURT = 'DELIVER_DEFENDANT_TO_COURT',
  DELIVER_CASE_FILE_TO_COURT = 'DELIVER_CASE_FILE_TO_COURT',
  DELIVER_CASE_FILES_RECORD_TO_COURT = 'DELIVER_CASE_FILES_RECORD_TO_COURT',
  DELIVER_REQUEST_TO_COURT = 'DELIVER_REQUEST_TO_COURT',
  DELIVER_COURT_RECORD_TO_COURT = 'DELIVER_COURT_RECORD_TO_COURT',
  DELIVER_SIGNED_RULING_TO_COURT = 'DELIVER_SIGNED_RULING_TO_COURT',
  DELIVER_CASE_CONCLUSION_TO_COURT = 'DELIVER_CASE_CONCLUSION_TO_COURT',
  DELIVER_CASE_TO_POLICE = 'DELIVER_CASE_TO_POLICE',
  DELIVER_INDICTMENT_CASE_TO_POLICE = 'DELIVER_INDICTMENT_CASE_TO_POLICE',
  DELIVER_INDICTMENT_TO_POLICE = 'DELIVER_INDICTMENT_TO_POLICE',
  DELIVER_CASE_FILES_RECORD_TO_POLICE = 'DELIVER_CASE_FILES_RECORD_TO_POLICE',
  DELIVER_SIGNED_RULING_TO_POLICE = 'DELIVER_SIGNED_RULING_TO_POLICE',
  DELIVER_APPEAL_TO_POLICE = 'DELIVER_APPEAL_TO_POLICE',
  ARCHIVE_CASE_FILE = 'ARCHIVE_CASE_FILE',
  ARCHIVE_CASE_FILES_RECORD = 'ARCHIVE_CASE_FILES_RECORD',
  SEND_HEADS_UP_NOTIFICATION = 'SEND_HEADS_UP_NOTIFICATION',
  SEND_READY_FOR_COURT_NOTIFICATION = 'SEND_READY_FOR_COURT_NOTIFICATION',
  SEND_RECEIVED_BY_COURT_NOTIFICATION = 'SEND_RECEIVED_BY_COURT_NOTIFICATION',
  SEND_COURT_DATE_NOTIFICATION = 'SEND_COURT_DATE_NOTIFICATION',
  SEND_DEFENDANTS_NOT_UPDATED_AT_COURT_NOTIFICATION = 'SEND_DEFENDANTS_NOT_UPDATED_AT_COURT_NOTIFICATION',
  SEND_RULING_NOTIFICATION = 'SEND_RULING_NOTIFICATION',
  SEND_MODIFIED_NOTIFICATION = 'SEND_MODIFIED_NOTIFICATION',
  SEND_REVOKED_NOTIFICATION = 'SEND_REVOKED_NOTIFICATION',
  SEND_DEFENDER_ASSIGNED_NOTIFICATION = 'SEND_DEFENDER_ASSIGNED_NOTIFICATION',
  SEND_APPEAL_TO_COURT_OF_APPEALS_NOTIFICATION = 'SEND_APPEAL_TO_COURT_OF_APPEALS_NOTIFICATION',
  SEND_APPEAL_RECEIVED_BY_COURT_NOTIFICATION = 'SEND_APPEAL_RECEIVED_BY_COURT_NOTIFICATION',
  SEND_APPEAL_STATEMENT_NOTIFICATION = 'SEND_APPEAL_STATEMENT_NOTIFICATION',
  SEND_APPEAL_COMPLETED_NOTIFICATION = 'SEND_APPEAL_COMPLETED_NOTIFICATION',
  SEND_APPEAL_JUDGES_ASSIGNED_NOTIFICATION = 'SEND_APPEAL_JUDGES_ASSIGNED_NOTIFICATION',
  SEND_APPEAL_CASE_FILES_UPDATED_NOTIFICATION = 'SEND_APPEAL_CASE_FILES_UPDATED_NOTIFICATION',
  SEND_APPEAL_WITHDRAWN_NOTIFICATION = 'SEND_APPEAL_WITHDRAWN_NOTIFICATION',
  SEND_INDICTMENT_DENIED_NOTIFICATION = 'SEND_INDICTMENT_DENIED_NOTIFICATION',
}

export enum MessageType {
  DELIVERY_TO_COURT_PROSECUTOR = 'DELIVERY_TO_COURT_PROSECUTOR',
  DELIVERY_TO_COURT_DEFENDANT = 'DELIVERY_TO_COURT_DEFENDANT',
  DELIVERY_TO_COURT_CASE_FILE = 'DELIVERY_TO_COURT_CASE_FILE',
  DELIVERY_TO_COURT_CASE_FILES_RECORD = 'DELIVERY_TO_COURT_CASE_FILES_RECORD',
  DELIVERY_TO_COURT_REQUEST = 'DELIVERY_TO_COURT_REQUEST',
  DELIVERY_TO_COURT_COURT_RECORD = 'DELIVERY_TO_COURT_COURT_RECORD',
  DELIVERY_TO_COURT_SIGNED_RULING = 'DELIVERY_TO_COURT_SIGNED_RULING',
  DELIVERY_TO_COURT_CASE_CONCLUSION = 'DELIVERY_TO_COURT_CASE_CONCLUSION',
  DELIVERY_TO_COURT_OF_APPEALS_APPEAL_RECEIVED_DATE = 'DELIVERY_TO_COURT_OF_APPEALS_APPEAL_RECEIVED_DATE',
  DELIVERY_TO_COURT_OF_APPEALS_ASSIGNED_ROLES = 'DELIVERY_TO_COURT_OF_APPEALS_ASSIGNED_ROLES',
  DELIVERY_TO_POLICE_CASE = 'DELIVERY_TO_POLICE_CASE',
  DELIVERY_TO_POLICE_INDICTMENT_CASE = 'DELIVERY_TO_POLICE_INDICTMENT_CASE',
  DELIVERY_TO_POLICE_INDICTMENT = 'DELIVERY_TO_POLICE_INDICTMENT',
  DELIVERY_TO_POLICE_CASE_FILES_RECORD = 'DELIVERY_TO_POLICE_CASE_FILES_RECORD',
  DELIVERY_TO_POLICE_SIGNED_RULING = 'DELIVERY_TO_POLICE_SIGNED_RULING',
  DELIVERY_TO_POLICE_APPEAL = 'DELIVERY_TO_POLICE_APPEAL',
  ARCHIVING_CASE_FILE = 'ARCHIVING_CASE_FILE',
  ARCHIVING_CASE_FILES_RECORD = 'ARCHIVING_CASE_FILES_RECORD',
  NOTIFICATION = 'NOTIFICATION',
}

export const messageEndpoint: { [key in MessageType]: string } = {
  DELIVERY_TO_COURT_PROSECUTOR: 'deliverProsecutorToCourt',
  DELIVERY_TO_COURT_DEFENDANT: 'deliverDefendantToCourt',
  DELIVERY_TO_COURT_CASE_FILE: 'deliverCaseFileToCourt',
  DELIVERY_TO_COURT_CASE_FILES_RECORD: 'deliverCaseFilesRecordToCourt',
  DELIVERY_TO_COURT_REQUEST: 'deliverRequestToCourt',
  DELIVERY_TO_COURT_COURT_RECORD: 'deliverCourtRecordToCourt',
  DELIVERY_TO_COURT_SIGNED_RULING: 'deliverSignedRulingToCourt',
  DELIVERY_TO_COURT_CASE_CONCLUSION: 'deliverCaseConclusionToCourt',
  DELIVERY_TO_COURT_OF_APPEALS_APPEAL_RECEIVED_DATE:
    'deliverAppealReceivedDateToCourtOfAppeals',
  DELIVERY_TO_COURT_OF_APPEALS_ASSIGNED_ROLES:
    'deliverAssignedRolesToCourtOfAppeals',
  DELIVERY_TO_POLICE_CASE: 'deliverCaseToPolice',
  DELIVERY_TO_POLICE_INDICTMENT_CASE: 'deliverIndictmentCaseToPolice',
  DELIVERY_TO_POLICE_INDICTMENT: 'deliverIndictmentToPolice',
  DELIVERY_TO_POLICE_CASE_FILES_RECORD: 'deliverCaseFilesRecordToPolice',
  DELIVERY_TO_POLICE_SIGNED_RULING: 'deliverSignedRulingToPolice',
  DELIVERY_TO_POLICE_APPEAL: 'deliverAppealToPolice',
  ARCHIVING_CASE_FILE: 'archiveCaseFile',
  ARCHIVING_CASE_FILES_RECORD: 'archiveCaseFilesRecord',
  NOTIFICATION: 'notification',
}

export type CaseMessage = {
  type: OldMessageType | MessageType
  user: User
  caseId: string
  elementId?: string
  body?: { [key: string]: unknown }
  numberOfRetries?: number
  nextRetry?: number
}

// These message types should be removed once all old messages have been processed
export type DefendantMessage = CaseMessage & { defendantId: string }
export type CaseFileMessage = CaseMessage & { caseFileId: string }
export type PoliceCaseMessage = CaseMessage & { policeCaseNumber: string }
