export enum LicenseType {
  IDENTIDY_CARD = 'IDENTIDY_CARD',
  PASSPORT = 'PASSPORT',
  DRIVERS_LICENSE = 'DriversLicense',
  WEAPON_LICENSE = 'WEAPON_LICENSE',
  FISHING_CARD = 'FISHING_CARD',
  ADR_LICENSE = 'ADR_LICENSE',
  MACHINE_CERTIFICATE = 'MACHINE_CERTIFICATE',
  CRIMINAL_RECORD_CERTIFICATE = 'CRIMINAL_RECORD_CERTIFICATE',
  VACCINE_CERTIFICATE = 'VACCINE_CERTIFICATE',
  DISABILIY_LICENSE = 'DISABILIY_LICENSE',
}

export enum LicenseStatus {
  VALID = 'VALID',
  NOT_VALID = 'NOT_VALID',
}
