import { Substance } from '@island.is/judicial-system/types'

export const strings = {
  [Substance.AMPHETAMINE]: 'Amfetamín',
  [Substance.ETIZOLAM]: 'Etízólam',
  [Substance.PHENAZEPAM]: 'Fenazepam',
  [Substance.FLUALPRAZOLAM]: 'Flúalprazólam',
  [Substance.BROMAZOLAM]: 'Brómazólam',
  [Substance.KETAMINE]: 'Ketamín',
  [Substance.KETOBEMIDONE]: 'Ketobemidone',
  [Substance.COCAINE]: 'Kókaín',
  [Substance.MDMA]: 'MDMA',
  [Substance.METHAMPHETAMINE]: 'Metamfetamín',
  [Substance.METHYLPHENIDATE]: 'Metýlfenídat',
  [Substance.O_DESMETHYLTRAMADOL]: 'O-Desmetýltramadól',
  [Substance.TETRAHYDROCANNABINOL]: 'Tetrahýdrókannabínól',
  [Substance.TRAMADOL]: 'Tramadól',
  [Substance.ZOPICLONE]: 'Zópíklón',
  [Substance.ALPRAZOLAM]: 'Alprazólam',
  [Substance.BROMAZEPAM]: 'Brómazepam',
  [Substance.BUPRENORPHINE]: 'Búprenorfín',
  [Substance.DEMOXEAPAM]: 'Demoxeapam',
  [Substance.DESMETHYLCHLORDIAZEPOXIDE]: 'Desmetýlklórdíazepoxíð',
  [Substance.DIAZEPAM]: 'Díazepam',
  [Substance.FENTANYL]: 'Fentanýl',
  [Substance.FLUNITRAZEPAM]: 'Flúnitrazepam',
  [Substance.GABAPENTIN]: 'Gabapentín',
  [Substance.CLONAZEPAM]: 'Klónazepam',
  [Substance.CHLORDIAZEPOXIDE]: 'Klórdíazepoxíð',
  [Substance.CODEINE]: 'Kódein',
  [Substance.LORAZEPAM]: 'Lorazepam',
  [Substance.METHADONE]: 'Metadón',
  [Substance.MIDAZOLAM]: 'Mídazólam',
  [Substance.MORPHINE]: 'Morfín',
  [Substance.NITRAZEPAM]: 'Nítrazepam',
  [Substance.NORBUPRENORPHINE]: 'Norbúprenorfín',
  [Substance.NORDIAZEPAM]: 'Nordíazepam',
  [Substance.OXAZEPAM]: 'Oxazepam',
  [Substance.OXYCODONE]: 'Oxýkódon',
  [Substance.PREGABALIN]: 'Pregabalín',
  [Substance.QUETIAPINE]: 'Quetíapín',
  [Substance.TEMAZEPAM]: 'Temazepam',
  [Substance.TRIAZOLAM]: 'Tríazólam',
  [Substance.ZOLPIDEM]: 'Zolpídem',
  [Substance.ALCOHOL]: 'Áfengi',
  [Substance.OLANZAPIN]: 'Olanzapín',
}
