import { FormSystemListItem } from '@island.is/api/schema'

export const getMunicipalitiesList = (): FormSystemListItem[] => {
  return municipalitiesList.map((municipality, index) => ({
    id: municipality.code,
    label: { is: municipality.name, en: municipality.name },
    value: municipality.code,
    displayOrder: index,
    isSelected: false,
  }))
}

const municipalitiesList: { code: string; name: string }[] = [
  { code: '0000', name: 'Reykjavíkurborg' },
  { code: '1000', name: 'Kópavogsbær' },
  { code: '1100', name: 'Seltjarnarnesbær' },
  { code: '1300', name: 'Garðabær' },
  { code: '1400', name: 'Hafnarfjarðarkaupstaður' },
  { code: '1604', name: 'Mosfellsbær' },
  { code: '1606', name: 'Kjósarhreppur' },
  { code: '2000', name: 'Reykjanesbær' },
  { code: '2300', name: 'Grindavíkurbær' },
  { code: '2506', name: 'Sveitarfélagið Vogar' },
  { code: '2510', name: 'Suðurnesjabær' },
  { code: '3000', name: 'Akraneskaupstaður' },
  { code: '3506', name: 'Skorradalshreppur' },
  { code: '3511', name: 'Hvalfjarðarsveit' },
  { code: '3609', name: 'Borgarbyggð' },
  { code: '3709', name: 'Grundarfjarðarbær' },
  { code: '3713', name: 'Eyja- og Miklaholtshreppur' },
  { code: '3714', name: 'Snæfellsbær' },
  { code: '3716', name: 'Sveitarfélagið Stykkishólmur' },
  { code: '3811', name: 'Dalabyggð' },
  { code: '4100', name: 'Bolungarvíkurkaupstaður' },
  { code: '4200', name: 'Ísafjarðarbær' },
  { code: '4502', name: 'Reykhólahreppur' },
  { code: '4604', name: 'Vesturbyggð' },
  { code: '4803', name: 'Súðavíkurhreppur' },
  { code: '4901', name: 'Árneshreppur' },
  { code: '4902', name: 'Kaldrananeshreppur' },
  { code: '4911', name: 'Strandabyggð' },
  { code: '5508', name: 'Húnaþing vestra' },
  { code: '5609', name: 'Sveitarfélagið Skagaströnd' },
  { code: '5613', name: 'Húnabyggð' },
  { code: '5716', name: 'Skagafjörður' },
  { code: '6000', name: 'Akureyrarbær' },
  { code: '6100', name: 'Norðurþing' },
  { code: '6250', name: 'Fjallabyggð' },
  { code: '6400', name: 'Dalvíkurbyggð' },
  { code: '6513', name: 'Eyjafjarðarsveit' },
  { code: '6515', name: 'Hörgársveit' },
  { code: '6601', name: 'Svalbarðsstrandarhreppur' },
  { code: '6602', name: 'Grýtubakkahreppur' },
  { code: '6611', name: 'Tjörneshreppur' },
  { code: '6613', name: 'Þingeyjarsveit' },
  { code: '6710', name: 'Langanesbyggð' },
  { code: '7300', name: 'Fjarðabyggð' },
  { code: '7400', name: 'Múlaþing' },
  { code: '7502', name: 'Vopnafjarðarhreppur' },
  { code: '7505', name: 'Fljótsdalshreppur' },
  { code: '8000', name: 'Vestmannaeyjabær' },
  { code: '8200', name: 'Sveitarfélagið Árborg' },
  { code: '8401', name: 'Sveitarfélagið Hornafjörður' },
  { code: '8508', name: 'Mýrdalshreppur' },
  { code: '8509', name: 'Skaftárhreppur' },
  { code: '8610', name: 'Ásahreppur' },
  { code: '8613', name: 'Rangárþing eystra' },
  { code: '8614', name: 'Rangárþing ytra' },
  { code: '8710', name: 'Hrunamannahreppur' },
  { code: '8716', name: 'Hveragerðisbær' },
  { code: '8717', name: 'Sveitarfélagið Ölfus' },
  { code: '8719', name: 'Grímsnes- og Grafningshreppur' },
  { code: '8720', name: 'Skeiða- og Gnúpverjahreppur' },
  { code: '8721', name: 'Bláskógabyggð' },
  { code: '8722', name: 'Flóahreppur' },
]
