import { FormSystemListItem } from '@island.is/api/schema'

export const getPostalCodesList = (): FormSystemListItem[] => {
  return postalCodesList.map((postalCode, index) => ({
    id: postalCode.code,
    label: { is: postalCode.code, en: postalCode.code },
    value: postalCode.code,
    displayOrder: index,
    isSelected: false,
  }))
}

const postalCodesList: { code: string; name: string }[] = [
  { code: '101', name: 'Reykjavík' },
  { code: '102', name: 'Reykjavík' },
  { code: '103', name: 'Reykjavík' },
  { code: '104', name: 'Reykjavík' },
  { code: '105', name: 'Reykjavík' },
  { code: '107', name: 'Reykjavík' },
  { code: '108', name: 'Reykjavík' },
  { code: '109', name: 'Reykjavík' },
  { code: '110', name: 'Reykjavík' },
  { code: '111', name: 'Reykjavík' },
  { code: '112', name: 'Reykjavík' },
  { code: '113', name: 'Reykjavík' },
  { code: '116', name: 'Reykjavík' },
  { code: '121', name: 'Reykjavík' },
  { code: '123', name: 'Reykjavík' },
  { code: '124', name: 'Reykjavík' },
  { code: '125', name: 'Reykjavík' },
  { code: '127', name: 'Reykjavík' },
  { code: '128', name: 'Reykjavík' },
  { code: '129', name: 'Reykjavík' },
  { code: '130', name: 'Reykjavík' },
  { code: '132', name: 'Reykjavík' },
  { code: '161', name: 'Reykjavík' },
  { code: '162', name: 'Reykjavík' },
  { code: '170', name: 'Seltjarnarnes' },
  { code: '172', name: 'Seltjarnarnes' },
  { code: '190', name: 'Vogar' },
  { code: '191', name: 'Vogar' },
  { code: '200', name: 'Kópavogur' },
  { code: '201', name: 'Kópavogur' },
  { code: '202', name: 'Kópavogur' },
  { code: '203', name: 'Kópavogur' },
  { code: '206', name: 'Kópavogur' },
  { code: '210', name: 'Garðabær' },
  { code: '212', name: 'Garðabær' },
  { code: '220', name: 'Hafnarfjörður' },
  { code: '221', name: 'Hafnarfjörður' },
  { code: '222', name: 'Hafnarfjörður' },
  { code: '225', name: 'Garðabær (Álftanes)' },
  { code: '230', name: 'Reykjanesbær' },
  { code: '232', name: 'Reykjanesbær' },
  { code: '233', name: 'Reykjanesbær' },
  { code: '235', name: 'Keflavíkurflugvöllur' },
  { code: '240', name: 'Grindavík' },
  { code: '241', name: 'Grindavík' },
  { code: '245', name: 'Sandgerði' },
  { code: '246', name: 'Sandgerði' },
  { code: '250', name: 'Garður' },
  { code: '251', name: 'Garður' },
  { code: '260', name: 'Reykjanesbær' },
  { code: '262', name: 'Reykjanesbær' },
  { code: '270', name: 'Mosfellsbær' },
  { code: '271', name: 'Mosfellsbær' },
  { code: '276', name: 'Kjós' },
  { code: '300', name: 'Akranes' },
  { code: '301', name: 'Akranes' },
  { code: '302', name: 'Akranes' },
  { code: '310', name: 'Borgarnes' },
  { code: '311', name: 'Borgarnes' },
  { code: '320', name: 'Reykholt í Borgarfirði' },
  { code: '340', name: 'Stykkishólmur' },
  { code: '341', name: 'Stykkishólmur' },
  { code: '342', name: 'Stykkishólmur' },
  { code: '345', name: 'Flatey á Breiðafirði' },
  { code: '350', name: 'Grundarfjörður' },
  { code: '351', name: 'Grundarfjörður' },
  { code: '355', name: 'Ólafsvík' },
  { code: '356', name: 'Snæfellsbær' },
  { code: '360', name: 'Hellissandur' },
  { code: '370', name: 'Búðardalur' },
  { code: '371', name: 'Búðardalur' },
  { code: '380', name: 'Reykhólahreppur' },
  { code: '381', name: 'Reykhólahreppur' },
  { code: '400', name: 'Ísafjörður' },
  { code: '401', name: 'Ísafjörður' },
  { code: '410', name: 'Hnífsdalur' },
  { code: '415', name: 'Bolungarvík' },
  { code: '416', name: 'Bolungarvík' },
  { code: '420', name: 'Súðavík' },
  { code: '421', name: 'Súðavík' },
  { code: '425', name: 'Flateyri' },
  { code: '426', name: 'Flateyri' },
  { code: '430', name: 'Suðureyri' },
  { code: '431', name: 'Suðureyri' },
  { code: '450', name: 'Patreksfjörður' },
  { code: '451', name: 'Patreksfjörður' },
  { code: '460', name: 'Tálknafjörður' },
  { code: '461', name: 'Tálknafjörður' },
  { code: '465', name: 'Bíldudalur' },
  { code: '466', name: 'Bíldudalur' },
  { code: '470', name: 'Þingeyri' },
  { code: '471', name: 'Þingeyri' },
  { code: '500', name: 'Staður' },
  { code: '510', name: 'Hólmavík' },
  { code: '511', name: 'Hólmavík' },
  { code: '512', name: 'Hólmavík' },
  { code: '520', name: 'Drangsnes' },
  { code: '524', name: 'Árneshreppur' },
  { code: '530', name: 'Hvammstangi' },
  { code: '531', name: 'Hvammstangi' },
  { code: '540', name: 'Blönduós' },
  { code: '541', name: 'Blönduós' },
  { code: '545', name: 'Skagaströnd' },
  { code: '546', name: 'Skagaströnd' },
  { code: '550', name: 'Sauðárkrókur' },
  { code: '551', name: 'Sauðárkrókur' },
  { code: '560', name: 'Varmahlíð' },
  { code: '561', name: 'Varmahlíð' },
  { code: '565', name: 'Hofsós' },
  { code: '566', name: 'Hofsós' },
  { code: '570', name: 'Fljót' },
  { code: '580', name: 'Siglufjörður' },
  { code: '581', name: 'Siglufjörður' },
  { code: '600', name: 'Akureyri' },
  { code: '601', name: 'Akureyri' },
  { code: '602', name: 'Akureyri' },
  { code: '603', name: 'Akureyri' },
  { code: '604', name: 'Akureyri' },
  { code: '605', name: 'Akureyri' },
  { code: '606', name: 'Akureyri' },
  { code: '607', name: 'Akureyri' },
  { code: '610', name: 'Grenivík' },
  { code: '616', name: 'Grenivík' },
  { code: '611', name: 'Grímsey' },
  { code: '620', name: 'Dalvík' },
  { code: '621', name: 'Dalvík' },
  { code: '625', name: 'Ólafsfjörður' },
  { code: '626', name: 'Ólafsfjörður' },
  { code: '630', name: 'Hrísey' },
  { code: '640', name: 'Húsavík' },
  { code: '641', name: 'Húsavík' },
  { code: '645', name: 'Fosshóll' },
  { code: '650', name: 'Laugar' },
  { code: '660', name: 'Mývatn' },
  { code: '670', name: 'Kópasker' },
  { code: '671', name: 'Kópasker' },
  { code: '675', name: 'Raufarhöfn' },
  { code: '676', name: 'Raufarhöfn' },
  { code: '680', name: 'Þórshöfn' },
  { code: '681', name: 'Þórshöfn' },
  { code: '685', name: 'Bakkafjörður' },
  { code: '686', name: 'Bakkafjörður' },
  { code: '690', name: 'Vopnafjörður' },
  { code: '691', name: 'Vopnafjörður' },
  { code: '700', name: 'Egilsstaðir' },
  { code: '701', name: 'Egilsstaðir' },
  { code: '710', name: 'Seyðisfjörður' },
  { code: '711', name: 'Seyðisfjörður' },
  { code: '715', name: 'Mjóifjörður' },
  { code: '720', name: 'Borgarfjörður (eystri)' },
  { code: '721', name: 'Borgarfjörður (eystri)' },
  { code: '730', name: 'Reyðarfjörður' },
  { code: '731', name: 'Reyðarfjörður' },
  { code: '735', name: 'Eskifjörður' },
  { code: '736', name: 'Eskifjörður' },
  { code: '740', name: 'Neskaupstaður' },
  { code: '741', name: 'Neskaupstaður' },
  { code: '750', name: 'Fáskrúðsfjörður' },
  { code: '751', name: 'Fáskrúðsfjörður' },
  { code: '755', name: 'Stöðvarfjörður' },
  { code: '756', name: 'Stöðvarfjörður' },
  { code: '760', name: 'Breiðdalsvík' },
  { code: '761', name: 'Breiðdalsvík' },
  { code: '765', name: 'Djúpivogur' },
  { code: '766', name: 'Djúpivogur' },
  { code: '780', name: 'Höfn í Hornafirði' },
  { code: '781', name: 'Höfn í Hornafirði' },
  { code: '785', name: 'Öræfi' },
  { code: '800', name: 'Selfoss' },
  { code: '801', name: 'Selfoss' },
  { code: '802', name: 'Selfoss' },
  { code: '803', name: 'Selfoss' },
  { code: '804', name: 'Selfoss' },
  { code: '805', name: 'Selfoss' },
  { code: '806', name: 'Selfoss' },
  { code: '810', name: 'Hveragerði' },
  { code: '815', name: 'Þorlákshöfn' },
  { code: '816', name: 'Ölfus' },
  { code: '820', name: 'Eyrarbakki' },
  { code: '825', name: 'Stokkseyri' },
  { code: '840', name: 'Laugarvatn' },
  { code: '845', name: 'Flúðir' },
  { code: '846', name: 'Flúðir' },
  { code: '850', name: 'Hella' },
  { code: '851', name: 'Hella' },
  { code: '860', name: 'Hvolsvöllur' },
  { code: '861', name: 'Hvolsvöllur' },
  { code: '870', name: 'Vík' },
  { code: '871', name: 'Vík' },
  { code: '880', name: 'Kirkjubæjarklaustur' },
  { code: '881', name: 'Kirkjubæjarklaustur' },
  { code: '900', name: 'Vestmannaeyjar' },
  { code: '902', name: 'Vestmannaeyjar' },
]
