export enum AssetsPaths {
  AssetsRoot = '/eignir',
  AssetsRealEstate = '/eignir/fasteignir',
  AssetsRealEstateDetail = '/eignir/fasteignir/:id',
  AssetsVehicles = '/eignir/okutaeki',
  AssetsMyVehicles = '/eignir/okutaeki/min-okutaeki',
  AssetsVehiclesDetail = '/eignir/okutaeki/min-okutaeki/:id',
  AssetsVehiclesLookup = '/eignir/okutaeki/leit',
  AssetsVehiclesHistory = '/eignir/okutaeki/okutaekjaferill',
  AssetsWorkMachines = '/eignir/vinnuvelar',
  AssetsWorkMachinesDetail = '/eignir/vinnuvelar/:regNumber/:id',
  AssetsIntellectualPropertiesOverview = '/eignir/hugverkarettindi',
  AssetsIntellectualPropertiesDesign = '/eignir/hugverkarettindi/honnun/:id',
  AssetsIntellectualPropertiesTrademark = '/eignir/hugverkarettindi/vorumerki/:id',
  AssetsIntellectualPropertiesPatent = '/eignir/hugverkarettindi/einkaleyfi/:id',
}
